### ISSUE TITLE
Tests are failing in develop

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#1000]
```
--- FAIL: TestReactorProposalHeartbeats (2.33s)
panic: close of closed channel [recovered]
        panic: close of closed channel

goroutine 1340 [running]:
testing.tRunner.func1(0xc4200fb4a0)
        /usr/local/go/src/testing/testing.go:711 +0x5d9
panic(0xddede0, 0x1074c20)
        /usr/local/go/src/runtime/panic.go:491 +0x2a2
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common.(*RepeatTimer).Stop(0xc420c5f640, 0xda9a00)
        /go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common/repeat_timer.go:151 +0x13a
github.com/tendermint/tendermint/p2p.(*MConnection).OnStop(0xc42145aff0)
        /go/src/github.com/tendermint/tendermint/p2p/connection.go:190 +0x85
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common.(*BaseService).Stop(0xc42145aff0, 0xc421594101, 0xc42149a520)
        /go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common/service.go:145 +0x2a8
github.com/tendermint/tendermint/p2p.(*peer).OnStop(0xc42099db00)
        /go/src/github.com/tendermint/tendermint/p2p/peer.go:241 +0x53
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common.(*BaseService).Stop(0xc42099db00, 0xc420aaf030, 0xc42177af28)
        /go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common/service.go:145 +0x2a8
github.com/tendermint/tendermint/p2p.(*peer).Stop(0xc42099db00, 0x1445b00, 0xc42099d600)
        <autogenerated>:1 +0x44
github.com/tendermint/tendermint/p2p.(*Switch).OnStop(0xc421db8400)
        /go/src/github.com/tendermint/tendermint/p2p/switch.go:219 +0x184
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common.(*BaseService).Stop(0xc421db8400, 0xec714f, 0x2b)
        /go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common/service.go:145 +0x2a8
github.com/tendermint/tendermint/consensus.stopConsensusNet(0x14400c0, 0xc42003f270, 0xc420c73100, 0x4, 0x4, 0xc420c731a0, 0x4, 0x4)
        /go/src/github.com/tendermint/tendermint/consensus/reactor_test.go:77 +0x1e1
github.com/tendermint/tendermint/consensus.TestReactorProposalHeartbeats(0xc4200fb4a0)
        /go/src/github.com/tendermint/tendermint/consensus/reactor_test.go:131 +0x6fc
testing.tRunner(0xc4200fb4a0, 0xffabe8)
        /usr/local/go/src/testing/testing.go:746 +0x16d
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:789 +0x569
exit status 2
FAIL    github.com/tendermint/tendermint/consensus      21.147s
make: *** [test_integrations] Error 1
```

HEAD: c2436c46
https://circleci.com/gh/tendermint/tendermint/2537#artifacts/containers/0

**Comment by melekes** [comment]
```
Read at 0x00c4200707b0 by goroutine 125:
  github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common.(*RepeatTimer).fireRoutine()
      /home/ubuntu/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common/repeat_timer.go:114 +0xc1

Previous write at 0x00c4200707b0 by goroutine 82:
  github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common.(*RepeatTimer).Reset()
      /home/ubuntu/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common/repeat_timer.go:130 +0xed
  github.com/tendermint/tendermint/p2p.(*MConnection).recvRoutine()
      /home/ubuntu/go/src/github.com/tendermint/tendermint/p2p/connection.go:500 +0xb4
```

**Comment by melekes** [comment]
Maybe I forgot to revert some changes? But by looking at the Git history - this race existed from the beginning.

**Comment by ebuchman** [comment]
https://github.com/tendermint/tmlibs/pull/110

**Comment by jaekwon** [comment]
https://github.com/tendermint/tmlibs/pull/111
