### ISSUE TITLE
Bizare deletion of priv_validator.json

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#1117]
I started my node, which is a genesis validator using `gaia start node`. I then shut down the process and rebooted the server. Then, I deleted all new temporary files (`validators, data, addrbook.json`). I then started the node with the exact same command. The result was a panic and everything getting deleted besides the `keys` folder.

```
avo@gaia-3:~$ cd .cosmos-gaia-cli/
avo@gaia-3:~/.cosmos-gaia-cli$ ls
addrbook.json  checkpoints  config.toml  data  genesis.json  keys  nohup.out  priv_validator.json  validators
avo@gaia-3:~/.cosmos-gaia-cli$ rm -rf addrbook.json data nohup.out validators/ checkpoints/
avo@gaia-3:~/.cosmos-gaia-cli$ ls
config.toml  genesis.json  keys  priv_validator.json
avo@gaia-3:~/.cosmos-gaia-cli$ gaia node start
E[01-18|18:36:21.111] enterPropose: Cannot propose anything: No commit for the previous block. module=consensus
panic: open /home/avo/.cosmos-gaia-cli/data/cs.wal/wal: no such file or directory

goroutine 1237 [running]:
github.com/cosmos/gaia/vendor/github.com/tendermint/tmlibs/autofile.(*Group).checkHeadSizeLimit(0xc422f237c0)
        /home/avo/.gvm/pkgsets/go1.9.2/global/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tmlibs/autofile/group.go:213 +0xa9
github.com/cosmos/gaia/vendor/github.com/tendermint/tmlibs/autofile.(*Group).processTicks(0xc422f237c0)
        /home/avo/.gvm/pkgsets/go1.9.2/global/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tmlibs/autofile/group.go:195 +0x2d
created by github.com/cosmos/gaia/vendor/github.com/tendermint/tmlibs/autofile.(*Group).OnStart
        /home/avo/.gvm/pkgsets/go1.9.2/global/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tmlibs/autofile/group.go:103 +0x41
avo@gaia-3:~/.cosmos-gaia-cli$ ls
avo@gaia-3:~/.cosmos-gaia-cli$ cd ..
avo@gaia-3:~$ ls
go  work
avo@gaia-3:~$ ls -al
total 60
drwxr-xr-x 10 avo  avo  4096 Jan 18 18:37 .
drwxr-xr-x  3 root root 4096 Jan 18 16:53 ..
-rw-------  1 avo  avo  2222 Jan 18 18:30 .bash_history
-rw-r--r--  1 avo  avo   220 Jan 18 16:53 .bash_logout
-rw-r--r--  1 avo  avo  3849 Jan 18 17:19 .bashrc
drwx------  2 avo  avo  4096 Jan 18 16:55 .cache
-rw-r--r--  1 avo  avo     0 Jan 18 16:53 .cloud-locale-test.skip
drwx------  3 avo  avo  4096 Jan 18 18:37 .cosmos-gaia-cli
drwxr-xr-x  3 avo  avo  4096 Jan 18 17:24 .glide
drwxrwxr-x 15 avo  avo  4096 Jan 18 17:19 .gvm
drwxrwxr-x  2 avo  avo  4096 Jan 18 16:54 .nano
-rw-r--r--  1 avo  avo   655 Jan 18 17:19 .profile
drwx------  2 avo  avo  4096 Jan 18 16:54 .ssh
-rw-r--r--  1 avo  avo     0 Jan 18 16:55 .sudo_as_admin_successful
-rw-------  1 avo  avo   659 Jan 18 17:28 .viminfo
drwxrwxr-x  2 avo  avo  4096 Jan 18 17:17 go
drwxrwxr-x  3 avo  avo  4096 Jan 18 17:17 work
avo@gaia-3:~$ cd .cosmos-gaia-cli/
avo@gaia-3:~/.cosmos-gaia-cli$ ls
keys
avo@gaia-3:~/.cosmos-gaia-cli$ ls
keys
avo@gaia-3:~/.cosmos-gaia-cli$ ls
keys
avo@gaia-3:~/.cosmos-gaia-cli$
```

**Comment by adrianbrink** [comment]
I'll close this since @ebuchman couldn't reproduce it. If it shows up again I'll have a better way to reproduce it.
