### ISSUE TITLE
Cosmos sentry node Error: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by davepuchyr** [tendermint/tendermint#1169]
BUG

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.15

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
https://github.com/cosmos/gaia

**Merkleeyes version** (use `git rev-parse --verify HEAD`, skip if you don't use it):

**Environment**:
- **OS** (e.g. from /etc/os-release): Fedora 27
- **Install tools**: dnf install golang
- **Others**: 
  - go version go1.9.2 linux/amd64
  - gcc (GCC) 7.2.1 20170915 (Red Hat 7.2.1-2)

**What happened**:

```
E[01-28|08:39:14.270] Stopping peer for error module=p2p peer="Peer{MConn{45.33.41.76:46656} 192.168.223.35:46656 out}" err="Error: runtime error: invalid memory address or nil pointer dereference
Stack: goroutine 8840 [running]:
runtime/debug.Stack(0xc421f33988, 0xc6f140, 0x13c3900)
   /usr/lib/golang/src/runtime/debug/stack.go:24 +0xa7
github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/p2p.(*MConnection)._recover(0xc4213f8870)
   /home/cosmos/go/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/p2p/connection.go:218 +0x6e
panic(0xc6f140, 0x13c3900)
   /usr/lib/golang/src/runtime/panic.go:491 +0x283
github.com/cosmos/gaia/vendor/github.com/tendermint/tmlibs/common.(*BitArray).Update(0xc42244a7e0, 0x0)
   /home/cosmos/go/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tmlibs/common/bit_array.go:315 +0x70
github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/consensus.(*PeerState).ApplyVoteSetBitsMessage(0xc4235481a0, 0xc42244e1e0, 0x0)
   /home/cosmos/go/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/consensus/reactor.go:1181 +0x112
github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusReactor).Receive(0xc4200ff900, 0xc420d97a23, 0x1381860, 0xc4245c4400, 0xc42469e000, 0x3b, 0x400)
   /home/cosmos/go/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/consensus/reactor.go:302 +0x1c99
github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/p2p.createMConnection.func1(0xc423dc5f23, 0xc42469e000, 0x3b, 0x400)
   /home/cosmos/go/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/p2p/peer.go:341 +0xbd
github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/p2p.(*MConnection).recvRoutine(0xc4213f8870)
   /home/cosmos/go/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/p2p/connection.go:490 +0x4af
created by github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/p2p.(*MConnection).OnStart
   /home/cosmos/go/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/p2p/connection.go:182 +0x187
"
```

**What you expected to happen**:
Smart ass response: I expect tendermint not to dereference a nil pointer. ;)

**How to reproduce it** (as minimally and precisely as possible):
I'm not sure that it's reproducible, but what I did was
```
cat /etc/systemd/system/gaia.service
[Unit]
Description=Cosmos Gaia Node
After=network-online.target

[Service]
User=cosmos
# set options in /home/cosmos/testnets/gaia-2/gaia/config.toml
ExecStart=/bin/sh -c '/home/cosmos/go/bin/gaia node start --home=/home/cosmos/testnets/gaia-2/gaia > /home/cosmos/gaia.log 2> /home/cosmos/gaia.err'

[Install]
WantedBy=multi-user.target

systemctl start gaia.service
sleep 60 # give gaia time to generate its data directory
systemctl stop gaia.service 
cd $GAIANET/data/.
rsync -avP other_sentry_node:$GAIANET/data/. . # gaia was stopped on other_sentry_node
systemctl start gaia.service
# sync'ing to the chain's last block was successful; the error happened long after the chain was initially sync'ed

```

**Anything else do we need to know**:
See above.

**Comment by odeke-em** [comment]
Thank you very much for the report @davepuchyr, for testing it out and welcome to Tendermint!

In deed, this is an oversight on our part, we'll get this fixed ASAP.

**Comment by ebuchman** [comment]
Thanks for the report. 

Certainly your expectation is reasonable :)

Did the node actually crash? Or just spat out the panic log and kept going ?

**Comment by davepuchyr** [comment]
It just spat out the panic and kept going.
