### ISSUE TITLE
Document clearly that a service must be started/stopped

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#1410]
```
goroutine 37 [running]:
github.com/tendermint/tools/tm-experiments/vendor/github.com/tendermint/tendermint/rpc/lib/client.(*WSClient).Send(0x0, 0x1bdfaa0, 0xc42006e180, 0x17004d3, 0x3, 0x170558c, 0x9, 0x170547e, 0x9, 0xc420a1c028, ...)
    /Users/zarkomilosevic/go-workspace/src/github.com/tendermint/tools/tm-experiments/vendor/github.com/tendermint/tendermint/rpc/lib/client/ws_client.go:199 +0x3a
github.com/tendermint/tools/tm-experiments/vendor/github.com/tendermint/tendermint/rpc/lib/client.(*WSClient).Call(0x0, 0x1bdfaa0, 0xc42006e180, 0x170547e, 0x9, 0xc420164e70, 0x19, 0x19)
    /Users/zarkomilosevic/go-workspace/src/github.com/tendermint/tools/tm-experiments/vendor/github.com/tendermint/tendermint/rpc/lib/client/ws_client.go:213 +0x183
github.com/tendermint/tools/tm-experiments/vendor/github.com/tendermint/tendermint/rpc/lib/client.(*WSClient).Subscribe(0x0, 0x1bdfaa0, 0xc42006e180, 0xc4201c0220, 0x19, 0xe, 0x1600ce0)
    /Users/zarkomilosevic/go-workspace/src/github.com/tendermint/tools/tm-experiments/vendor/github.com/tendermint/tendermint/rpc/lib/client/ws_client.go:471 +0x138
github.com/tendermint/tools/tm-experiments/vendor/github.com/tendermint/tendermint/rpc/client.(*WSEvents).Subscribe(0xc42099e000, 0x1bdfaa0, 0xc42006e180, 0x170376a, 0x7, 0x1bda720, 0xc42019c7a0, 0xc42006e540, 0x0, 0x0)
    /Users/zarkomilosevic/go-workspace/src/github.com/tendermint/tools/tm-experiments/vendor/github.com/tendermint/tendermint/rpc/client/httpclient.go:254 +0x7f
github.com/tendermint/tools/tm-experiments/vendor/github.com/tendermint/tendermint/rpc/client.WaitForOneEvent(0x1bde6e0, 0xc42019c720, 0x1707e4d, 0xe, 0x12a05f200, 0x0, 0x0, 0x0, 0x0)
    /Users/zarkomilosevic/go-workspace/src/github.com/tendermint/tools/tm-experiments/vendor/github.com/tendermint/tendermint/rpc/client/helpers.go:66 +0x15f
main.monitorTask(0x170c01c, 0x13)
    /Users/zarkomilosevic/go-workspace/src/github.com/tendermint/tools/tm-experiments/main.go:79 +0x8b
created by main.main
    /Users/zarkomilosevic/go-workspace/src/github.com/tendermint/tools/tm-experiments/main.go:31 +0x1ae
```

This is what you'll get if you forget to `Start()` a `HTTPClient`. We should document this clearly in code with a default example like:

```
client := HTTPClient(...)
err := client.Start()
if ...
```

**Comment by jackzampolin** [comment]
I think @alessio 's recent server improvements may have solved this. If I'm 😜 reopen.

**Comment by melekes** [comment]
The error "client is not running. Use .Start() method to start" will be returned to the user if `Subscribe` is called, but HTTP client is not running.
