### ISSUE TITLE
`testnet` command creates invalid JSON for `gaiad`

### ISSUE THREAD

**Issue by greg-szabo** [tendermint/tendermint#1515]
BUG REPORT

Setup: (linux)
```
[greg@ip-10-0-1-132 ~]$ ~/bin/tendermint version
0.19.0-dev-dcaad712

[greg@ip-10-0-1-132 ~]$ ~/bin/gaiad version
0.15.0-rc0-4ac80c3

[greg@ip-10-0-1-132 x]$ tendermint testnet --v 4 --o . --populate-persistent-peers --starting-ip-address 192.167.10.2
I[04-27|23:32:43.977] Generated private validator                  module=main path=node0/config/priv_validator.json
I[04-27|23:32:43.978] Generated node key                           module=main path=node0/config/node_key.json
I[04-27|23:32:43.978] Generated genesis file                       module=main path=node0/config/genesis.json
I[04-27|23:32:43.980] Generated private validator                  module=main path=node1/config/priv_validator.json
I[04-27|23:32:43.980] Generated node key                           module=main path=node1/config/node_key.json
I[04-27|23:32:43.980] Generated genesis file                       module=main path=node1/config/genesis.json
I[04-27|23:32:43.982] Generated private validator                  module=main path=node2/config/priv_validator.json
I[04-27|23:32:43.982] Generated node key                           module=main path=node2/config/node_key.json
I[04-27|23:32:43.982] Generated genesis file                       module=main path=node2/config/genesis.json
I[04-27|23:32:43.984] Generated private validator                  module=main path=node3/config/priv_validator.json
I[04-27|23:32:43.984] Generated node key                           module=main path=node3/config/node_key.json
I[04-27|23:32:43.984] Generated genesis file                       module=main path=node3/config/genesis.json
Successfully initialized 4 node directories
```

Command run:
```
[greg@ip-10-0-1-132 x]$ gaiad --home ./node0 start
I[04-27|23:34:00.299] Starting ABCI with Tendermint                module=main
I[04-27|23:34:00.326] Starting multiAppConn                        module=proxy impl=multiAppConn
I[04-27|23:34:00.326] Starting localClient                         module=abci-client connection=query impl=localClient
I[04-27|23:34:00.326] Starting localClient                         module=abci-client connection=mempool impl=localClient
I[04-27|23:34:00.326] Starting localClient                         module=abci-client connection=consensus impl=localClient
I[04-27|23:34:00.326] ABCI Handshake                               module=consensus appHeight=0 appHash=
I[04-27|23:34:00.326] ABCI Replay Blocks                           module=consensus appHeight=0 storeHeight=0 stateHeight=0
panic: unexpected end of JSON input

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/cmd/gaia/app.(*GaiaApp).initChainer(0xc4200c4000, 0xea8ce0, 0xc4209bf6e0, 0xc420031880, 0x6, 0xc4201de780, 0x4, 0x4, 0x0, 0x0, ...)
	/home/greg/go/src/github.com/cosmos/cosmos-sdk/cmd/gaia/app/app.go:135 +0x2e5
github.com/cosmos/cosmos-sdk/cmd/gaia/app.(*GaiaApp).(github.com/cosmos/cosmos-sdk/cmd/gaia/app.initChainer)-fm(0xea8ce0, 0xc4209bf6e0, 0xc420031880, 0x6, 0xc4201de780, 0x4, 0x4, 0x0, 0x0, 0x0)
	/home/greg/go/src/github.com/cosmos/cosmos-sdk/cmd/gaia/app/app.go:78 +0x75
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc4200d0c60, 0xc4201de780, 0x4, 0x4, 0x0, 0x0, 0x0)
	/home/greg/go/src/github.com/cosmos/cosmos-sdk/baseapp/baseapp.go:250 +0xc7
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/abci/client.(*localClient).InitChainSync(0xc4209c0e40, 0xc4201de780, 0x4, 0x4, 0x0, 0x0, 0x0, 0x4, 0xc4201de780, 0xc4209d5480)
	/home/greg/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/abci/client/local_client.go:199 +0x81
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc420996b60, 0xc4201de780, 0x4, 0x4, 0x0, 0x0, 0x0, 0xc4200a07a0, 0xc420018598, 0x463dfc)
	/home/greg/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/proxy/app_conn.go:65 +0x53
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc4200c4b00, 0xc4201dc7b0, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/greg/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/consensus/replay.go:267 +0xe9c
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc4200c4b00, 0xeafc60, 0xc4201de300, 0x4, 0xea93e0)
	/home/greg/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/consensus/replay.go:240 +0x3e5
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/proxy.(*multiAppConn).OnStart(0xc4201de300, 0xc4201f3140, 0x15)
	/home/greg/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/proxy/multi_app_conn.go:108 +0x527
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/common.(*BaseService).Start(0xc4201de300, 0x0, 0x0)
	/home/greg/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/common/service.go:130 +0x3bd
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/node.NewNode(0xc4200c1100, 0xea9e20, 0xc42021a900, 0xe9f800, 0xc4209d4b00, 0xc420206650, 0xe39bf8, 0xea93e0, 0xc4209d4b40, 0x14, ...)
	/home/greg/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/node/node.go:168 +0x71c
github.com/cosmos/cosmos-sdk/server.startCmd.startInProcess(0xe3a310, 0xc4201d7260, 0x1d, 0x0)
	/home/greg/go/src/github.com/cosmos/cosmos-sdk/server/start.go:97 +0x296
github.com/cosmos/cosmos-sdk/server.startCmd.run(0xe3a310, 0xc4201d7260, 0xc4200ba280, 0xc4201d7440, 0x0, 0x2, 0x0, 0x0)
	/home/greg/go/src/github.com/cosmos/cosmos-sdk/server/start.go:61 +0x98
github.com/cosmos/cosmos-sdk/server.(startCmd).(github.com/cosmos/cosmos-sdk/server.run)-fm(0xc4200ba280, 0xc4201d7440, 0x0, 0x2, 0x0, 0x0)
	/home/greg/go/src/github.com/cosmos/cosmos-sdk/server/start.go:38 +0x61
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200ba280, 0xc4201d7400, 0x2, 0x2, 0xc4200ba280, 0xc4201d7400)
	/home/greg/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:756 +0x468
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1326040, 0xc08d60, 0xc420019e01, 0xc4201d7360)
	/home/greg/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:846 +0x30a
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).Execute(0x1326040, 0xc4201d7360, 0xc420019f30)
	/home/greg/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:794 +0x2b
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/cli.Executor.Execute(0x1326040, 0xe3a740, 0x2, 0xc42001cb20)
	/home/greg/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/cli/setup.go:89 +0x4e
main.main()
	/home/greg/go/src/github.com/cosmos/cosmos-sdk/cmd/gaia/cmd/gaiad/main.go:44 +0xbf
```

Result: `panic: unexpected end of JSON input`
Expected result: gaiad running

**Comment by ebuchman** [comment]
don't think it should be. gaiad expects things that tendermint will never know about. need to implement `gaiad testnet` to do this
