### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by awrelll** [tendermint/tendermint#1525]
**What happened**:
`gaiad 0.15.0-rc0-0f2aa6b` crashed while I tryed to connect to my sentry, pex is set to false

I'm running my validator node on Ubuntu 16.04.4 LTS + go version go1.10 linux/amd64

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xae9c0b]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/node.(*Node).OnStart(0xc43a3a0240, 0xc43a32b420, 0xd)
	/root/.go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/node/node.go:413 +0x54b
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/common.(*BaseService).Start(0xc43a3a0240, 0xe9a060, 0xc437119710)
	/root/.go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/common/service.go:130 +0x3bd
github.com/cosmos/cosmos-sdk/server.startCmd.startInProcess(0xe2b3c0, 0xc4201c82c0, 0x1d, 0x0)
	/root/.go/src/github.com/cosmos/cosmos-sdk/server/start.go:107 +0x2bd
github.com/cosmos/cosmos-sdk/server.startCmd.run(0xe2b3c0, 0xc4201c82c0, 0xc420107400, 0x13398b0, 0x0, 0x0, 0x0, 0x0)
	/root/.go/src/github.com/cosmos/cosmos-sdk/server/start.go:61 +0x98
github.com/cosmos/cosmos-sdk/server.(startCmd).(github.com/cosmos/cosmos-sdk/server.run)-fm(0xc420107400, 0x13398b0, 0x0, 0x0, 0x0, 0x0)
	/root/.go/src/github.com/cosmos/cosmos-sdk/server/start.go:38 +0x61
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).execute(0xc420107400, 0x13398b0, 0x0, 0x0, 0xc420107400, 0x13398b0)
	/root/.go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:756 +0x468
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1310f20, 0xbfaf00, 0xc420485e01, 0xc4201c83a0)
	/root/.go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:846 +0x30a
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).Execute(0x1310f20, 0xc4201c83a0, 0xc420485f30)
	/root/.go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:794 +0x2b
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/cli.Executor.Execute(0x1310f20, 0xe2b7e8, 0x2, 0xc4200a7910)
	/root/.go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/cli/setup.go:89 +0x4e
main.main()
	/root/.go/src/github.com/cosmos/cosmos-sdk/cmd/gaiad/main.go:44 +0xbf
```

**Comment by ebuchman** [comment]
Looks like AddrBook is used without being initialized when pex=false. Will fix today, thanks

**Comment by ebuchman** [comment]
fixed on develop
