### ISSUE TITLE
Mempool nil conversion bug

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#156]
```
panic: interface conversion: interface is nil, not chan mempool.ResetInfo
​
goroutine 27282008 [running]:
github.com/tendermint/tendermint/mempool.(*MempoolReactor).ResetForBlockAndState(0xc20894b980, 0xc208e54260, 0xc2094d84e0)
	/go/src/github.com/tendermint/tendermint/mempool/reactor.go:99 +0x1b7
github.com/tendermint/tendermint/consensus.(*ConsensusState).saveBlock(0xc2080a08c0, 0xc208e54260, 0xc209152190, 0xc2089f2be0)
	/go/src/github.com/tendermint/tendermint/consensus/state.go:1311 +0x242
github.com/tendermint/tendermint/consensus.(*ConsensusState).FinalizeCommit(0xc2080a08c0, 0x476f)
	/go/src/github.com/tendermint/tendermint/consensus/state.go:1008 +0x622
created by github.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit
	/go/src/github.com/tendermint/tendermint/consensus/state.go:978 +0x2d2
```

**Comment by ebuchman** [comment]
so, I guess this is because peers can be added to the switch, and end up in the memR.Switch.Peers().List(), before they've been added to the reactor (and get the PeerMempoolChKey initialized). so i'll add a check for if the peer.Data.Get(types.PeerMempoolChKey) is nil, and if so just move on
