### ISSUE TITLE
Custom ABCI and Tendermint - Single Binary.

### ISSUE THREAD

**Issue by gianfelipe93** [tendermint/tendermint#1572]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): 0.15.0-381fe193

**ABCI app** (name for built-in, URL for self-written if it's publicly available): https://github.com/blockfreight/go-bftx/blob/feature/single-binary/cmd/bftnode/bftnode.go

**Merkleeyes version** (use `git rev-parse --verify HEAD`, skip if you don't use it):

**Environment**:
- **OS** (e.g. from /etc/os-release): MacOS
- **Install tools**:
- **Others**:

**What happened**: I am trying to create a custom ABCI App (https://github.com/blockfreight/go-bftx/blob/feature/single-binary/cmd/bftnode/bftnode.go) and integrate it with Tendermint to generate a single binary with both.
I created a genesis.json file (https://github.com/blockfreight/go-bftx/blob/feature/single-binary/genesis.json) but when I run the code I am getting the following error:
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x157c2ed]

goroutine 1 [running]:
github.com/blockfreight/go-bftx/vendor/github.com/tendermint/tendermint/state.MakeGenesisState(0xc4200f42a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/gianfelipe/Documents/Go/src/github.com/blockfreight/go-bftx/vendor/github.com/tendermint/tendermint/state/state.go:161 +0x19d
github.com/blockfreight/go-bftx/vendor/github.com/tendermint/tendermint/state.LoadStateFromDBOrGenesisDoc(0x1cd9140, 0xc4201a0020, 0xc4200f42a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/gianfelipe/Documents/Go/src/github.com/blockfreight/go-bftx/vendor/github.com/tendermint/tendermint/state/store.go:52 +0x19a
github.com/blockfreight/go-bftx/vendor/github.com/tendermint/tendermint/node.NewNode(0xc4201ac000, 0x1cd53c0, 0xc4203f8460, 0x1cca6e0, 0xc4205352a0, 0xc4201a9090, 0x18fd390, 0x1cd4620, 0xc4201a8dc0, 0x19, ...)
	/Users/gianfelipe/Documents/Go/src/github.com/blockfreight/go-bftx/vendor/github.com/tendermint/tendermint/node/node.go:153 +0x24a
main.main()
	/Users/gianfelipe/Documents/Go/src/github.com/blockfreight/go-bftx/cmd/bftnode/bftnode.go:101 +0x79f
```

I tried to understand what is causing the error and I think it is because my PubKey doesn't have an address: https://github.com/tendermint/tendermint/blob/v0.15.0/state/state.go#L161

But again, I don't know how to fix it.

**What you expected to happen**: I expected that I would be able to start a new node with my custom ABCI APP.

**How to reproduce it** (as minimally and precisely as possible): Run the following commands:
1. go get github.com/blockfreight/go-bftx
2. cd $GOPATH/src/github.com/blockfreight/go-bftx
3. git fetch
4. git checkout feature/single-binary
5. glide install
6. glide update
7. make
8. bftnode

**Logs (you can paste a part showing an error or attach the whole file)**:
```
1. Getting config
2. Creating logger
3. Creating genesisFile
4. Genesis: &{GenesisTime:2016-04-26 22:00:00 +0000 UTC ChainID:chain-IdealX ConsensusParams:0xc420014400 Validators:[{PubKey:{PubKeyInner:PubKeyEd25519{9C41B6D9945CEC571E32A38252D331EDD893280BB43BF2F1E96AD9FFE2916472}} Power:10 Name:bftx-0}] AppHash: AppOptions:<nil>}
5. Creating Private Validator File
6. Creating Blockfreight App
7. Creating Blockfreight Node
&{2016-04-26 22:00:00 +0000 UTC chain-IdealX 0xc420014780 [{{PubKeyEd25519{9C41B6D9945CEC571E32A38252D331EDD893280BB43BF2F1E96AD9FFE2916472}} 10 bftx-0}]  <nil>} <nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x157c2ed]

goroutine 1 [running]:
github.com/blockfreight/go-bftx/vendor/github.com/tendermint/tendermint/state.MakeGenesisState(0xc4200f42a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/gianfelipe/Documents/Go/src/github.com/blockfreight/go-bftx/vendor/github.com/tendermint/tendermint/state/state.go:161 +0x19d
github.com/blockfreight/go-bftx/vendor/github.com/tendermint/tendermint/state.LoadStateFromDBOrGenesisDoc(0x1cd9140, 0xc4201a0020, 0xc4200f42a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/gianfelipe/Documents/Go/src/github.com/blockfreight/go-bftx/vendor/github.com/tendermint/tendermint/state/store.go:52 +0x19a
github.com/blockfreight/go-bftx/vendor/github.com/tendermint/tendermint/node.NewNode(0xc4201ac000, 0x1cd53c0, 0xc4203f8460, 0x1cca6e0, 0xc4205352a0, 0xc4201a9090, 0x18fd390, 0x1cd4620, 0xc4201a8dc0, 0x19, ...)
	/Users/gianfelipe/Documents/Go/src/github.com/blockfreight/go-bftx/vendor/github.com/tendermint/tendermint/node/node.go:153 +0x24a
main.main()
	/Users/gianfelipe/Documents/Go/src/github.com/blockfreight/go-bftx/cmd/bftnode/bftnode.go:101 +0x79f
```

**`/dump_consensus_state` output for consensus bugs*: 

**Anything else do we need to know**: I think that is all.

Please, let me know if you guys need more information about it.

**Comment by ebuchman** [comment]
> I tried to understand what is causing the error and I think it is because my PubKey doesn't have an address: https://github.com/tendermint/tendermint/blob/v0.15.0/state/state.go#L161


All implementations of `PubKey` must implement an `Address` method. 

Also, 0.15 is old - best to upgrade to 0.19 series

**Comment by gianfelipe93** [comment]
@ebuchman I have create a new issue for this upgrading problem - https://github.com/tendermint/tendermint/issues/1584

**Comment by ebuchman** [comment]
Need to update the `iavl` to the latest and add `go-amino` as a dependency (we switched from go-wire to go-amino)

**Comment by gianfelipe93** [comment]
I get this error sometimes:
```
[ERROR]	Error scanning github.com/tendermint/tmlibs/pubsub: cannot find package "." in:
	/Users/gianfelipe/.glide/cache/src/https-github.com-tendermint-tmlibs/pubsub
[ERROR]	Error scanning github.com/tendermint/tmlibs/pubsub/query: cannot find package "." in:
	/Users/gianfelipe/.glide/cache/src/https-github.com-tendermint-tmlibs/pubsub/query
```

but I am almost sure the packages exist. Do you know what may cause this error ?

**Comment by gianfelipe93** [comment]
I fixed this package error by adding the dependencies:
```
- package: github.com/tendermint/iavl
  version: v0.7.0
- package: github.com/tendermint/go-amino
  version: v0.9.7
- package: github.com/tendermint/tmlibs
  version: v0.8.3-rc0
``` 
But I am still getting the same error (I will show the entire output of the `make` command this time):
```
glide install
[INFO]	Lock file (glide.lock) does not exist. Performing update.
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Fetching github.com/syndtr/goleveldb
[INFO]	--> Fetching github.com/graphql-go/graphql
[INFO]	--> Fetching github.com/tendermint/abci
[INFO]	--> Fetching github.com/tendermint/tendermint
[INFO]	--> Fetching github.com/tendermint/iavl
[INFO]	--> Fetching github.com/tendermint/go-common
[INFO]	--> Fetching github.com/tendermint/go-merkle
[INFO]	--> Fetching github.com/mnmtanish/go-graphiql
[INFO]	--> Fetching github.com/tendermint/go-crypto
[INFO]	--> Fetching github.com/graphql-go/handler
[INFO]	--> Fetching github.com/urfave/cli
[INFO]	--> Fetching github.com/graphql-go/graphql-go-handler
[INFO]	--> Fetching github.com/davecgh/go-spew
[INFO]	--> Fetching github.com/tendermint/go-amino
[INFO]	--> Fetching github.com/tendermint/tmlibs
[INFO]	--> Setting version for github.com/tendermint/tendermint to v0.19.3.
[INFO]	--> Detected semantic version. Setting version for github.com/urfave/cli to v1.19.1
[INFO]	--> Setting version for github.com/tendermint/iavl to v0.7.0.
[INFO]	--> Setting version for github.com/tendermint/tmlibs to v0.8.3-rc0.
[INFO]	--> Setting version for github.com/tendermint/go-amino to v0.9.7.
[INFO]	--> Detected semantic version. Setting version for github.com/tendermint/go-crypto to v0.6.2
[INFO]	--> Detected semantic version. Setting version for github.com/davecgh/go-spew to v1.1.0
[INFO]	--> Detected semantic version. Setting version for github.com/tendermint/abci to v0.10.3
[INFO]	Resolving imports
[INFO]	--> Fetching github.com/pkg/errors
[INFO]	--> Fetching golang.org/x/crypto
[INFO]	--> Fetching github.com/go-kit/kit
[INFO]	--> Detected semantic version. Setting version for github.com/go-kit/kit to v0.7.0
[INFO]	--> Fetching github.com/go-logfmt/logfmt
[INFO]	--> Detected semantic version. Setting version for github.com/go-logfmt/logfmt to v0.3.0
[INFO]	--> Fetching golang.org/x/net
[INFO]	--> Fetching google.golang.org/grpc
[INFO]	--> Fetching github.com/gogo/protobuf
[INFO]	--> Detected semantic version. Setting version for github.com/gogo/protobuf to v1.0.0
[INFO]	--> Fetching github.com/tendermint/go-wire
[INFO]	--> Setting version for github.com/tendermint/go-wire to master.
[INFO]	--> Fetching github.com/golang/protobuf
[INFO]	--> Fetching gopkg.in/yaml.v2
[INFO]	--> Fetching github.com/btcsuite/btcd
[INFO]	--> Fetching github.com/tendermint/ed25519
[WARN]	Conflict: github.com/tendermint/tmlibs rev is currently v0.8.3-rc0, but github.com/tendermint/iavl wants develop
[INFO]	github.com/tendermint/tmlibs reference v0.8.3-rc0:
[INFO] - author: Jae Kwon <jae@tendermint.com>
[INFO] - commit date: Mon, 23 Apr 2018 02:36:49 -0700
[INFO] - subject (first line): Add developer branch 0.8.3 to CHANGELOG
[INFO]	Keeping github.com/tendermint/tmlibs v0.8.3-rc0
[INFO]	--> Fetching github.com/ebuchman/fail-test
[INFO]	--> Fetching github.com/gorilla/websocket
[INFO]	--> Fetching github.com/jmhodges/levigo
[INFO]	--> Fetching github.com/rcrowley/go-metrics
[INFO]	--> Fetching github.com/go-stack/stack
[INFO]	--> Fetching github.com/kr/logfmt
[INFO]	--> Fetching google.golang.org/genproto
[INFO]	--> Fetching github.com/golang/snappy
[INFO]	--> Fetching golang.org/x/text
[INFO]	Downloading dependencies. Please wait...
[INFO]	Setting references for remaining imports
[INFO]	Exporting resolved dependencies...
[INFO]	--> Exporting github.com/tendermint/iavl
[INFO]	--> Exporting github.com/tendermint/go-amino
[INFO]	--> Exporting github.com/davecgh/go-spew
[INFO]	--> Exporting github.com/tendermint/tmlibs
[INFO]	--> Exporting github.com/tendermint/go-common
[INFO]	--> Exporting github.com/syndtr/goleveldb
[INFO]	--> Exporting github.com/tendermint/tendermint
[INFO]	--> Exporting github.com/graphql-go/handler
[INFO]	--> Exporting github.com/tendermint/abci
[INFO]	--> Exporting github.com/go-logfmt/logfmt
[INFO]	--> Exporting github.com/tendermint/go-crypto
[INFO]	--> Exporting github.com/tendermint/go-merkle
[INFO]	--> Exporting github.com/graphql-go/graphql
[INFO]	--> Exporting github.com/graphql-go/graphql-go-handler
[INFO]	--> Exporting github.com/urfave/cli
[INFO]	--> Exporting github.com/mnmtanish/go-graphiql
[INFO]	--> Exporting github.com/pkg/errors
[INFO]	--> Exporting github.com/go-kit/kit
[INFO]	--> Exporting golang.org/x/net
[INFO]	--> Exporting golang.org/x/crypto
[INFO]	--> Exporting github.com/gogo/protobuf
[INFO]	--> Exporting github.com/tendermint/go-wire
[INFO]	--> Exporting github.com/golang/protobuf
[INFO]	--> Exporting github.com/btcsuite/btcd
[INFO]	--> Exporting github.com/tendermint/ed25519
[INFO]	--> Exporting github.com/ebuchman/fail-test
[INFO]	--> Exporting github.com/gorilla/websocket
[INFO]	--> Exporting google.golang.org/grpc
[INFO]	--> Exporting github.com/jmhodges/levigo
[INFO]	--> Exporting github.com/rcrowley/go-metrics
[INFO]	--> Exporting github.com/kr/logfmt
[INFO]	--> Exporting github.com/go-stack/stack
[INFO]	--> Exporting github.com/golang/snappy
[INFO]	--> Exporting google.golang.org/genproto
[INFO]	--> Exporting golang.org/x/text
[INFO]	--> Exporting gopkg.in/yaml.v2
[INFO]	Replacing existing vendor dependencies
[INFO]	Project relies on 36 dependencies.
go get github.com/mitchellh/gox github.com/rigelrozanski/shelldown/cmd/shelldown
go install ./cmd/...
# github.com/blockfreight/go-bftx/vendor/github.com/tendermint/iavl
vendor/github.com/tendermint/iavl/node.go:13:2: imported and not used: "github.com/blockfreight/go-bftx/vendor/github.com/tendermint/go-wire" as amino
vendor/github.com/tendermint/iavl/node.go:56:14: undefined: wire
vendor/github.com/tendermint/iavl/node.go:59:17: undefined: wire
vendor/github.com/tendermint/iavl/node.go:62:21: undefined: wire
vendor/github.com/tendermint/iavl/node.go:71:24: undefined: wire
vendor/github.com/tendermint/iavl/node.go:76:23: undefined: wire
vendor/github.com/tendermint/iavl/node.go:82:24: undefined: wire
vendor/github.com/tendermint/iavl/node.go:221:2: undefined: wire
vendor/github.com/tendermint/iavl/proof.go:10:2: imported and not used: "github.com/blockfreight/go-bftx/vendor/github.com/tendermint/go-wire" as amino
vendor/github.com/tendermint/iavl/proof_key.go:8:2: imported and not used: "github.com/blockfreight/go-bftx/vendor/github.com/tendermint/go-wire" as amino
vendor/github.com/tendermint/iavl/node.go:221:2: too many errors
make: *** [install] Error 2
```

**Comment by zramsay** [comment]
try `rm -r github.com/blockfreight/go-bftx/vendor` and `glide cc` then run it again

**Comment by gianfelipe93** [comment]
Hello @zramsay 

I tried it, but still getting the same error:
```
~/Documents/Go/src/github.com/blockfreight/go-bftx   feature/single-binary  rm -r vendor                                                                                                                                                          
~/Documents/Go/src/github.com/blockfreight/go-bftx   feature/single-binary  glide cc                                                                                                                                                                
[INFO]	Glide cache has been cleared.
~/Documents/Go/src/github.com/blockfreight/go-bftx   feature/single-binary  make                                                                                                                                                                    
glide install
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Fetching github.com/rcrowley/go-metrics
[INFO]	--> Fetching github.com/pkg/errors
[INFO]	--> Fetching github.com/mnmtanish/go-graphiql
[INFO]	--> Fetching github.com/davecgh/go-spew
[INFO]	--> Fetching github.com/kr/logfmt
[INFO]	--> Fetching github.com/btcsuite/btcd
[INFO]	--> Fetching github.com/tendermint/abci
[INFO]	--> Fetching github.com/syndtr/goleveldb
[INFO]	--> Fetching github.com/go-logfmt/logfmt
[INFO]	--> Fetching github.com/golang/snappy
[INFO]	--> Fetching github.com/go-stack/stack
[INFO]	--> Fetching github.com/gogo/protobuf
[INFO]	--> Fetching github.com/golang/protobuf
[INFO]	--> Fetching github.com/ebuchman/fail-test
[INFO]	--> Fetching github.com/gorilla/websocket
[INFO]	--> Fetching github.com/graphql-go/graphql
[INFO]	--> Fetching github.com/graphql-go/graphql-go-handler
[INFO]	--> Fetching github.com/jmhodges/levigo
[INFO]	--> Fetching github.com/graphql-go/handler
[INFO]	--> Fetching github.com/go-kit/kit
[INFO]	--> Fetching github.com/tendermint/ed25519
[INFO]	--> Fetching github.com/tendermint/go-amino
[INFO]	--> Fetching github.com/tendermint/go-common
[INFO]	--> Fetching github.com/tendermint/go-crypto
[INFO]	--> Fetching github.com/tendermint/go-merkle
[INFO]	--> Fetching github.com/tendermint/go-wire
[INFO]	--> Fetching github.com/tendermint/iavl
[INFO]	--> Fetching github.com/tendermint/tendermint
[INFO]	--> Fetching github.com/tendermint/tmlibs
[INFO]	--> Fetching github.com/urfave/cli
[INFO]	--> Fetching golang.org/x/crypto
[INFO]	--> Fetching golang.org/x/net
[INFO]	--> Fetching golang.org/x/text
[INFO]	--> Fetching google.golang.org/genproto
[INFO]	--> Fetching google.golang.org/grpc
[INFO]	--> Fetching gopkg.in/yaml.v2
[INFO]	Setting references.
[INFO]	--> Setting version for github.com/kr/logfmt to b84e30acd515aadc4b783ad4ff83aff3299bdfe0.
[INFO]	--> Setting version for github.com/mnmtanish/go-graphiql to cef5a61bd62b996aa67029c6c858f673d6e51718.
[INFO]	--> Setting version for github.com/rcrowley/go-metrics to e2704e165165ec55d062f5919b4b29494e9fa790.
[INFO]	--> Setting version for github.com/graphql-go/graphql to 51e8a07b6f0348c492363059ce33f9a91f75f3f9.
[INFO]	--> Setting version for github.com/go-logfmt/logfmt to 390ab7935ee28ec6b286364bba9b4dd6410cb3d5.
[INFO]	--> Setting version for github.com/gogo/protobuf to 1adfc126b41513cc696b209667c8656ea7aac67c.
[INFO]	--> Setting version for github.com/graphql-go/graphql-go-handler to c1c8ee7b173a5f70fe039529659fbb30f1a435a0.
[INFO]	--> Setting version for github.com/btcsuite/btcd to 1432d294a5b055c297457c25434efbf13384cc46.
[INFO]	--> Setting version for github.com/syndtr/goleveldb to 9637fa0b2f0db13c99d899b91007edb7df4610b7.
[INFO]	--> Setting version for github.com/golang/protobuf to 927b65914520a8b7d44f5c9057611cfec6b2e2d0.
[INFO]	--> Setting version for github.com/gorilla/websocket to 21ab95fa12b9bdd8fecf5fa3586aad941cc98785.
[INFO]	--> Setting version for github.com/tendermint/abci to 78a8905690ef54f9d57e3b2b0ee7ad3a04ef3f1f.
[INFO]	--> Setting version for github.com/ebuchman/fail-test to 95f809107225be108efcf10a3509e4ea6ceef3c4.
[INFO]	--> Setting version for github.com/golang/snappy to 553a641470496b2327abcac10b36396bd98e45c9.
[INFO]	--> Setting version for github.com/go-kit/kit to ca4112baa34cb55091301bdc13b1420a122b1b9e.
[INFO]	--> Setting version for github.com/davecgh/go-spew to 346938d642f2ec3594ed81d874461961cd0faa76.
[INFO]	--> Setting version for github.com/pkg/errors to 816c9085562cd7ee03e7f8188a1cfd942858cded.
[INFO]	--> Setting version for github.com/go-stack/stack to 259ab82a6cad3992b4e21ff5cac294ccb06474bc.
[INFO]	--> Setting version for github.com/graphql-go/handler to c1c8ee7b173a5f70fe039529659fbb30f1a435a0.
[INFO]	--> Setting version for github.com/jmhodges/levigo to c42d9e0ca023e2198120196f842701bb4c55d7b9.
[INFO]	--> Setting version for github.com/tendermint/ed25519 to d8387025d2b9d158cf4efb07e7ebf814bcce2057.
[INFO]	--> Setting version for github.com/tendermint/go-amino to c7424fdd930314cc4c344b331e112dac004718ef.
[INFO]	--> Setting version for github.com/tendermint/go-crypto to 915416979bf70efa4bcbf1c6cd5d64c5fff9fc19.
[INFO]	--> Setting version for github.com/tendermint/go-common to c23635790521deee1b50b6489e47717bff473606.
[INFO]	--> Setting version for github.com/tendermint/go-merkle to 714d4d04557fd068a7c2a1748241ce8428015a96.
[INFO]	--> Setting version for github.com/tendermint/go-wire to ecf42f8907e063f630fcce7605c61252db93c355.
[INFO]	--> Setting version for github.com/tendermint/iavl to fd37a0fa3a7454423233bc3d5ea828f38e0af787.
[INFO]	--> Setting version for github.com/tendermint/tmlibs to cc5f287c4798ffe88c04d02df219ecb6932080fd.
[INFO]	--> Setting version for github.com/tendermint/tendermint to aab98828fe4904965fb1c4eeed16dc6aae0e14b6.
[INFO]	--> Setting version for github.com/urfave/cli to 0bdeddeeb0f650497d603c4ad7b20cfe685682f6.
[INFO]	--> Setting version for golang.org/x/crypto to 1a580b3eff7814fc9b40602fd35256c63b50f491.
[INFO]	--> Setting version for google.golang.org/grpc to be1fb4f27549f736b9b4ec26104c7c6b29845ad0.
[INFO]	--> Setting version for google.golang.org/genproto to 7bb2a897381c9c5ab2aeb8614f758d7766af68ff.
[INFO]	--> Setting version for golang.org/x/net to 2491c5de3490fced2f6cff376127c667efeed857.
[INFO]	--> Setting version for golang.org/x/text to 5c1cf69b5978e5a34c5f9ba09a83e56acc4b7877.
[INFO]	--> Setting version for gopkg.in/yaml.v2 to 5420a8b6744d3b0345ab293f6fcba19c978f1183.
[INFO]	Exporting resolved dependencies...
[INFO]	--> Exporting github.com/btcsuite/btcd
[INFO]	--> Exporting github.com/go-kit/kit
[INFO]	--> Exporting github.com/gogo/protobuf
[INFO]	--> Exporting github.com/golang/snappy
[INFO]	--> Exporting github.com/ebuchman/fail-test
[INFO]	--> Exporting github.com/tendermint/abci
[INFO]	--> Exporting github.com/go-logfmt/logfmt
[INFO]	--> Exporting github.com/davecgh/go-spew
[INFO]	--> Exporting github.com/go-stack/stack
[INFO]	--> Exporting github.com/graphql-go/graphql
[INFO]	--> Exporting github.com/kr/logfmt
[INFO]	--> Exporting github.com/graphql-go/graphql-go-handler
[INFO]	--> Exporting github.com/jmhodges/levigo
[INFO]	--> Exporting github.com/gorilla/websocket
[INFO]	--> Exporting github.com/graphql-go/handler
[INFO]	--> Exporting github.com/golang/protobuf
[INFO]	--> Exporting github.com/rcrowley/go-metrics
[INFO]	--> Exporting github.com/mnmtanish/go-graphiql
[INFO]	--> Exporting github.com/pkg/errors
[INFO]	--> Exporting github.com/syndtr/goleveldb
[INFO]	--> Exporting github.com/tendermint/ed25519
[INFO]	--> Exporting github.com/tendermint/go-amino
[INFO]	--> Exporting github.com/tendermint/go-common
[INFO]	--> Exporting github.com/tendermint/go-merkle
[INFO]	--> Exporting github.com/tendermint/go-wire
[INFO]	--> Exporting github.com/tendermint/go-crypto
[INFO]	--> Exporting github.com/tendermint/iavl
[INFO]	--> Exporting github.com/tendermint/tendermint
[INFO]	--> Exporting github.com/tendermint/tmlibs
[INFO]	--> Exporting github.com/urfave/cli
[INFO]	--> Exporting golang.org/x/net
[INFO]	--> Exporting golang.org/x/text
[INFO]	--> Exporting google.golang.org/genproto
[INFO]	--> Exporting google.golang.org/grpc
[INFO]	--> Exporting gopkg.in/yaml.v2
[INFO]	--> Exporting golang.org/x/crypto
[INFO]	Replacing existing vendor dependencies
go get github.com/mitchellh/gox github.com/rigelrozanski/shelldown/cmd/shelldown
go install ./cmd/...
# github.com/blockfreight/go-bftx/vendor/github.com/tendermint/iavl
vendor/github.com/tendermint/iavl/node.go:13:2: imported and not used: "github.com/blockfreight/go-bftx/vendor/github.com/tendermint/go-wire" as amino
vendor/github.com/tendermint/iavl/node.go:56:14: undefined: wire
vendor/github.com/tendermint/iavl/node.go:59:17: undefined: wire
vendor/github.com/tendermint/iavl/node.go:62:21: undefined: wire
vendor/github.com/tendermint/iavl/node.go:71:24: undefined: wire
vendor/github.com/tendermint/iavl/node.go:76:23: undefined: wire
vendor/github.com/tendermint/iavl/node.go:82:24: undefined: wire
vendor/github.com/tendermint/iavl/node.go:221:2: undefined: wire
vendor/github.com/tendermint/iavl/proof.go:10:2: imported and not used: "github.com/blockfreight/go-bftx/vendor/github.com/tendermint/go-wire" as amino
vendor/github.com/tendermint/iavl/proof_key.go:8:2: imported and not used: "github.com/blockfreight/go-bftx/vendor/github.com/tendermint/go-wire" as amino
vendor/github.com/tendermint/iavl/node.go:221:2: too many errors
make: *** [install] Error 2
```

**Comment by gianfelipe93** [comment]
@zramsay I have create a new issue for this upgrading problem - #1584

**Comment by gianfelipe93** [comment]
Hey guys,

is there any documentation/example to help me understand how to compile my app and get a single binary which would container Tendermint and my app inside of it ?

**Comment by melekes** [comment]
Hey! No, there is no such docs at the moment.

You'll need to provide different client creator here https://github.com/tendermint/tendermint/blob/c84be3b8ddf46040567897f7d8163d35aa561a25/node/node.go#L81

It will look like this:

```go
func GiansAppClientCreator(addr, transport, dbDir string) ClientCreator {
	return NewLocalClientCreator(gianapp.NewApplication())
}

n := NewNode(config,
		privval.LoadOrGenFilePV(config.PrivValidatorFile()),
		GiansAppClientCreator(config.ProxyApp, config.ABCI, config.DBDir()),
		DefaultGenesisDocProviderFunc(config),
		DefaultDBProvider,
		logger,
	)
if err := n.Start(); err != nil {
	return fmt.Errorf("Failed to start node: %v", err)
}
logger.Info("Started node", "nodeInfo", n.Switch().NodeInfo())

// Trap signal, run forever.
n.RunForever()
```
