### ISSUE TITLE
Null pointer access

### ISSUE THREAD

**Issue by zmanian** [tendermint/tendermint#1631]
Tendermint v0.19.6-rc1

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xacc957]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/consensus.(*baseWAL).SearchForEndHeight(0xc42948a5a0, 0x21619, 0xc4296186f0, 0xbaf720, 0xc42573ffc0, 0x16, 0x20)
	/home/zaki/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/consensus/wal.go:179 +0x2a7
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).catchupReplay(0xc4253442c0, 0x21619, 0x0, 0x0)
	/home/zaki/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/consensus/replay.go:110 +0xbb
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart(0xc4253442c0, 0xc425224340, 0x17)
	/home/zaki/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/consensus/state.go:264 +0x18f
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/common.(*BaseService).Start(0xc4253442c0, 0xcf9100, 0x11)
	/home/zaki/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/common/service.go:130 +0x3bd
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusReactor).OnStart(0xc4201f9e00, 0xc4252241a0, 0x19)
	/home/zaki/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/consensus/reactor.go:68 +0x132
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/common.(*BaseService).Start(0xc4201f9e00, 0x0, 0x0)
	/home/zaki/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/common/service.go:130 +0x3bd
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/p2p.(*Switch).OnStart(0xc420031b80, 0xc42622bee0, 0x13)
	/home/zaki/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/p2p/switch.go:181 +0xc6
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/common.(*BaseService).Start(0xc420031b80, 0xc423ca5bc0, 0x1)
	/home/zaki/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/common/service.go:130 +0x3bd
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/node.(*Node).OnStart(0xc42020de00, 0xc428615cd0, 0xd)
	/home/zaki/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/node/node.go:418 +0x576
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/common.(*BaseService).Start(0xc42020de00, 0xec09c0, 0xc4201021b0)
	/home/zaki/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/common/service.go:130 +0x3bd
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc42000cf60, 0xc42000cfa0, 0x1d, 0x0)
	/home/zaki/go/src/github.com/cosmos/cosmos-sdk/server/start.go:90 +0x2bd
github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc4201c8a00, 0x136bc28, 0x0, 0x0, 0x0, 0x0)
	/home/zaki/go/src/github.com/cosmos/cosmos-sdk/server/start.go:34 +0xaa
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).execute(0xc4201c8a00, 0x136bc28, 0x0, 0x0, 0xc4201c8a00, 0x136bc28)
	/home/zaki/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:762 +0x468
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4201c8280, 0xc1aec0, 0xc420947e01, 0xc42000d140)
	/home/zaki/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4201c8280, 0xc42000d140, 0xc420947ed8)
	/home/zaki/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/cli.Executor.Execute(0xc4201c8280, 0xe4e8b0, 0x2, 0xc420039460)
	/home/zaki/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/cli/setup.go:89 +0x4e
main.main()
	/home/zaki/go/src/github.com/cosmos/cosmos-sdk/cmd/gaia/cmd/gaiad/main.go:32 +0x209

```

**Comment by ebuchman** [comment]
Any chance you can post the WAL file this is happening against ?

**Comment by zmanian** [comment]
I rebooted and it didn't reoccur.

**Comment by melekes** [comment]
Should be fixed by https://github.com/tendermint/tendermint/pull/1607
