### ISSUE TITLE
bind: can't assign requested address

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#1632]
OSX go1.10.1 darwin/amd64

```
ok  	github.com/tendermint/tendermint/mempool	3.328s
ok  	github.com/tendermint/tendermint/node	0.094s
2018/05/26 21:59:23 net.Listen tcp :0: listen tcp 127.0.0.2:0: bind: can't assign requested address
FAIL	github.com/tendermint/tendermint/p2p	2.307s
ok  	github.com/tendermint/tendermint/p2p/conn	11.109s
?   	github.com/tendermint/tendermint/p2p/dummy	[no test files]
--- FAIL: TestPEXReactorUsesSeedsIfNeeded (4.01s)
panic: listen tcp 127.0.0.4:33478: bind: can't assign requested address [recovered]
	panic: listen tcp 127.0.0.4:33478: bind: can't assign requested address

goroutine 10 [running]:
testing.tRunner.func1(0xc42041ea50)
	/usr/local/go/src/testing/testing.go:742 +0x29d
panic(0x1446e80, 0xc420182820)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/tendermint/tendermint/p2p.NewDefaultListener(0x14b6343, 0x3, 0xc4200acdb0, 0xf, 0x14b8701, 0x1633020, 0x18874a0, 0xc420108420, 0x24)
	/Users/jae/gocode/src/github.com/tendermint/tendermint/p2p/listener.go:67 +0x83d
github.com/tendermint/tendermint/p2p/pex.TestPEXReactorUsesSeedsIfNeeded(0xc42041ea50)
	/Users/jae/gocode/src/github.com/tendermint/tendermint/p2p/pex/pex_reactor_test.go:232 +0x207
testing.tRunner(0xc42041ea50, 0x15f7e08)
	/usr/local/go/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:824 +0x2e0
FAIL	github.com/tendermint/tendermint/p2p/pex	4.092s
ok  	github.com/tendermint/tendermint/p2p/trust	(cached)
```

**Comment by xla** [comment]
This is a limitation off macOS[0] as the RFC[1] is explicit about `127.0.0/8`. It's not sensible to expect that devs run an array on sudo commands in order to make this work, so we need to find a different way of addressing this issue. Noteworthy this works in linux environments.

[0] https://superuser.com/questions/458875/how-do-you-get-loopback-addresses-other-than-127-0-0-1-to-work-on-os-x
[1] https://tools.ietf.org/html/rfc3330.html
