### ISSUE TITLE
Panic in wal after node restart

### ISSUE THREAD

**Issue by zmanian** [tendermint/tendermint#1659]
I've seen this happen to both my nodes on gaia-5001 when I restarted them.

I took a snapshot of the machine so we can debug.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb1b7e7]

goroutine 33 [running]:
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/consensus.(*baseWAL).SearchForEndHeight(0xc4279b3590, 0x35c7b, 0xc4254beb90, 0x20, 0xc426500c00, 0x7f92a92c5850, 0x0)
	/home/ubuntu/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/consensus/wal.go:179 +0x2a7
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).catchupReplay(0xc42691eb00, 0x35c7b, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/consensus/replay.go:110 +0xc8
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart(0xc42691eb00, 0xc42c8f9ea0, 0x17)
	/home/ubuntu/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/consensus/state.go:255 +0x169
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/common.(*BaseService).Start(0xc42691eb00, 0xc4287862e0, 0x9)
	/home/ubuntu/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/common/service.go:130 +0x405
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusReactor).SwitchToConsensus(0xc427cd2680, 0xc4287862e0, 0x9, 0x35c7a, 0xc2, 0xc427ccc8a0, 0x14, 0x14, 0x1, 0xc427ccc8c0, ...)
	/home/ubuntu/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/consensus/reactor.go:101 +0x177
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine(0xc427432000)
	/home/ubuntu/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/blockchain/reactor.go:259 +0x1507
created by github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).OnStart
	/home/ubuntu/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/blockchain/reactor.go:117 +0x90

```

**Comment by melekes** [comment]
Isn't this the same as https://github.com/tendermint/tendermint/issues/1631?

**Comment by zmanian** [comment]
I am not sure. 

This error basically stopped gaia-5001. Many peers are experiencing it on restart.

It doesn't self repair like the previous one.

I have a disk snapshot of a machine in this state.

**Comment by melekes** [comment]
What tendermint version?

**Comment by zmanian** [comment]
This SDK tag
https://github.com/cosmos/cosmos-sdk/tree/v0.17.3-rc1

I believe v0.19.6

**Comment by zmanian** [comment]
I think everyone who experienced this issue was on v0.17-3-rc1 and not the latest v0.17.3 when this issue cropped up.

**Comment by melekes** [comment]
Need a WAL file(s) for analysis.

**Comment by melekes** [comment]
```
$ ./wal2json ~/.gaiad/data/cs.wal/wal
panic: failed to decode msg: checksums do not match: (read: 2332507906, actual: 3113055119)

goroutine 1 [running]:
main.main()
        /home/ubuntu/go/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/scripts/wal2json/main.go:36 +0x56e
```

for _some reason_ checksums do not match
