### ISSUE TITLE
Full node crashes with too many RPC connections 

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1740]
A full node will crash if a user opens a great number of RPC connections over websockets.

**Comment by xla** [comment]
@ebuchman Do you have a trace or log dump for this?

**Comment by ebuchman** [comment]
No, it was reported anecdotally. Should be replicateable by just opening many websocket connections

**Comment by ebuchman** [comment]
Here's a log from one of my machines crashing as reported in #1755 : 
[gaiad.6002.oom.log](https://github.com/tendermint/tendermint/files/2107608/gaiad.6002.oom.log)

**Comment by ebuchman** [comment]
Here's a persistent record in the heap dump from the pprof server. Note this is after I killed the websocket client, so it should have been cleaned up. Looks like some memory is not being collected:

```

0: 0 [1: 4864] @ 0x10d21dd 0x10d1b91 0x10d1f79 0x1327d31 0x1327fa1 0x1320375 0x16ae531 0x16ad0c6 0x14592ad 0x16af0bb 0x16c9288 0x12ce204 0x12cfe70 0x16b3623 0x12ce204 0x12d0f5c 0x12cd221 0x1059811
#	0x10d21dc	bytes.makeSlice+0x6c											/Users/ethanbuchman/goRoot/1.10/src/bytes/buffer.go:230
#	0x10d1b90	bytes.(*Buffer).grow+0x150										/Users/ethanbuchman/goRoot/1.10/src/bytes/buffer.go:144
#	0x10d1f78	bytes.(*Buffer).WriteString+0xd8									/Users/ethanbuchman/goRoot/1.10/src/bytes/buffer.go:186
#	0x1327d30	encoding/json.newline+0x80										/Users/ethanbuchman/goRoot/1.10/src/encoding/json/indent.go:64
#	0x1327fa0	encoding/json.Indent+0x240										/Users/ethanbuchman/goRoot/1.10/src/encoding/json/indent.go:116
#	0x1320374	encoding/json.MarshalIndent+0xe4									/Users/ethanbuchman/goRoot/1.10/src/encoding/json/encode.go:177
#	0x16ae530	github.com/tendermint/tendermint/rpc/lib/server.(*wsConnection).writeRoutine+0x320			/Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/rpc/lib/server/handlers.go:665
#	0x16ad0c5	github.com/tendermint/tendermint/rpc/lib/server.(*wsConnection).OnStart+0x85				/Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/rpc/lib/server/handlers.go:476
#	0x14592ac	github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common.(*BaseService).Start+0x3bc	/Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common/service.go:130
#	0x16af0ba	github.com/tendermint/tendermint/rpc/lib/server.(*WebsocketManager).WebsocketHandler+0x39a		/Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/rpc/lib/server/handlers.go:739
#	0x16c9287	github.com/tendermint/tendermint/rpc/lib/server.(*WebsocketManager).WebsocketHandler-fm+0x47		/Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/node/node.go:508
#	0x12ce203	net/http.HandlerFunc.ServeHTTP+0x43									/Users/ethanbuchman/goRoot/1.10/src/net/http/server.go:1947
#	0x12cfe6f	net/http.(*ServeMux).ServeHTTP+0x12f									/Users/ethanbuchman/goRoot/1.10/src/net/http/server.go:2337
#	0x16b3622	github.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1+0x3e2			/Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/rpc/lib/server/http_server.go:138
#	0x12ce203	net/http.HandlerFunc.ServeHTTP+0x43									/Users/ethanbuchman/goRoot/1.10/src/net/http/server.go:1947
#	0x12d0f5b	net/http.serverHandler.ServeHTTP+0xbb									/Users/ethanbuchman/goRoot/1.10/src/net/http/server.go:2694
#	0x12cd220	net/http.(*conn).serve+0x650										/Users/ethanbuchman/goRoot/1.10/src/net/http/server.go:1830

```

**Comment by melekes** [comment]
```
I[06-18|21:19:03.613] Served RPC HTTP response                     module=rpc-server method=GET url=/consensus_state status=200 duration=0 remoteAddr=127.0.0.1:33874             2018/06/18 21:19:03 http: Accept error: accept tcp [::]:46657: accept4: too many open files; retrying in 1s
I[06-18|21:19:03.884] HTTPRestRPC                                  module=rpc-server method=/validators args="[<*int64 Value>]" returns="[<*core_types.ResultValidators Value> <error Value>]"
I[06-18|21:19:03.885] Served RPC HTTP response                     module=rpc-server method=GET url=/validators status=200 duration=1 remoteAddr=127.0.0.1:33936                  I[06-18|21:19:03.885] HTTPRestRPC                                  module=rpc-server method=/status args=[] returns="[<*core_types.ResultStatus Value> <error Value>]"
I[06-18|21:19:03.885] Served RPC HTTP response                     module=rpc-server method=GET url=/status status=200 duration=0 remoteAddr=127.0.0.1:33874                      I[06-18|21:19:03.970] Timed out                                    module=consensus dur=3s height=197705 round=0 step=RoundStepPropose
panic: open /home/pz/.gaiad/data/cs.wal/wal: too many open files

goroutine 3001 [running]:                                                                                                                                                         github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/autofile.(*Group).checkHeadSizeLimit(0xc43e18a320)
        /home/pz/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/autofile/group.go:225 +0xa9
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/autofile.(*Group).processTicks(0xc43e18a320)                                                                             /home/pz/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/autofile/group.go:207 +0x2d
created by github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/autofile.(*Group).OnStart                                                                                     /home/pz/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tmlibs/autofile/group.go:105 +0x3f
```

```
Peng:
I did some digging into this `too many open files` error. The issue is the system's max open files per process.
This is the command to find how many files `gaiad` has open:
`ls /proc/(pidof gaiad)/fd/ | wc -l`
For my Debian instance, `ulimit -Sn` (the max open files per process) is `1024`
For my faucet node, which has not gone down yet, `ls /proc/(pidof gaiad)/fd/ | wc -l` returns `963` files open
For my explorer and validator nodes, both have crashed twice already tue to `too many open files`. I surmise that both of those nodes' `gaiad` processes attempted to open more than `1024` files.

My temporary solution will be to edit `vi /etc/security/limits.conf` and increase the system's open files limit per process to 2048 and see what happens.

Ethan:
defntly doesnt seem right that they just keep growing

Peng:
Ok, both nodes crashed again. Validator due to `CONSENSUS FAILURE - too many open files`. Will attempt to increase the fd limit now
```

**Comment by melekes** [comment]
We need to bound the number of WS connections.

**Comment by xla** [comment]
> We need to bound the number of WS connections. and it's better if the node do not crash in any case

It would be a good start if we expose metrics for such resources, i.e. number of open connection (websocket, p2p, etc.).
