### ISSUE TITLE
Bug in the blockpool

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#185]
Got this error on a live chain. Have not been able to reproduce yet. Appears that while a node was fast syncing, it received blocks from a node on a different chain with only one validator.

```
INFO[02-26|11:43:20] error in validation                      module=blockchain error="Invalid validation -- wrong set size: 7 vs 1"
INFO[02-26|11:43:20] TrySend                                  module=p2p channel=40 conn=MConn{10.0.0.16:60807} msg="[bcBlockRequestMessage 994]"
INFO[02-26|11:43:20] Consensus ticker                         module=blockchain numPending=259 total=298 outbound=7 inbound=3
INFO[02-26|11:43:20] TrySend                                  module=p2p channel=40 conn=MConn{10.0.1.4:46656} msg="[bcBlockRequestMessage 995]"
INFO[02-26|11:43:20] TrySend                                  module=p2p channel=40 conn=MConn{10.0.0.9:46656} msg="[bcBlockRequestMessage 996]"
INFO[02-26|11:43:20] TrySend                                  module=p2p channel=40 conn=MConn{10.0.0.37:44787} msg="[bcBlockRequestMessage 997]"
INFO[02-26|11:43:20] TrySend                                  module=p2p channel=40 conn=MConn{10.0.0.29:46656} msg="[bcBlockRequestMessage 998]"
INFO[02-26|11:43:20] TrySend                                  module=p2p channel=40 conn=MConn{10.0.0.44:46656} msg="[bcBlockRequestMessage 999]"
INFO[02-26|11:43:20] TrySend                                  module=p2p channel=40 conn=MConn{10.0.0.37:44787} msg="[bcBlockRequestMessage 1000]"
INFO[02-26|11:43:20] error in validation                      module=blockchain error="Invalid validation -- wrong set size: 7 vs 1"
panic: Paniced on a Sanity Check: Expected block to be non-nil

goroutine 30 [running]:
github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/common.PanicSanity(0x991520, 0xc820096fe0)
        /go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/common/errors.go:26 +0xf5
github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/blockchain.(*BlockPool).RedoRequest(0xc820156c80, 0x379)
        /go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/blockchain/pool.go:187 +0x104
github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine(0xc820156dc0)
        /go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/blockchain/reactor.go:224 +0x11ef
created by github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).OnStart
        /go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/blockchain/reactor.go:86 +0xff

goroutine 1 [chan receive]:
main.main()
        /go/src/github.com/eris-ltd/eris-db/cmd/erisdb/main.go:31 +0x301

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 11 [select]:
github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc8200ce380)
        /go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205 +0x271
created by github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
        /go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:236 +0x26b
```

**Comment by ebuchman** [comment]
on a related note, not sure we ensure genesis states are synced. is something we should check in the peer handshake

**Comment by ebuchman** [comment]
Unable to replicate using the following:
- start a test net of 4 nodes, let it grow. 
- kill and rm one node. restart it so its fast syncing
- start a new test net with 1 node, same network name as other network, connect it to the fast syncing peer
