### ISSUE TITLE
error occurred when using SocketPV

### ISSUE THREAD

**Issue by WeibingChen** [tendermint/tendermint#2027]
1. first, I start cmd/priv_val_server/main.go, it reports connection refused:

```
$ go run ./main.go --chain-id='1234' --priv="/Users/donnie/.travis/config/remote/priv_validator.json" --addr=":26659"

I[07-23|10:25:53.860] Starting private validator                   module=priv_val addr=:26659 chainID=1234 privPath=/Users/donnie/.travis/config/remote/priv_validator.json
I[07-23|10:25:53.863] Starting RemoteSigner                        module=priv_val impl=RemoteSigner
E[07-23|10:25:53.863] connect                                      module=priv_val addr=:26659 err="Error{dial tcp :26659: connect: connection refused}"
...
E[07-23|10:26:20.901] OnStart                                      module=priv_val err="Error{dialed maximum retries}"
panic: Error{dialed maximum retries}

goroutine 1 [running]:
main.main()
	$GOPATH/src/github.com/tendermint/tendermint/cmd/priv_val_server/main.go:44 +0x7d6
exit status 2
```

2. second, i change ~/.tendermint/config/config.toml and add `priv_validator_laddr = ":26669"`. Then I start tendermint with nilapp, I got error as below:
```
$ tendermint node start --home ~/.tendermint --proxy_app="nilapp"
...
I[07-23|10:25:57.428] Completed ABCI Handshake - Tendermint and App are synced module=consensus appHeight=0 appHash=
I[07-23|10:25:57.428] Starting SocketPV                            module=privval impl=SocketPV
E[07-23|10:25:58.431] OnStart                                      module=privval err="Error{waited for remote signer for too long}"
ERROR: Failed to create node: Error starting private validator client: Error{waited for remote signer for too long}

```

**Comment by melekes** [comment]
Have you tried starting Tendermint first and only then starting `priv_val_server`?

**Comment by melekes** [comment]
Also, I can't find any docs on running remote private validator.

**Comment by WeibingChen** [comment]
@melekes yes, I've tried starting Tendermint first. It reported the same error.
I also found that error comes from   `conn, err := sc.listener.Accept()`， the base error is `accept tcp [::]:26669: i/o timeout`. I checked the acceptDeadline value that is `1.000000003s`, very strange. The value is defined  by `acceptDeadline = time.Second + defaultAcceptDeadlineSeconds`. I think there is a spell mistake, it should be '*' instead.

**Comment by melekes** [comment]
@WeibingChen thanks for putting your time to it. I think you're right about acceptDeadline. Created a PR fixing this https://github.com/tendermint/tendermint/pull/2040

**Comment by melekes** [comment]
```
$ tendermint node start --home ~/.tendermint --proxy_app="nilapp"
I[08-01|12:12:34.014] Starting multiAppConn                        module=proxy impl=multiAppConn
I[08-01|12:12:34.015] Starting localClient                         module=abci-client connection=query impl=localClient
I[08-01|12:12:34.016] Starting localClient                         module=abci-client connection=mempool impl=localClient
I[08-01|12:12:34.017] Starting localClient                         module=abci-client connection=consensus impl=localClient
I[08-01|12:12:34.018] ABCI Handshake                               module=consensus appHeight=0 appHash=
I[08-01|12:12:34.018] ABCI Replay Blocks                           module=consensus appHeight=0 storeHeight=0 stateHeight=0
I[08-01|12:12:34.019] Completed ABCI Handshake - Tendermint and App are synced module=consensus appHeight=0 appHash=
I[08-01|12:12:34.020] Starting SocketPV                            module=privval impl=SocketPV
I[08-01|12:12:36.877] This node is a validator                     module=consensus addr=D4EA6C6D607E3E1E0D80C88083DBCCEE7AF5E821 pubKey=PubKeyEd25519{ACE1EC8105B84061DB3A722B1073226D3C83BE79B19BA82EA9228869D2DEF468}
I[08-01|12:12:36.890] Starting Node                                module=main impl=Node
I[08-01|12:12:36.890] Starting EventBus                            module=events impl=EventBus
I[08-01|12:12:36.890] Local listener                               module=p2p ip=:: port=26656
I[08-01|12:12:36.891] Starting DefaultListener                     module=p2p impl=Listener(@10.0.2.15:26656)
I[08-01|12:12:36.891] P2P Node ID                                  module=main ID=3abc36007b4cfaec3844cc50de1b1752a3bf7600 file=/home/vagrant/.tendermint/config/node_key.json
I[08-01|12:12:36.892] Add our address to book                      module=p2p book=/home/vagrant/.tendermint/config/addrbook.json addr=3abc36007b4cfaec3844cc50de1b1752a3bf7600@10.0.2.15:26656
I[08-01|12:12:36.893] Starting RPC HTTP server on tcp://0.0.0.0:26657 module=rpc-server
I[08-01|12:12:36.893] Starting P2P Switch                          module=p2p impl="P2P Switch"
I[08-01|12:12:36.893] Starting MempoolReactor                      module=mempool impl=MempoolReactor
I[08-01|12:12:36.893] Starting BlockchainReactor                   module=blockchain impl=BlockchainReactor
I[08-01|12:12:36.893] Starting ConsensusReactor                    module=consensus impl=ConsensusReactor
I[08-01|12:12:36.893] ConsensusReactor                             module=consensus fastSync=false
I[08-01|12:12:36.893] Starting ConsensusState                      module=consensus impl=ConsensusState
I[08-01|12:12:36.893] Starting baseWAL                             module=consensus wal=/home/vagrant/.tendermint/data/cs.wal/wal impl=baseWAL
I[08-01|12:12:36.893] Starting TimeoutTicker                       module=consensus impl=TimeoutTicker
I[08-01|12:12:36.894] Catchup by replaying consensus messages      module=consensus height=1
I[08-01|12:12:36.894] Replay: Timeout                              module=consensus height=1 round=0 step=RoundStepNewHeight dur=990.453821ms
I[08-01|12:12:36.894] Need to set a buffer and log message here for sanity. module=consensus height=1 round=0 startTime=2018-08-01T12:12:37.885919317Z now=2018-08-01T12:12:36.894485507Z
I[08-01|12:12:36.894] enterNewRound(1/0). Current: 1/0/RoundStepNewHeight module=consensus height=1 round=0
I[08-01|12:12:36.894] enterPropose(1/0). Current: 1/0/RoundStepNewRound module=consensus height=1 round=0
I[08-01|12:12:36.895] enterPropose: Our turn to propose            module=consensus height=1 round=0 proposer=D4EA6C6D607E3E1E0D80C88083DBCCEE7AF5E821 privValidator=SocketPV
I[08-01|12:12:39.874] Replay: New Step                             module=consensus height=1 round=0 step=RoundStepPropose
I[08-01|12:12:39.875] Replay: Proposal                             module=consensus height=1 round=0 header=1:181876F13B06 pol=-1 peer=local
E[08-01|12:12:39.875] Error with msg                               module=consensus height=1 round=0 type=*consensus.ProposalMessage peer= err="Error invalid proposal signature" msg="[Proposal Proposal{1/0 1:181876F13B06 (-1,:0:000000000000) /EADA99552CE0.../ @ 2018-08-01T12:09:35.385544369Z}]"
I[08-01|12:12:39.876] Replay: BlockPart                            module=consensus height=1 round=0 peer=local
I[08-01|12:12:39.876] Received a block part when we're not expecting any module=consensus height=1 round=0 index=0 peer=
I[08-01|12:12:39.876] Replay: Done                                 module=consensus
I[08-01|12:12:39.876] Starting EvidenceReactor                     module=evidence impl=EvidenceReactor
I[08-01|12:12:39.876] Starting PEXReactor                          module=p2p impl=PEXReactor
I[08-01|12:12:39.876] Starting AddrBook                            module=p2p book=/home/vagrant/.tendermint/config/addrbook.json impl=AddrBook
I[08-01|12:12:39.876] Starting IndexerService                      module=txindex impl=IndexerService
I[08-01|12:12:39.876] Started node                                 module=main nodeInfo="NodeInfo{id: 3abc36007b4cfaec3844cc50de1b1752a3bf7600, moniker: ubuntu-xenial, network: test-chain-tuFSXT [listen 10.0.2.15:26656], version: 0.22.8-0c7338c5 ([amino_version=0.10.1 p2p_version=0.5.0 consensus_version=v1/0.2.2 rpc_version=0.7.0/3 tx_index=on rpc_addr=tcp://0.0.0.0:26657])}"
I[08-01|12:12:39.876] Ensure peers                                 module=p2p numOutPeers=0 numInPeers=0 numDialing=0 numToDial=10
I[08-01|12:12:39.876] No addresses to dial nor connected peers. Falling back to seeds module=p2p
I[08-01|12:12:39.897] Timed out                                    module=consensus dur=3s height=1 round=0 step=RoundStepPropose
I[08-01|12:12:39.897] enterPrevote(1/0). Current: 1/0/RoundStepPropose module=consensus
I[08-01|12:12:39.897] enterPrevote: ProposalBlock is nil           module=consensus height=1 round=0
E[08-01|12:12:39.898] CONSENSUS FAILURE!!!                         module=consensus err="Error{remote signer timed out}" stack="goroutine 50 [running]:\nruntime/debug.Stack(0xc4207ab4d0, 0xd106e0, 0xc420076100)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func1(0xc42016a600)\n\t/home/vagrant/go/src/github.com/tendermint/tendermint/consensus/state.go:558 +0x57\npanic(0xd106e0, 0xc420076100)\n\t/usr/local/go/src/runtime/panic.go:502 +0x229\ngithub.com/tendermint/tendermint/privval.(*SocketPV).GetAddress(0xc4201c72b0, 0xc4207cfd60, 0x60000c4200760c0, 0x0)\n\t/home/vagrant/go/src/github.com/tendermint/tendermint/privval/socket.go:111 +0x76\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).signAddVote(0xc42016a600, 0xdece01, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8)\n\t/home/vagrant/go/src/github.com/tendermint/tendermint/consensus/state.go:1642 +0x6a\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).defaultDoPrevote(0xc42016a600, 0x1, 0x0)\n\t/home/vagrant/go/src/github.com/tendermint/tendermint/consensus/state.go:982 +0x4bf\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).(github.com/tendermint/tendermint/consensus.defaultDoPrevote)-fm(0x1, 0x0)\n\t/home/vagrant/go/src/github.com/tendermint/tendermint/consensus/state.go:153 +0x3e\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterPrevote(0xc42016a600, 0x1, 0x0)\n\t/home/vagrant/go/src/github.com/tendermint/tendermint/consensus/state.go:964 +0x567\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).handleTimeout(0xc42016a600, 0xb2d05e00, 0x1, 0x0, 0x3, 0x1, 0x0, 0x3, 0xbed086cd74ce0e55, 0xe82a92e9, ...)\n\t/home/vagrant/go/src/github.com/tendermint/tendermint/consensus/state.go:673 +0xc6d\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc42016a600, 0x0)\n\t/home/vagrant/go/src/github.com/tendermint/tendermint/consensus/state.go:589 +0x424\ncreated by github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/home/vagrant/go/src/github.com/tendermint/tendermint/consensus/state.go:295 +0x140\n"

$ go run ./main.go --chain-id='1234' --priv="/home/vagrant/.tendermint/config/priv_validator.
json" --addr=":26669"
I[08-01|12:12:06.857] Starting private validator                   module=priv_val addr=:26669 chainID=1234 privPath=/home/vagrant/.tendermint/config/priv_validator.json
I[08-01|12:12:06.859] Starting RemoteSigner                        module=priv_val impl=RemoteSigner
E[08-01|12:12:09.862] connect                                      module=priv_val err="Error{read tcp 127.0.0.1:32920->127.0.0.1:26669: i/o timeout}"
E[08-01|12:12:15.864] connect                                      module=priv_val err="Error{read tcp 127.0.0.1:32922->127.0.0.1:26669: i/o timeout}"
E[08-01|12:12:21.867] connect                                      module=priv_val err="Error{read tcp 127.0.0.1:32924->127.0.0.1:26669: i/o timeout}"
E[08-01|12:12:27.869] connect                                      module=priv_val err="Error{read tcp 127.0.0.1:32926->127.0.0.1:26669: i/o timeout}"
E[08-01|12:12:30.871] connect                                      module=priv_val addr=:26669 err="Error{dial tcp :26669: connect: connection refused}"
E[08-01|12:12:33.873] connect                                      module=priv_val addr=:26669 err="Error{dial tcp :26669: connect: connection refused}"
E[08-01|12:12:36.896] handleConnection                             module=priv_val err="Error signing proposal: Conflicting data"
```

**Comment by zmanian** [comment]
I can look into this relative to the KMS over the next couple days.

**Comment by melekes** [comment]
Thanks @zmanian. Not if I will get to it first :) Also, **I was not able to find any docs as of how to run remote priv validator**

**Comment by Liamsi** [comment]
@melekes I wanted to test if the kms connects to tendermint correctly. It looks like this issue and the realted PR are mandatory for this to be possible, or am I getting this wrong?

**Comment by melekes** [comment]
> It looks like this issue and the realted PR are mandatory for this to be possible,

correct

**Comment by Liamsi** [comment]
Can I help somehow to get https://github.com/tendermint/tendermint/pull/2134 merged? Does it need testing? Or did just no one had the time to review it yet?

**Comment by melekes** [comment]
It's Work in Progress. It does not fix the consensus failure 😞 I never had time to work on it

**Comment by Liamsi** [comment]
I'm happy to prioritize this and work on it (next week though).

**Comment by ebuchman** [comment]
This is fixed in https://github.com/tendermint/tendermint/pull/2548.

I'm going to close this for that, and for additional priv validator work we need to do in https://github.com/tendermint/tendermint/issues/1255
