### ISSUE TITLE
Tendermint node crashes

### ISSUE THREAD

**Issue by yrozhkov** [tendermint/tendermint#2087]
BUG REPORT
tendermint version : 0.22.7
ABCI app: Java self written
OS: Linux 4.14.51-60.38.amzn1.x86_64

4 nodes all validators
used tendermint testnet to create files

config diff:
```
addr_book_strict = true
---
> addr_book_strict = false
140c140
< size = 100000
---
> size = 1000000
143c143
< cache_size = 100000
---
> cache_size = 1000000
```

I have encountered below error in one of the nodes
I have deleted data directory
tendermint unsafe_reset_priv_validator
Restarted tendermint
After it reached same block this error happend again

Log:
```
I[07-27|03:34:19.308] Executed block                               module=state height=12393 validTxs=1 invalidTxs=0
[TendermintCore]--Fri Jul 27 03:34:19 UTC 2018 -- requestCommit hash = 2f7fe2554bf3949d7c4fd297d4baaa853b268e280a2bc64283ea00f5573280ef latest=fdf5f2cadd311e7fc5f79c5131a98185435780b0d90ca114a9e9010d7ac09164
I[07-27|03:34:19.352] Committed state                              module=state height=12393 txs=1 appHash=32663766653235353462663339343964376334666432393764346261616138353362323638653238306132626336343238336561303066353537333238306566
I[07-27|03:34:19.352] Recheck txs                                  module=mempool numtxs=0 height=12393
I[07-27|03:34:19.357] Indexed block                                module=txindex height=12393
panic: Panicked questionably: Failed to process committed block (12394:3C5C435821C998464715DBAE3B92A323A6A36AA4): Wrong Block.Header.AppHash.  Expected 32663766653235353462663339343964376334666432393764346261616138353362323638653238306132626336343238336561303066353537333238306566, got 34303761386463326462393363383865353063366163313336346539633532646630383565346330653861326533623566373339313738336636326666636166

goroutine 65 [running]:
github.com/tendermint/tendermint/libs/common.PanicQ(0xc3bf00, 0xc42eabb9e0)
	/home/ec2-user/projects/src/github.com/tendermint/tendermint/libs/common/errors.go:245 +0xf3
github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine(0xc42076e600)
	/home/ec2-user/projects/src/github.com/tendermint/tendermint/blockchain/reactor.go:304 +0xa6d
created by github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).OnStart
	/home/ec2-user/projects/src/github.com/tendermint/tendermint/blockchain/reactor.go:118 +0x90
[SocketThread -MemPool] ERROR com.github.jtendermint.jabci.socket.TSocket$SocketHandler - Error with SocketThread -MemPool
[SocketThread -Info] ERROR com.github.jtendermint.jabci.socket.TSocket$SocketHandler - Error with SocketThread -Info
com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:86)
	at com.google.protobuf.CodedInputStream$StreamDecoder.refillBuffer(CodedInputStream.java:2766)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readRawByte(CodedInputStream.java:2840)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readRawVarint64SlowPath(CodedInputStream.java:2631)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readRawVarint64(CodedInputStream.java:2624)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readUInt64(CodedInputStream.java:2252)
	at com.github.jtendermint.jabci.socket.TSocket$SocketHandler.run(TSocket.java:256)
[SocketThread -Consensus] ERROR com.github.jtendermint.jabci.socket.TSocket$SocketHandler - Error with SocketThread -Consensus
com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:86)
	at com.google.protobuf.CodedInputStream$StreamDecoder.refillBuffer(CodedInputStream.java:2766)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readRawByte(CodedInputStream.java:2840)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readRawVarint64SlowPath(CodedInputStream.java:2631)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readRawVarint64(CodedInputStream.java:2624)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readUInt64(CodedInputStream.java:2252)
	at com.github.jtendermint.jabci.socket.TSocket$SocketHandler.run(TSocket.java:256)
com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:86)
	at com.google.protobuf.CodedInputStream$StreamDecoder.refillBuffer(CodedInputStream.java:2766)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readRawByte(CodedInputStream.java:2840)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readRawVarint64SlowPath(CodedInputStream.java:2631)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readRawVarint64(CodedInputStream.java:2624)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readUInt64(CodedInputStream.java:2252)
	at com.github.jtendermint.jabci.socket.TSocket$SocketHandler.run(TSocket.java:256)
[SocketThread -MemPool] INFO com.github.jtendermint.jabci.socket.TSocket$SocketHandler
```

 Note: If "the input ended unexpectedly" it could mean: 
 
- tendermint was shut down
- the protobuf file is not up to date. [SocketThread -Consensus] INFO com.github.jtendermint.jabci.socket.TSocket$SocketHandler

**Comment by ebuchman** [comment]
Is your app fully deterministic? If its possible to compute different values by applying the same transaction than this will happen.

**Comment by yrozhkov** [comment]
I did some more research and see one odd thing that same transaction made it to 2 adjacent block in other nodes. I will run my app in debug mode and see if it is tendermint sends me same  tx or it is my fault

**Comment by yrozhkov** [comment]
My guess is that either cache_size of 1000000 or mempool 1000000 was too big for current host memory size
