### ISSUE TITLE
consensus:CONSENSUS FAILURE!!!

### ISSUE THREAD

**Issue by xieyiwen** [tendermint/tendermint#2222]
**Tendermint v0.23** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

**101.132.96.156:26657** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
CentOS 7 X64
- **Install tools**:
docker

- **Others**:

**What happened**:
CONSENSUS FAILURE!!!

**What you expected to happen**:
i running five node in my Cloud Elastic Compute Service.I get an error when I start，the block height is 0

**Have you tried the latest version**: yes/no

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
```shell
runtime error: invalid memory address or nil pointer dereference" stack="goroutine 80 [running]:
runtime/debug.Stack(0xc4204cb060, 0x1a95d40, 0x2342c50)
/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func2(0xc420182900, 0x1d60b28)
/Users/envin_xie/gopath/src/universe-chain/src/vendor/github.com/tendermint/tendermint/consensus/state.go:570 +0x57panic(0x1a95d40, 0x2342c50)
/usr/local/go/src/runtime/panic.go:502 +0x229
vendor/github.com/tendermint/tendermint/state.validateBlock(0x1e08f60, 0xc4201b4090, 0xc420037500, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/Users/envin_xie/gopath/src/universe-chain/src/vendor/github.com/tendermint/tendermint/state/validation.go:61 +0x422
vendor/github.com/tendermint/tendermint/state.(*BlockExecutor).ValidateBlock(0xc4208acde0, 0xc420037500, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/Users/envin_xie/gopath/src/universe-chain/src/vendor/github.com/tendermint/tendermint/state/execution.go:62 +0x8c
vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).defaultDoPrevote(0xc420182900, 0x1, 0x0)
/Users/envin_xie/gopath/src/universe-chain/src/vendor/github.com/tendermint/tendermint/consensus/state.go:999 +0x23c
vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).(vendor/github.com/tendermint/tendermint/consensus.defaultDoPrevote)-fm(0x1, 0x0)
/Users/envin_xie/gopath/src/universe-chain/src/vendor/github.com/tendermint/tendermint/consensus/state.go:153 +0x3e
vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterPrevote(0xc420182900, 0x1, 0x0)
/Users/envin_xie/gopath/src/universe-chain/src/vendor/github.com/tendermint/tendermint/consensus/state.go:976 +0x567
vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).addProposalBlockPart(0xc420182900, 0xc42012b200, 0x0, 0x0, 0xc4204cbb40, 0xc4204cbb60, 0x178b1e9)
/Users/envin_xie/gopath/src/universe-chain/src/vendor/github.com/tendermint/tendermint/consensus/state.go:1459 +0x47c
vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc420182900, 0x1a7c680, 0xc42012b200, 0x0, 0x0)
/Users/envin_xie/gopath/src/universe-chain/src/vendor/github.com/tendermint/tendermint/consensus/state.go:632 +0x6c9
vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc420182900, 0x0)
/Users/envin_xie/gopath/src/universe-chain/src/vendor/github.com/tendermint/tendermint/consensus/state.go:605 +0x587
created by vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart
/Users/envin_xie/gopath/src/universe-chain/src/vendor/github.com/tendermint/tendermint/consensus/state.go:295 +0x140

```
**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by HaoyangLiu** [comment]
Block LastCommit pointer must not be nil. In the following code, commit is a pointer and it will be assigned to block LastCommit. Only when error happens, will it be nil.
```
func (cs *ConsensusState) createProposalBlock() (block *types.Block, blockParts *types.PartSet) {
	var commit *types.Commit
	if cs.Height == 1 {
		// We're creating a proposal for the first block.
		// The commit is empty, but not nil.
		commit = &types.Commit{}
	} else if cs.LastCommit.HasTwoThirdsMajority() {
		// Make the commit from LastCommit
		commit = cs.LastCommit.MakeCommit()
	} else {
		// This shouldn't happen.
		cs.Logger.Error("enterPropose: Cannot propose anything: No commit for the previous block.")
		return
	}

	// Mempool validated transactions
	txs := cs.mempool.Reap(cs.state.ConsensusParams.BlockSize.MaxTxs)
	evidence := cs.evpool.PendingEvidence()
	block, parts := cs.state.MakeBlock(cs.Height, txs, commit, evidence)
	return block, parts
}
```
Does your log contain the following error message?
```
enterPropose: Cannot propose anything: No commit for the previous block.
```

**Comment by xieyiwen** [comment]
I will use Chinese to explain to you

首先感谢您的关注与回复。
我构建了自己的abci application,然后启动链。此时，我只启动了一个节点，并且是第一次启动。然后就回报错。
另外没有下面的错误信息：
```shell
enterPropose: Cannot propose anything: No commit for the previous block.
```

区块信息如下：
```shell
I[08-15|09:15:24.359] Signed proposal                              module=consensus height=1 round=0 proposal="Proposal{1/0 1:FC610E7FED08 (-1,:0:000000000000) ACE1D6E51A1A @ 2018-08-15T09:15:24.357037801Z}"
D[08-15|09:15:24.360] Signed proposal block: Block{
  Header{
    ChainID:        test-chain-m8GgKx
    Height:         1
    Time:           2018-08-15 17:15:24.356722576 +0800 CST m=+1.041563380
    NumTxs:         0
    TotalTxs:       0
    LastBlockID:    :0:000000000000
    LastCommit:     
    Data:           
    Validators:     F5F05A0D6183A577949A66DEB0EA995995146B0B
    App:            
    Consensus:       D6B74BB35BDFFD8392340F2A379173548AE188FE
    Results:        
    Evidence:       
  }#599F2ED6CB3B17BC14328DA577B92D447A0D9323
  Data{
    
  }#
  EvidenceData{
    
  }#
  Commit{
    BlockID:    :0:000000000000
    Precommits: 
  }#
}#599F2ED6CB3B17BC14328DA577B92D447A0D9323 module=consensus 
D[08-15|09:15:24.360] Broadcast                                    module=p2p channel=32 msgBytes=C96A6FA8080218032801
I[08-15|09:15:24.361] Received proposal                            module=consensus proposal="Proposal{1/0 1:FC610E7FED08 (-1,:0:000000000000) ACE1D6E51A1A @ 2018-08-15T09:15:24.357037801Z}"
I[08-15|09:15:24.362] Received complete proposal block             module=consensus height=1 hash=
I[08-15|09:15:24.362] enterPrevote(1/0). Current: 1/0/RoundStepPropose module=consensus 
D[08-15|09:15:24.362] Broadcast                                    module=p2p channel=32 msgBytes=C96A6FA8080218042801
E[08-15|09:15:24.362] CONSENSUS FAILURE!!!  
```

**Comment by melekes** [comment]
Is there a way to replicate this easily? Do you get this error every time you try to run tendermint core?

**Comment by xieyiwen** [comment]
> Is there a way to replicate this easily? Do you get this error every time you try to run tendermint?
yeah.  If I modify the code, this error will disappear
`
state.validateBlock(stateDB dbm.DB, state State, block *types.Block)

    if block.LastCommit != nil && len(block.LastCommit.Precommits) != 0 {
			return errors.New("Block at height "+strconv.FormatInt(cnst.BaseHeight+1,10)+" (first block) should have no LastCommit precommits")
		}
`

**Comment by xieyiwen** [comment]
if i modify `state.validateBlock` , another problem came up again.
the blockHeight does not grow，the blockHeight keep 0
i read those log information:
```
D[08-15|12:30:04.184] Broadcast                                    module=p2p channel=32 msgBytes=C96A6FA80802108C061806200E2801
D[08-15|12:30:04.184] addVote                                      module=consensus voteHeight=1 voteType=2 valIndex=0 csHeight=1
D[08-15|12:30:04.185] Broadcast                                    module=p2p channel=32 msgBytes=1919B3D50802108C061802
I[08-15|12:30:04.185] Added to precommit                           module=consensus vote="Vote{0:0E6540608F19 1/390/2(Precommit) 000000000000 9651F6EE8684 @ 2018-08-15T12:30:04.182665124Z}" precommits="VoteSet{H:1 R:390 T:2 +2/3::0:000000000000(1) BA{1:x} map[]}"
I[08-15|12:30:04.185] enterNewRound(1/391). Current: 1/390/RoundStepPrecommit module=consensus height=1 round=391
I[08-15|12:30:04.193] Resetting Proposal info                      module=consensus height=1 round=391
I[08-15|12:30:04.193] enterPropose(1/391). Current: 1/391/RoundStepNewRound module=consensus height=1 round=391
D[08-15|12:30:04.193] This node is a validator                     module=consensus height=1 round=391
I[08-15|12:30:04.193] enterPropose: Our turn to propose            module=consensus height=1 round=391 proposer=0E6540608F19767E40648A376E47980ADADC9296 privValidator="PrivValidator{0E6540608F19767E40648A376E47980ADADC9296 LH:1, LR:390, LS:3}"
D[08-15|12:30:04.193] Received tick                                module=consensus old_ti="{Duration:3m18s Height:1 Round:390 Step:RoundStepPropose}" new_ti="{Duration:3m18.5s Height:1 Round:391 Step:RoundStepPropose}"
D[08-15|12:30:04.193] Scheduled timeout                            module=consensus dur=3m18.5s height=1 round=391 step=RoundStepPropose
I[08-15|12:30:04.195] Signed proposal                              module=consensus height=1 round=391 proposal="Proposal{1/391 1:57D626739B3B (390,:1:52C4DF4BFC6A) F4334D47ADEA @ 2018-08-15T12:30:04.193974812Z}"
D[08-15|12:30:04.196] Signed proposal block: Block{
  Header{
    ChainID:        test-chain-nArI5s
    Height:         1
    Time:           2018-08-15 20:30:04.193843138 +0800 CST m=+8.947608674
    NumTxs:         0
    TotalTxs:       0
    LastBlockID:    :0:000000000000
    LastCommit:     
    Data:           
    Validators:     BDA4CEAD89689D00E110D5A711947C662309407B
    App:            
    Consensus:       D6B74BB35BDFFD8392340F2A379173548AE188FE
    Results:        
    Evidence:       
  }#8487D8C4503003A6B65D7027872DCC7F4D4B6C4B
  Data{
    
  }#
  EvidenceData{
    
  }#
  Commit{
    BlockID:    :0:000000000000
    Precommits: 
  }#
}#8487D8C4503003A6B65D7027872DCC7F4D4B6C4B module=consensus 
D[08-15|12:30:04.196] Broadcast                                    module=p2p channel=32 msgBytes=C96A6FA80802108E061803200E2801

```

**Comment by ebuchman** [comment]
How can we replicate this? We have not been able to see this issue.

**Comment by xieyiwen** [comment]
i found the reason for this error.
my go-amino's version is 0.11.1 .this is wrong,  when i change to v0.10.1, it's fine
