### ISSUE TITLE
Panic when returning something else than OK in CheckTx()

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#226]
Panic occurs when using gRPC (not tested with socket TMSP) and returning FAILED_PRECONDITION inside CheckTx() - used to signal in this case that the "tx" bytes were not a valid transaction.

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x6c6496]

goroutine 26 [running]:
panic(0xb64440, 0xc82000e0d0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/tendermint/tendermint/mempool.(*Mempool).resCbNormal(0xc8204dd340, 0xc820647750, 0xc820654780)
        /home/mda/gocode/src/github.com/tendermint/tendermint/mempool/mempool.go:159 +0xa6
github.com/tendermint/tendermint/mempool.(*Mempool).resCb(0xc8204dd340, 0xc820647750, 0xc820654780)
        /home/mda/gocode/src/github.com/tendermint/tendermint/mempool/mempool.go:150 +0x40
github.com/tendermint/tendermint/mempool.(*Mempool).(github.com/tendermint/tendermint/mempool.resCb)-fm(0xc820647750, 0xc820654780)
        /home/mda/gocode/src/github.com/tendermint/tendermint/mempool/mempool.go:80 +0x34
github.com/tendermint/tmsp/client.(*grpcClient).finishAsyncCall(0xc82007e2d0, 0xc820647750, 0xc820654780, 0x7fa7e74423a0)
        /home/mda/gocode/src/github.com/tendermint/tmsp/client/grpc_client.go:209 +0xcf
github.com/tendermint/tmsp/client.(*grpcClient).CheckTxAsync(0xc82007e2d0, 0xc8207de4c0, 0x3a, 0x3a, 0x0)
        /home/mda/gocode/src/github.com/tendermint/tmsp/client/grpc_client.go:148 +0x384
github.com/tendermint/tendermint/proxy.(*remoteAppConn).CheckTxAsync(0xc8203fdcd0, 0xc8207de4c0, 0x3a, 0x3a, 0xc82064b3e0)
        <autogenerated>:5 +0x6d
github.com/tendermint/tendermint/mempool.(*Mempool).CheckTx(0xc8204dd340, 0xc8207de4c0, 0x3a, 0x3a, 0xc820647740, 0x0, 0x0)
        /home/mda/gocode/src/github.com/tendermint/tendermint/mempool/mempool.go:139 +0x670
github.com/tendermint/tendermint/mempool.(*MempoolReactor).BroadcastTx(0xc8204dd3b0, 0xc8207de4c0, 0x3a, 0x3a, 0xc820647740, 0x0, 0x0)
        /home/mda/gocode/src/github.com/tendermint/tendermint/mempool/reactor.go:90 +0x59
github.com/tendermint/tendermint/rpc/core.BroadcastTxSync(0xc8207de4c0, 0x3a, 0x3a, 0xbc9880, 0x0, 0x0)
        /home/mda/gocode/src/github.com/tendermint/tendermint/rpc/core/mempool.go:24 +0xca
github.com/tendermint/tendermint/rpc/grpc.(*broadcastAPI).BroadcastTx(0x117cb68, 0x7fa7e9bda800, 0xc82064c8a0, 0xc82064b3a0, 0xc8207de440, 0x0, 0x0)
        /home/mda/gocode/src/github.com/tendermint/tendermint/rpc/grpc/api.go:13 +0x4c
github.com/tendermint/tendermint/rpc/grpc._BroadcastAPI_BroadcastTx_Handler(0xb245e0, 0x117cb68, 0x7fa7e9bda800, 0xc82064c8a0, 0xc8207de480, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/mda/gocode/src/github.com/tendermint/tendermint/rpc/grpc/types.pb.go:293 +0x168
google.golang.org/grpc.(*Server).processUnaryRPC(0xc8203d02d0, 0x7fa7e6bfb2d8, 0xc82088f830, 0xc820807500, 0xc8204270a0, 0x1150d30, 0xc82064c870, 0x0, 0x0)
        /home/mda/gocode/src/google.golang.org/grpc/server.go:530 +0xeb5
google.golang.org/grpc.(*Server).handleStream(0xc8203d02d0, 0x7fa7e6bfb2d8, 0xc82088f830, 0xc820807500, 0xc82064c870)
        /home/mda/gocode/src/google.golang.org/grpc/server.go:687 +0x109d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc8206475b0, 0xc8203d02d0, 0x7fa7e6bfb2d8, 0xc82088f830, 0xc820807500)
        /home/mda/gocode/src/google.golang.org/grpc/server.go:352 +0xa0
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/mda/gocode/src/google.golang.org/grpc/server.go:353 +0x9a

**Comment by mdyring** [comment]
BTW, same goes for AppendTx().

**Comment by mdyring** [comment]
Oops. Should set request->code instead of return error at gRPC level.
