### ISSUE TITLE
I use websocket rpc  attach  tendermint, get The error , and all rpc  can't to  use

### ISSUE THREAD

**Issue by koala0923** [tendermint/tendermint#2368]
CONSENSUS FAILURE!!!                         module=consensus err="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 56 [running]:\nruntime/debug.Stack(0xc4200c3180, 0xbf2ee0, 0x1333f20)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func1(0xc420174600)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:558 +0x57\npanic(0xbf2ee0, 0x1333f20)\n\t/usr/local/go/src/runtime/panic.go:502 +0x229\ngithub.com/tendermint/tendermint/mempool.(*Mempool).collectTxs(0xc4201a2120, 0x2710, 0xc4201a2128, 0xc42000ccb8, 0xc421eb8930)\n\t/root/go/src/github.com/tendermint/tendermint/mempool/mempool.go:392 +0x1db\ngithub.com/tendermint/tendermint/mempool.(*Mempool).Reap(0xc4201a2120, 0x2710, 0x0, 0x0, 0x0)\n\t/root/go/src/github.com/tendermint/tendermint/mempool/mempool.go:381 +0x9f\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).createProposalBlock(0xc420174600, 0x4, 0x10)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:928 +0x8e\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).defaultDecideProposal(0xc420174600, 0xb, 0x0)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:861 +0x885\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).(github.com/tendermint/tendermint/consensus.defaultDecideProposal)-fm(0xb, 0x0)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:152 +0x3e\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterPropose(0xc420174600, 0xb, 0x0)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:838 +0x8fd\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterNewRound(0xc420174600, 0xb, 0x0)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:754 +0x9d3\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).handleTimeout(0xc420174600, 0x3b2e9006, 0xb, 0x0, 0x1, 0xb, 0x0, 0x1, 0xbede4fb71d219fa5, 0x9b76efad9, ...)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:668 +0x5b4\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc420174600, 0x0)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:589 +0x432\ncreated by github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:295 +0x140\n"

**Comment by ValarDragon** [comment]
Please fill out the bug report template, format the newlines in the logs. The current state of this issue provides no context, and consequently will be impossible to debug.

**Comment by ebuchman** [comment]
Are you using Ethermint here? Which version? Ethermint is in development and not fully working yet, and we don't currently support the older versions of it.

**Comment by koala0923** [comment]
> Are you using Ethermint here? Which version? Ethermint is in development and not fully working yet, and we don't currently support the older versions of it.

I use Ethermint  "0.5.3"
