### ISSUE TITLE
Can't run tendermint node (version 0.24.0)

### ISSUE THREAD

**Issue by pavlovdog** [tendermint/tendermint#2390]
**Tendermint version**
0.24.0

**Environment**:
```
uname -a
Linux local 4.15.0-33-generic #36~16.04.1-Ubuntu SMP Wed Aug 15 17:21:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**OS**:
Ubuntu 16.04

**What happened**:
I've installed Tendermint with `go get github.com/tendermint/tendermint/cmd/tendermint` without any troubles. `tendermint init` also works fine. But when I'm trying to start node with `tendermint node` I'm receiving the following error:

```
pavlovdog@local:~$ tendermint node
panic: Panicked on a Crisis: Failed to load genesis doc due to unmarshaling error: Amino:JSON time must be UTC and end with 'Z' but got "2018-01-31T12:54:42.923436441+03:00". (bytes: 7B2267656E657369735F74696D65223A22323031382D30312D33315431323A35343A34322E3932333433363434312B30333A3030222C22636861696E5F6964223A22746573742D636861696E2D56456E456845222C22636F6E73656E7375735F706172616D73223A7B22626C6F636B5F73697A655F706172616D73223A7B226D61785F6279746573223A32323032303039362C226D61785F747873223A3130303030302C226D61785F676173223A2D317D2C2274785F73697A655F706172616D73223A7B226D61785F6279746573223A31303234302C226D61785F676173223A2D317D2C22626C6F636B5F676F737369705F706172616D73223A7B22626C6F636B5F706172745F73697A655F6279746573223A36353533367D2C2265766964656E63655F706172616D73223A7B226D61785F616765223A3130303030307D7D2C2276616C696461746F7273223A5B7B227075625F6B6579223A7B2274797065223A2265643235353139222C2264617461223A2231433338454344313639334333424332383932424432374637433545374538303839394143354236344636394543394237333633353034424638323033383245227D2C22706F776572223A31302C226E616D65223A22227D5D2C226170705F68617368223A22227D)

goroutine 1 [running]:
github.com/tendermint/tendermint/libs/common.PanicCrisis(0xc98f80, 0xc42019a550)
	/home/pavlovdog/go/src/github.com/tendermint/tendermint/libs/common/errors.go:232 +0xb8
github.com/tendermint/tendermint/node.loadGenesisDoc(0xfe2520, 0xc4201aa0d0, 0xc4201aa0d0, 0x0, 0x0)
	/home/pavlovdog/go/src/github.com/tendermint/tendermint/node/node.go:740 +0x26a
github.com/tendermint/tendermint/node.NewNode(0xc42026f320, 0xfdb460, 0xc420207a40, 0xc4200bc6e0, 0xfceb60, 0xc42026ba10, 0xc4200bc8e0, 0xf60d00, 0xc4200bc8f0, 0xfda0e0, ...)
	/home/pavlovdog/go/src/github.com/tendermint/tendermint/node/node.go:172 +0x194
github.com/tendermint/tendermint/node.DefaultNewNode(0xc42026f320, 0xfda0e0, 0xc420113d00, 0x0, 0xc42007bac8, 0x596d60)
	/home/pavlovdog/go/src/github.com/tendermint/tendermint/node/node.go:89 +0x25a
github.com/tendermint/tendermint/cmd/tendermint/commands.NewRunNodeCmd.func1(0xc4200d3400, 0x149ee10, 0x0, 0x0, 0x0, 0x0)
	/home/pavlovdog/go/src/github.com/tendermint/tendermint/cmd/tendermint/commands/run_node.go:53 +0x5e
github.com/spf13/cobra.(*Command).execute(0xc4200d3400, 0x149ee10, 0x0, 0x0, 0xc4200d3400, 0x149ee10)
	/home/pavlovdog/go/src/github.com/spf13/cobra/command.go:762 +0x468
github.com/spf13/cobra.(*Command).ExecuteC(0x1474e60, 0xd0ea40, 0xc42007be01, 0xc4201a3460)
	/home/pavlovdog/go/src/github.com/spf13/cobra/command.go:852 +0x30a
github.com/spf13/cobra.(*Command).Execute(0x1474e60, 0xc4201a3460, 0xc42007be98)
	/home/pavlovdog/go/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0x1474e60, 0xf61828, 0x2, 0xc4201b8e20)
	/home/pavlovdog/go/src/github.com/tendermint/tendermint/libs/cli/setup.go:89 +0x4e
main.main()
	/home/pavlovdog/go/src/github.com/tendermint/tendermint/cmd/tendermint/main.go:45 +0x24d
```

**How to reproduce it**:
```
tendermint init
tendermint node
```

**Comment by srmo** [comment]
Did you do a clean install? Maybe you have an old config incl genesis in default home.

**Comment by pavlovdog** [comment]
@srmo maybe not, I've already used Tendermint when the version was `0.15.0`. How can I clean my environment and do the clean install?

**Comment by zramsay** [comment]
Here's the nuclear option:

```
rm -rf ~/.tendermint
rm -rf $GOPATH/src/githhub.com/tendermint/tendermint
go get github.com/tendermint/tendermint
cd $GOPATH/src/github.com/tendermint/tendermint
make get_vendor_deps
make install
```

we'll improve the documentation on upgrading in #2376
