### ISSUE TITLE
privval: non-deterministic test failure

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2677]
https://circleci.com/gh/tendermint/tendermint/30540#tests/containers/3

```
panic: test timed out after 5m0s

goroutine 134 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1240 +0x146
created by time.goFunc
	/usr/local/go/src/time/sleep.go:172 +0x52

goroutine 1 [chan receive, 5 minutes]:
testing.(*T).Run(0xc420139ef0, 0xe03db6, 0x15, 0xf46918, 0xc4200adc01)
	/usr/local/go/src/testing/testing.go:825 +0x597
testing.runTests.func1(0xc420139ef0)
	/usr/local/go/src/testing/testing.go:1063 +0xa5
testing.tRunner(0xc420139ef0, 0xc4200add48)
	/usr/local/go/src/testing/testing.go:777 +0x16e
testing.runTests(0xc4204e07a0, 0x1384140, 0x15, 0x15, 0xc42049c080)
	/usr/local/go/src/testing/testing.go:1061 +0x4e2
testing.(*M).Run(0xc42049c080, 0x0)
	/usr/local/go/src/testing/testing.go:978 +0x2ce
main.main()
	_testmain.go:134 +0x325

goroutine 5 [syscall, 5 minutes]:
os/signal.signal_recv(0x488741)
	/usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x30
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x4f

goroutine 132 [runnable]:
time.Sleep(0xf4240)
	/usr/local/go/src/runtime/time.go:102 +0x146
github.com/tendermint/tendermint/privval.(*RemoteSigner).connect(0xc4209981a0, 0xc400000001, 0x5, 0x7f36f8145d90, 0x0)
	/go/src/github.com/tendermint/tendermint/privval/socket.go:423 +0x9ed
github.com/tendermint/tendermint/privval.(*RemoteSigner).OnStart(0xc4209981a0, 0xc420900900, 0x15)
	/go/src/github.com/tendermint/tendermint/privval/socket.go:396 +0x5e
github.com/tendermint/tendermint/libs/common.(*BaseService).Start(0xc4209981a0, 0xc4208dc620, 0xc420998270)
	/go/src/github.com/tendermint/tendermint/libs/common/service.go:139 +0x534
github.com/tendermint/tendermint/privval.testSetupSocketPair(0xc4209901e0, 0xc4208dc5a0, 0xc, 0xfb9540, 0xc42091e250, 0x169504d6, 0x464d6b)
	/go/src/github.com/tendermint/tendermint/privval/socket_test.go:411 +0x275
github.com/tendermint/tendermint/privval.TestSocketPVHeartbeat(0xc4209901e0)
	/go/src/github.com/tendermint/tendermint/privval/socket_test.go:97 +0xa0
testing.tRunner(0xc4209901e0, 0xf46918)
	/usr/local/go/src/testing/testing.go:777 +0x16e
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:824 +0x565
FAIL	github.com/tendermint/tendermint/privval	300.046s
Exited with code 1
```

**Comment by ebuchman** [comment]
Oh, this is actually on old code.

**Comment by ebuchman** [comment]
A new one:

```
--- FAIL: TestIPCPVVoteResetDeadline (0.02s)
	Error Trace:	ipc_test.go:51
	Error:      	Received unexpected error:
	            	remote signer timed out
	Test:       	TestIPCPVVoteResetDeadline
coverage: 82.9% of statements
panic: test timed out after 5m0s

goroutine 442 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1240 +0x146
created by time.goFunc
	/usr/local/go/src/time/sleep.go:172 +0x52

goroutine 1 [chan receive, 4 minutes]:
testing.(*T).Run(0xc4204b43c0, 0xe16c1e, 0x1d, 0xf54818, 0xc4200afc01)
	/usr/local/go/src/testing/testing.go:825 +0x597
testing.runTests.func1(0xc4204b43c0)
	/usr/local/go/src/testing/testing.go:1063 +0xa5
testing.tRunner(0xc4204b43c0, 0xc4200afd48)
	/usr/local/go/src/testing/testing.go:777 +0x16e
testing.runTests(0xc4204fa700, 0x1399860, 0x18, 0x18, 0xc4201bc080)
	/usr/local/go/src/testing/testing.go:1061 +0x4e2
testing.(*M).Run(0xc4201bc080, 0x0)
	/usr/local/go/src/testing/testing.go:978 +0x2ce
main.main()
	_testmain.go:148 +0x325

goroutine 19 [syscall, 5 minutes]:
os/signal.signal_recv(0x488741)
	/usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x30
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x4f

goroutine 184 [select]:
github.com/tendermint/tendermint/privval.(*TCPVal).OnStart.func1(0xc4208ee0e0)
	/go/src/github.com/tendermint/tendermint/privval/tcp.go:118 +0x168
created by github.com/tendermint/tendermint/privval.(*TCPVal).OnStart
	/go/src/github.com/tendermint/tendermint/privval/tcp.go:116 +0x5c8

goroutine 190 [chan receive]:
github.com/tendermint/tendermint/libs/common.Parallel(0xc4209239a8, 0x2, 0x2, 0x0, 0xc420880900)
	/go/src/github.com/tendermint/tendermint/libs/common/async.go:163 +0x24e
github.com/tendermint/tendermint/p2p/conn.shareEphPubKey(0x7fe67005d0c0, 0xc42000e028, 0xc420880900, 0x0, 0xb2d0574e, 0xc420923ac0)
	/go/src/github.com/tendermint/tendermint/p2p/conn/secret_connection.go:212 +0x1b7
github.com/tendermint/tendermint/p2p/conn.MakeSecretConnection(0x7fe67005d0c0, 0xc42000e028, 0xfc6fe0, 0xc42002aa00, 0xc42000e028, 0x0, 0x13a41e0)
	/go/src/github.com/tendermint/tendermint/p2p/conn/secret_connection.go:61 +0xb8
github.com/tendermint/tendermint/privval.(*RemoteSigner).connect(0xc4208ce1a0, 0x1, 0xb, 0x6cddf0, 0x6d0a74)
	/go/src/github.com/tendermint/tendermint/privval/tcp_server.go:114 +0x655
github.com/tendermint/tendermint/privval.(*RemoteSigner).OnStart(0xc4208ce1a0, 0xc420881580, 0x15)
	/go/src/github.com/tendermint/tendermint/privval/tcp_server.go:66 +0x55
github.com/tendermint/tendermint/libs/common.(*BaseService).Start(0xc4208ce1a0, 0xc4208648a0, 0xc4209ca000)
	/go/src/github.com/tendermint/tendermint/libs/common/service.go:139 +0x534
github.com/tendermint/tendermint/privval.testSetupSocketPair(0xc4204b5c20, 0xc4204b3530, 0xc, 0xfc7be0, 0xc4200f20c0, 0x1, 0xc4204b3510)
	/go/src/github.com/tendermint/tendermint/privval/tcp_test.go:427 +0x2c3
github.com/tendermint/tendermint/privval.TestRemoteSignHeartbeatErrors(0xc4204b5c20)
	/go/src/github.com/tendermint/tendermint/privval/tcp_test.go:307 +0xa0
testing.tRunner(0xc4204b5c20, 0xf54818)
	/usr/local/go/src/testing/testing.go:777 +0x16e
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:824 +0x565

goroutine 399 [IO wait]:
internal/poll.runtime_pollWait(0x7fe6700118f0, 0x72, 0x134a838)
	/usr/local/go/src/runtime/netpoll.go:173 +0x5e
internal/poll.(*pollDesc).wait(0xc42094a818, 0x72, 0xfbee00, 0x134a838, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xe5
internal/poll.(*pollDesc).waitRead(0xc42094a818, 0xc42083e500, 0x1, 0xa)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x4b
internal/poll.(*FD).Read(0xc42094a800, 0xc42083e584, 0x1, 0xa, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x22a
net.(*netFD).Read(0xc42094a800, 0xc42083e584, 0x1, 0xa, 0x1000000007f9d76, 0xc4201220e0, 0xa)
	/usr/local/go/src/net/fd_unix.go:202 +0x66
net.(*conn).Read(0xc42000e028, 0xc42083e584, 0x1, 0xa, 0xc4204ad558, 0x439518, 0xa)
	/usr/local/go/src/net/net.go:176 +0x85
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-amino.(*Codec).UnmarshalBinaryReader(0xc4201220e0, 0x7fe67005d0f0, 0xc42000e028, 0xce8080, 0xc420880940, 0x100000, 0xc420831540, 0xfbdd60, 0xc42050e008)
	/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-amino/amino.go:268 +0x125
github.com/tendermint/tendermint/p2p/conn.shareEphPubKey.func2(0x1, 0xf54770, 0xc42083e580, 0xc4200c8600, 0xc420156380, 0x0)
	/go/src/github.com/tendermint/tendermint/p2p/conn/secret_connection.go:222 +0x123
github.com/tendermint/tendermint/libs/common.Parallel.func1(0xc42083e580, 0xc420156380, 0x1, 0xc420908840, 0xc4200c8600)
	/go/src/github.com/tendermint/tendermint/libs/common/async.go:149 +0x86
created by github.com/tendermint/tendermint/libs/common.Parallel
	/go/src/github.com/tendermint/tendermint/libs/common/async.go:135 +0x117
FAIL	github.com/tendermint/tendermint/privval	300.052s
Exited with code 1
```

@xla @Slamper thoughts?

**Comment by ebuchman** [comment]
I think we can fix these with the following patch, which I'll push to PR #2923. It just extends the connection deadline to 100ms instead of 5ms, and makes the sleeps a function of that parameter:

```
diff --git a/privval/ipc_test.go b/privval/ipc_test.go
index c8d6dfc77..f42a6e27e 100644
--- a/privval/ipc_test.go
+++ b/privval/ipc_test.go
@@ -14,7 +14,12 @@ import (
 	"github.com/tendermint/tendermint/types"
 )
 
-func TestIPCPVVote(t *testing.T) {
+var (
+	testConnDeadline   = 100 * time.Millisecond
+	testConnDeadline23 = 66 * time.Millisecond // 2/3 of the other one
+)
+
+func TestIPCPVVoteSimple(t *testing.T) {
 	var (
 		chainID = cmn.RandStr(12)
 		sc, rs  = testSetupIPCSocketPair(t, chainID, types.NewMockPV())
@@ -45,14 +50,15 @@ func TestIPCPVVoteResetDeadline(t *testing.T) {
 	defer sc.Stop()
 	defer rs.Stop()
 
-	time.Sleep(3 * time.Millisecond)
+	// Wait less than the full testConnDeadline
+	time.Sleep(testConnDeadline23)
 
 	require.NoError(t, rs.privVal.SignVote(chainID, want))
 	require.NoError(t, sc.SignVote(chainID, have))
 	assert.Equal(t, want.Signature, have.Signature)
 
-	// This would exceed the deadline if it was not extended by the previous message
-	time.Sleep(3 * time.Millisecond)
+	// This would exceed the deadline if it was not extended by the previous message.
+	time.Sleep(testConnDeadline23)
 
 	require.NoError(t, rs.privVal.SignVote(chainID, want))
 	require.NoError(t, sc.SignVote(chainID, have))
@@ -72,7 +78,9 @@ func TestIPCPVVoteKeepalive(t *testing.T) {
 	defer sc.Stop()
 	defer rs.Stop()
 
-	time.Sleep(10 * time.Millisecond)
+	// Wait longer than the testConnDeadline.
+	// Connection only stays alive because of Ping.
+	time.Sleep(testConnDeadline * 2)
 
 	require.NoError(t, rs.privVal.SignVote(chainID, want))
 	require.NoError(t, sc.SignVote(chainID, have))
@@ -103,10 +111,10 @@ func testSetupIPCSocketPair(
 		)
 	)
 
-	IPCValConnTimeout(5 * time.Millisecond)(sc)
+	IPCValConnTimeout(testConnDeadline)(sc)
 	IPCValHeartbeat(time.Millisecond)(sc)
 
-	IPCRemoteSignerConnDeadline(time.Millisecond * 5)(rs)
+	IPCRemoteSignerConnDeadline(testConnDeadline)(rs)
 
 	testStartIPCRemoteSigner(t, readyc, rs)
```
