### ISSUE TITLE
consensus: non-deterministic test failure

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2723]
Found in https://circleci.com/gh/tendermint/tendermint/31318#tests/containers/3

```
--- FAIL: TestWaitingTimeoutOnNilPolka (0.05s)
panic: Timeout expired while waiting for NewTimeout event [recovered]
	panic: Timeout expired while waiting for NewTimeout event

goroutine 38820 [running]:
testing.tRunner.func1(0xc4278aa3c0)
	/usr/local/go/src/testing/testing.go:742 +0x567
panic(0xefb1a0, 0xc4225429d0)
	/usr/local/go/src/runtime/panic.go:502 +0x24a
github.com/tendermint/tendermint/consensus.ensureNewEvent(0xc4227b3440, 0x1, 0x0, 0x1c9c380, 0x104fcd1, 0x32)
	/go/src/github.com/tendermint/tendermint/consensus/common_test.go:358 +0x69f
github.com/tendermint/tendermint/consensus.ensureNewTimeout(0xc4227b3440, 0x1, 0x0, 0x989680)
	/go/src/github.com/tendermint/tendermint/consensus/common_test.go:414 +0x70
github.com/tendermint/tendermint/consensus.TestWaitingTimeoutOnNilPolka(0xc4278aa3c0)
	/go/src/github.com/tendermint/tendermint/consensus/state_test.go:986 +0x370
testing.tRunner(0xc4278aa3c0, 0x1185580)
	/usr/local/go/src/testing/testing.go:777 +0x16e
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:824 +0x565
FAIL	github.com/tendermint/tendermint/consensus	36.265s
```

**Comment by ebuchman** [comment]
This thing happens so often now

**Comment by Liamsi** [comment]
ref: https://github.com/tendermint/tendermint/pull/3560

**Comment by melekes** [comment]
Should be fixed in https://github.com/tendermint/tendermint/pull/3582.
