### ISSUE TITLE
Prometheus: panic: label name "peer_id" missing in label map

### ISSUE THREAD

**Issue by danil-lashin** [tendermint/tendermint#2766]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): v0.26.0-rc0

**ABCI app** (name for built-in, URL for self-written if it's publicly available): https://github.com/MinterTeam/minter-go-node

**Environment**:
- **OS** (e.g. from /etc/os-release): MacOS 10.14.1 (18B75)
- **Install tools**: -
- **Others**: -

**What happened**:  When setting `prometheus = true` in config following panic happens: `panic: label name "peer_id" missing in label map`

**What you expected to happen**: Node should start normally

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible): Run Minter Node with `prometheus = true` in config (~/.minter/config/config.toml)

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
```
panic: label name "peer_id" missing in label map

goroutine 113 [running]:
github.com/MinterTeam/minter-go-node/vendor/github.com/prometheus/client_golang/prometheus.(*CounterVec).With(0xc000170b28, 0xc0009d4570, 0x2, 0xc0009d4570)
	/Users/daniillashin/go/src/github.com/MinterTeam/minter-go-node/vendor/github.com/prometheus/client_golang/prometheus/counter.go:217 +0x79
github.com/MinterTeam/minter-go-node/vendor/github.com/go-kit/kit/metrics/prometheus.(*Counter).Add(0xc00000c680, 0x4010000000000000)
	/Users/daniillashin/go/src/github.com/MinterTeam/minter-go-node/vendor/github.com/go-kit/kit/metrics/prometheus/prometheus.go:45 +0x5c
github.com/MinterTeam/minter-go-node/vendor/github.com/tendermint/tendermint/p2p.(*peer).Send(0xc0008b85b0, 0x199e200, 0xc000c3824c, 0x4, 0x4, 0x4)
	/Users/daniillashin/go/src/github.com/MinterTeam/minter-go-node/vendor/github.com/tendermint/tendermint/p2p/peer.go:243 +0x18f
github.com/MinterTeam/minter-go-node/vendor/github.com/tendermint/tendermint/p2p/pex.(*PEXReactor).RequestAddrs(0xc0001ec000, 0x1d16b20, 0xc0008b85b0)
	/Users/daniillashin/go/src/github.com/MinterTeam/minter-go-node/vendor/github.com/tendermint/tendermint/p2p/pex/pex_reactor.go:282 +0x1cc
github.com/MinterTeam/minter-go-node/vendor/github.com/tendermint/tendermint/p2p/pex.(*PEXReactor).AddPeer(0xc0001ec000, 0x1d16b20, 0xc0008b85b0)
	/Users/daniillashin/go/src/github.com/MinterTeam/minter-go-node/vendor/github.com/tendermint/tendermint/p2p/pex/pex_reactor.go:166 +0x8f
github.com/MinterTeam/minter-go-node/vendor/github.com/tendermint/tendermint/p2p.(*Switch).startInitPeer(0xc00029b440, 0x1d16b20, 0xc0008b85b0, 0x2, 0x1d0b4a0)
	/Users/daniillashin/go/src/github.com/MinterTeam/minter-go-node/vendor/github.com/tendermint/tendermint/p2p/switch.go:654 +0xdb
github.com/MinterTeam/minter-go-node/vendor/github.com/tendermint/tendermint/p2p.(*Switch).addPeer(0xc00029b440, 0x1d16b20, 0xc0008b85b0, 0xc000b93390, 0x10)
	/Users/daniillashin/go/src/github.com/MinterTeam/minter-go-node/vendor/github.com/tendermint/tendermint/p2p/switch.go:623 +0x314
github.com/MinterTeam/minter-go-node/vendor/github.com/tendermint/tendermint/p2p.(*Switch).addOutboundPeerWithConfig(0xc00029b440, 0xc000bd74c0, 0xc000156000, 0xc00003dd00, 0x28, 0x12)
	/Users/daniillashin/go/src/github.com/MinterTeam/minter-go-node/vendor/github.com/tendermint/tendermint/p2p/switch.go:577 +0x4b5
github.com/MinterTeam/minter-go-node/vendor/github.com/tendermint/tendermint/p2p.(*Switch).DialPeerWithAddress(0xc00029b440, 0xc000bd74c0, 0x0, 0x0, 0x0)
	/Users/daniillashin/go/src/github.com/MinterTeam/minter-go-node/vendor/github.com/tendermint/tendermint/p2p/switch.go:443 +0xcc
github.com/MinterTeam/minter-go-node/vendor/github.com/tendermint/tendermint/p2p/pex.(*PEXReactor).dialPeer(0xc0001ec000, 0xc000bd74c0)
	/Users/daniillashin/go/src/github.com/MinterTeam/minter-go-node/vendor/github.com/tendermint/tendermint/p2p/pex/pex_reactor.go:457 +0xa3
created by github.com/MinterTeam/minter-go-node/vendor/github.com/tendermint/tendermint/p2p/pex.(*PEXReactor).ensurePeers
	/Users/daniillashin/go/src/github.com/MinterTeam/minter-go-node/vendor/github.com/tendermint/tendermint/p2p/pex/pex_reactor.go:407 +0x5d9
```

**Config (you can paste only the changes you've made)**:  `prometheus = true`

**node command runtime flags**: -

**`/dump_consensus_state` output for consensus bugs** -

**Anything else we need to know**: -

**Comment by ebuchman** [comment]
Thanks for reporting. Sorry about this. Fixed on develop and tagged as v0.26.1-rc1
