### ISSUE TITLE
Panic in tendermint core when subscribing to tx event over ws rpc

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/tendermint#285]
How to reproduce:

```
go get github.com/ethanfrey/tenderize
go test github.com/ethanfrey/tenderize/client/tests
```

Causes a nice panic.  If you want the tendermint logs (I turned them off, too much noise for me), check out `main_test.go`.

After digging through the source, I think I figured out the issue, not sure I should be bold enough to change core code (even on a fork...). The wrong type is returned when new transactions are appended.

`tendermint/tendermint/state/execution.go:78` is guaranteed to fire `*tmsp.Response_AppendTx` cast to `*tmsp.Response`

```
	proxyCb := func(req *tmsp.Request, res *tmsp.Response) {
		switch r := res.Value.(type) {
		case *tmsp.Response_AppendTx:
...
			eventCache.FireEvent(types.EventStringTx(req.GetAppendTx().Tx), res)
```

This behavior is expected and used in the `tendermint/tendermint/rpc/core/mempool.go:56-58` (`BroadcastTxCommit`)

```
	eventSwitch.AddListenerForEvent("rpc", types.EventStringTx(tx), func(data events.EventData) {
		appendTxResCh <- data.(*tmsp.Response)
	})
```

However, when we subscribe to this event, it expects a completely different type, namely `EventDataTx`, which we see here:
`tendermint/tendermint/rpc/core/events.go:17-18`

```
		tmResult := ctypes.TMResult(&ctypes.ResultEvent{event, types.TMEventData(msg)})
		wsCtx.TryWriteRPCResponse(rpctypes.NewRPCResponse(wsCtx.Request.ID+"#event", &tmResult, ""))
```

It all works good until it tried to serialize 😞 

I'm not sure how to transform the structs properly, or if that will break some other code...

**Comment by ethanfrey** [comment]
In case you want the logs, the ws subscriber got this struct:

`&types.Response{Value:(*types.Response_AppendTx)(0xc8203d24c8)}`

And this is the panic that results: 

```
panic: Paniced on a Sanity Check: Unexpected pointer type *types.Response for registered interface TMEventData. Was it registered as a value receiver rather than as a pointer receiver?

goroutine 9 [running]:
panic(0x631de0, 0xc8204b0bb0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/tendermint/go-common.PanicSanity(0x744460, 0xc8204b0b70)
	/Users/ethan/golang/src/github.com/tendermint/go-common/errors.go:26 +0xf5
github.com/tendermint/go-wire.JSONBytes(0x600f20, 0xc8204b0a50, 0x0, 0x0, 0x0)
	/Users/ethan/golang/src/github.com/tendermint/go-wire/util.go:33 +0x113
github.com/tendermint/go-rpc/types.NewRPCResponse(0x871320, 0x6, 0x600f20, 0xc8204b0a50, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/ethan/golang/src/github.com/tendermint/go-rpc/types/types.go:55 +0x90
github.com/tendermint/tendermint/rpc/core.Subscribe.func1(0x842ba0, 0xc8204b0640)
	/Users/ethan/golang/src/github.com/tendermint/tendermint/rpc/core/events.go:19 +0x236
github.com/tendermint/go-events.(*eventCell).FireEvent(0xc82044f500, 0x842ba0, 0xc8204b0640)
	/Users/ethan/golang/src/github.com/tendermint/go-events/events.go:164 +0xac
github.com/tendermint/go-events.(*EventSwitch).FireEvent(0xc82001cb40, 0xc820481020, 0x2b, 0x842ba0, 0xc8204b0640)
	/Users/ethan/golang/src/github.com/tendermint/go-events/events.go:130 +0xc6
github.com/tendermint/go-events.(*EventCache).Flush(0xc820480f30)
	/Users/ethan/golang/src/github.com/tendermint/go-events/event_cache.go:38 +0x121
github.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc82071e000, 0x1)
	/Users/ethan/golang/src/github.com/tendermint/tendermint/consensus/state.go:1256 +0xf91
github.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc82071e000, 0x1)
	/Users/ethan/golang/src/github.com/tendermint/tendermint/consensus/state.go:1198 +0x2dd
github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit.func1(0xc82071e000, 0x0, 0x1)
	/Users/ethan/golang/src/github.com/tendermint/tendermint/consensus/state.go:1152 +0x60
github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit(0xc82071e000, 0x1, 0x0)
	/Users/ethan/golang/src/github.com/tendermint/tendermint/consensus/state.go:1179 +0x758
github.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc82071e000, 0x0, 0xc8204b77a0, 0x0, 0x0, 0xc82013d901, 0xc8204ba120, 0x14, 0x20, 0x0, ...)
	/Users/ethan/golang/src/github.com/tendermint/tendermint/consensus/state.go:1483 +0x15a0
github.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc82071e000, 0x0, 0xc8204b77a0, 0x0, 0x0, 0x0, 0x0)
	/Users/ethan/golang/src/github.com/tendermint/tendermint/consensus/state.go:1380 +0x76
github.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc82071e000, 0x746d00, 0xc82043f650, 0x0, 0x0, 0x1, 0x0, 0x6, 0xecf8204fa, 0x19a01444, ...)
	/Users/ethan/golang/src/github.com/tendermint/tendermint/consensus/state.go:684 +0x836
github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc82071e000, 0x0)
	/Users/ethan/golang/src/github.com/tendermint/tendermint/consensus/state.go:634 +0x430
created by github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart
	/Users/ethan/golang/src/github.com/tendermint/tendermint/consensus/state.go:322 +0x35e
```

**Comment by ebuchman** [comment]
oh boy you're totally right. the fire event should wrap the res in an EventDataTx.

**Comment by ebuchman** [comment]
addressed by https://github.com/tendermint/tendermint/pull/291
