### ISSUE TITLE
docs: js counter example does not work

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#2931]
```
git clone https://github.com/tendermint/js-abci.git
cd js-abci/example
npm install
cd ..
node example/counter.js
==>
module.js:550
    throw err;
    ^

Error: Cannot find module 'abci'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/js-abci/example/counter.js:1:86)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

node -v v8.14.0
npm -v 6.4.1
js-abci@732db2f5cca02cdccfdb6ab4fd2f6450e6f76923

**Comment by melekes** [comment]
PR with a fix/feature was merged to develop. Will be shipped with 0.26.5 or 0.27.0 release (check the changelog).
