### ISSUE TITLE
connection error : module=abci-server error="Error reading message: unexpected EOF"

### ISSUE THREAD

**Issue by kunaldhariwal** [tendermint/tendermint#2962]
```
kunaldhariwal@kunaldhariwal:~$ abci-cli kvstore
I[12-02|14:33:22.632] Starting ABCIServer                          module=abci-server impl=ABCIServer
I[12-02|14:33:22.632] Waiting for new connection...                module=abci-server 
I[12-02|14:33:48.039] Accepted a new connection                    module=abci-server 
I[12-02|14:33:48.039] Waiting for new connection...                module=abci-server 
I[12-02|14:33:48.040] Accepted a new connection                    module=abci-server 
I[12-02|14:33:48.040] Waiting for new connection...                module=abci-server 
I[12-02|14:33:48.040] Accepted a new connection                    module=abci-server 
I[12-02|14:33:48.040] Waiting for new connection...                module=abci-server 
E[12-02|14:33:48.041] Connection error                             module=abci-server error="Error reading message: unexpected EOF"
E[12-02|14:33:48.044] Connection was closed by client              module=abci-server 
E[12-02|14:33:48.044] Connection was closed by client              module=abci-server 

```

```
kunaldhariwal@kunaldhariwal:~$ tendermint node
E[2126-12-02|20:12:12.322] Stopping abci.socketClient for error: EOF    module=abci-client connection=consensus
ERROR: Failed to create node: Error during handshake: Error on replay: EOF
```

I have this version of abci installed.
and when i try make install_abci, It gives an MAKE error even though i am in the working directory.

```
kunaldhariwal@kunaldhariwal:~$ abci-cli version
0.12.0
kunaldhariwal@kunaldhariwal:~$ tendermint version
0.26.4

```

**Comment by melekes** [comment]
0.12.0 is deprecated. Please use the latest version which you can find here https://github.com/tendermint/tendermint/tree/master/abci/cmd/abci-cli

What guide are you following? How did you install abci-cli?

**Comment by kunaldhariwal** [comment]
@melekes  I used this command to install abci-cli : 

go get -u github.com/tendermint/abci/cmd/...

**Comment by kunaldhariwal** [comment]
@melekes I now installed abci 0.15.0.
but now tendermint node is giving this error:

```

kunaldhariwal@kunaldhariwal:~$ tendermint node 
panic: Error initializing DB: resource temporarily unavailable

goroutine 1 [running]:
github.com/tendermint/tendermint/libs/db.NewDB(0xe37019, 0xa, 0xc000188ff0, 0x7, 0xc0001d8e40, 0x24, 0xc000188f40, 0xd)
	/home/kunaldhariwal/go/src/github.com/tendermint/tendermint/libs/db/db.go:51 +0x2a0
github.com/tendermint/tendermint/node.DefaultDBProvider(0xc0009342e0, 0xc0009342e0, 0x197, 0xc0001a6550, 0x40)
	/home/kunaldhariwal/go/src/github.com/tendermint/tendermint/node/node.go:61 +0xc2
github.com/tendermint/tendermint/node.NewNode(0xc0008e87e0, 0x1060120, 0xc0002046e0, 0xc000928dd0, 0x1053260, 0xc00090af60, 0xc000928ff0, 0xf980e0, 0xc000929000, 0x105eb60, ...)
	/home/kunaldhariwal/go/src/github.com/tendermint/tendermint/node/node.go:162 +0x83
github.com/tendermint/tendermint/node.DefaultNewNode(0xc0008e87e0, 0x105eb60, 0xc000907e40, 0xc0001a3500, 0xc00012bbe8, 0x1f)
	/home/kunaldhariwal/go/src/github.com/tendermint/tendermint/node/node.go:89 +0x25a
github.com/tendermint/tendermint/cmd/tendermint/commands.NewRunNodeCmd.func1(0xc00022eb40, 0x177cad8, 0x0, 0x0, 0x0, 0x0)
	/home/kunaldhariwal/go/src/github.com/tendermint/tendermint/cmd/tendermint/commands/run_node.go:55 +0x5b
github.com/tendermint/tendermint/vendor/github.com/spf13/cobra.(*Command).execute(0xc00022eb40, 0x177cad8, 0x0, 0x0, 0xc00022eb40, 0x177cad8)
	/home/kunaldhariwal/go/src/github.com/tendermint/tendermint/vendor/github.com/spf13/cobra/command.go:698 +0x47a
github.com/tendermint/tendermint/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1752860, 0xc000198fa0, 0xc00012be28, 0x7e5dad)
	/home/kunaldhariwal/go/src/github.com/tendermint/tendermint/vendor/github.com/spf13/cobra/command.go:783 +0x2dc
github.com/tendermint/tendermint/vendor/github.com/spf13/cobra.(*Command).Execute(0x1752860, 0x7e5662, 0xc000187310)
	/home/kunaldhariwal/go/src/github.com/tendermint/tendermint/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0x1752860, 0xf9a0d8, 0x2, 0xc0000314a0)
	/home/kunaldhariwal/go/src/github.com/tendermint/tendermint/libs/cli/setup.go:89 +0x4e
main.main()
	/home/kunaldhariwal/go/src/github.com/tendermint/tendermint/cmd/tendermint/main.go:45 +0x246
```

**Comment by melekes** [comment]
Check that another Tendermint is not running: `ps aux | grep tendermint`.

**Comment by kunaldhariwal** [comment]
It's working fine now, thanks for such quick replies.

**Comment by kunaldhariwal** [comment]
@melekes  I'm sorry to ask but if i want to run some other program apart from the examples. how do i run that? and how do i specify its location ? 
how do i create one and would the extension be .go?

**Comment by vamshireddy08** [comment]
> It's working fine now, thanks for such quick replies.

I am facing with the same issue. could you tell me what steps you have followed to resolve this issue.
