### ISSUE TITLE
non-deterministic test failure in TestWaitingTimeoutOnNilPolka

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3204]
Found on circle.

```
--- FAIL: TestWaitingTimeoutOnNilPolka (0.04s)
panic: Timeout expired while waiting for NewTimeout event [recovered]
	panic: Timeout expired while waiting for NewTimeout event

goroutine 39159 [running]:
testing.tRunner.func1(0xc009c46100)
	/usr/local/go/src/testing/testing.go:792 +0x6a7
panic(0xf7f7a0, 0xc00145f7e0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/tendermint/tendermint/consensus.ensureNewEvent(0xc006dd8a80, 0x1, 0x0, 0x1c9c380, 0x10ccf8d, 0x32)
	/go/src/github.com/tendermint/tendermint/consensus/common_test.go:362 +0x61f
github.com/tendermint/tendermint/consensus.ensureNewTimeout(0xc006dd8a80, 0x1, 0x0, 0x989680)
	/go/src/github.com/tendermint/tendermint/consensus/common_test.go:434 +0x70
github.com/tendermint/tendermint/consensus.TestWaitingTimeoutOnNilPolka(0xc009c46100)
	/go/src/github.com/tendermint/tendermint/consensus/state_test.go:1110 +0x362
testing.tRunner(0xc009c46100, 0x1203548)
	/usr/local/go/src/testing/testing.go:827 +0x163
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:878 +0x65a
FAIL	github.com/tendermint/tendermint/consensus	57.070s
Exited with code 1
```

See logs [build_42381_step_109_container_3.txt](https://github.com/tendermint/tendermint/files/2792557/build_42381_step_109_container_3.txt)

**Comment by ebuchman** [comment]
Duplicate of https://github.com/tendermint/tendermint/issues/2723
