### ISSUE TITLE
Potential deadlocks as reported by go-deadlock

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#3217]
```
POTENTIAL DEADLOCK: Inconsistent locking. saw this ordering in one goroutine:
happened before
bit_array.go:355 common.(*BitArray).Update { bA.mtx.Lock() } <<<<<
bit_array_test.go:198 common.TestUpdateNeverPanics { a.Update(b) }

happened after
bit_array.go:356 common.(*BitArray).Update { o.mtx.Lock() } <<<<<
bit_array_test.go:198 common.TestUpdateNeverPanics { a.Update(b) }

in another goroutine: happened before
bit_array.go:355 common.(*BitArray).Update { bA.mtx.Lock() } <<<<<
bit_array_test.go:199 common.TestUpdateNeverPanics { b.Update(a) }

happened after
bit_array.go:356 common.(*BitArray).Update { o.mtx.Lock() } <<<<<
bit_array_test.go:199 common.TestUpdateNeverPanics { b.Update(a) }

Other goroutines holding locks:
goroutine 100745 lock 0xc0022a4db0
bit_array.go:355 common.(*BitArray).Update { bA.mtx.Lock() } <<<<<
bit_array_test.go:199 common.TestUpdateNeverPanics { b.Update(a) }
```

Refs https://github.com/tendermint/tendermint/pull/3218

**Comment by ebuchman** [comment]
I don't really understand this - where are the go-routines related to this test?

**Comment by melekes** [comment]
It does not show go-routines (at least in this case). I guess we will need to examine TestUpdateNeverPanics.

**Comment by ebuchman** [comment]
That's what I'm saying - TestUpdateNeverPanics seems to have no associated go-routines!

**Comment by ancazamfir** [comment]
Yes, but I think the library assumes that if the code uses locks it is to safely access data across multiple go-routines. I think the order in bit array's Update() is wrong.

**Comment by melekes** [comment]
```
panic: sync: negative WaitGroup counter

goroutine 28 [running]:
sync.(*WaitGroup).Add(0xc0001a0090, 0xffffffffffffffff)
        /usr/local/Cellar/go/1.14.4/libexec/src/sync/waitgroup.go:74 +0x2c0
sync.(*WaitGroup).Done(...)
        /usr/local/Cellar/go/1.14.4/libexec/src/sync/waitgroup.go:99
github.com/tendermint/tendermint/abci/client.(*socketClient).didRecvResponse(0xc0001260a0, 0xc00006c270, 0x0, 0x0)
        /Users/antonk/go/src/github.com/tendermint/tendermint/abci/client/socket_client.go:205 +0x1f3
github.com/tendermint/tendermint/abci/client.(*socketClient).recvResponseRoutine(0xc0001260a0, 0xb43d038, 0xc000010040)
        /Users/antonk/go/src/github.com/tendermint/tendermint/abci/client/socket_client.go:174 +0x155
created by github.com/tendermint/tendermint/abci/client.(*socketClient).OnStart
        /Users/antonk/go/src/github.com/tendermint/tendermint/abci/client/socket_client.go:77 +0x399

WARNING: DATA RACE
Write at 0x00c00038a590 by goroutine 85:
  github.com/tendermint/tendermint/blockchain/v1.(*testReactor).sendPeerError()
      /Users/antonk/go/src/github.com/tendermint/tendermint/blockchain/v1/reactor_fsm_test.go:912 +0x1e7
  github.com/tendermint/tendermint/blockchain/v1.bcReactor.sendPeerError-fm()
      /Users/antonk/go/src/github.com/tendermint/tendermint/blockchain/v1/reactor_fsm.go:360 +0x6e
  github.com/tendermint/tendermint/blockchain/v1.(*BpPeer).onTimeout()
      /Users/antonk/go/src/github.com/tendermint/tendermint/blockchain/v1/peer.go:164 +0xcc
  github.com/tendermint/tendermint/blockchain/v1.(*BpPeer).onTimeout-fm()
      /Users/antonk/go/src/github.com/tendermint/tendermint/blockchain/v1/peer.go:163 +0x26

Previous write at 0x00c00038a590 by goroutine 76:
  [failed to restore the stack]

Goroutine 85 (running) created at:
  time.goFunc()
      /usr/local/Cellar/go/1.14.4/libexec/src/time/sleep.go:168 +0x51
==================

WARNING: DATA RACE
Write at 0x00c00038a580 by goroutine 85:
  github.com/tendermint/tendermint/blockchain/v1.(*testReactor).sendPeerError()
      /Users/antonk/go/src/github.com/tendermint/tendermint/blockchain/v1/reactor_fsm_test.go:911 +0x1b7
  github.com/tendermint/tendermint/blockchain/v1.bcReactor.sendPeerError-fm()
      /Users/antonk/go/src/github.com/tendermint/tendermint/blockchain/v1/reactor_fsm.go:360 +0x6e
  github.com/tendermint/tendermint/blockchain/v1.(*BpPeer).onTimeout()
      /Users/antonk/go/src/github.com/tendermint/tendermint/blockchain/v1/peer.go:164 +0xcc
  github.com/tendermint/tendermint/blockchain/v1.(*BpPeer).onTimeout-fm()
      /Users/antonk/go/src/github.com/tendermint/tendermint/blockchain/v1/peer.go:163 +0x26

Previous write at 0x00c00038a580 by goroutine 76:
  [failed to restore the stack]

Goroutine 85 (running) created at:
  time.goFunc()
      /usr/local/Cellar/go/1.14.4/libexec/src/time/sleep.go:168 +0x51
==================
```
