### ISSUE TITLE
TestStateLockPOLSafety1 fails (non-deterministically?)

### ISSUE THREAD

**Issue by Liamsi** [tendermint/tendermint#3317]
```
--- FAIL: TestStateLockPOLSafety1 (0.13s)
    state_test.go:710: old prop hash 65C399828562B907806FC80DBCC22E8581F46D2FFF70B630C5124AFC40F15181
    state_test.go:719: ### ONTO ROUND 1
    state_test.go:746: new prop hash 65C399828562B907806FC80DBCC22E8581F46D2FFF70B630C5124AFC40F15181
panic: Timeout expired while waiting for NewTimeout event [recovered]
	panic: Timeout expired while waiting for NewTimeout event

goroutine 38740 [running]:
testing.tRunner.func1(0xc000c0c200)
	/usr/local/go/src/testing/testing.go:792 +0x6a7
panic(0xf818a0, 0xc0074bf5b0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/tendermint/tendermint/consensus.ensureNewEvent(0xc0094dab40, 0x1, 0x1, 0x1c9c380, 0x10cef01, 0x32)
	/go/src/github.com/tendermint/tendermint/consensus/common_test.go:362 +0x61f
github.com/tendermint/tendermint/consensus.ensureNewTimeout(0xc0094dab40, 0x1, 0x1, 0x989680)
	/go/src/github.com/tendermint/tendermint/consensus/common_test.go:404 +0x70
github.com/tendermint/tendermint/consensus.TestStateLockPOLSafety1(0xc000c0c200)
	/go/src/github.com/tendermint/tendermint/consensus/state_test.go:761 +0x1027
testing.tRunner(0xc000c0c200, 0x12055e0)
	/usr/local/go/src/testing/testing.go:827 +0x163
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:878 +0x65a
FAIL	github.com/tendermint/tendermint/consensus	59.575s
Exited with code 1

```

ref https://github.com/tendermint/tendermint/pull/3316

**Comment by melekes** [comment]
Should be fixed in https://github.com/tendermint/tendermint/pull/3582.
