### ISSUE TITLE
close flushTimer twice

### ISSUE THREAD

**Issue by guagualvcha** [tendermint/tendermint#3352]
### Description
I get log in seed:

```
panic: close of closed channel

goroutine 8133080 [running]:
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/libs/common.(*ThrottleTimer).Stop(0xc0045cb980, 0xc00aca7200)
        /root/bnbchain/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/libs/common/throttle_timer.go:71 +0x41
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/p2p/conn.(*MConnection).FlushStop(0xc0042897c0)
        /root/bnbchain/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/p2p/conn/connection.go:216 +0x36
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/p2p.(*peer).FlushStop(0xc006d2bc80)
        /root/bnbchain/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/p2p/peer.go:193 +0x44
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/p2p/pex.(*PEXReactor).Receive.func1(0x12d6500, 0xc006d2bc80, 0xc0000bc240)
        /root/bnbchain/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/p2p/pex/pex_reactor.go:234 +0x31
created by github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/p2p/pex.(*PEXReactor).Receive
        /root/bnbchain/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/p2p/pex/pex_reactor.go:232 +0x87e
panic: close of closed channel
```
### Rationale

Seed is running in seed mode, when it receive a `pexRequestMessage` and the peer is not persistent, it will:
```
src.FlushStop()
r.Switch.StopPeerGracefully(src)
```
But if other reactor called `StopPeerForError`,  since `FlushStop` is not an interface of `BaseService`, it may happend with`mconnection.OnStopn()` at the same time, which will cause panic.

**Comment by ebuchman** [comment]
What version please

**Comment by guagualvcha** [comment]
v0.29.1-rc0

**Comment by melekes** [comment]
I believe this was fixed in https://github.com/tendermint/tendermint/pull/3254.

Have you tried the latest version?

**Comment by guagualvcha** [comment]
I believe so
