### ISSUE TITLE
panic: accept routine exited: filter timed out

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#3369]
```
panic: accept routine exited: filter timed out

goroutine 791038 [running]:
github.com/tendermint/tendermint/p2p.(*Switch).acceptRoutine(0xc000352690)
        /home/jslave/workspace/02.Fetch.Binary@3/go/src/github.com/tendermint/tendermint/p2p/switch.go:516 +0xead
created by github.com/tendermint/tendermint/p2p.(*Switch).OnStart
        /home/jslave/workspace/02.Fetch.Binary@3/go/src/github.com/tendermint/tendermint/p2p/switch.go:204 +0x1ea
```

happend on tendermint 0.30.1 under high LA (50-100), machine was struggling with the load.

**Comment by ebuchman** [comment]
Oh, we shouldn't kill the acceptRoutine for this error. It just means it took to long getting a response from the ABCI app on whether to accept this peer. So in that case we should just reject the peer, but no need to kill the whole routine!

**Comment by melekes** [comment]
Merged to develop.
