### ISSUE TITLE
blockchain: non-deterministic test fail

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3400]
```
=== RUN   TestBadBlockStopsPeer
...
I[2019-03-10|09:19:32.335] Executed block                               height=146 validTxs=10 invalidTxs=0
I[2019-03-10|09:19:32.335] Committed state                              height=146 txs=10 appHash=
I[2019-03-10|09:19:32.336] Executed block                               height=147 validTxs=10 invalidTxs=0
I[2019-03-10|09:19:32.336] Committed state                              height=147 txs=10 appHash=
I[2019-03-10|09:19:32.339] Starting P2P Switch                          switch=0 impl="P2P Switch"
panic: Panicked on a Sanity Check: BlockStore can only save contiguous blocks. Wanted 149, got 147

goroutine 1251 [running]:
github.com/tendermint/tendermint/libs/common.PanicSanity(0xecf420, 0xc00130ebf0)
	/go/src/github.com/tendermint/tendermint/libs/common/errors.go:224 +0xc6
github.com/tendermint/tendermint/blockchain.(*BlockStore).SaveBlock(0xc000524840, 0xc0012cd680, 0xc000bacd20, 0xc00017c680)
	/go/src/github.com/tendermint/tendermint/blockchain/store.go:151 +0x807
github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine(0xc0013abba0)
	/go/src/github.com/tendermint/tendermint/blockchain/reactor.go:332 +0xfb0
created by github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).OnStart
	/go/src/github.com/tendermint/tendermint/blockchain/reactor.go:117 +0x129
FAIL	github.com/tendermint/tendermint/blockchain	7.102s
Exited with code 1

```

Seen in https://circleci.com/gh/tendermint/tendermint/49647#tests/containers/2

[build_49647_step_105_container_2.txt.zip](https://github.com/tendermint/tendermint/files/2949953/build_49647_step_105_container_2.txt.zip)

**Comment by melekes** [comment]
Just got this locally:

```
panic: Panicked on a Sanity Check: BlockStore can only save contiguous blocks. Wanted 149, got 1

goroutine 1395 [running]:
github.com/tendermint/tendermint/libs/common.PanicSanity(...)
        /home/vagrant/go/src/github.com/tendermint/tendermint/libs/common/errors.go:224
github.com/tendermint/tendermint/blockchain.(*BlockStore).SaveBlock(0xc0010d4f30, 0xc000e1b4a0, 0xc000445e00, 0xc0013e1680)
        /home/vagrant/go/src/github.com/tendermint/tendermint/blockchain/store.go:151 +0x7e4
github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine(0xc0010b49c0)
        /home/vagrant/go/src/github.com/tendermint/tendermint/blockchain/reactor.go:332 +0xa5f
created by github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).OnStart
        /home/vagrant/go/src/github.com/tendermint/tendermint/blockchain/reactor.go:117 +0x84
FAIL    github.com/tendermint/tendermint/blockchain     3.638s
```

**Comment by Liamsi** [comment]
Happened again in https://circleci.com/gh/tendermint/tendermint/50796#tests/containers/2 (#3449)
Also the race detector complained there.

**Comment by ebuchman** [comment]
Bumping this up to the next release since it keeps tripping. Not sure if something changed to make this happen more but we should deal with it.

**Comment by melekes** [comment]
Do we have to spend time on this given the blockchain package will be completely rewritten?

**Comment by xla** [comment]
Referrencing #3506 for tracking purposes.

**Comment by milosevic** [comment]
It does not make sense working on this now. We will pretty soon have new version of reactor and tests will be written in completely very different way.

**Comment by ebuchman** [comment]
New race on the same test:

```
==================
WARNING: DATA RACE
Write at 0x00c0014c5830 by goroutine 97:
  github.com/tendermint/tendermint/blockchain.TestBadBlockStopsPeer()
      /go/src/github.com/tendermint/tendermint/blockchain/reactor_test.go:235 +0x978
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:865 +0x163

Previous read at 0x00c0014c5830 by goroutine 461:
  github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine()
      /go/src/github.com/tendermint/tendermint/blockchain/reactor.go:339 +0xeca

Goroutine 97 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:916 +0x65a
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1157 +0xa8
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:865 +0x163
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1155 +0x523
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1072 +0x2eb
  github.com/tendermint/tendermint/blockchain.TestMain()
      /go/src/github.com/tendermint/tendermint/blockchain/store_test.go:111 +0x5cb
  main.main()
      _testmain.go:114 +0x330

Goroutine 461 (running) created at:
  github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).OnStart()
      /go/src/github.com/tendermint/tendermint/blockchain/reactor.go:117 +0x127
  github.com/tendermint/tendermint/libs/common.(*BaseService).Start()
      /go/src/github.com/tendermint/tendermint/libs/common/service.go:139 +0x504
  github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).Start()
      <autogenerated>:1 +0x43
  github.com/tendermint/tendermint/p2p.(*Switch).OnStart()
      /go/src/github.com/tendermint/tendermint/p2p/switch.go:208 +0x123
  github.com/tendermint/tendermint/libs/common.(*BaseService).Start()
      /go/src/github.com/tendermint/tendermint/libs/common/service.go:139 +0x504
  github.com/tendermint/tendermint/p2p.StartSwitches()
      /go/src/github.com/tendermint/tendermint/p2p/test_util.go:158 +0x75
  github.com/tendermint/tendermint/p2p.MakeConnectedSwitches()
      /go/src/github.com/tendermint/tendermint/p2p/test_util.go:79 +0x18e
  github.com/tendermint/tendermint/blockchain.TestBadBlockStopsPeer()
      /go/src/github.com/tendermint/tendermint/blockchain/reactor_test.go:210 +0x72b
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:865 +0x163
==================

```

**Comment by erikgrinaker** [comment]
This was mitigated in b9a0d47f1467f1b8b8a589ee0da68374af0ab7bb, reactor is slated for removal once v2 get some real-world testing.
