### ISSUE TITLE
bug: uninitialized votesets

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#341]
The crash/restart tests just caught this bug, related to queryMaj23 logic around existing votesets:

```
NOTE[12-22|00:41:06] enterNewRound(28/0). Current: 28/0/RoundStepNewHeight module=consensus
NOTE[12-22|00:41:06] enterPrecommit: No +2/3 prevotes during enterPrecommit. Precommitting nil. module=consensus
WARN[12-22|00:41:06] Attempt to finalize failed. We don't have the commit block. module=consensus
NOTE[12-22|00:41:07] Finalizing commit of block with 0 txs    module=consensus height=28 hash=E772057B06DC00560B10384F6C2D9C5F18183E9E root=07F03D501B085AC9BCA8594743DD81B177166A0F
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4c7444]

goroutine 349 [running]:
panic(0xbb0960, 0xc820012080)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/tendermint/tendermint/types.(*VoteSet).TwoThirdsMajority(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x28b90fc01042c00)
        /go/src/github.com/tendermint/tendermint/types/vote_set.go:387 +0x1d4
github.com/tendermint/tendermint/consensus.(*ConsensusReactor).queryMaj23Routine(0xc8201528c0, 0xc82030e460, 0xc8200c2000)
        /go/src/github.com/tendermint/tendermint/consensus/reactor.go:603 +0x24f
created by github.com/tendermint/tendermint/consensus.(*ConsensusReactor).AddPeer
        /go/src/github.com/tendermint/tendermint/consensus/reactor.go:125 +0x1a3
```

**Comment by akalyaev** [comment]
Can't reproduce this on `restart_test` branch.

**Comment by ebuchman** [comment]
I haven't been able to reproduce since either.

**Comment by ebuchman** [comment]
got it again on circle! this time during the fast sync tests:

```
NOTE[01-11|15:19:56] Saving block                             module=dummy height=29 root=07F03D501B085AC9BCA8594743DD81B177166A0F
NOTE[01-11|15:19:56] Saving block                             module=dummy height=30 root=07F03D501B085AC9BCA8594743DD81B177166A0F
NOTE[01-11|15:19:56] Saving block                             module=dummy height=31 root=07F03D501B085AC9BCA8594743DD81B177166A0F
NOTE[01-11|15:19:56] Saving block                             module=dummy height=32 root=07F03D501B085AC9BCA8594743DD81B177166A0F
NOTE[01-11|15:19:56] Saving block                             module=dummy height=33 root=07F03D501B085AC9BCA8594743DD81B177166A0F
NOTE[01-11|15:19:56] Saving block                             module=dummy height=34 root=07F03D501B085AC9BCA8594743DD81B177166A0F
NOTE[01-11|15:19:56] IsCaughtUp: true                         module=blockchain height=35 maxPeerHeight=35
NOTE[01-11|15:19:56] Time to switch to consensus reactor!     module=blockchain height=35
NOTE[01-11|15:19:56] SwitchToConsensus                        module=consensus
WARN[01-11|15:19:56] Height not found in wal. Writing new height module=consensus height=35
NOTE[01-11|15:19:56] Catchup by replaying consensus messages  module=consensus height=35
NOTE[01-11|15:19:56] Replay: New Step                         module=consensus height=35 round=0 step=RoundStepNewHeight
NOTE[01-11|15:19:56] Replay: Done                             module=consensus
WARN[01-11|15:19:56] Timer already stopped                    module=consensus
WARN[01-11|15:19:57] Need to set a buffer and log.Warn() here for sanity. module=consensus startTime=2017-01-11T15:19:57+0000 now=2017-01-11T15:19:57+0000
NOTE[01-11|15:19:57] enterNewRound(35/0). Current: 35/0/RoundStepNewHeight module=consensus
NOTE[01-11|15:19:57] enterPrecommit: No +2/3 prevotes during enterPrecommit. Precommitting nil. module=consensus
WARN[01-11|15:19:57] Attempt to finalize failed. We don't have the commit block. module=consensus
NOTE[01-11|15:19:57] Finalizing commit of block with 0 txs    module=consensus height=35 hash=72E3074121899659C7AC2C3DE64C09E490DDF930 root=07F03D501B085AC9BCA8594743DD81B177166A0F
NOTE[01-11|15:19:57] Saving block                             module=dummy height=35 root=07F03D501B085AC9BCA8594743DD81B177166A0F
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4c7444]

goroutine 370 [running]:
panic(0xbb2ac0, 0xc820012080)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/tendermint/tendermint/types.(*VoteSet).TwoThirdsMajority(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1006bc30235ea00)
	/go/src/github.com/tendermint/tendermint/types/vote_set.go:387 +0x1d4
github.com/tendermint/tendermint/consensus.(*ConsensusReactor).queryMaj23Routine(0xc8204baaf0, 0xc8204d9420, 0xc8200b2000)
	/go/src/github.com/tendermint/tendermint/consensus/reactor.go:603 +0x24f
created by github.com/tendermint/tendermint/consensus.(*ConsensusReactor).AddPeer
	/go/src/github.com/tendermint/tendermint/consensus/reactor.go:125 +0x1a3
```

**Comment by jaekwon** [comment]
Oops.  We just need to handle the cases when the voteSets are nil, and return nil/false for TwoThirdsMajority().
