### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by zillerium** [tendermint/tendermint#3425]
I saw this error from 2017 and 2018 but not recently. I installed as root (sudo did not work). I am running as sudo. I get the error shown. I installed using a script (below). 

```
trevor@ipfs-droplet:~/tendermint$ sudo tendermint node --proxy_app=kvstore
 
NOTE[03-13|15:03:43] Loaded PrivValidator                     module=types file=/home/trevor/.tendermint/priv_validator.json privValidator="PrivValidator{C9AF69E487CFC01E7C4D6180F87344E164FAF1C6 LH:0, LR:0, LS:0}"
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/tendermint/go-common.Connect(0x7ffd7ef5e8ca, 0x7, 0xb, 0xb, 0xc42004b5b8, 0x4110d0)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/go-common/net.go:11 +0xc5
github.com/tendermint/abci/client.(*socketClient).OnStart(0xc42007f220, 0xc42004b5d8, 0x413327)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/abci/client/socket_client.go:68 +0x3e
github.com/tendermint/go-common.(*BaseService).Start(0xc42007f220, 0xc42007f220, 0xc42004b660, 0xc42001b9c0)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/go-common/service.go:96 +0x2c2
github.com/tendermint/abci/client.NewSocketClient(0x7ffd7ef5e8ca, 0x7, 0xc42007c400, 0x0, 0x0, 0xc42004b708)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/abci/client/socket_client.go:57 +0x23c
github.com/tendermint/abci/client.NewClient(0x7ffd7ef5e8ca, 0x7, 0xac2e46, 0x6, 0x0, 0x2, 0xc42001b980, 0x4, 0x4)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/abci/client/client.go:49 +0x17a
github.com/tendermint/tendermint/proxy.(*remoteClientCreator).NewABCIClient(0xc42043cc30, 0xc42007c480, 0xd40c90, 0xc42001b980, 0xf02a00)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/tendermint/proxy/client.go:57 +0x55
github.com/tendermint/tendermint/proxy.(*multiAppConn).OnStart(0xc42007c3f0, 0xc420458ec0, 0x15)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/tendermint/proxy/multi_app_conn.go:78 +0x3e
github.com/tendermint/go-common.(*BaseService).Start(0xc42007c3f0, 0xc42007c300, 0x0, 0x0)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/go-common/service.go:96 +0x2c2
github.com/tendermint/tendermint/node.NewNode(0xec7480, 0xc420120ba0, 0xc42049c320, 0xeba520, 0xc42043cc30, 0x0)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/tendermint/node/node.go:68 +0x47a
github.com/tendermint/tendermint/node.NewNodeDefault(0xec7480, 0xc420120ba0, 0x1)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/tendermint/node/node.go:51 +0xba
github.com/tendermint/tendermint/node.RunNode(0xec7480, 0xc420120ba0)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/tendermint/node/node.go:350 +0x4fa
main.main()
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/tendermint/cmd/tendermint/main.go:42 +0x2e4
```
 

```
Version 0.8.0
Ubuntu 18.04

I installed from this -

#!/usr/bin/env bash

# XXX: this script is meant to be used only on a fresh Ubuntu 16.04 instance
# and has only been tested on Digital Ocean

# get and unpack golang
curl -O https://storage.googleapis.com/golang/go1.10.linux-amd64.tar.gz
tar -xvf go1.10.linux-amd64.tar.gz

apt install make

## move go and add binary to path
mv go /usr/local
echo "export PATH=\$PATH:/usr/local/go/bin" >> ~/.profile

## create the GOPATH directory, set GOPATH and put on PATH
mkdir goApps
echo "export GOPATH=/root/goApps" >> ~/.profile
echo "export PATH=\$PATH:\$GOPATH/bin" >> ~/.profile

source ~/.profile

## get the code and move into it
REPO=github.com/tendermint/tendermint
go get $REPO
cd $GOPATH/src/$REPO

## build
git checkout master
make get_tools
make get_vendor_deps
make install
```

**Comment by melekes** [comment]
v0.8.0 is a really old version. Have you tried the latest v0.30.2 version? If no, I'd strongly advise to upgrade. There has been thousands of improvements made since v0.8.0.

**Comment by melekes** [comment]
Closing due to no response.

**Comment by zillerium** [comment]
I did not have time yet to test this. You closed this after one day. I have a lot of other work to do.

**Comment by melekes** [comment]
Sorry about that. When do you think you'll have time to check?

**Comment by zillerium** [comment]
I will work on the problem this weekend. I was preparing for the Paris hackthon (Cosmos/Tendermint one).

**Comment by zillerium** [comment]
I did not actually have time to test this I will close this now.

**Comment by harshsinghiitd** [comment]
@melekes When ever we follow the installation step it give tendermint v0.8.0. All if we try to upgrade it shows up "Already up to date"

**Comment by melekes** [comment]
@harshsinghiitd I'd suggest to do a clean install.

1) Remove everything old

```
rm -rf ~/.tendermint
rm -rf $GOPATH/src/github.com/tendermint/tendermint
rm -rf $GOPATH/bin/tendermint
```

2) Install go https://golang.org/doc/install
3) Install Tendermint Core https://tendermint.com/docs/introduction/install.html#install-tendermint
