### ISSUE TITLE
consensus: Exception in consensus/reactor.go AddPeer during shutdown

### ISSUE THREAD

**Issue by seanyoung** [tendermint/tendermint#3535]
Tendermint 0.31.2
OS: Fedora 29
Burrow: 0.25.0

One of the burrow tests throws an exception in tendermint. Steps to reproduce:

- checkout burrow 0.25.0
- remove integration/governance/governance_test.go line 278 (note comment above!)
- using go 1.12, run:

go test --cpu 256  -v -tags integration ./integration/governance/...

And you should see it go bang with the exception:

```
	// goroutine 2181 [running]:
	// runtime/debug.Stack(0x12786c0, 0xc000085d70, 0xc000085c50)
	// /home/sean/go1.12.1/src/runtime/debug/stack.go:24 +0x9d
	// github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/libs/db.(*GoLevelDB).Get(0xc005c5b318, 0xc01fd71840, 0x5, 0x8, 0x5, 0x8, 0x5)
	// /home/sean/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/libs/db/go_level_db.go:57 +0xaf
	// github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/blockchain.(*BlockStore).LoadSeenCommit(0xc00bfd6120, 0x12, 0xc002b85c90)
	// /home/sean/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/blockchain/store.go:128 +0xf2
	// github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).LoadCommit(0xc002b85c00, 0x12, 0x0)
	// /home/sean/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/consensus/state.go:273 +0xb2
	// github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusReactor).queryMaj23Routine(0xc0008ec680, 0x12ad1a0, 0xc010f79800, 0xc009119520)
	// /home/sean/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/consensus/reactor.go:789 +0x291
	// created by github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusReactor).AddPeer
	// /home/sean/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/consensus/reactor.go:171 +0x23a
```

I'm not sure how the code is supposed to be race-free. When a new peer connects, 
consensus/reactor.go:789 is called, which creates a new go routine queryMaj23Routine(). This does a LoadSeenCommit() asynchronously AFTER the node has been shut down. How can this work?

Thanks

**Comment by ebuchman** [comment]
Is this stack trace showing a panic or a race or what?

**Comment by seanyoung** [comment]
It's a panic

**Comment by melekes** [comment]
Could you post the actual panic message?

**Comment by melekes** [comment]
Closing due to no response.
