### ISSUE TITLE
When creating testnet with 5 nodes node_key.json not found

### ISSUE THREAD

**Issue by gauthamzz** [tendermint/tendermint#3538]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): 0.29.1-4d7b29cd

i created 5 node network using `tendermint testnet -n 5` command

it created 5 nodes 

but when 
```
sudo tendermint show_node_id --home node4
ERROR: open node4/config/node_key.json: no such file or directory
```
It works for all other nodes 0 to 3 (4 nodes)

**Comment by ebuchman** [comment]
Huh the command actually panics for me. Does it panic for you?

```
I[2019-04-09|23:38:12.478] Generated private validator                  module=main keyFile=mytestnet/node3/config/priv_validator_key.json stateFile=mytestnet/node3/data/priv_validator_state.json
I[2019-04-09|23:38:12.479] Generated node key                           module=main path=mytestnet/node3/config/node_key.json
I[2019-04-09|23:38:12.479] Generated genesis file                       module=main path=mytestnet/node3/config/genesis.json
panic: open mytestnet/node4/data/write-file-atomic-1433638732424959482: no such file or directory

goroutine 1 [running]:
github.com/tendermint/tendermint/privval.(*FilePVLastSignState).Save(0xc000894048)
	/Users/me/programming/goApps/src/github.com/tendermint/tendermint/privval/file.go:127 +0x107
github.com/tendermint/tendermint/privval.(*FilePV).Save(0xc000894000)
	/Users/me/programming/goApps/src/github.com/tendermint/tendermint/privval/file.go:258 +0x64
github.com/tendermint/tendermint/cmd/tendermint/commands.initFilesWithConfig(0xc0001bd900, 0x16, 0x1ed)
	/Users/me/programming/goApps/src/github.com/tendermint/tendermint/cmd/tendermint/commands/init.go:37 +0xcff
github.com/tendermint/tendermint/cmd/tendermint/commands.testnetFiles(0x237cf00, 0xc0000a9800, 0x0, 0x2, 0x0, 0x0)
	/Users/me/programming/goApps/src/github.com/tendermint/tendermint/cmd/tendermint/commands/testnet.go:118 +0x7ac
github.com/tendermint/tendermint/vendor/github.com/spf13/cobra.(*Command).execute(0x237cf00, 0xc0000a97c0, 0x2, 0x2, 0x237cf00, 0xc0000a97c0)
	/Users/me/programming/goApps/src/github.com/tendermint/tendermint/vendor/github.com/spf13/cobra/command.go:698 +0x47a
github.com/tendermint/tendermint/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x237c8a0, 0xc0000a9720, 0xc000099e28, 0x13f3aad)
	/Users/me/programming/goApps/src/github.com/tendermint/tendermint/vendor/github.com/spf13/cobra/command.go:783 +0x2dc
github.com/tendermint/tendermint/vendor/github.com/spf13/cobra.(*Command).Execute(0x237c8a0, 0x13f335b, 0xc000157320)
	/Users/me/programming/goApps/src/github.com/tendermint/tendermint/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0x237c8a0, 0x1bb1de0, 0x2, 0xc000037880)
	/Users/me/programming/goApps/src/github.com/tendermint/tendermint/libs/cli/setup.go:89 +0x4e
main.main()
	/Users/me/programming/goApps/src/github.com/tendermint/tendermint/cmd/tendermint/main.go:45 +0x246
```

Note `--n` is for non-validator nodes. If you want to make a testnet with 5 validators (instead of 4), use `--v`.  That should work fine. We'll have to investigate the `--n` issue

**Comment by bradyjoestar** [comment]
I'm try to solve this issue but found it's very difficlut to reproduce it.

**Comment by gauthamzz** [comment]
It doesn’t panic for me. It’s just says the file is not found.
