### ISSUE TITLE
p2p: TestNewNetAddressStringWithOptionalID fails on develop

### ISSUE THREAD

**Issue by coriolinus** [tendermint/tendermint#3542]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

```sh
~/go/src/github.com/tendermint/tendermint
$ git rev-parse --verify HEAD
Wed Apr 10 15:24:43 CEST 2019
9a415b057238d118c1edf23d673ebf9ce4f8d2ae
```

**Environment**:
- **OS** (e.g. from /etc/os-release):

OSX Mojave v10.14.4

**What happened**:

```sh
~/go/src/github.com/tendermint/tendermint
$ git pull && dep ensure && git rev-parse HEAD && git rev-parse --abbrev-ref HEAD && go test ./p2p -run TestNewNetAddressStringWithOptionalID
Wed Apr 10 15:26:50 CEST 2019
Already up to date.
9a415b057238d118c1edf23d673ebf9ce4f8d2ae
develop
--- FAIL: TestNewNetAddressStringWithOptionalID (0.00s)
    --- FAIL: TestNewNetAddressStringWithOptionalID/malformed_udp_input (0.00s)
        Error Trace:    netaddress_test.go:68
        Error:      	Expected value not to be nil.
        Test:       	TestNewNetAddressStringWithOptionalID/malformed_udp_input
        Messages:   	udp//127.0.0.1:8080
FAIL
FAIL	github.com/tendermint/tendermint/p2p	0.061s
```

**What you expected to happen**:

Test success

**Comment by coriolinus** [comment]
Actually it turns out that several tests fail on `develop`:

```sh
~/go/src/github.com/tendermint/tendermint
$ go test ./... | rg -v '^ok' | rg -v '^\?'
Wed Apr 10 15:30:54 CEST 2019
--- FAIL: TestHandshakeReplayNone (0.40s)
panic: open /var/folders/b9/zjyrkvh10s55spq3hgwkmqcr0000gn/T/-TestHandshakeReplayNone_2_679381296/data/1/kvstore.db: too many open files [recovered]
	panic: open /var/folders/b9/zjyrkvh10s55spq3hgwkmqcr0000gn/T/-TestHandshakeReplayNone_2_679381296/data/1/kvstore.db: too many open files

goroutine 31240 [running]:
testing.tRunner.func1(0xc000a52700)
	/usr/local/opt/go/libexec/src/testing/testing.go:830 +0x392
panic(0x1841800, 0xc0098fa030)
	/usr/local/opt/go/libexec/src/runtime/panic.go:522 +0x1b5
github.com/tendermint/tendermint/abci/example/kvstore.NewPersistentKVStoreApplication(0xc001c79d40, 0x5c, 0x2)
	/Users/prgn/go/src/github.com/tendermint/tendermint/abci/example/kvstore/persistent_kvstore.go:37 +0x1d6
github.com/tendermint/tendermint/consensus.buildTMStateFromChain(0xc000d2a3c0, 0x1b86bc0, 0xc0001515c0, 0xa, 0x1, 0x1923db6, 0x6, 0xc00708ece0, 0xf, 0x0, ...)
	/Users/prgn/go/src/github.com/tendermint/tendermint/consensus/replay_test.go:456 +0x123
github.com/tendermint/tendermint/consensus.testHandshakeReplay(0xc000a52700, 0xc000d2a3c0, 0x6, 0x2)
	/Users/prgn/go/src/github.com/tendermint/tendermint/consensus/replay_test.go:357 +0x578
github.com/tendermint/tendermint/consensus.TestHandshakeReplayNone(0xc000a52700)
	/Users/prgn/go/src/github.com/tendermint/tendermint/consensus/replay_test.go:314 +0x79
testing.tRunner(0xc000a52700, 0x1a80108)
	/usr/local/opt/go/libexec/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/opt/go/libexec/src/testing/testing.go:916 +0x35a
FAIL	github.com/tendermint/tendermint/consensus	14.160s
--- FAIL: TestNewNetAddressStringWithOptionalID (0.00s)
    --- FAIL: TestNewNetAddressStringWithOptionalID/malformed_udp_input (0.00s)
        Error Trace:    netaddress_test.go:68
        Error:      	Expected value not to be nil.
        Test:       	TestNewNetAddressStringWithOptionalID/malformed_udp_input
        Messages:   	udp//127.0.0.1:8080
2019/04/10 15:30:57 Failed to accept conn: accept tcp 127.0.0.1:56099: use of closed network connection
2019/04/10 15:30:57 Failed to accept conn: accept tcp 127.0.0.1:56103: use of closed network connection
2019/04/10 15:30:57 Failed to accept conn: accept tcp 127.0.0.1:56113: use of closed network connection
2019/04/10 15:30:58 Failed to accept conn: accept tcp 127.0.0.1:56117: use of closed network connection
2019/04/10 15:30:58 Failed to accept conn: accept tcp 127.0.0.1:56121: use of closed network connection
2019/04/10 15:30:58 Failed to accept conn: accept tcp 127.0.0.1:56125: use of closed network connection
2019/04/10 15:30:58 Failed to accept conn: accept tcp 127.0.0.1:56129: use of closed network connection
2019/04/10 15:30:58 Failed to accept conn: accept tcp 127.0.0.1:56160: use of closed network connection
2019/04/10 15:30:58 Failed to accept conn: accept tcp 127.0.0.1:56157: use of closed network connection
2019/04/10 15:30:58 Failed to accept conn: accept tcp 127.0.0.1:56191: use of closed network connection
2019/04/10 15:30:58 Failed to accept conn: accept tcp 127.0.0.1:56181: use of closed network connection
2019/04/10 15:30:58 Failed to accept conn: accept tcp 127.0.0.1:56183: use of closed network connection
2019/04/10 15:30:58 Failed to accept conn: accept tcp 127.0.0.1:56185: use of closed network connection
2019/04/10 15:30:58 Failed to accept conn: accept tcp 127.0.0.1:56187: use of closed network connection
2019/04/10 15:30:58 Failed to accept conn: accept tcp 127.0.0.1:56189: use of closed network connection
FAIL
FAIL	github.com/tendermint/tendermint/p2p	1.153s
--- FAIL: TestCheckSeeds (0.03s)
        Error Trace:    pex_reactor_test.go:225
        Error:      	An error is expected but got nil.
        Test:       	TestCheckSeeds
FAIL
FAIL	github.com/tendermint/tendermint/p2p/pex	8.343s
```

**Comment by Liamsi** [comment]
Thank you! I'm not sure what causes the tests to fail but I can not reproduce this locally.

**Comment by coriolinus** [comment]
Well that's fascinating.

Possibly it was dep? I note that this has produced a diff in `Gopkg.lock`:

```sh
~/go/src/github.com/tendermint/tendermint
$ dep ensure && git diff
Wed Apr 10 15:52:54 CEST 2019
diff --git a/Gopkg.lock b/Gopkg.lock
index 530cd89d..56c79ab6 100644
--- a/Gopkg.lock
+++ b/Gopkg.lock
@@ -170,9 +170,12 @@
   revision = "b84e30acd515aadc4b783ad4ff83aff3299bdfe0"
 
 [[projects]]
-  digest = "1:c568d7727aa262c32bdf8a3f7db83614f7af0ed661474b24588de635c20024c7"
+  digest = "1:53e8c5c79716437e601696140e8b1801aae4204f4ec54a504333702a49572c4f"
   name = "github.com/magiconair/properties"
-  packages = ["."]
+  packages = [
+    ".",
+    "assert",
+  ]
   pruneopts = "UT"
   revision = "c2353362d570a7bfa228149c62842019201cfb71"
   version = "v1.8.0"
@@ -516,6 +519,7 @@
     "github.com/golang/protobuf/ptypes/timestamp",
     "github.com/gorilla/websocket",
     "github.com/jmhodges/levigo",
+    "github.com/magiconair/properties/assert",
     "github.com/pkg/errors",
     "github.com/prometheus/client_golang/prometheus",
     "github.com/prometheus/client_golang/prometheus/promhttp",
```

**Comment by coriolinus** [comment]
Did a little debugging. The test case `TestNewNetAddressStringWithOptionalID/malformed_udp_input` depends on the following line to return an error:

https://github.com/tendermint/tendermint/blob/9a415b057238d118c1edf23d673ebf9ce4f8d2ae/p2p/netaddress.go#L112

`host`, as of that line, is `"udp//127.0.0.1"`.

I stopped stepping into functions at https://github.com/golang/go/blob/eddb41eb2cb7699f3515a229ff069ca914c7c879/src/net/lookup.go#L191

but possibly the OSX `DefaultResolver` is more tolerant of malformed host lines than most? In any case, it returned two plausible-looking IPs and no error.

**Comment by Liamsi** [comment]
> but possibly the OSX DefaultResolver is more tolerant of malformed host lines than most? In any case, it returned two plausible-looking IPs and no error.

I also ran the tests on OSX Mojave (I'll verify if I'm also using the exact same version in bit, too).

**Comment by coriolinus** [comment]
Minimal test case: create `cmd/lookup_badudp/main.go` containing:

```go
package main

import (
	"fmt"
	"net"
)

func main() {
	ips, err := net.LookupIP("udp//127.0.0.1")
	fmt.Println("ips:", ips)
	fmt.Println("err:", err)
}
```

And run:

```sh
~/go/src/github.com/tendermint/tendermint
$ go run ./cmd/lookup_badudp/
Wed Apr 10 17:44:38 CEST 2019
ips: [62.138.238.45 62.138.239.45]
err: <nil>
```

**Comment by Liamsi** [comment]
here 🤷‍♂️ 
```
ips: []
err: lookup udp//127.0.0.1: no such host
```

**Comment by Liamsi** [comment]
(finger slipped, didn't mean to close this, just wanted to comment)

**Comment by coriolinus** [comment]
In case it's not OSX but go itself:

```sh
$ go version
Wed Apr 10 18:01:08 CEST 2019
go version go1.12.1 darwin/amd64
```

**Comment by coriolinus** [comment]
Well, there's a partial solution: turns out that the malformed URL was being forwarded to my ISP, which decided to return a "user-friendly" html help page instead of an error when given a malformed URL. Changing my DNS host to 1.1.1.1 makes `TestNewNetAddressStringWithOptionalID` pass for me now.

However, this isn't a complete resolution, because there is still a failing test:

```sh
prgn@prgn-oneiro ~/go/src/github.com/tendermint/tendermint
$ go test ./... | rg -v '^ok' | rg -v '^\?'
Thu Apr 11 14:04:13 CEST 2019
--- FAIL: TestHandshakeReplayNone (0.45s)
panic: open /var/folders/b9/zjyrkvh10s55spq3hgwkmqcr0000gn/T/-TestHandshakeReplayNone_2_339143766/data/2/kvstore.db: too many open files [recovered]
	panic: open /var/folders/b9/zjyrkvh10s55spq3hgwkmqcr0000gn/T/-TestHandshakeReplayNone_2_339143766/data/2/kvstore.db: too many open files

goroutine 31967 [running]:
testing.tRunner.func1(0xc0001cdf00)
	/usr/local/opt/go/libexec/src/testing/testing.go:830 +0x392
panic(0x1841f00, 0xc009bceab0)
	/usr/local/opt/go/libexec/src/runtime/panic.go:522 +0x1b5
github.com/tendermint/tendermint/abci/example/kvstore.NewPersistentKVStoreApplication(0xc001855ec0, 0x5c, 0x2)
	/Users/prgn/go/src/github.com/tendermint/tendermint/abci/example/kvstore/persistent_kvstore.go:37 +0x1d6
github.com/tendermint/tendermint/consensus.testHandshakeReplay(0xc0001cdf00, 0xc0000d52c0, 0x6, 0x2)
	/Users/prgn/go/src/github.com/tendermint/tendermint/consensus/replay_test.go:361 +0x69a
github.com/tendermint/tendermint/consensus.TestHandshakeReplayNone(0xc0001cdf00)
	/Users/prgn/go/src/github.com/tendermint/tendermint/consensus/replay_test.go:314 +0x79
testing.tRunner(0xc0001cdf00, 0x1a80828)
	/usr/local/opt/go/libexec/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/opt/go/libexec/src/testing/testing.go:916 +0x35a
FAIL	github.com/tendermint/tendermint/consensus	19.577s
prgn@prgn-oneiro ~/go/src/github.com/tendermint/tendermint
$ git rev-parse --short HEAD
Thu Apr 11 14:04:50 CEST 2019
9a415b05
```

**Comment by coriolinus** [comment]
Actually that also turns out to be a config issue:

```sh
$ ulimit -S -n 2048
Thu Apr 11 14:07:29 CEST 2019
prgn@prgn-oneiro ~/go/src/github.com/tendermint/tendermint
$ go test ./... | rg -v '^ok' | rg -v '^\?'
Thu Apr 11 14:07:34 CEST 2019
prgn@prgn-oneiro ~/go/src/github.com/tendermint/tendermint
$ echo $?
Thu Apr 11 14:08:10 CEST 2019
0
```

The tests all pass on `develop` and the issue was with my system configuration. Thanks for working with me to figure this out!
