### ISSUE TITLE
consensus non-deterministic test

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3598]
I'm getting this quite a bit running locally:

```
go test ./consensus/
--- FAIL: TestStateLockPOLRelock (0.10s)
panic: Timeout expired while waiting for NewVote event [recovered]
        panic: Timeout expired while waiting for NewVote event

goroutine 27552 [running]:
testing.tRunner.func1(0xc007b9c400)
        /Users/ethanbuchman/goRoot/1.11.5/src/testing/testing.go:792 +0x387
panic(0x17a8420, 0x1ac5410)
        /Users/ethanbuchman/goRoot/1.11.5/src/runtime/panic.go:513 +0x1b9
github.com/tendermint/tendermint/consensus.ensureVote(0xc001fb43c0, 0x1, 0x0, 0x2)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/consensus/common_test.go:504 +0x4f8
github.com/tendermint/tendermint/consensus.ensurePrecommit(0xc001fb43c0, 0x1, 0x0)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/consensus/common_test.go:493 +0x44
github.com/tendermint/tendermint/consensus.TestStateLockPOLRelock(0xc007b9c400)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/consensus/state_test.go:529 +0x418
testing.tRunner(0xc007b9c400, 0x1a2c3e0)
        /Users/ethanbuchman/goRoot/1.11.5/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
        /Users/ethanbuchman/goRoot/1.11.5/src/testing/testing.go:878 +0x35c
FAIL    github.com/tendermint/tendermint/consensus      5.732s

```

I'm also getting "too many open files" and am busy trying to debug that. Seems there's a GoLevelDB we have to close in the tests. But otherwise I keep running into the above issue with NewVote

**Comment by tessr** [comment]
I'm going to close this since we did a bunch of work to cleanup flaky tests earlier this year. Can re-open this issue if this problem shows up again!
