### ISSUE TITLE
Example in docs on Websocket RPC Subscribe

### ISSUE THREAD

**Issue by folex** [tendermint/tendermint#3678]
**Tendermint version**: 0.30.2

**Environment**:
- **OS**: macOS 10.14.4
- **Install tools**: docker 

**Have you tried the latest version**: no

I'm trying to run example from https://tendermint.com/rpc/#subscribe , but I'm not sure if I'm using correct imports. In doc, there is a `client`, but no import, and I use `rpc/client`:

```go
rpcclient "github.com/tendermint/tendermint/rpc/client"
client := rpcclient.NewHTTP(...)
ctx, _ := context.WithTimeout(context.Background(), 10 * time.Second)
query := "tm.event = 'Tx' AND tx.height = 3"
resultCh, err := client.Subscribe(ctx, "test-client", query, 1)
```

I had to tweak the code a bit (query is string, not Query, txs => resultCh), and now I'm stuck with SIGSEGV.

Minified stack trace:

```
panic SIGSEGV
rpc/lib/client.(*WSClient).Call(0x0, ...) ws_client.go:217
rpc/lib/client.(*WSClient).Subscribe(0x0, ...) ws_client.go:485
rpc/client.(*WSEvents).Subscribe(...) httpclient.go:309
test
```

P.S. Also, there's shell example missing. I could contribute it, but it will require usage of [websocat](https://github.com/vi/websocat). Would you accept such an example? It could look like this:
```bash
# installation info: https://github.com/vi/websocat
websocat -t --jsonrpc ws://localhost:26657/websocket
subscribe "tm.event = 'Tx'"
```

**Comment by melekes** [comment]
> Would you accept such an example? It could look like this:

we will! please go ahead

**Comment by melekes** [comment]
Can't replicate with latest develop and the following client:

```
package main

import (
	"context"
	"os"
	"os/signal"
	"syscall"

	"github.com/tendermint/tendermint/libs/log"

	tmclient "github.com/tendermint/tendermint/rpc/client"
	tmtypes "github.com/tendermint/tendermint/types"
)

func main() {
	logger := log.NewTMLogger(log.NewSyncWriter(os.Stdout))

	client := tmclient.NewHTTP("tcp://localhost:26657", "/websocket")
	client.SetLogger(logger)
	err := client.Start()
	if err != nil {
		logger.Error("Failed to start a client", "err", err)
		os.Exit(1)
	}
	defer client.Stop()

	query := "tm.event = 'Tx' AND tx.height = 200"
	out, err := client.Subscribe(context.Background(), "test", query, 1000)
	if err != nil {
		logger.Error("Failed to subscribe to query", "err", err, "query", query)
		os.Exit(1)
	}

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, os.Interrupt, syscall.SIGTERM)

	for {
		select {
		case result := <-out:
			logger.Info("got tx",
				"index", result.Data.(tmtypes.EventDataTx).Index)
		case <-quit:
			os.Exit(0)
		}
	}
}
```

**Comment by melekes** [comment]
@folex are you sure you're using correct dependencies (`make get_vendor_deps`)? Also please ensure that Go is installed properly. Segfault is usually a sign of incorrectly installed go. Tendermint requires Go1.11.4 or higher.

**Comment by melekes** [comment]
Documentation for `/subscribe` endpoint needs to be updated https://github.com/tendermint/tendermint/blob/develop/rpc/core/events.go#L66

**Comment by melekes** [comment]
@folex have you figured out the SIGSEGV fault?

**Comment by folex** [comment]
Sorry for the delay! SIGSEGV still happening.

```$ go version
go version go1.12.5 darwin/amd64
```

```
$ git show HEAD
commit 4253e67c07c69be6d7f7263ab03944ce30a9fc90 (HEAD -> master, origin/master, origin/HEAD)
Merge: 1c6d9d20 d2eab536
Author: Ethan Buchman <ethan@coinculture.info>
Date:   Fri Apr 19 07:46:11 2019 -0400

    Merge pull request #3571 from tendermint/v0.31

    V0.31.5
```

I did `make get_vendor_deps`, and other tests I wrote (mainly about block de/serialization and signatures) are working fine. 

Maybe the reason is that I use `master` which is `0.31.5` against running `0.30.2` Tendermint?

Here's how I run my test:
- I have modified `libs/pubsub/pubsub_test.go`: https://gist.github.com/folex/c988e0426645eefd37ddf1ac836c36cb
- I run `$ /usr/local/bin/go test -timeout 30s github.com/tendermint/tendermint/libs/pubsub -run '^(TestWebsocket)$' -v`

And the output is:
```
=== RUN   TestWebsocket
--- FAIL: TestWebsocket (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x16f7737]

goroutine 28 [running]:
testing.tRunner.func1(0xc000120c00)
	/usr/local/Cellar/go/1.12.5/libexec/src/testing/testing.go:830 +0x392
panic(0x1813c80, 0x2194940)
	/usr/local/Cellar/go/1.12.5/libexec/src/runtime/panic.go:522 +0x1b5
github.com/tendermint/tendermint/rpc/lib/client.(*WSClient).Call(0x0, 0x1b4f0a0, 0xc0000cf020, 0x1906cb4, 0x9, 0xc0000fbdb0, 0x10, 0xc0004e1c00)
	/Users/folex/Development/go/src/github.com/tendermint/tendermint/rpc/lib/client/ws_client.go:217 +0x37
github.com/tendermint/tendermint/rpc/lib/client.(*WSClient).Subscribe(...)
	/Users/folex/Development/go/src/github.com/tendermint/tendermint/rpc/lib/client/ws_client.go:485
github.com/tendermint/tendermint/rpc/client.(*WSEvents).Subscribe(0xc00011efc0, 0x1b4f0a0, 0xc0000cf020, 0x190815f, 0xb, 0x191ab19, 0x21, 0xc0000fbf68, 0x1, 0x1, ...)
	/Users/folex/Development/go/src/github.com/tendermint/tendermint/rpc/client/httpclient.go:309 +0x154
github.com/tendermint/tendermint/libs/pubsub_test.TestWebsocket(0xc000120c00)
	/Users/folex/Development/go/src/github.com/tendermint/tendermint/libs/pubsub/pubsub_test.go:31 +0x10b
testing.tRunner(0xc000120c00, 0x1a5e768)
	/usr/local/Cellar/go/1.12.5/libexec/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.12.5/libexec/src/testing/testing.go:916 +0x35a
FAIL	github.com/tendermint/tendermint/libs/pubsub	0.049s
```

**Comment by melekes** [comment]
> Maybe the reason is that I use master which is 0.31.5 against running 0.30.2 Tendermint?

New client accessing old server. That might be it!

**Comment by folex** [comment]
So, I've read your example more closely, and my mistake was that I didn't call `client.Start()` :) 

Now - no SIGSEGV, everything is OK. Thanks!
