### ISSUE TITLE
non-deterministic test panic in TestNodeDelayedStart

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3680]
```
=== RUN   TestNodeDelayedStart
I[2019-05-27|18:24:48.603] Starting multiAppConn                        module=proxy impl=multiAppConn
I[2019-05-27|18:24:48.603] Starting localClient                         module=abci-client connection=query impl=localClient
I[2019-05-27|18:24:48.603] Starting localClient                         module=abci-client connection=mempool impl=localClient
I[2019-05-27|18:24:48.603] Starting localClient                         module=abci-client connection=consensus impl=localClient
I[2019-05-27|18:24:48.603] Starting EventBus                            module=events impl=EventBus
I[2019-05-27|18:24:48.603] Starting PubSub                              module=pubsub impl=PubSub
I[2019-05-27|18:24:48.603] Starting IndexerService                      module=txindex impl=IndexerService
I[2019-05-27|18:24:48.603] ABCI Handshake App Info                      module=consensus height=0 hash= software-version=0.16.0 protocol-version=1
I[2019-05-27|18:24:48.604] ABCI Replay Blocks                           module=consensus appHeight=0 storeHeight=0 stateHeight=0
I[2019-05-27|18:24:48.604] Completed ABCI Handshake - Tendermint and App are synced module=consensus appHeight=0 appHash=
I[2019-05-27|18:24:48.604] Version info                                 software=0.31.5 block=10 p2p=7
I[2019-05-27|18:24:48.604] This node is a validator                     module=consensus addr=A3258DCBF45DCA0DF052981870F2D1441A36D145 pubKey=PubKeyEd25519{013FFE69A2F5781D38EFB32E77D24C9BC4A1F0122F39894F182F4A90852615A1}
I[2019-05-27|18:24:48.605] P2P Node ID                                  module=p2p ID=c1c86bee152bf13f6d8fdb45416e06b4aece27ab file=/tmp/-node_delayed_start_test_500077208/config/node_key.json
I[2019-05-27|18:24:48.605] Adding persistent peers                      module=p2p addrs=[]
I[2019-05-27|18:24:48.605] Add our address to book                      module=p2p book=/tmp/-node_delayed_start_test_500077208/config/addrbook.json addr=<nil>:0
I[2019-05-27|18:24:48.605] Starting Node                                impl=Node
I[2019-05-27|18:24:48.605] Genesis time is in the future. Sleeping until then... genTime=2019-05-27T18:24:50.600698413Z
I[2019-05-27|18:24:50.601] Starting RPC HTTP server on [::]:36657       module=rpc-server 
I[2019-05-27|18:24:50.601] Starting P2P Switch                          module=p2p impl="P2P Switch"
I[2019-05-27|18:24:50.601] Starting BlockchainReactor                   module=blockchain impl=BlockchainReactor
I[2019-05-27|18:24:50.602] Starting ConsensusReactor                    module=consensus impl=ConsensusReactor
I[2019-05-27|18:24:50.602] ConsensusReactor                             module=consensus fastSync=false
I[2019-05-27|18:24:50.602] Starting ConsensusState                      module=consensus impl=ConsensusState
I[2019-05-27|18:24:50.602] Starting baseWAL                             module=consensus wal=/tmp/-node_delayed_start_test_500077208/data/cs.wal/wal impl=baseWAL
I[2019-05-27|18:24:50.603] Starting Group                               module=consensus wal=/tmp/-node_delayed_start_test_500077208/data/cs.wal/wal impl=Group
I[2019-05-27|18:24:50.603] Starting TimeoutTicker                       module=consensus impl=TimeoutTicker
I[2019-05-27|18:24:50.603] Searching for height                         module=consensus wal=/tmp/-node_delayed_start_test_500077208/data/cs.wal/wal height=1 min=0 max=0
D[2019-05-27|18:24:50.603] Starting timeout routine                     module=consensus 
I[2019-05-27|18:24:50.603] Searching for height                         module=consensus wal=/tmp/-node_delayed_start_test_500077208/data/cs.wal/wal height=0 min=0 max=0
I[2019-05-27|18:24:50.603] Found                                        module=consensus wal=/tmp/-node_delayed_start_test_500077208/data/cs.wal/wal height=0 index=0
I[2019-05-27|18:24:50.603] Catchup by replaying consensus messages      module=consensus height=1
I[2019-05-27|18:24:50.603] Replay: Done                                 module=consensus 
I[2019-05-27|18:24:50.604] Starting EvidenceReactor                     module=evidence impl=EvidenceReactor
I[2019-05-27|18:24:50.604] Starting PEXReactor                          module=pex impl=PEXReactor
I[2019-05-27|18:24:50.604] Starting AddrBook                            module=p2p book=/tmp/-node_delayed_start_test_500077208/config/addrbook.json impl=AddrBook
D[2019-05-27|18:24:50.604] Received tick                                module=consensus old_ti="{Duration:0s Height:0 Round:0 Step:RoundStepUnknown}" new_ti="{Duration:-1.988920335s Height:1 Round:0 Step:RoundStepNewHeight}"
D[2019-05-27|18:24:50.604] Timer already stopped                        module=consensus 
I[2019-05-27|18:24:50.604] Starting Reactor                             module=mempool impl=Reactor
D[2019-05-27|18:24:50.604] Scheduled timeout                            module=consensus dur=-1.988920335s height=1 round=0 step=RoundStepNewHeight
I[2019-05-27|18:24:50.604] Timed out                                    module=consensus dur=-1.988920335s height=1 round=0 step=RoundStepNewHeight
I[2019-05-27|18:24:50.604] Saving AddrBook to file                      module=p2p book=/tmp/-node_delayed_start_test_500077208/config/addrbook.json size=0
I[2019-05-27|18:24:50.604] Ensure peers                                 module=pex numOutPeers=0 numInPeers=0 numDialing=0 numToDial=10
D[2019-05-27|18:24:50.604] Received tock                                module=consensus timeout=-1.988920335s height=1 round=0 step=RoundStepNewHeight
I[2019-05-27|18:24:50.604] enterNewRound(1/0). Current: 1/0/RoundStepNewHeight module=consensus height=1 round=0
I[2019-05-27|18:24:50.604] enterPropose(1/0). Current: 1/0/RoundStepNewRound module=consensus height=1 round=0
D[2019-05-27|18:24:50.604] This node is a validator                     module=consensus height=1 round=0
D[2019-05-27|18:24:50.604] Received tick                                module=consensus old_ti="{Duration:-1.988920335s Height:1 Round:0 Step:RoundStepNewHeight}" new_ti="{Duration:40ms Height:1 Round:0 Step:RoundStepPropose}"
D[2019-05-27|18:24:50.605] Timer already stopped                        module=consensus 
I[2019-05-27|18:24:50.605] enterPropose: Our turn to propose            module=consensus height=1 round=0 proposer=A3258DCBF45DCA0DF052981870F2D1441A36D145 privValidator="PrivValidator{A3258DCBF45DCA0DF052981870F2D1441A36D145 LH:0, LR:0, LS:0}"
I[2019-05-27|18:24:50.605] No addresses to dial. Falling back to seeds  module=pex 
E[2019-05-27|18:24:50.605] Couldn't connect to any seeds                module=p2p 
D[2019-05-27|18:24:50.605] Scheduled timeout                            module=consensus dur=40ms height=1 round=0 step=RoundStepPropose
--- PASS: TestNodeDelayedStart (2.01s)
=== RUN   TestNodeSetAppVersion
D[2019-05-27|18:24:50.607] Broadcast                                    module=p2p channel=32 msgBytes=C96A6FA808011803200128FFFFFFFFFFFFFFFFFF01
E[2019-05-27|18:24:50.607] CONSENSUS FAILURE!!!                         module=consensus err="open /tmp/-node_delayed_start_test_500077208/data/write-file-atomic-7883882141588180703: no such file or directory" stack="goroutine 129 [running]:\nruntime/debug.Stack(0xc0001db1a0, 0x1124600, 0xc000b2d050)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xab\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func2(0xc000035500, 0x137a308)\n\t/go/src/github.com/tendermint/tendermint/consensus/state.go:602 +0x6a\npanic(0x1124600, 0xc000b2d050)\n\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\ngithub.com/tendermint/tendermint/privval.(*FilePVLastSignState).Save(0xc000aa2ae8)\n\t/go/src/github.com/tendermint/tendermint/privval/file.go:126 +0x1a5\ngithub.com/tendermint/tendermint/privval.(*FilePV).saveSigned(0xc000aa2aa0, 0x1, 0x0, 0x1, 0xc0000e8600, 0x7e, 0xfd, 0xc000c28fc0, 0x40, 0x40)\n\t/go/src/github.com/tendermint/tendermint/privval/file.go:372 +0x10f\ngithub.com/tendermint/tendermint/privval.(*FilePV).signProposal(0xc000aa2aa0, 0xc000b8b530, 0xf, 0xc000214c60, 0xe2a1d8, 0xbf3328bca4191bc5)\n\t/go/src/github.com/tendermint/tendermint/privval/file.go:358 +0x605\ngithub.com/tendermint/tendermint/privval.(*FilePV).SignProposal(0xc000aa2aa0, 0xc000b8b530, 0xf, 0xc000214c60, 0x7135a9, 0xc0000ffa60)\n\t/go/src/github.com/tendermint/tendermint/privval/file.go:248 +0x67\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).defaultDecideProposal(0xc000035500, 0x1, 0x0)\n\t/go/src/github.com/tendermint/tendermint/consensus/state.go:917 +0x442\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterPropose(0xc000035500, 0x1, 0x0)\n\t/go/src/github.com/tendermint/tendermint/consensus/state.go:885 +0x8c5\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterNewRound(0xc000035500, 0x1, 0x0)\n\t/go/src/github.com/tendermint/tendermint/consensus/state.go:826 +0x967\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).handleTimeout(0xc000035500, 0xffffffff89737bf1, 0x1, 0x0, 0x1, 0x1, 0x0, 0x1, 0x24ab2e0c, 0xed47e2270, ...)\n\t/go/src/github.com/tendermint/tendermint/consensus/state.go:737 +0x6a6\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc000035500, 0x0)\n\t/go/src/github.com/tendermint/tendermint/consensus/state.go:651 +0x520\ncreated by github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/go/src/github.com/tendermint/tendermint/consensus/state.go:334 +0x3c8\n"
I[2019-05-27|18:24:50.607] Stopping baseWAL                             module=consensus wal=/tmp/-node_delayed_start_test_500077208/data/cs.wal/wal impl=baseWAL
I[2019-05-27|18:24:50.607] Stopping Group                               module=consensus wal=/tmp/-node_delayed_start_test_500077208/data/cs.wal/wal impl=Group
I[2019-05-27|18:24:50.610] Starting multiAppConn                        module=proxy impl=multiAppConn

```

The test passes but it seems a directory is cleaned up before the priv val stops properly

**Comment by tessr** [comment]
Doing some issue cleanup today. I don't think we've seen this bug in a while; I'm going to close it and we can reopen if it surfaces again.
