### ISSUE TITLE
AddressBook: Nil Address

### ISSUE THREAD

**Issue by alexanderbez** [tendermint/tendermint#3741]
**Tendermint version**:

v0.32.0-dev0

**ABCI app**

Gaia

**What happened**:

A 4 node local network of gaia hangs during start:

```
I[2019-06-20|16:31:22.880] Starting ABCI with Tendermint                module=main
I[2019-06-20|16:31:23.028] Starting multiAppConn                        module=proxy impl=multiAppConn
I[2019-06-20|16:31:23.029] Starting localClient                         module=abci-client connection=query impl=localClient
I[2019-06-20|16:31:23.029] Starting localClient                         module=abci-client connection=mempool impl=localClient
I[2019-06-20|16:31:23.029] Starting localClient                         module=abci-client connection=consensus impl=localClient
I[2019-06-20|16:31:23.029] Starting EventBus                            module=events impl=EventBus
I[2019-06-20|16:31:23.029] Starting PubSub                              module=pubsub impl=PubSub
I[2019-06-20|16:31:23.066] Starting IndexerService                      module=txindex impl=IndexerService
I[2019-06-20|16:31:23.066] ABCI Handshake App Info                      module=consensus height=0 hash= software-version= protocol-version=0
I[2019-06-20|16:31:23.066] ABCI Replay Blocks                           module=consensus appHeight=0 storeHeight=0 stateHeight=0
I[2019-06-20|16:31:23.071] asserted all invariants                      module=x/crisis duration=13.3µs height=0
I[2019-06-20|16:31:23.089] Completed ABCI Handshake - Tendermint and App are synced module=consensus appHeight=0 appHash=
I[2019-06-20|16:31:23.089] Version info                                 module=node software=0.31.7 block=10 p2p=7
I[2019-06-20|16:31:23.089] This node is a validator                     module=consensus addr=060B95D2B8C399D715B0EE6A3CBC828224B3F62C pubKey=PubKeyEd25519{AFE053776F3CF570A91D39118EAFEAFB39572962201C6A67A048FA63239978AA}
I[2019-06-20|16:31:23.169] P2P Node ID                                  module=p2p ID=a206f3fd5e8f1ba3f6817141df9c909aba0819e3 file=/gaiad/node0/gaiad/config/node_key.json
I[2019-06-20|16:31:23.169] Adding persistent peers                      module=p2p addrs="[a2130493db7d51045df5547bcbe04d3d32f98216@192.168.10.5:26656 a3fb0c1bbe7dbbf8b0756374adf02d1ccac4c413@192.168.10.4:26656 ee6c6e397cec825795422622d5f3f867ce2ddd55@192.168.10.3:26656]"
I[2019-06-20|16:31:23.169] Add our address to book                      module=p2p book=/gaiad/node0/gaiad/config/addrbook.json addr=<nil>:0
```

The problem seems to be:

```
I[2019-06-20|16:31:23.169] Add our address to book                      module=p2p book=/gaiad/node0/gaiad/config/addrbook.json addr=<nil>:0
```

**To Replicate**:

1. Clone gaia
2. Check out branch `bez/update-sdk-events`
3. Modify `networks/local/gaiadnode/Dockerfile` as follows:
```
-CMD ["start"]
+CMD ["start", "--log_level=*:debug"]
```
4. Run: `rm -fr ./build/**; make clean install build-linux localnet-start`
5. Tail one of the container logs: `docker logs -f gaiadnode0`

ref: https://github.com/tendermint/tendermint/issues/3716

/cc @melekes

**Comment by alexanderbez** [comment]
https://github.com/tendermint/tendermint/pull/3740 closes this apparently.

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/pull/3740 should fix this.

**Comment by alexanderbez** [comment]
@melekes, the nodes still stall:

```
I[2019-06-21|12:05:51.022] Starting ABCI with Tendermint                module=main
I[2019-06-21|12:05:51.186] Starting multiAppConn                        module=proxy impl=multiAppConn
I[2019-06-21|12:05:51.186] Starting localClient                         module=abci-client connection=query impl=localClient
I[2019-06-21|12:05:51.186] Starting localClient                         module=abci-client connection=mempool impl=localClient
I[2019-06-21|12:05:51.186] Starting localClient                         module=abci-client connection=consensus impl=localClient
I[2019-06-21|12:05:51.186] Starting EventBus                            module=events impl=EventBus
I[2019-06-21|12:05:51.186] Starting PubSub                              module=pubsub impl=PubSub
I[2019-06-21|12:05:51.230] Starting IndexerService                      module=txindex impl=IndexerService
I[2019-06-21|12:05:51.231] ABCI Handshake App Info                      module=consensus height=0 hash= software-version= protocol-version=0
I[2019-06-21|12:05:51.231] ABCI Replay Blocks                           module=consensus appHeight=0 storeHeight=0 stateHeight=0
I[2019-06-21|12:05:51.234] asserted all invariants                      module=x/crisis duration=11µs height=0
I[2019-06-21|12:05:51.245] Completed ABCI Handshake - Tendermint and App are synced module=consensus appHeight=0 appHash=
I[2019-06-21|12:05:51.245] Version info                                 module=node software=0.31.7 block=10 p2p=7
I[2019-06-21|12:05:51.245] This node is a validator                     module=consensus addr=4F9A4DF162A0E8E26770E6470A59CAD8684E5A7E pubKey=PubKeyEd25519{A899146397C44D55584ED3DEA338821498DB43535F8622F461864CF3FE6DACE8}
I[2019-06-21|12:05:51.295] P2P Node ID                                  module=p2p ID=a363d98879564e59e8a88006b7b642bec7fa7b68 file=/gaiad/node1/gaiad/config/node_key.json
I[2019-06-21|12:05:51.296] Adding persistent peers                      module=p2p addrs="[01fb1529989a39e65d1735f161480e184e676692@192.168.10.5:26656 56f0551e5172552ff0552aaf9b8fbf9f38250404@192.168.10.4:26656 8e3109249f3b32f8343058e0b1f1b9b33741e3ea@192.168.10.2:26656]"
I[2019-06-21|12:05:51.296] Add our address to book                      module=p2p book=/gaiad/node1/gaiad/config/addrbook.json addr=a363d98879564e59e8a88006b7b642bec7fa7b68@0.0.0.0:26656
```

**Comment by alexanderbez** [comment]
output from aborting the process:

```
SIGABRT: abort
PC=0x45ec33 m=0 sigcode=0

goroutine 34 [syscall]:
runtime.notetsleepg(0x1db42e0, 0x6fc0391a4, 0x0)
	/usr/local/go/src/runtime/lock_futex.go:227 +0x34 fp=0xc000f8b760 sp=0xc000f8b730 pc=0x40acb4
runtime.timerproc(0x1db42c0)
	/usr/local/go/src/runtime/time.go:311 +0x2ea fp=0xc000f8b7d8 sp=0xc000f8b760 pc=0x44c6aa
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000f8b7e0 sp=0xc000f8b7d8 pc=0x45cdd1
created by runtime.(*timersBucket).addtimerLocked
	/usr/local/go/src/runtime/time.go:169 +0x10e

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7fefbcc57a38, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc000018298, 0x72, 0x0, 0x0, 0x11441be)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000018280, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1ba
net.(*netFD).accept(0xc000018280, 0x10a3b60, 0x50, 0xc000200190)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0004ba040, 0xc000050700, 0x7fefbf107008, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).AcceptTCP(0xc0004ba040, 0x40c698, 0x30, 0x10a3b60)
	/usr/local/go/src/net/tcpsock.go:247 +0x48
net/http.tcpKeepAliveListener.Accept(0xc0004ba040, 0x10a3b60, 0xc0001fa3f0, 0xfebb60, 0x1d94c60)
	/usr/local/go/src/net/http/server.go:3264 +0x2f
net/http.(*Server).Serve(0xc000add380, 0x14d6a40, 0xc0004ba040, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2859 +0x22d
net/http.(*Server).ListenAndServe(0xc000add380, 0xc000add380, 0x1dccc80)
	/usr/local/go/src/net/http/server.go:2797 +0xe4
net/http.ListenAndServe(0xc0001d1440, 0xe, 0x0, 0x0, 0x14db200, 0xc000a05980)
	/usr/local/go/src/net/http/server.go:3037 +0x74
github.com/tendermint/tendermint/node.NewNode(0xc000171a40, 0x14d5440, 0xc000a4cdc0, 0xc000443b90, 0x14bcf80, 0xc000a05940, 0xc000443e40, 0x1338910, 0xc000443e50, 0x14db200, ...)
	/Users/aleksbez/go/pkg/mod/github.com/tendermint/tendermint@v0.32.0-dev1/node/node.go:633 +0x13a4
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc00000d100, 0x1339158, 0x1d, 0x0, 0x0)
	/Users/aleksbez/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.28.2-0.20190621120424-861ea2b59e1b/server/start.go:126 +0x4c2
github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc000440c80, 0xc000153b90, 0x0, 0x3, 0x0, 0x0)
	/Users/aleksbez/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.28.2-0.20190621120424-861ea2b59e1b/server/start.go:43 +0xb5
github.com/spf13/cobra.(*Command).execute(0xc000440c80, 0xc000011580, 0x3, 0x4, 0xc000440c80, 0xc000011580)
	/Users/aleksbez/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:762 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000aca00, 0x1166257, 0xc00005ded8, 0x5821b4)
	/Users/aleksbez/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:850 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/aleksbez/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:800
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0000aca00, 0x1339568, 0x114c97d, 0x10)
	/Users/aleksbez/go/pkg/mod/github.com/tendermint/tendermint@v0.32.0-dev1/libs/cli/setup.go:89 +0x3c
main.main()
	/Users/aleksbez/go/src/github.com/cosmos/gaia/cmd/gaiad/main.go:67 +0x818
```

**Comment by melekes** [comment]
Fixed in https://github.com/tendermint/tendermint/pull/3743.
