### ISSUE TITLE
Panic in HTTP RPC handler when remote signer is offline

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#3883]
**ABCI app** (name for built-in, URL for self-written if it's publicly available):
cosmos-sdk v0.36.0

**What happened**:
Using tmkms: During tmkms upgrade the following panic occured

```
Aug 06 20:20:05 i-054c5a397bb89993a gaiad[1765]: E[2019-08-06|20:20:05.421] Error signing vote                           module=consensus height=227417 round=0 vote="Vote{10:32363E5BAA6B 227417/00/2(Precommit) 000000000000 000000000000 @ 2019-08-06T20:20:05.421156365Z}" err="remote signer timed out"
Aug 06 20:20:05 i-054c5a397bb89993a gaiad[1765]: E[2019-08-06|20:20:05.424] Panic in RPC HTTP handler                    module=rpc-server err="write tcp [::1]:26657->[::1]:43340: i/o timeout" stack="goroutine 221694746 [running]:\nruntime/debug.Stack(0xc0015ed7e0, 0xff1b00, 0xc006d1d9a0)\n\t/usr/lib/go-1.11/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1.1(0xc00443bd00, 0x1466ba0, 0xc000c70ce0, 0xbf4a9619a7ca6328, 0x37c2966a37136, 0x1ee3880, 0xc007542e00)\n\t/root/gopath/pkg/mod/github.com/tendermint/tendermint@v0.32.1/rpc/lib/server/http_server.go:163 +0x50c\npanic(0xff1b00, 0xc006d1d9a0)\n\t/usr/lib/go-1.11/src/runtime/panic.go:513 +0x1b9\ngithub.com/tendermint/tendermint/rpc/lib/server.WriteRPCResponseHTTP(0x1464520, 0xc00443bd00, 0x11192f1, 0x3, 0x145b9a0, 0x1455d00, 0xc0051ba000, 0x1fb1, 0x33f7, 0x0)\n\t/root/gopath/pkg/mod/github.com/tendermint/tendermint@v0.32.1/rpc/lib/server/http_server.go:114 +0x1da\ngithub.com/tendermint/tendermint/rpc/lib/server.makeHTTPHandler.func2(0x1464520, 0xc00443bd00, 0xc007542e00)\n\t/root/gopath/pkg/mod/github.com/tendermint/tendermint@v0.32.1/rpc/lib/server/handlers.go:287 +0x6ce\nnet/http.HandlerFunc.ServeHTTP(0xc0009ae240, 0x1464520, 0xc00443bd00, 0xc007542e00)\n\t/usr/lib/go-1.11/src/net/http/server.go:1964 +0x44\nnet/http.(*ServeMux).ServeHTTP(0xc0009ae030, 0x1464520, 0xc00443bd00, 0xc007542e00)\n\t/usr/lib/go-1.11/src/net/http/server.go:2361 +0x127\ngithub.com/tendermint/tendermint/rpc/lib/server.maxBytesHandler.ServeHTTP(0x145a560, 0xc0009ae030, 0xf4240, 0x1464520, 0xc00443bd00, 0xc007542e00)\n\t/root/gopath/pkg/mod/github.com/tendermint/tendermint@v0.32.1/rpc/lib/server/http_server.go:208 +0xcf\ngithub.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1(0x1464ba0, 0xc000129500, 0xc007542e00)\n\t/root/gopath/pkg/mod/github.com/tendermint/tendermint@v0.32.1/rpc/lib/server/http_server.go:181 +0x25e\nnet/http.HandlerFunc.ServeHTTP(0xc000c4b230, 0x1464ba0, 0xc000129500, 0xc007542e00)\n\t/usr/lib/go-1.11/src/net/http/server.go:1964 +0x44\nnet
Aug 06 20:20:05 i-054c5a397bb89993a gaiad[1765]: /http.serverHandler.ServeHTTP(0xc00088de10, 0x1464ba0, 0xc000129500, 0xc007542e00)\n\t/usr/lib/go-1.11/src/net/http/server.go:2741 +0xab\nnet/http.(*conn).serve(0xc000eb5c20, 0x1465fa0, 0xc003104700)\n\t/usr/lib/go-1.11/src/net/http/server.go:1847 +0x646\ncreated by net/http.(*Server).Serve\n\t/usr/lib/go-1.11/src/net/http/server.go:2851 +0x2f5\n"
Aug 06 20:20:05 i-054c5a397bb89993a gaiad[1765]: 2019/08/06 20:20:05 http: multiple response.WriteHeader calls
Aug 06 20:20:05 i-054c5a397bb89993a gaiad[1765]: 2019/08/06 20:20:05 http: panic serving [::1]:43340: write tcp [::1]:26657->[::1]:43340: i/o timeout
```

**How to reproduce it** (as minimally and precisely as possible):
Stopping tmkms and hitting the /status RPC.

**Comment by melekes** [comment]
Similar issue: https://github.com/tendermint/tendermint/issues/4275

**Comment by melekes** [comment]
Related issue: https://github.com/tendermint/tendermint/issues/4802

It's okay to panic if you can't write to a client's socket. Panics are handled by Go HTTP server.

What I don't understand is how tmkms and /status RPC are connected. We don't call tmkms during `/status` processing. Although, we do call `consensusState`, which tries to get a hold of the mutex (https://github.com/tendermint/tendermint/issues/3161). So maybe fixing the https://github.com/tendermint/tendermint/issues/3161 will also fix this issue.

**Comment by melekes** [comment]
@mdyring would you mind checking if you can replicate the issue w/ https://github.com/tendermint/tendermint/pull/4844 applied (current master)?

**Comment by melekes** [comment]
Should be fixed by https://github.com/tendermint/tendermint/pull/4844
