### ISSUE TITLE
TestMempoolNoProgressUntilTxsAvailable non-deterministic failure

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#3897]
https://circleci.com/gh/tendermint/tendermint/68675

```
--- FAIL: TestMempoolNoProgressUntilTxsAvailable (0.11s)
I[2019-08-12|17:41:51.163] Stopping queryMaj23Routine for peer          module=consensus test=byzantine validator=2 peer="Peer{MConn{pipe} 033c67b5415a4bbc13e20792db36a8562d841d53 in}"
panic: Timeout expired while waiting for new activity on the channel [recovered]
	panic: Timeout expired while waiting for new activity on the channel

goroutine 289 [running]:
testing.tRunner.func1(0xc00114fc00)
	/usr/local/go/src/testing/testing.go:830 +0x69d
panic(0xfdd300, 0x1378e00)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/tendermint/tendermint/consensus.ensureNewEventOnChannel(0xc000f20a20)
	/go/src/github.com/tendermint/tendermint/consensus/common_test.go:548 +0x146
github.com/tendermint/tendermint/consensus.TestMempoolNoProgressUntilTxsAvailable(0xc00114fc00)
	/go/src/github.com/tendermint/tendermint/consensus/mempool_test.go:36 +0x3b5
testing.tRunner(0xc00114fc00, 0x1260178)
	/usr/local/go/src/testing/testing.go:865 +0x164
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x65b
FAIL	github.com/tendermint/tendermint/consensus	1.991s
```

**Comment by melekes** [comment]
Fixed in https://github.com/tendermint/tendermint/pull/4891
