### ISSUE TITLE
Panic in RPC HTTP handler with batch requests over `tendermint lite`

### ISSUE THREAD

**Issue by tomtau** [tendermint/tendermint#3916]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installedfrom source):
0.32.2-76f3db06

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
https://github.com/crypto-com/chain/tree/master/chain-abci
**Environment**:
- **OS** (e.g. from /etc/os-release): macOS 10.14.6 and Ubuntu 18.04
- **Install tools**:
- **Others**:

**What happened**:
Ran `tendermint lite -node <remote node rpc> --chain-id <...> --laddr tcp://localhost:26657`

and submitted a few batch RPC requests (POST for `block_results`).

And after a short time, there was a panic (see the log below).

**What you expected to happen**:
No panics -- e.g. if I submit the same requests directly to the remote node's RPC, it works fine.

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
- Run tendermint in +- default settings (empty blocks are produced) for some time on a remote node.
- startup `tendermint lite` against the remote node
- keep submitting batch JSONRPC requests for `block_results`

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
```
...
I[2019-08-23|15:08:56.964] HTTPJSONRPC                                  module=main method=block args="[<*rpctypes.Context Value> <*int64 Value>]" returns="[<*core_types.ResultBlock Value> <error Value>]"
I[2019-08-23|15:08:57.680] HTTPJSONRPC                                  module=main method=block args="[<*rpctypes.Context Value> <*int64 Value>]" returns="[<*core_types.ResultBlock Value> <error Value>]"
E[2019-08-23|15:08:57.689] Panic in RPC HTTP handler                    module=main err="write tcp 127.0.0.1:26657->127.0.0.1:52362: i/o timeout" stack="goroutine 58 [running]:\nruntime/debug.Stack(0xc0013115c8, 0x1a019a0, 0xc0003690e0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1.1(0xc0012965c0, 0x1d9cf80, 0xc000085f60, 0xbf50021e64fcbc18, 0x78d789402, 0x24f33c0, 0xc000193500)\n\t/go/src/github.com/tendermint/tendermint/rpc/lib/server/http_server.go:161 +0x552\npanic(0x1a019a0, 0xc0003690e0)\n\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\ngithub.com/tendermint/tendermint/rpc/lib/server.WriteRPCResponseArrayHTTP(0x1d98540, 0xc0012965c0, 0xc001326800, 0x14, 0x20)\n\t/go/src/github.com/tendermint/tendermint/rpc/lib/server/http_server.go:130 +0x300\ngithub.com/tendermint/tendermint/rpc/lib/server.makeJSONRPCHandler.func1(0x1d98540, 0xc0012965c0, 0xc000193500)\n\t/go/src/github.com/tendermint/tendermint/rpc/lib/server/handlers.go:167 +0x45c\ngithub.com/tendermint/tendermint/rpc/lib/server.handleInvalidJSONRPCPaths.func1(0x1d98540, 0xc0012965c0, 0xc000193500)\n\t/go/src/github.com/tendermint/tendermint/rpc/lib/server/handlers.go:181 +0x9c\nnet/http.HandlerFunc.ServeHTTP(0xc0009444a0, 0x1d98540, 0xc0012965c0, 0xc000193500)\n\t/usr/local/go/src/net/http/server.go:1995 +0x44\nnet/http.(*ServeMux).ServeHTTP(0xc000080540, 0x1d98540, 0xc0012965c0, 0xc000193500)\n\t/usr/local/go/src/net/http/server.go:2375 +0x1d6\ngithub.com/tendermint/tendermint/rpc/lib/server.maxBytesHandler.ServeHTTP(0x1d83bc0, 0xc000080540, 0xf4240, 0x1d98540, 0xc0012965c0, 0xc000193500)\n\t/go/src/github.com/tendermint/tendermint/rpc/lib/server/http_server.go:206 +0xd0\ngithub.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1(0x1d98c80, 0xc0009602a0, 0xc000193500)\n\t/go/src/github.com/tendermint/tendermint/rpc/lib/server/http_server.go:179 +0x317\nnet/http.HandlerFunc.ServeHTTP(0xc00094ae70, 0x1d98c80, 0xc0009602a0, 0xc000193500)\n\t/usr/local/go/src/net/http/server.go:1995 +0x44\nnet/http.serverHandler.ServeHTTP(0xc000149ad0, 0x1d98c80, 0xc0009602a0, 0xc000193500)\n\t/usr/local/go/src/net/http/server.go:2774 +0xa8\nnet/http.(*conn).serve(0xc001298c80, 0x1d9c480, 0xc00092cf80)\n\t/usr/local/go/src/net/http/server.go:1878 +0x851\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2884 +0x2f4\n"
2019/08/23 15:08:57 http: superfluous response.WriteHeader call from github.com/tendermint/tendermint/rpc/lib/server.(*ResponseWriterWrapper).WriteHeader (http_server.go:191)
2019/08/23 15:08:57 http: panic serving 127.0.0.1:52362: write tcp 127.0.0.1:26657->127.0.0.1:52362: i/o timeout
goroutine 58 [running]:
net/http.(*conn).serve.func1(0xc001298c80)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x1a019a0, 0xc0003690e0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/tendermint/tendermint/rpc/lib/server.WriteRPCResponseHTTPError(0x1d98540, 0xc0012965c0, 0x1f4, 0x1aff6c6, 0x3, 0x1d84ae0, 0x1d6dd30, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/tendermint/tendermint/rpc/lib/server/http_server.go:100 +0x2a4
github.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1.1(0xc0012965c0, 0x1d9cf80, 0xc000085f60, 0xbf50021e64fcbc18, 0x78d789402, 0x24f33c0, 0xc000193500)
	/go/src/github.com/tendermint/tendermint/rpc/lib/server/http_server.go:163 +0x758
panic(0x1a019a0, 0xc0003690e0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/tendermint/tendermint/rpc/lib/server.WriteRPCResponseArrayHTTP(0x1d98540, 0xc0012965c0, 0xc001326800, 0x14, 0x20)
	/go/src/github.com/tendermint/tendermint/rpc/lib/server/http_server.go:130 +0x300
github.com/tendermint/tendermint/rpc/lib/server.makeJSONRPCHandler.func1(0x1d98540, 0xc0012965c0, 0xc000193500)
	/go/src/github.com/tendermint/tendermint/rpc/lib/server/handlers.go:167 +0x45c
github.com/tendermint/tendermint/rpc/lib/server.handleInvalidJSONRPCPaths.func1(0x1d98540, 0xc0012965c0, 0xc000193500)
	/go/src/github.com/tendermint/tendermint/rpc/lib/server/handlers.go:181 +0x9c
net/http.HandlerFunc.ServeHTTP(0xc0009444a0, 0x1d98540, 0xc0012965c0, 0xc000193500)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0xc000080540, 0x1d98540, 0xc0012965c0, 0xc000193500)
	/usr/local/go/src/net/http/server.go:2375 +0x1d6
github.com/tendermint/tendermint/rpc/lib/server.maxBytesHandler.ServeHTTP(0x1d83bc0, 0xc000080540, 0xf4240, 0x1d98540, 0xc0012965c0, 0xc000193500)
	/go/src/github.com/tendermint/tendermint/rpc/lib/server/http_server.go:206 +0xd0
github.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1(0x1d98c80, 0xc0009602a0, 0xc000193500)
	/go/src/github.com/tendermint/tendermint/rpc/lib/server/http_server.go:179 +0x317
net/http.HandlerFunc.ServeHTTP(0xc00094ae70, 0x1d98c80, 0xc0009602a0, 0xc000193500)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.serverHandler.ServeHTTP(0xc000149ad0, 0x1d98c80, 0xc0009602a0, 0xc000193500)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc001298c80, 0x1d9c480, 0xc00092cf80)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
...
```
**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by melekes** [comment]
note: lite package is undergoing heavy refactoring right now https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-044-lite-client-with-weak-subjectivity.md

**Comment by melekes** [comment]
TODO:

- [ ] test this with a new light client proxy

**Comment by melekes** [comment]
@cmwaters could you check ^^?

**Comment by cmwaters** [comment]
I have run the same test with the new light client and it doesn't seem to be panicking upon requests. However, I have observed the following:

When I try request `block_results` (without any parameters i.e. for the latest height) I get this: 
```
{
  "jsonrpc": "2.0",
  "id": -1,
  "error": {
    "code": -32603,
    "message": "Internal error",
    "data": "failed to update light client to 7: failed to obtain the header #7: signed header not found"
  }
}
```

It is trying to update the client to a height that hasn't been reached yet. In this case it should return the result for the block at height 6

When I try to batch RPC requests (irrelevant whether it is `block_results` or another RPC call I get this:
```
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32600,
    "message": "Invalid Request",
    "data": "error reading request body: http: request body too large"
  }
}
```
where the request size was only 385 Bytes (in a full node it can handle messages up to 1MB)

@melekes what is your view on these two issues

**Comment by melekes** [comment]
> It is trying to update the client to a height that hasn't been reached yet. In this case it should return the result for the block at height 6

agree!

> where the request size was only 385 Bytes (in a full node it can handle messages up to 1MB)

that's weird. we should fix this

**Comment by cmwaters** [comment]
I will close this now and open issues on the aforementioned problems
