### ISSUE TITLE
`mempool` Memory Loading Error on 32-bit Ubuntu 16.04 Machine

### ISSUE THREAD

**Issue by jon-certik** [tendermint/tendermint#3968]
**Tendermint version**: 0.32.3-22000c6a (Latest `master` to date)

**OS**:

```bash
Linux <MY_MACHINE> 4.15.0-58-generic #64~16.04.1-Ubuntu SMP Wed Aug 7 14:09:34 UTC 2019 i686 i686 i686 GNU/Linux
```

**What happened**: Running `go test .` in `mempool` module results in the following memory loading error.

**What you expected to happen**: All tests passed.

**Have you tried the latest version**: Yes. Latest version to date.

**How to reproduce it**: Run `go test .` in `memopool/` on a 32-bit Ubuntu 16.04 machine.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

```bash
--- FAIL: TestCacheAfterUpdate (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x804aa5b]

goroutine 12 [running]:
testing.tRunner.func1(0x9c9e1e0)
	/usr/local/go/src/testing/testing.go:830 +0x345
panic(0x86b1b00, 0x8e3b4c8)
	/usr/local/go/src/runtime/panic.go:522 +0x16e
runtime/internal/atomic.Load64(0xa3f25d4, 0x0, 0xa3f2584)
	/usr/local/go/src/runtime/internal/atomic/asm_386.s:194 +0xb
github.com/tendermint/tendermint/mempool.(*CListMempool).TxsBytes(...)
	/home/jun/Desktop/tendermint/mempool/clist_mempool.go:171
github.com/tendermint/tendermint/mempool.(*CListMempool).CheckTxWithInfo(0xa3f2580, 0x9c2bb5c, 0x1, 0x1, 0x0, 0x9c80000, 0x0, 0x0)
	/home/jun/Desktop/tendermint/mempool/clist_mempool.go:222 +0xa8
github.com/tendermint/tendermint/mempool.(*CListMempool).CheckTx(...)
	/home/jun/Desktop/tendermint/mempool/clist_mempool.go:212
github.com/tendermint/tendermint/mempool.TestCacheAfterUpdate(0x9c9e1e0)
	/home/jun/Desktop/tendermint/mempool/cache_test.go:61 +0x364
testing.tRunner(0x9c9e1e0, 0x8894b60)
	/usr/local/go/src/testing/testing.go:865 +0x97
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x2b5
FAIL	github.com/tendermint/tendermint/mempool	0.053s
```

**Config (you can paste only the changes you've made)**: None.

**Comment by jon-certik** [comment]
All test passed after the patch #3969 :

```bash
PASS
ok  	github.com/tendermint/tendermint/mempool	26.860s
```
