### ISSUE TITLE
"Testing removing two validators at once" timed out

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#398]
From https://circleci.com/gh/tendermint/tendermint/654

```
[34mINFO[0m[02-08|07:24:08] Block{
  Header{
    ChainID:        tendermint_test
    Height:         17
    Time:           2017-02-08 07:24:07.327 +0000 UTC
    NumTxs:         0
    LastBlockID:    3814059B681B9344DC499A982BEC1B6E73EB5460:1:41F7ED421857
    LastCommit:     619A7442FE651824531A01B2B49E5EA85A7D196C
    Data:           
    Validators:     035D2E579D8FDDD8EFFBB86D1FA1CFE19A42777B
    App:            C43AADFBC80BDED94D46A3BCE7B330DFE661FEE1
  }#2CF09284438F1950709BF04EB57C46F73497C71F
  Data{
    
  }#
  Commit{
    BlockID:    3814059B681B9344DC499A982BEC1B6E73EB5460:1:41F7ED421857
    Precommits: Vote{0:192DCBA191B0 16/00/2(Precommit) 3814059B681B /8FF3AB2C4E33.../}
    Vote{1:50B021FFC989 16/00/2(Precommit) 3814059B681B /F8DD8389AD2E.../}
    Vote{2:7F2B3424E6FF 16/00/2(Precommit) 3814059B681B /3732D7285AB9.../}
    Vote{3:AC3636D65D72 16/00/2(Precommit) 3814059B681B /19E6F0B211EE.../}
    Vote{4:CD8F78980E4F 16/00/2(Precommit) 3814059B681B /21231CE03FFA.../}
  }#619A7442FE651824531A01B2B49E5EA85A7D196C
}#2CF09284438F1950709BF04EB57C46F73497C71F [34mmodule[0m=consensus
[34mINFO[0m[02-08|07:24:08] Executed block                           [34mmodule[0m=state [34mheight[0m=17 [34mvalid txs[0m=0 [34minvalid txs[0m=0
[34mINFO[0m[02-08|07:24:08] Saved state                              [34mmodule[0m=dummy [34mroot[0m=C43AADFBC80BDED94D46A3BCE7B330DFE661FEE1
[32mNOTE[0m[02-08|07:24:08] Saving block                             [32mmodule[0m=dummy [32mheight[0m=17 [32mroot[0m=C43AADFBC80BDED94D46A3BCE7B330DFE661FEE1
[34mINFO[0m[02-08|07:24:08] Added to lastPrecommits: VoteSet{H:17 R:0 T:2 +2/3:2CF09284438F1950709BF04EB57C46F73497C71F:1:008F1FA73FEA BA{5:XX_XX} map[]} [34mmodule[0m=consensus
[34mINFO[0m[02-08|07:24:08] Added to lastPrecommits: VoteSet{H:17 R:0 T:2 +2/3:2CF09284438F1950709BF04EB57C46F73497C71F:1:008F1FA73FEA BA{5:XXXXX} map[]} [34mmodule[0m=consensus
[32mNOTE[0m[02-08|07:24:08] enterNewRound(18/0). Current: 18/0/RoundStepNewHeight [32mmodule[0m=consensus
[34mINFO[0m[02-08|07:24:08] enterPropose(18/0). Current: 18/0/RoundStepNewRound [34mmodule[0m=consensus
[34mINFO[0m[02-08|07:24:08] enterPropose: Not our turn to propose    [34mmodule[0m=consensus [34mproposer[0m=192DCBA191B09CC0A255C95CF27849056DABA0BD [34mprivValidator[0m="PrivValidator{CD8F78980E4F32A186F77D53D9429E2EBE6AC1E4 LH:17, LR:0, LS:3}"
[34mINFO[0m[02-08|07:24:08] Executed block                           [34mmodule[0m=state [34mheight[0m=17 [34mvalid txs[0m=0 [34minvalid txs[0m=0
[34mINFO[0m[02-08|07:24:08] Recheck txs                              [34mmodule[0m=mempool [34mnumtxs[0m=0
[34mINFO[0m[02-08|07:24:08] Saved state                              [34mmodule[0m=dummy [34mroot[0m=C43AADFBC80BDED94D46A3BCE7B330DFE661FEE1
[32mNOTE[0m[02-08|07:24:08] Saving block                             [32mmodule[0m=dummy [32mheight[0m=17 [32mroot[0m=C43AADFBC80BDED94D46A3BCE7B330DFE661FEE1
[34mINFO[0m[02-08|07:24:08] Recheck txs                              [34mmodule[0m=mempool [34mnumtxs[0m=0
[34mINFO[0m[02-08|07:24:08] Executed block                           [34mmodule[0m=state [34mheight[0m=17 [34mvalid txs[0m=0 [34minvalid txs[0m=0
[34mINFO[0m[02-08|07:24:08] Saved state                              [34mmodule[0m=dummy [34mroot[0m=C43AADFBC80BDED94D46A3BCE7B330DFE661FEE1
[32mNOTE[0m[02-08|07:24:08] Saving block                             [32mmodule[0m=dummy [32mheight[0m=17 [32mroot[0m=C43AADFBC80BDED94D46A3BCE7B330DFE661FEE1
[34mINFO[0m[02-08|07:24:08] Recheck txs                              [34mmodule[0m=mempool [34mnumtxs[0m=0
[33mWARN[0m[02-08|07:24:08] Got block                                [33mmodule[0m=consensus [33mheight[0m=17 [33mvalidator[0m=4
[33mWARN[0m[02-08|07:24:08] Done wait group                          [33mmodule[0m=consensus [33mheight[0m=17 [33mvalidator[0m=4
[34mINFO[0m[02-08|07:24:08] Executed block                           [34mmodule[0m=state [34mheight[0m=17 [34mvalid txs[0m=0 [34minvalid txs[0m=0
[34mINFO[0m[02-08|07:24:08] Saved state                              [34mmodule[0m=dummy [34mroot[0m=C43AADFBC80BDED94D46A3BCE7B330DFE661FEE1
[32mNOTE[0m[02-08|07:24:08] Saving block                             [32mmodule[0m=dummy [32mheight[0m=17 [32mroot[0m=C43AADFBC80BDED94D46A3BCE7B330DFE661FEE1
[34mINFO[0m[02-08|07:24:08] Recheck txs                              [34mmodule[0m=mempool [34mnumtxs[0m=0
[33mWARN[0m[02-08|07:24:08] Got block                                [33mmodule[0m=consensus [33mheight[0m=17 [33mvalidator[0m=5
[33mWARN[0m[02-08|07:24:08] Done wait group                          [33mmodule[0m=consensus [33mheight[0m=17 [33mvalidator[0m=5
[33mWARN[0m[02-08|07:24:08] Got block                                [33mmodule[0m=consensus [33mheight[0m=17 [33mvalidator[0m=0
[33mWARN[0m[02-08|07:24:08] Done wait group                          [33mmodule[0m=consensus [33mheight[0m=17 [33mvalidator[0m=0
[34mINFO[0m[02-08|07:24:08] Added to lastPrecommits: VoteSet{H:17 R:0 T:2 +2/3:2CF09284438F1950709BF04EB57C46F73497C71F:1:008F1FA73FEA BA{5:XXXXX} map[]} [34mmodule[0m=consensus
[32mNOTE[0m[02-08|07:24:08] enterNewRound(18/0). Current: 18/0/RoundStepNewHeight [32mmodule[0m=consensus
[34mINFO[0m[02-08|07:24:08] enterPropose(18/0). Current: 18/0/RoundStepNewRound [34mmodule[0m=consensus
[34mINFO[0m[02-08|07:24:08] enterPropose: Not our turn to propose    [34mmodule[0m=consensus [34mproposer[0m=192DCBA191B09CC0A255C95CF27849056DABA0BD [34mprivValidator[0m="PrivValidator{7F2B3424E6FFA8EEE96ED38285156EE5AF77559A LH:17, LR:0, LS:3}"
[34mINFO[0m[02-08|07:24:08] Executed block                           [34mmodule[0m=state [34mheight[0m=17 [34mvalid txs[0m=0 [34minvalid txs[0m=0
[34mINFO[0m[02-08|07:24:08] Saved state                              [34mmodule[0m=dummy [34mroot[0m=C43AADFBC80BDED94D46A3BCE7B330DFE661FEE1
[32mNOTE[0m[02-08|07:24:08] Saving block                             [32mmodule[0m=dummy [32mheight[0m=17 [32mroot[0m=C43AADFBC80BDED94D46A3BCE7B330DFE661FEE1
[34mINFO[0m[02-08|07:24:08] Recheck txs                              [34mmodule[0m=mempool [34mnumtxs[0m=0
[33mWARN[0m[02-08|07:24:08] Got block                                [33mmodule[0m=consensus [33mheight[0m=17 [33mvalidator[0m=1
[33mWARN[0m[02-08|07:24:08] Done wait group                          [33mmodule[0m=consensus [33mheight[0m=17 [33mvalidator[0m=1
[34mINFO[0m[02-08|07:24:08] Added to lastPrecommits: VoteSet{H:17 R:0 T:2 +2/3:2CF09284438F1950709BF04EB57C46F73497C71F:1:008F1FA73FEA BA{5:XXXX_} map[]} [34mmodule[0m=consensus
[33mWARN[0m[02-08|07:24:08] Got block                                [33mmodule[0m=consensus [33mheight[0m=17 [33mvalidator[0m=6
[33mWARN[0m[02-08|07:24:08] Done wait group                          [33mmodule[0m=consensus [33mheight[0m=17 [33mvalidator[0m=6
[34mINFO[0m[02-08|07:24:08] Added to lastPrecommits: VoteSet{H:17 R:0 T:2 +2/3:2CF09284438F1950709BF04EB57C46F73497C71F:1:008F1FA73FEA BA{5:_XXXX} map[]} [34mmodule[0m=consensus
[34mINFO[0m[02-08|07:24:08] Stopping P2P Switch                      [34mmodule[0m=p2p [34mimpl[0m="P2P Switch"
[34mINFO[0m[02-08|07:24:08] Stopping Peer                            [34mmodule[0m=p2p [34mimpl[0m="Peer{MConn{pipe} 43C8DC30679B in}"
[34mINFO[0m[02-08|07:24:08] Stopping MConnection                     [34mmodule[0m=p2p [34mimpl[0m=MConn{pipe}
[34mINFO[0m[02-08|07:24:08] Added to lastPrecommits: VoteSet{H:17 R:0 T:2 +2/3:2CF09284438F1950709BF04EB57C46F73497C71F:1:008F1FA73FEA BA{5:XXXXX} map[]} [34mmodule[0m=consensus
[32mNOTE[0m[02-08|07:24:08] enterNewRound(18/0). Current: 18/0/RoundStepNewHeight [32mmodule[0m=consensus
[34mINFO[0m[02-08|07:24:08] enterPropose(18/0). Current: 18/0/RoundStepNewRound [34mmodule[0m=consensus
[34mINFO[0m[02-08|07:24:08] enterPropose: Not our turn to propose    [34mmodule[0m=consensus [34mproposer[0m=192DCBA191B09CC0A255C95CF27849056DABA0BD [34mprivValidator[0m="PrivValidator{AC3636D65D729D53406D7E751D2498CDB779027C LH:17, LR:0, LS:3}"
[34mINFO[0m[02-08|07:24:08] Added to lastPrecommits: VoteSet{H:17 R:0 T:2 +2/3:2CF09284438F1950709BF04EB57C46F73497C71F:1:008F1FA73FEA BA{5:XXXXX} map[]} [34mmodule[0m=consensus
[32mNOTE[0m[02-08|07:24:08] enterNewRound(18/0). Current: 18/0/RoundStepNewHeight [32mmodule[0m=consensus
[34mINFO[0m[02-08|07:24:08] enterPropose(18/0). Current: 18/0/RoundStepNewRound [34mmodule[0m=consensus
[34mINFO[0m[02-08|07:24:08] enterPropose: Not our turn to propose    [34mmodule[0m=consensus [34mproposer[0m=192DCBA191B09CC0A255C95CF27849056DABA0BD [34mprivValidator[0m="PrivValidator{0FBD9970B1E5B3A1136A1D5C228D9EA487CF44C6 LH:15, LR:0, LS:3}"
[34mINFO[0m[02-08|07:24:08] Stopping Peer                            [34mmodule[0m=p2p [34mimpl[0m="Peer{MConn{pipe} 6255B7EBC074 in}"
[34mINFO[0m[02-08|07:24:08] Stopping MConnection                     [34mmodule[0m=p2p [34mimpl[0m=MConn{pipe}
[32mNOTE[0m[02-08|07:24:08] Stopping gossipDataRoutine for Peer{MConn{pipe} 43C8DC30679B in}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 43C8DC30679B in}"
[34mINFO[0m[02-08|07:24:08] Added to lastPrecommits: VoteSet{H:17 R:0 T:2 +2/3:2CF09284438F1950709BF04EB57C46F73497C71F:1:008F1FA73FEA BA{5:XXXX_} map[]} [34mmodule[0m=consensus
[34mINFO[0m[02-08|07:24:08] Added to lastPrecommits: VoteSet{H:17 R:0 T:2 +2/3:2CF09284438F1950709BF04EB57C46F73497C71F:1:008F1FA73FEA BA{5:XX_XX} map[]} [34mmodule[0m=consensus
[32mNOTE[0m[02-08|07:24:08] Stopping gossipDataRoutine for Peer{MConn{pipe} 6255B7EBC074 in}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 6255B7EBC074 in}"
[33mWARN[0m[02-08|07:24:08] Connection failed @ recvRoutine (reading byte) [33mmodule[0m=p2p [33mconn[0m=MConn{pipe} [33merror[0m=EOF
[34mINFO[0m[02-08|07:24:08] Stopping MConnection                     [34mmodule[0m=p2p [34mimpl[0m=MConn{pipe}
[34mINFO[0m[02-08|07:24:08] Added to lastPrecommits: VoteSet{H:17 R:0 T:2 +2/3:2CF09284438F1950709BF04EB57C46F73497C71F:1:008F1FA73FEA BA{5:XXXXX} map[]} [34mmodule[0m=consensus
[32mNOTE[0m[02-08|07:24:08] enterNewRound(18/0). Current: 18/0/RoundStepNewHeight [32mmodule[0m=consensus
[34mINFO[0m[02-08|07:24:08] enterPropose(18/0). Current: 18/0/RoundStepNewRound [34mmodule[0m=consensus
[34mINFO[0m[02-08|07:24:08] enterPropose: Not our turn to propose    [34mmodule[0m=consensus [34mproposer[0m=192DCBA191B09CC0A255C95CF27849056DABA0BD [34mprivValidator[0m="PrivValidator{5223DFC33198815A971BAC1149A7005EA4298AB1 LH:15, LR:0, LS:3}"
[34mINFO[0m[02-08|07:24:08] Added to lastPrecommits: VoteSet{H:17 R:0 T:2 +2/3:2CF09284438F1950709BF04EB57C46F73497C71F:1:008F1FA73FEA BA{5:XXXXX} map[]} [34mmodule[0m=consensus
[32mNOTE[0m[02-08|07:24:08] enterNewRound(18/0). Current: 18/0/RoundStepNewHeight [32mmodule[0m=consensus
[34mINFO[0m[02-08|07:24:08] enterPropose(18/0). Current: 18/0/RoundStepNewRound [34mmodule[0m=consensus
[34mINFO[0m[02-08|07:24:08] enterPropose: Our turn to propose        [34mmodule[0m=consensus [34mproposer[0m=192DCBA191B09CC0A255C95CF27849056DABA0BD [34mprivValidator[0m="PrivValidator{192DCBA191B09CC0A255C95CF27849056DABA0BD LH:17, LR:0, LS:3}"
[34mINFO[0m[02-08|07:24:08] Added to lastPrecommits: VoteSet{H:17 R:0 T:2 +2/3:2CF09284438F1950709BF04EB57C46F73497C71F:1:008F1FA73FEA BA{5:XX_XX} map[]} [34mmodule[0m=consensus
[32mNOTE[0m[02-08|07:24:08] Stopping gossipVotesRoutine for Peer{MConn{pipe} 43C8DC30679B in}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 43C8DC30679B in}"
[34mINFO[0m[02-08|07:24:08] Added to lastPrecommits: VoteSet{H:17 R:0 T:2 +2/3:2CF09284438F1950709BF04EB57C46F73497C71F:1:008F1FA73FEA BA{5:XXXXX} map[]} [34mmodule[0m=consensus
[32mNOTE[0m[02-08|07:24:08] enterNewRound(18/0). Current: 18/0/RoundStepNewHeight [32mmodule[0m=consensus
[34mINFO[0m[02-08|07:24:08] enterPropose(18/0). Current: 18/0/RoundStepNewRound [34mmodule[0m=consensus
[34mINFO[0m[02-08|07:24:08] enterPropose: Not our turn to propose    [34mmodule[0m=consensus [34mproposer[0m=192DCBA191B09CC0A255C95CF27849056DABA0BD [34mprivValidator[0m="PrivValidator{50B021FFC989D95F9065C05127BD79706117BF60 LH:17, LR:0, LS:3}"
[34mINFO[0m[02-08|07:24:08] Signed proposal                          [34mmodule[0m=consensus [34mheight[0m=18 [34mround[0m=0 [34mproposal[0m="Proposal{18/0 1:370EAB6F9E53 (-1,:0:000000000000) /B472364B2F16.../}"
[34mINFO[0m[02-08|07:24:08] Received complete proposal block         [34mmodule[0m=consensus [34mheight[0m=18 [34mhash[0m=D2EB03DB3C650C7453EC0B39294441AF5F6E5499
[34mINFO[0m[02-08|07:24:08] enterPrevote(18/0). Current: 18/0/RoundStepPropose [34mmodule[0m=consensus
[32mNOTE[0m[02-08|07:24:08] Stopping gossipVotesRoutine for Peer{MConn{pipe} 6255B7EBC074 in}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 6255B7EBC074 in}"
[34mINFO[0m[02-08|07:24:08] Stopping Peer                            [34mmodule[0m=p2p [34mimpl[0m="Peer{MConn{pipe} 7576D1E11F02 in}"
[34mINFO[0m[02-08|07:24:08] Stopping MConnection                     [34mmodule[0m=p2p [34mimpl[0m=MConn{pipe}
[34mINFO[0m[02-08|07:24:08] Stopping Peer                            [34mmodule[0m=p2p [34mimpl[0m="Peer{MConn{pipe} 49042790EC7F out}"
[32mNOTE[0m[02-08|07:24:08] Stopping peer for error                  [32mmodule[0m=p2p [32mpeer[0m="Peer{MConn{pipe} 49042790EC7F out}" [32merror[0m=EOF
[33mWARN[0m[02-08|07:24:08] Connection failed @ recvRoutine (reading byte) [33mmodule[0m=p2p [33mconn[0m=MConn{pipe} [33merror[0m=EOF
[34mINFO[0m[02-08|07:24:08] Stopping MConnection                     [34mmodule[0m=p2p [34mimpl[0m=MConn{pipe}
[34mINFO[0m[02-08|07:24:08] Stopping Peer                            [34mmodule[0m=p2p [34mimpl[0m="Peer{MConn{pipe} 1444AA50E91F in}"
[34mINFO[0m[02-08|07:24:08] Stopping MConnection                     [34mmodule[0m=p2p [34mimpl[0m=MConn{pipe}
[33mWARN[0m[02-08|07:24:08] Connection failed @ recvRoutine (reading byte) [33mmodule[0m=p2p [33mconn[0m=MConn{pipe} [33merror[0m=EOF
[34mINFO[0m[02-08|07:24:08] Stopping MConnection                     [34mmodule[0m=p2p [34mimpl[0m=MConn{pipe}
[33mWARN[0m[02-08|07:24:08] MConnection flush failed                 [33mmodule[0m=p2p [33merror[0m="io: read/write on closed pipe"
[34mINFO[0m[02-08|07:24:08] Stopping Peer                            [34mmodule[0m=p2p [34mimpl[0m="Peer{MConn{pipe} 49042790EC7F out}"
[32mNOTE[0m[02-08|07:24:08] Stopping peer for error                  [32mmodule[0m=p2p [32mpeer[0m="Peer{MConn{pipe} 49042790EC7F out}" [32merror[0m=EOF
[34mINFO[0m[02-08|07:24:09] Stopping Peer                            [34mmodule[0m=p2p [34mimpl[0m="Peer{MConn{pipe} 49042790EC7F out}"
[32mNOTE[0m[02-08|07:24:09] Stopping peer for error                  [32mmodule[0m=p2p [32mpeer[0m="Peer{MConn{pipe} 49042790EC7F out}" [32merror[0m=EOF
[33mWARN[0m[02-08|07:24:09] MConnection flush failed                 [33mmodule[0m=p2p [33merror[0m="io: read/write on closed pipe"
[34mINFO[0m[02-08|07:24:09] Stopping Peer                            [34mmodule[0m=p2p [34mimpl[0m="Peer{MConn{pipe} 8B8B53E8DE2B in}"
[34mINFO[0m[02-08|07:24:09] Stopping MConnection                     [34mmodule[0m=p2p [34mimpl[0m=MConn{pipe}
[33mWARN[0m[02-08|07:24:09] Connection failed @ recvRoutine (reading byte) [33mmodule[0m=p2p [33mconn[0m=MConn{pipe} [33merror[0m=EOF
[34mINFO[0m[02-08|07:24:09] Stopping MConnection                     [34mmodule[0m=p2p [34mimpl[0m=MConn{pipe}
[32mNOTE[0m[02-08|07:24:09] Stopping gossipDataRoutine for Peer{MConn{pipe} 8B8B53E8DE2B in}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 8B8B53E8DE2B in}"
[32mNOTE[0m[02-08|07:24:09] Stopping gossipDataRoutine for Peer{MConn{pipe} 49042790EC7F out}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 49042790EC7F out}"
[34mINFO[0m[02-08|07:24:09] Stopping Peer                            [34mmodule[0m=p2p [34mimpl[0m="Peer{MConn{pipe} 40A12E57C59B in}"
[34mINFO[0m[02-08|07:24:09] Stopping MConnection                     [34mmodule[0m=p2p [34mimpl[0m=MConn{pipe}
[34mINFO[0m[02-08|07:24:09] Stopping ConsensusReactor                [34mmodule[0m=consensus [34mimpl[0m=ConsensusReactor
[34mINFO[0m[02-08|07:24:09] Stopping ConsensusState                  [34mmodule[0m=consensus [34mimpl[0m=ConsensusState
[34mINFO[0m[02-08|07:24:09] Stopping P2P Switch                      [34mmodule[0m=p2p [34mimpl[0m="P2P Switch"
[34mINFO[0m[02-08|07:24:09] Stopping Peer                            [34mmodule[0m=p2p [34mimpl[0m="Peer{MConn{pipe} 40A12E57C59B in}"
[34mINFO[0m[02-08|07:24:09] Stopping MConnection                     [34mmodule[0m=p2p [34mimpl[0m=MConn{pipe}
[34mINFO[0m[02-08|07:24:09] Stopping Peer                            [34mmodule[0m=p2p [34mimpl[0m="Peer{MConn{pipe} 49042790EC7F out}"
[32mNOTE[0m[02-08|07:24:09] Stopping peer for error                  [32mmodule[0m=p2p [32mpeer[0m="Peer{MConn{pipe} 49042790EC7F out}" [32merror[0m=EOF
[33mWARN[0m[02-08|07:24:09] Connection failed @ recvRoutine (reading byte) [33mmodule[0m=p2p [33mconn[0m=MConn{pipe} [33merror[0m=EOF
[34mINFO[0m[02-08|07:24:09] Stopping MConnection                     [34mmodule[0m=p2p [34mimpl[0m=MConn{pipe}
[33mWARN[0m[02-08|07:24:09] MConnection flush failed                 [33mmodule[0m=p2p [33merror[0m="io: read/write on closed pipe"
[33mWARN[0m[02-08|07:24:09] Connection failed @ recvRoutine (reading byte) [33mmodule[0m=p2p [33mconn[0m=MConn{pipe} [33merror[0m=EOF
[34mINFO[0m[02-08|07:24:09] Stopping MConnection                     [34mmodule[0m=p2p [34mimpl[0m=MConn{pipe}
[33mWARN[0m[02-08|07:24:09] MConnection flush failed                 [33mmodule[0m=p2p [33merror[0m="io: read/write on closed pipe"
[34mINFO[0m[02-08|07:24:09] Stopping Peer                            [34mmodule[0m=p2p [34mimpl[0m="Peer{MConn{pipe} 49042790EC7F out}"
[32mNOTE[0m[02-08|07:24:09] Stopping peer for error                  [32mmodule[0m=p2p [32mpeer[0m="Peer{MConn{pipe} 49042790EC7F out}" [32merror[0m=EOF
[34mINFO[0m[02-08|07:24:09] Stopping Peer                            [34mmodule[0m=p2p [34mimpl[0m="Peer{MConn{pipe} 49042790EC7F out}"
[32mNOTE[0m[02-08|07:24:09] Stopping peer for error                  [32mmodule[0m=p2p [32mpeer[0m="Peer{MConn{pipe} 49042790EC7F out}" [32merror[0m=EOF
[33mWARN[0m[02-08|07:24:09] MConnection flush failed                 [33mmodule[0m=p2p [33merror[0m="io: read/write on closed pipe"
[34mINFO[0m[02-08|07:24:09] Signed and pushed vote                   [34mmodule[0m=consensus [34mheight[0m=18 [34mround[0m=0 [34mvote[0m="Vote{0:192DCBA191B0 18/00/1(Prevote) D2EB03DB3C65 /4AB165CCAAEA.../}" [34merror[0m=nil
[34mINFO[0m[02-08|07:24:09] Stopping WAL                             [34mmodule[0m=consensus [34mimpl[0m=WAL
[32mNOTE[0m[02-08|07:24:09] Stopping gossipVotesRoutine for Peer{MConn{pipe} 49042790EC7F out}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 49042790EC7F out}"
[32mNOTE[0m[02-08|07:24:09] Stopping gossipVotesRoutine for Peer{MConn{pipe} 49042790EC7F out}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 49042790EC7F out}"
[32mNOTE[0m[02-08|07:24:09] Stopping gossipVotesRoutine for Peer{MConn{pipe} 49042790EC7F out}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 49042790EC7F out}"
[32mNOTE[0m[02-08|07:24:09] Stopping gossipVotesRoutine for Peer{MConn{pipe} 8B8B53E8DE2B in}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 8B8B53E8DE2B in}"
[32mNOTE[0m[02-08|07:24:09] Stopping gossipDataRoutine for Peer{MConn{pipe} 1444AA50E91F in}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 1444AA50E91F in}"
[32mNOTE[0m[02-08|07:24:09] Stopping gossipVotesRoutine for Peer{MConn{pipe} 40A12E57C59B in}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 40A12E57C59B in}"
[32mNOTE[0m[02-08|07:24:09] Stopping gossipVotesRoutine for Peer{MConn{pipe} 7576D1E11F02 in}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 7576D1E11F02 in}"
[32mNOTE[0m[02-08|07:24:09] Stopping gossipVotesRoutine for Peer{MConn{pipe} 1444AA50E91F in}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 1444AA50E91F in}"
[32mNOTE[0m[02-08|07:24:09] Stopping gossipDataRoutine for Peer{MConn{pipe} 49042790EC7F out}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 49042790EC7F out}"
[32mNOTE[0m[02-08|07:24:09] Stopping gossipDataRoutine for Peer{MConn{pipe} 40A12E57C59B in}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 40A12E57C59B in}"
[32mNOTE[0m[02-08|07:24:09] Stopping gossipDataRoutine for Peer{MConn{pipe} 40A12E57C59B in}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 40A12E57C59B in}"
[32mNOTE[0m[02-08|07:24:09] Stopping gossipDataRoutine for Peer{MConn{pipe} 49042790EC7F out}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 49042790EC7F out}"
[32mNOTE[0m[02-08|07:24:09] Stopping gossipVotesRoutine for Peer{MConn{pipe} 40A12E57C59B in}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 40A12E57C59B in}"
[32mNOTE[0m[02-08|07:24:09] Stopping gossipVotesRoutine for Peer{MConn{pipe} 49042790EC7F out}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 49042790EC7F out}"
[32mNOTE[0m[02-08|07:24:09] Stopping gossipVotesRoutine for Peer{MConn{pipe} 49042790EC7F out}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 49042790EC7F out}"
[32mNOTE[0m[02-08|07:24:09] Stopping gossipVotesRoutine for Peer{MConn{pipe} 49042790EC7F out}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 49042790EC7F out}"
[32mNOTE[0m[02-08|07:24:09] Stopping gossipDataRoutine for Peer{MConn{pipe} 49042790EC7F out}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 49042790EC7F out}"
[32mNOTE[0m[02-08|07:24:09] Stopping gossipDataRoutine for Peer{MConn{pipe} 49042790EC7F out}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 49042790EC7F out}"
[32mNOTE[0m[02-08|07:24:09] Stopping gossipDataRoutine for Peer{MConn{pipe} 49042790EC7F out}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 49042790EC7F out}"
[32mNOTE[0m[02-08|07:24:09] Stopping gossipDataRoutine for Peer{MConn{pipe} 7576D1E11F02 in}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 7576D1E11F02 in}"
[32mNOTE[0m[02-08|07:24:09] Stopping queryMaj23Routine for Peer{MConn{pipe} 49042790EC7F out}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 49042790EC7F out}"
[32mNOTE[0m[02-08|07:24:09] Stopping queryMaj23Routine for Peer{MConn{pipe} 49042790EC7F out}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 49042790EC7F out}"
[32mNOTE[0m[02-08|07:24:09] Stopping queryMaj23Routine for Peer{MConn{pipe} 43C8DC30679B in}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 43C8DC30679B in}"
[32mNOTE[0m[02-08|07:24:09] Stopping queryMaj23Routine for Peer{MConn{pipe} 6255B7EBC074 in}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 6255B7EBC074 in}"
[32mNOTE[0m[02-08|07:24:09] Stopping queryMaj23Routine for Peer{MConn{pipe} 8B8B53E8DE2B in}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 8B8B53E8DE2B in}"
[32mNOTE[0m[02-08|07:24:09] Stopping queryMaj23Routine for Peer{MConn{pipe} 7576D1E11F02 in}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 7576D1E11F02 in}"
[32mNOTE[0m[02-08|07:24:09] Stopping queryMaj23Routine for Peer{MConn{pipe} 1444AA50E91F in}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 1444AA50E91F in}"
[32mNOTE[0m[02-08|07:24:09] Stopping queryMaj23Routine for Peer{MConn{pipe} 49042790EC7F out}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 49042790EC7F out}"
[32mNOTE[0m[02-08|07:24:09] Stopping queryMaj23Routine for Peer{MConn{pipe} 40A12E57C59B in}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 40A12E57C59B in}"
[32mNOTE[0m[02-08|07:24:10] Stopping queryMaj23Routine for Peer{MConn{pipe} 49042790EC7F out}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 49042790EC7F out}"
[32mNOTE[0m[02-08|07:24:12] Stopping queryMaj23Routine for Peer{MConn{pipe} 40A12E57C59B in}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 40A12E57C59B in}"
[32mNOTE[0m[02-08|07:24:12] Stopping queryMaj23Routine for Peer{MConn{pipe} 49042790EC7F out}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 49042790EC7F out}"
[32mNOTE[0m[02-08|07:24:12] Stopping queryMaj23Routine for Peer{MConn{pipe} 49042790EC7F out}. [32mmodule[0m=consensus [32mpeer[0m="Peer{MConn{pipe} 49042790EC7F out}"
panic: test timed out after 30m0s
```

**Comment by melekes** [comment]
`make test_race` sometimes blocks

```
goroutine 1 [chan receive, 29 minutes]:
testing.(*T).Run(0xc420062600, 0xc68019, 0x17, 0xdfcbf0, 0x51fc01)
	/usr/local/go/src/testing/testing.go:647 +0x56e
testing.RunTests.func1(0xc420062600)
	/usr/local/go/src/testing/testing.go:793 +0xba
testing.tRunner(0xc420062600, 0xc420047d20)
	/usr/local/go/src/testing/testing.go:610 +0xca
testing.RunTests(0xdfd780, 0x10f6b00, 0x1a, 0x1a, 0xc420047db8)
	/usr/local/go/src/testing/testing.go:799 +0x4bb
testing.(*M).Run(0xc420047ef0, 0x30)
	/usr/local/go/src/testing/testing.go:743 +0x130
main.main()
	github.com/tendermint/tendermint/consensus/_test/_testmain.go:168 +0x2f9
```

there are lot of messages like this in the log

**Comment by ebuchman** [comment]
So, when I was testing this before the 0.8 release, I would use `kill -6` to send SIGABRT and get a stack trace dump of the program. I wonder if its possible to add that as part of the CI somehow - do we have any kind of access to the timer? ie. if we havent got output in over 3 minutes, say, we run the sigabrt and capture the output and dump it to the artifacts

**Comment by adrianbrink** [comment]
I'm closing this since we are two minor versions ahead.
