### ISSUE TITLE
Interrupt catch-up can never be resumed

### ISSUE THREAD

**Issue by srmo** [tendermint/tendermint#436]
BUG REPORT

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.9.0

**ABCI app**
Proprietary Java app

**OS**
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux

**Environment**
* 4 nodes on physically dislocated VMs (in different networks around the globe) (N1-N4)
* all 4 nodes are validators
* ABCI App persists height/hash after each commit for ABCI Handshake
* all nodes use the same node N1 as seed
* all nodes have `fastsync = true`

**What happened**:
One of the nodes stopped. Reason unknown. Last messages before stopping
```WARN[03-22|15:15:20] Need to set a buffer and log.Warn() here for sanity. module=consensus startTime=2017-03-22T15:15:21-0400 now=2017-03-22T15:15:20-0400
NOTE[03-22|15:15:20] enterNewRound(481148/1). Current: 481148/0/RoundStepNewHeight module=consensus
NOTE[03-22|15:15:20] enterPrecommit: No +2/3 prevotes during enterPrecommit. Precommitting nil. module=consensus
WARN[03-22|15:15:20] Attempt to finalize failed. We don't have the commit block. module=consensus height=481148 proposal-block= commit-block=2104096F72AB8DB6C252D6178F677B4026707144
WARN[03-22|15:15:20] Connection failed @ recvRoutine (reading byte) module=p2p conn=MConn{83.169.3.162:46656} error=EOF
NOTE[03-22|15:15:20] Stopping peer for error                  module=p2p peer="Peer{MConn{83.169.3.162:46656} 50D4E2821096 out}" error=EOF
NOTE[03-22|15:15:20] Stopping gossipVotesRoutine for Peer{MConn{83.169.3.162:46656} 50D4E2821096 out}. module=consensus peer="Peer{MConn{83.169.3.162:46656} 50D4E2821096 out}"
NOTE[03-22|15:15:20] Stopping gossipDataRoutine for Peer{MConn{83.169.3.162:46656} 50D4E2821096 out}. module=consensus peer="Peer{MConn{83.169.3.162:46656} 50D4E2821096 out}"
NOTE[03-22|15:15:22] Stopping queryMaj23Routine for Peer{MConn{83.169.3.162:46656} 50D4E2821096 out}. module=consensus peer="Peer{MConn{83.169.3.162:46656} 50D4E2821096 out}"
```

When restarting node and ABCI app, the replay started:
```NOTE[03-27|07:26:29] ABCI Handshake                           module=consensus appHeight=481147 appHash=4E3E5F169C1792AFCD5DC873710C237C2B1DB2D1
NOTE[03-27|07:26:29] ABCI Replay Blocks                       module=consensus appHeight=481147 storeHeight=481147 stateHeight=481147
NOTE[03-27|07:26:29] Completed ABCI Handshake - Tendermint and App are synced module=consensus appHeight=481147 appHash=4E3E5F169C1792AFCD5DC873710C237C2B1DB2D1
NOTE[03-27|07:26:32] ConsensusReactor                         module=consensus fastSync=true
NOTE[03-27|07:26:32] Starting RPC HTTP server on tcp socket 0.0.0.0:46657 module=rpcserver
NOTE[03-27|07:26:32] Started node                             module=main nodeInfo="&{PubKey:PubKeyEd25519{77416EA70324C01D102A34551B796D3B3D85C6555B845997D7F246D2AF4C0B9F} Moniker:gc-e3 Network:test-gridchain RemoteAddr: ListenAddr:46.101.126.24:46656 Version:0.9.0 Other:[wire_version=0.6.0 p2p_version=0.4.0 consensus_version=v1/0.2.2 rpc_version=0.6.0/3 rpc_addr=tcp://0.0.0.0:46657]}"
NOTE[03-27|07:26:33] Peer handshake                           module=p2p peerNodeInfo="&{PubKey:PubKeyEd25519{50D4E28210961EC75076CB3C203D7EAFD87EA8791FE9D31322386D0951886214} Moniker:gc-e1 Network:test-gridchain RemoteAddr: ListenAddr:83.169.3.162:46656 Version:0.9.0 Other:[wire_version=0.6.0 p2p_version=0.4.0 consensus_version=v1/0.2.2 rpc_version=0.6.0/3 rpc_addr=tcp://0.0.0.0:46657]}"
NOTE[03-27|07:26:33] Added peer                               module=p2p peer="Peer{MConn{83.169.3.162:46656} 50D4E2821096 out}"
NOTE[03-27|07:26:33] Dialed and added peer                    module=p2p address=83.169.3.162:46656 peer="Peer{MConn{83.169.3.162:46656} 50D4E2821096 out}"
NOTE[03-27|07:26:33] Connected to seed                        module=p2p peer="Peer{MConn{83.169.3.162:46656} 50D4E2821096 out}"
NOTE[03-27|07:26:33] IsCaughtUp: false                        module=blockchain height=481148 maxPeerHeight=643143
NOTE[03-27|07:26:34] New websocket connection                 module=rpcserver remote=127.0.0.1:50005
NOTE[03-27|07:26:34] IsCaughtUp: false                        module=blockchain height=481148 maxPeerHeight=643143
NOTE[03-27|07:26:36] IsCaughtUp: false                        module=blockchain height=481158 maxPeerHeight=643143
NOTE[03-27|07:26:40] IsCaughtUp: false                        module=blockchain height=481178 maxPeerHeight=643143
NOTE[03-27|07:26:43] IsCaughtUp: false                        module=blockchain height=481198 maxPeerHeight=643143
NOTE[03-27|07:26:45] IsCaughtUp: false                        module=blockchain height=481208 maxPeerHeight=643143
NOTE[03-27|07:26:50] IsCaughtUp: false                        module=blockchain height=481238 maxPeerHeight=643147
NOTE[03-27|07:26:53] IsCaughtUp: false                        module=blockchain height=481258 maxPeerHeight=643147
NOTE[03-27|07:26:55] IsCaughtUp: false                        module=blockchain height=481268 maxPeerHeight=643147
[...]
[...]
```
During this replay, the connection handshake with the seed could be seen in the seed's node log.

For the sake of testing, I stopped the node and app before catchup was finished. (Sidenote: I'm worried about how slow this catchup-replay was. 10b/s seems a bit weak. Unclear, if this is related to the ABCI app or not, requires more profiling)

Now, when trying another restart the catch-up never continues and there's also no handshake with the seed. 
```
NOTE[03-27|07:37:49] Loaded PrivValidator                     module=types file=./config/tendermint/priv_validator.json privValidator="PrivValidator{CB5A29D3D16A290280522BEBAD7B6FC9A1EF297F LH:481148, LR:1, LS:3}"
INFO[03-27|07:37:49] Starting multiAppConn                    module=proxy impl=multiAppConn
WARN[03-27|07:37:49] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abcicli
WARN[03-27|07:37:52] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abcicli
WARN[03-27|07:37:55] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abcicli
WARN[03-27|07:37:58] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abcicli
WARN[03-27|07:38:01] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abcicli
WARN[03-27|07:38:04] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abcicli
WARN[03-27|07:38:07] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abcicli
WARN[03-27|07:38:10] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abcicli
WARN[03-27|07:38:13] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abcicli
WARN[03-27|07:38:16] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abcicli
WARN[03-27|07:38:19] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abcicli
WARN[03-27|07:38:22] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abcicli
WARN[03-27|07:38:25] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abcicli
WARN[03-27|07:38:28] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abcicli
WARN[03-27|07:38:31] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abcicli
WARN[03-27|07:38:34] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abcicli
WARN[03-27|07:38:37] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abcicli
WARN[03-27|07:38:40] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abcicli
NOTE[03-27|07:38:43] ABCI Handshake                           module=consensus appHeight=481492 appHash=89F88E7C4EA56FCC51186E74C5926055536AE4BC
NOTE[03-27|07:38:43] ABCI Replay Blocks                       module=consensus appHeight=481492 storeHeight=481493 stateHeight=481492
INFO[03-27|07:38:43] Replay last block using real app         module=consensus
DBUG[03-27|07:38:43] addRound(round)                          module=consensus round=0
INFO[03-27|07:38:43] Starting EventSwitch                     module=events impl=EventSwitch
INFO[03-27|07:38:43] Starting ConsensusState                  module=consensus impl=ConsensusState
INFO[03-27|07:38:43] Starting WAL                             module=consensus impl=WAL
INFO[03-27|07:38:43] Starting TimeoutTicker                   module=consensus impl=TimeoutTicker
DBUG[03-27|07:38:43] Starting timeout routine                 module=consensus
WARN[03-27|07:38:44] Replay: wal.group.Search returned EOF    module=consensus height=481493
DBUG[03-27|07:38:44] Received tick                            module=consensus old_ti="{Duration:0s Height:0 Round:0 Step:RoundStepUnknown}" new_ti="{Duration:843.077502ms Height:481493 Round:0 Step:RoundStepNewHeight}"
DBUG[03-27|07:38:44] Timer already stopped                    module=consensus
DBUG[03-27|07:38:44] Scheduled timeout                        module=consensus dur=843.077502ms height=481493 round=0 step=RoundStepNewHeight
INFO[03-27|07:38:44] Timed out                                module=consensus dur=843.077502ms height=481493 round=0 step=RoundStepNewHeight
DBUG[03-27|07:38:44] Received tock                            module=consensus timeout=843.077502ms height=481493 round=0 step=RoundStepNewHeight
NOTE[03-27|07:38:44] enterNewRound(481493/0). Current: 481493/0/RoundStepNewHeight module=consensus
DBUG[03-27|07:38:44] addRound(round)                          module=consensus round=1
INFO[03-27|07:38:44] enterPropose(481493/0). Current: 481493/0/RoundStepNewRound module=consensus
DBUG[03-27|07:38:44] Received tick                            module=consensus old_ti="{Duration:843.077502ms Height:481493 Round:0 Step:RoundStepNewHeight}" new_ti="{Duration:3s Height:481493 Round:0 Step:RoundStepPropose}"
DBUG[03-27|07:38:44] Timer already stopped                    module=consensus
DBUG[03-27|07:38:44] Scheduled timeout                        module=consensus dur=3s height=481493 round=0 step=RoundStepPropose
INFO[03-27|07:38:47] Timed out                                module=consensus dur=3s height=481493 round=0 step=RoundStepPropose
DBUG[03-27|07:38:47] Received tock                            module=consensus timeout=3s height=481493 round=0 step=RoundStepPropose
INFO[03-27|07:38:47] enterPrevote(481493/0). Current: 481493/0/RoundStepPropose module=consensus
WARN[03-27|07:38:47] enterPrevote: ProposalBlock is nil       module=consensus
```

Apparently, the ABCI app saw the commits of the previous replay and thinks it's already at height 481493, which is true from the ABCI's point of view.
But the cs.wal disagrees - at least that's how interpret the log `WARN[03-27|07:51:31] Replay: wal.group.Search returned EOF    module=consensus height=481493` and priv_validator also still shows the old height 
```dev@gridchain-3(DO): [~]$ cat config/tendermint/priv_validator.json
{
	"address": "CB5A29D3D16A290280522BEBAD7B6FC9A1EF297F",
	"last_height": 481148,
	"last_round": 1,
	"last_signature": [
		1,
		"291339B33C0EB02842D683640DBFCE0D1A7C9FD61EE0D63BA02BFFFE71212FD0E60134AFF6AB75FDC8850324E9AFEE1CB1D0708437E8E89BE5207A1680752101"
	],
	"last_signbytes": "7B22636861696E5F6964223A22746573742D67726964636861696E222C22766F7465223A7B22626C6F636B5F6964223A7B7D2C22686569676874223A3438313134382C22726F756E64223A312C2274797065223A327D7D",
	"last_step": 3,
[...]
```

Looking at the cs.wal files, everthings starts to get more and more confusing to me:
cs.wal/wal:
```[...]
{"time":"2017-03-22T19:15:20.560Z","msg":[1,{"height":481148,"round":0,"step":"RoundStepNewHeight"}]}
{"time":"2017-03-22T19:15:20.819Z","msg":[2,{"msg":[20,{"Vote":{"validator_address":"4F93C03AC39F19378123F1EDD282FFF110B9C28C","validator_index":2,"height":481148,"round":1,"type":2,"block_id":{"hash":"2104096F72AB8DB6C252D6178F677B4026707144","parts":{"total":1,"hash":"9A06E4109FF1CA347277E70FAB503265414E852B"}},"signature":[1,"4409FF0C101AA50507E5DDA949DD256A1A2F93920CB6884D50910E46A678EB5C6184A99901CB37EB5E4B192EDAD94DBCBB02C30B62495733BEF077D6E7C52106"]}}],"peer_key":"50D4E28210961EC75076CB3C203D7EAFD87EA8791FE9D31322386D0951886214"}]}
{"time":"2017-03-22T19:15:20.820Z","msg":[2,{"msg":[20,{"Vote":{"validator_address":"152BA9D191890E3E111B735D50AE46EDAB707536","validator_index":0,"height":481148,"round":1,"type":2,"block_id":{"hash":"2104096F72AB8DB6C252D6178F677B4026707144","parts":{"total":1,"hash":"9A06E4109FF1CA347277E70FAB503265414E852B"}},"signature":[1,"7BCC2EA75D68E5E7613D6D829B895E1A1ECC247EA97E02A80C282CC08D0C9B21EE4991C6727DDC483390AB8AF86088351B2E0193BCBB6BE5C2B9F7DF88B5FC06"]}}],"peer_key":"50D4E28210961EC75076CB3C203D7EAFD87EA8791FE9D31322386D0951886214"}]}
{"time":"2017-03-22T19:15:20.821Z","msg":[2,{"msg":[20,{"Vote":{"validator_address":"3BD45B598029ECD2A6FFC7EA490B5B7B8FE700D7","validator_index":1,"height":481148,"round":1,"type":2,"block_id":{"hash":"2104096F72AB8DB6C252D6178F677B4026707144","parts":{"total":1,"hash":"9A06E4109FF1CA347277E70FAB503265414E852B"}},"signature":[1,"3B35580F9F4FE335EE7E0E1082A912B10FA583870FD0C929DEFD60AE6A69CADD477D7F05A82045320A78CE8467242E206F889A42D97FB17FD354808E5DEFDB0E"]}}],"peer_key":"50D4E28210961EC75076CB3C203D7EAFD87EA8791FE9D31322386D0951886214"}]}
{"time":"2017-03-22T19:15:20.822Z","msg":[1,{"height":481148,"round":1,"step":"RoundStepPropose"}]}
{"time":"2017-03-22T19:15:20.823Z","msg":[1,{"height":481148,"round":1,"step":"RoundStepPrecommit"}]}
{"time":"2017-03-22T19:15:20.823Z","msg":[1,{"height":481148,"round":1,"step":"RoundStepCommit"}]}
{"time":"2017-03-22T19:15:20.824Z","msg":[2,{"msg":[20,{"Vote":{"validator_address":"CB5A29D3D16A290280522BEBAD7B6FC9A1EF297F","validator_index":3,"height":481148,"round":1,"type":2,"block_id":{"hash":"","parts":{"total":0,"hash":""}},"signature":[1,"291339B33C0EB02842D683640DBFCE0D1A7C9FD61EE0D63BA02BFFFE71212FD0E60134AFF6AB75FDC8850324E9AFEE1CB1D0708437E8E89BE5207A1680752101"]}}],"peer_key":""}]}
{"time":"2017-03-22T19:15:24.323Z","msg":[3,{"duration":3500000000,"height":481148,"round":1,"step":3}]}
{"time":"2017-03-27T11:28:58.681Z","msg":[3,{"duration":803292456,"height":481493,"round":0,"step":1}]}
{"time":"2017-03-27T11:28:58.682Z","msg":[1,{"height":481493,"round":0,"step":"RoundStepPropose"}]}
{"time":"2017-03-27T11:29:01.683Z","msg":[3,{"duration":3000000000,"height":481493,"round":0,"step":3}]}
{"time":"2017-03-27T11:29:01.683Z","msg":[1,{"height":481493,"round":0,"step":"RoundStepPrevote"}]}
{"time":"2017-03-27T11:33:11.897Z","msg":[3,{"duration":900790632,"height":481493,"round":0,"step":1}]}
{"time":"2017-03-27T11:33:11.897Z","msg":[1,{"height":481493,"round":0,"step":"RoundStepPropose"}]}
{"time":"2017-03-27T11:33:14.897Z","msg":[3,{"duration":3000000000,"height":481493,"round":0,"step":3}]}
{"time":"2017-03-27T11:33:14.898Z","msg":[1,{"height":481493,"round":0,"step":"RoundStepPrevote"}]}
{"time":"2017-03-27T11:38:44.862Z","msg":[3,{"duration":843077502,"height":481493,"round":0,"step":1}]}
{"time":"2017-03-27T11:38:44.862Z","msg":[1,{"height":481493,"round":0,"step":"RoundStepPropose"}]}
{"time":"2017-03-27T11:38:47.863Z","msg":[3,{"duration":3000000000,"height":481493,"round":0,"step":3}]}
{"time":"2017-03-27T11:38:47.863Z","msg":[1,{"height":481493,"round":0,"step":"RoundStepPrevote"}]}
{"time":"2017-03-27T11:51:32.381Z","msg":[3,{"duration":806805209,"height":481493,"round":0,"step":1}]}
{"time":"2017-03-27T11:51:32.381Z","msg":[1,{"height":481493,"round":0,"step":"RoundStepPropose"}]}
{"time":"2017-03-27T11:51:35.382Z","msg":[3,{"duration":3000000000,"height":481493,"round":0,"step":3}]}
{"time":"2017-03-27T11:51:35.382Z","msg":[1,{"height":481493,"round":0,"step":"RoundStepPrevote"}]}
``` 
The last entries are from the restart tests, so replay updated to 481493 but last message was 481148
The last cs.wal/wal.412 file is even more strange to me:
last entries
```{"time":"2017-03-22T18:55:35.080Z","msg":[1,{"height":480367,"round":0,"step":"RoundStepPrevote"}]}
{"time":"2017-03-22T18:55:35.080Z","msg":[2,{"msg":[20,{"Vote":{"validator_address":"CB5A29D3D16A290280522BEBAD7B6FC9A1EF297F","validator_index":3,"height":480367,"round":0,"type":1,"block_id":{"hash":"F08876B4CFE007EBBD9C2EE6FF4659A7E46ACBDA","parts":{"total":1,"hash":"B72F3E3FF83A5F8A05E1BFB9CDE2E73D2E613689"}},"signature":[1,"C68ABFF93DB273D652FCBD2C981D479FB2119C469C3542B891376117DA9C617CBF8379257B32DE020C707DA84180A154A41CF462FE664C9EDF8FDE058D68A408"]}}],"peer_key":""}]}
{"time":"2017-03-22T18:55:35.082Z","msg":[2,{"msg":[20,{"Vote":{"validator_address":"4F93C03AC39F19378123F1EDD282FFF110B9C28C","validator_index":2,"height":480367,"round":0,"type":1,"block_id":{"hash":"F08876B4CFE007EBBD9C2EE6FF4659A7E46ACBDA","parts":{"total":1,"hash":"B72F3E3FF83A5F8A05E1BFB9CDE2E73D2E613689"}},"signature":[1,"0970A5316CAB6D93D28EADF3D7ABB56499A56D1C5867A36BE0F8CBA4EB54185D042E00E72089C6153D1218CA087E89D6F0E5A1EAEC44BAD5FB4A2D740136BA0D"]}}],"peer_key":"50D4E28210961EC75076CB3C203D7EAFD87EA8791FE9D31322386D0951886214"}]}
``` 
where we only see height 480367

**What you expected to happen**:
The catch-up works even when a previous replay was interrupted.

**How to reproduce it** (as minimally and precisely as possible):
No idea. Working on it.

**Anything else do we need to know**:
Ask :)

**Comment by srmo** [comment]
PS: maybe this is related to https://github.com/tendermint/tendermint/issues/248 https://github.com/tendermint/tendermint/issues/243 ?

**Comment by srmo** [comment]
Reproduced with the dumm -persist app
* 2 nodes on the same machine
* both nodes in fast-sync
* node 1 is validator
* node 2 is non-validator and has node 1 as seed
* start node 1 
* start dummy -persist against node 1
* start node 2
* start dummy -persist against node 2
** persist dir different from other dummy
* waited until node 2 was on ~100 blocks
* stopped dummy 2
* stopped node 2
* waited a long time until node 1 was at ~3k blocks
* started node 2
* started dummy 2
*== catch-up started
* interrupted dummy 2 after catching up to 152 blocks
* stopped node 2
* restarted node 2
* restarted dummy 2
*== stops
* stopped dummy 2
* stopped node 2
* node log from restart
```
NOTE[03-27|16:02:10] Loaded PrivValidator                     module=types file=/Users/smueller/.tendermint2/priv_validator.json privValidator="PrivValidator{F271FBDBD1505B525E434A091F8FA21DE5FEDC91 LH:0, LR:0, LS:0}"
WARN[03-27|16:02:10] abci.socketClient failed to connect to tcp://127.0.0.1:47658.  Retrying... module=abcicli
WARN[03-27|16:02:13] abci.socketClient failed to connect to tcp://127.0.0.1:47658.  Retrying... module=abcicli
NOTE[03-27|16:02:16] ABCI Handshake                           module=consensus appHeight=152 appHash=
NOTE[03-27|16:02:16] ABCI Replay Blocks                       module=consensus appHeight=152 storeHeight=153 stateHeight=152
WARN[03-27|16:02:16] Replay: wal.group.Search returned EOF    module=consensus height=153
NOTE[03-27|16:02:17] enterNewRound(153/0). Current: 153/0/RoundStepNewHeight module=consensus
WARN[03-27|16:02:20] enterPrevote: ProposalBlock is nil       module=consensus
WARN[03-27|16:03:20] Stopping abci.socketClient for error: EOF module=abcicli
WARN[03-27|16:03:20] Stopping abci.socketClient for error: EOF module=abcicli
WARN[03-27|16:03:20] Stopping abci.socketClient for error: EOF module=abcicli
```

* log restart from dummy 2 
```NOTE[03-27|16:02:15] Loaded state                             module=dummy block=152 root=
NOTE[03-27|16:02:15] Waiting for new connection...            module=abci-server
NOTE[03-27|16:02:16] Accepted a new connection                module=abci-server
NOTE[03-27|16:02:16] Waiting for new connection...            module=abci-server
NOTE[03-27|16:02:16] Accepted a new connection                module=abci-server
NOTE[03-27|16:02:16] Waiting for new connection...            module=abci-server
NOTE[03-27|16:02:16] Accepted a new connection                module=abci-server
NOTE[03-27|16:02:16] Waiting for new connection...            module=abci-server
``` 
[node1.tar.gz](https://github.com/tendermint/tendermint/files/872668/node1.tar.gz)
[node2.tar.gz](https://github.com/tendermint/tendermint/files/872669/node2.tar.gz)

**Comment by srmo** [comment]
PS: for what it's worth, here's the log output from node 1 when interrupting the first restart
```NOTE[03-27|16:02:01] Connected to seed                        module=p2p peer="Peer{MConn{127.0.0.1:46656} 8586E2BA48D1 out}"
NOTE[03-27|16:02:01] IsCaughtUp: false                        module=blockchain height=96 maxPeerHeight=3388
NOTE[03-27|16:02:02] IsCaughtUp: false                        module=blockchain height=113 maxPeerHeight=3388
WARN[03-27|16:02:02] Stopping abci.socketClient for error: EOF module=abcicli
WARN[03-27|16:02:02] Stopping abci.socketClient for error: EOF module=abcicli
WARN[03-27|16:02:02] Stopping abci.socketClient for error: EOF module=abcicli
WARN[03-27|16:02:02] Error in proxyAppConn.BeginBlock         module=state error=EOF
panic: Paniced questionably: Failed to process committed block (153:529B9D99836774F022AAB6B61669299CB813E558): Exec failed for application: EOF

goroutine 100 [running]:
panic(0x5a36c0, 0xc421426d30)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-common.PanicQ(0x5a36c0, 0xc421426d10)
	/Users/smueller/development/projects/tendermint/code/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-common/errors.go:44 +0xe0
github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine(0xc42029b130)
	/Users/smueller/development/projects/tendermint/code/src/github.com/tendermint/tendermint/blockchain/reactor.go:252 +0x1167
created by github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).OnStart
	/Users/smueller/development/projects/tendermint/code/src/github.com/tendermint/tendermint/blockchain/reactor.go:96 +0x71
``` 

Please note that no such error was seen in the scenario described initially

**Comment by srmo** [comment]
Did a new run with dummy -persist, as the initial test was based on a locally cahnged version of tendermint 0.9.0, which somehow lead to problems with p2p versioning and other people couldn't use the node data.
Here's the new experiment with a fresh 0.9.0 install
Setup and run are the same.
* node 2 was stopped at 76 blocks
* node 2 was restarted when node 1 was around 392 blocks
* node 2 started to catch-up
* node 2 catch-up was interrupted at height 128
* trying to bring node 2 up lead to the same error
```
NOTE[03-27|17:01:43] ABCI Handshake                           module=consensus appHeight=128 appHash=
NOTE[03-27|17:01:43] ABCI Replay Blocks                       module=consensus appHeight=128 storeHeight=129 stateHeight=128
WARN[03-27|17:01:43] Replay: wal.group.Search returned EOF    module=consensus height=129
NOTE[03-27|17:01:44] enterNewRound(129/0). Current: 129/0/RoundStepNewHeight module=consensus
WARN[03-27|17:01:47] enterPrevote: ProposalBlock is nil       module=consensus
WARN[03-27|17:02:25] Stopping abci.socketClient for error: EOF module=abcicli
WARN[03-27|17:02:25] Stopping abci.socketClient for error: EOF module=abcicli
WARN[03-27|17:02:25] Stopping abci.socketClient for error: EOF module=abcicli
```

[node1.tar.gz](https://github.com/tendermint/tendermint/files/872832/node1.tar.gz)
[node2.tar.gz](https://github.com/tendermint/tendermint/files/872831/node2.tar.gz)

**Comment by ebuchman** [comment]
Solved by https://github.com/tendermint/tendermint/pull/438
