### ISSUE TITLE
Make consensus/test_data deterministic

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#468]
The WAL test data should be generated in-process from a Go script, and ideally deterministically. Going in-process also let's us remove `block_part_size` from the config, where it never should have been in the first place - the only use for changing that parameter currently is testing the WAL on blocks with many parts.

**Comment by melekes** [comment]
Looks like this is not possible. I've tried to write a generator https://gist.github.com/melekes/262cb290c2b7a370f58d28b219c90d1a, but the problem is I can't use a node package inside because of circular imports

```
import cycle not allowed in test
package github.com/tendermint/tendermint/consensus (test)
        imports github.com/tendermint/tendermint/consensus/walgen
        imports github.com/tendermint/tendermint/node
        imports github.com/tendermint/tendermint/consensus
```

**Comment by ebuchman** [comment]
Oh, we can just copy the relevant parts of node.go. We don't need much, just set up state, start proxyAppConn, start ConsensusState.

**Comment by melekes** [comment]
OK, got it working

```
{"time":"2017-01-02T15:04:05Z","msg":{"height":0}}
ENDHEIGHT 0
{"time":"2017-01-02T15:04:05Z","msg":{"duration":9573975,"height":1,"round":0,"step":1}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":1,"round":0,"step":"RoundStepPropose"}}
{"time":"2017-01-02T15:04:05Z","msg":{"msg":{"Proposal":{"height":1,"round":0,"block_parts_header":{"total":1,"hash":"F19FD50CCED52C5C332D6F83583B82EE820D4CAB"},"pol_round":-1,"pol_block_id":{"hash":"","parts":{"total":0,"hash":""}},"signature":{"type":"ed25519","data":"5DD3388D37A19009AF2DEEC629F6256FF40355D21F09BCB144DDD45E15EE2B5E687579695D9673DF1E2D52780F664239849D5B65793CAFB8043F2E276F5F0501"}}},"peer_key":""}}
{"time":"2017-01-02T15:04:05Z","msg":{"msg":{"Height":1,"Round":0,"Part":{"index":0,"bytes":"0101010F74656E6465726D696E745F74657374000000000000000114FDD2918272B0C000000000000001147297262C6CD96190E46846C9A0DE1227E76077CF0001000100000000","proof":{"aunts":[]}}},"peer_key":""}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":1,"round":0,"step":"RoundStepPrevote"}}
{"time":"2017-01-02T15:04:05Z","msg":{"msg":{"Vote":{"validator_address":"D028C9981F7A87F3093672BF0D5B0E2A1B3ED456","validator_index":0,"height":1,"round":0,"type":1,"block_id":{"hash":"0087FB76C2C6B50F3ADA0D6DD8D59B856DA92384","parts":{"total":1,"hash":"F19FD50CCED52C5C332D6F83583B82EE820D4CAB"}},"signature":{"type":"ed25519","data":"278D13A44514222F1DC49B14428A8DD2158219CA6E8A2837CCC7C602721D25580792DDFBA04D0B10B73A057408C69294A14A670B0E86242EFD1B88370345290D"}}},"peer_key":""}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":1,"round":0,"step":"RoundStepPrecommit"}}
{"time":"2017-01-02T15:04:05Z","msg":{"msg":{"Vote":{"validator_address":"D028C9981F7A87F3093672BF0D5B0E2A1B3ED456","validator_index":0,"height":1,"round":0,"type":2,"block_id":{"hash":"0087FB76C2C6B50F3ADA0D6DD8D59B856DA92384","parts":{"total":1,"hash":"F19FD50CCED52C5C332D6F83583B82EE820D4CAB"}},"signature":{"type":"ed25519","data":"A347C890081306ACE7E230791A16AFD09923506F0C10D9615BDBD4CABF2DF2452E7E8BF5DFF97FBE70F212023ECE2B0A2AF8601292E04BDEEFA75801AF793A01"}}},"peer_key":""}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":1,"round":0,"step":"RoundStepCommit"}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":1}}
ENDHEIGHT 1
{"time":"2017-01-02T15:04:05Z","msg":{"height":2,"round":0,"step":"RoundStepNewHeight"}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":2,"round":0,"step":"RoundStepPropose"}}
{"time":"2017-01-02T15:04:05Z","msg":{"msg":{"Proposal":{"height":2,"round":0,"block_parts_header":{"total":1,"hash":"D7C25F538EC6C27E12B638FA6015BBC74BAC8C97"},"pol_round":-1,"pol_block_id":{"hash":"","parts":{"total":0,"hash":""}},"signature":{"type":"ed25519","data":"204FBFBE0C00AC344E572895BD81E62F9658346C86FB3A7520D209A2F0B28CAEAFD7E1F750094C931DDB97C210966030714E5D8E5E558FEA0B870F266DCB0E00"}}},"peer_key":""}}
{"time":"2017-01-02T15:04:05Z","msg":{"msg":{"Height":2,"Round":0,"Part":{"index":0,"bytes":"0101010F74656E6465726D696E745F74657374000000000000000214FDD291842D32000001140087FB76C2C6B50F3ADA0D6DD8D59B856DA9238401010114F19FD50CCED52C5C332D6F83583B82EE820D4CAB0114557F0E5A97AF531EFAB47DC13A8AAA97358059F70001147297262C6CD96190E46846C9A0DE1227E76077CF0001000101140087FB76C2C6B50F3ADA0D6DD8D59B856DA9238401010114F19FD50CCED52C5C332D6F83583B82EE820D4CAB0101010114D028C9981F7A87F3093672BF0D5B0E2A1B3ED456000000000000000001000201140087FB76C2C6B50F3ADA0D6DD8D59B856DA9238401010114F19FD50CCED52C5C332D6F83583B82EE820D4CAB01A347C890081306ACE7E230791A16AFD09923506F0C10D9615BDBD4CABF2DF2452E7E8BF5DFF97FBE70F212023ECE2B0A2AF8601292E04BDEEFA75801AF793A01","proof":{"aunts":[]}}},"peer_key":""}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":2,"round":0,"step":"RoundStepPrevote"}}
{"time":"2017-01-02T15:04:05Z","msg":{"msg":{"Vote":{"validator_address":"D028C9981F7A87F3093672BF0D5B0E2A1B3ED456","validator_index":0,"height":2,"round":0,"type":1,"block_id":{"hash":"337E9B1885405BA7565747455443112BE3F6D474","parts":{"total":1,"hash":"D7C25F538EC6C27E12B638FA6015BBC74BAC8C97"}},"signature":{"type":"ed25519","data":"3A8A7D6140E81209C0D875EDCED2C4C7F05CDF6863589E3E500008549C68A16C2DCEFF18260E88FEA869188F011D2585DB225E76232C0EB3B0E7A133AE497106"}}},"peer_key":""}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":2,"round":0,"step":"RoundStepPrecommit"}}
{"time":"2017-01-02T15:04:05Z","msg":{"msg":{"Vote":{"validator_address":"D028C9981F7A87F3093672BF0D5B0E2A1B3ED456","validator_index":0,"height":2,"round":0,"type":2,"block_id":{"hash":"337E9B1885405BA7565747455443112BE3F6D474","parts":{"total":1,"hash":"D7C25F538EC6C27E12B638FA6015BBC74BAC8C97"}},"signature":{"type":"ed25519","data":"CAF1C33DF110BD255618913E5C2F2A0D734B473878344878FB53B80CCBE4A0FD7C5E292AF59F709E6B09EBFE310D0560551B38C47007C1987C7CD831FE97B004"}}},"peer_key":""}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":2,"round":0,"step":"RoundStepCommit"}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":2}}
ENDHEIGHT 2
{"time":"2017-01-02T15:04:05Z","msg":{"height":3,"round":0,"step":"RoundStepNewHeight"}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":3,"round":0,"step":"RoundStepPropose"}}
{"time":"2017-01-02T15:04:05Z","msg":{"msg":{"Proposal":{"height":3,"round":0,"block_parts_header":{"total":1,"hash":"5752080CD6250C2E01CD24A68BC9C0F9F736C95A"},"pol_round":-1,"pol_block_id":{"hash":"","parts":{"total":0,"hash":""}},"signature":{"type":"ed25519","data":"7C5E1B4A8B9C904E893CC6A513E89BFECCCAE22389E6028605824DC15E35F88E2485045250BC798AD5E9DAD2C13EA9BB2531783CBB74424F28B2D4481A008200"}}},"peer_key":""}}
{"time":"2017-01-02T15:04:05Z","msg":{"msg":{"Height":3,"Round":0,"Part":{"index":0,"bytes":"0101010F74656E6465726D696E745F74657374000000000000000314FDD29185AAAA40000114337E9B1885405BA7565747455443112BE3F6D47401010114D7C25F538EC6C27E12B638FA6015BBC74BAC8C9701143BC2452ADF27AD7186621311904213C2D67AD3AE0001147297262C6CD96190E46846C9A0DE1227E76077CF000100010114337E9B1885405BA7565747455443112BE3F6D47401010114D7C25F538EC6C27E12B638FA6015BBC74BAC8C970101010114D028C9981F7A87F3093672BF0D5B0E2A1B3ED45600000000000000000200020114337E9B1885405BA7565747455443112BE3F6D47401010114D7C25F538EC6C27E12B638FA6015BBC74BAC8C9701CAF1C33DF110BD255618913E5C2F2A0D734B473878344878FB53B80CCBE4A0FD7C5E292AF59F709E6B09EBFE310D0560551B38C47007C1987C7CD831FE97B004","proof":{"aunts":[]}}},"peer_key":""}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":3,"round":0,"step":"RoundStepPrevote"}}
{"time":"2017-01-02T15:04:05Z","msg":{"msg":{"Vote":{"validator_address":"D028C9981F7A87F3093672BF0D5B0E2A1B3ED456","validator_index":0,"height":3,"round":0,"type":1,"block_id":{"hash":"5FE7EF6E9772660D91A65CD4EDBB31E8BAE7D8C0","parts":{"total":1,"hash":"5752080CD6250C2E01CD24A68BC9C0F9F736C95A"}},"signature":{"type":"ed25519","data":"5308006F27870C2D7219A2CE2AFA43B253E09260694D9D0A04034EC96A959E62052BFA07CDE21F1EFBA8BC2785AEC894944C0E0B55B49A0CF87CD20F15E5940A"}}},"peer_key":""}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":3,"round":0,"step":"RoundStepPrecommit"}}
{"time":"2017-01-02T15:04:05Z","msg":{"msg":{"Vote":{"validator_address":"D028C9981F7A87F3093672BF0D5B0E2A1B3ED456","validator_index":0,"height":3,"round":0,"type":2,"block_id":{"hash":"5FE7EF6E9772660D91A65CD4EDBB31E8BAE7D8C0","parts":{"total":1,"hash":"5752080CD6250C2E01CD24A68BC9C0F9F736C95A"}},"signature":{"type":"ed25519","data":"180D75E7E04154FB8C7A1EF92F14B6F25CB9100582172FB0B6283B8F501E124824C8637E6E0D67AD42AEB57D6358ED52F172B73AFBE7221E24FD321199C5D509"}}},"peer_key":""}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":3,"round":0,"step":"RoundStepCommit"}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":3}}
ENDHEIGHT 3
{"time":"2017-01-02T15:04:05Z","msg":{"height":4,"round":0,"step":"RoundStepNewHeight"}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":4,"round":0,"step":"RoundStepPropose"}}
{"time":"2017-01-02T15:04:05Z","msg":{"msg":{"Proposal":{"height":4,"round":0,"block_parts_header":{"total":1,"hash":"39C9FFC17158E7778D71124BC250255A237F858F"},"pol_round":-1,"pol_block_id":{"hash":"","parts":{"total":0,"hash":""}},"signature":{"type":"ed25519","data":"5BF9A85397B7B59710759003962B91434C930140ABEBE2685C79D58822429D551740B749BB7450E00EFDBB5AC393B66CA6A350511A0AE0E9B80534562DCA7906"}}},"peer_key":""}}
{"time":"2017-01-02T15:04:05Z","msg":{"msg":{"Height":4,"Round":0,"Part":{"index":0,"bytes":"0101010F74656E6465726D696E745F74657374000000000000000414FDD29186FA5BC00001145FE7EF6E9772660D91A65CD4EDBB31E8BAE7D8C0010101145752080CD6250C2E01CD24A68BC9C0F9F736C95A01143FFC77F0A7CB3304AD821E4973F9A4AFD612B2AA0001147297262C6CD96190E46846C9A0DE1227E76077CF0001000101145FE7EF6E9772660D91A65CD4EDBB31E8BAE7D8C0010101145752080CD6250C2E01CD24A68BC9C0F9F736C95A0101010114D028C9981F7A87F3093672BF0D5B0E2A1B3ED456000000000000000003000201145FE7EF6E9772660D91A65CD4EDBB31E8BAE7D8C0010101145752080CD6250C2E01CD24A68BC9C0F9F736C95A01180D75E7E04154FB8C7A1EF92F14B6F25CB9100582172FB0B6283B8F501E124824C8637E6E0D67AD42AEB57D6358ED52F172B73AFBE7221E24FD321199C5D509","proof":{"aunts":[]}}},"peer_key":""}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":4,"round":0,"step":"RoundStepPrevote"}}
{"time":"2017-01-02T15:04:05Z","msg":{"msg":{"Vote":{"validator_address":"D028C9981F7A87F3093672BF0D5B0E2A1B3ED456","validator_index":0,"height":4,"round":0,"type":1,"block_id":{"hash":"4FE189BA54B8B74E2EB75EBC17B0CBDC33C5B79A","parts":{"total":1,"hash":"39C9FFC17158E7778D71124BC250255A237F858F"}},"signature":{"type":"ed25519","data":"12308BA7F829CFED58D8590A5C9E786BF6827661019C12FBA091D67EC9F1F2679181CB9B214CC96ED33C82103871A79D02CBD71617CCE45A4A926C9C2F079106"}}},"peer_key":""}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":4,"round":0,"step":"RoundStepPrecommit"}}
{"time":"2017-01-02T15:04:05Z","msg":{"msg":{"Vote":{"validator_address":"D028C9981F7A87F3093672BF0D5B0E2A1B3ED456","validator_index":0,"height":4,"round":0,"type":2,"block_id":{"hash":"4FE189BA54B8B74E2EB75EBC17B0CBDC33C5B79A","parts":{"total":1,"hash":"39C9FFC17158E7778D71124BC250255A237F858F"}},"signature":{"type":"ed25519","data":"FAF93A0EDDED185BDA9C42289010F919AF3D65C9ABE1CC9471FD203056B5274E0F07DB9CB50764A15EB77736FBACD0764793E83409E4F98C4637C2F2888BCF05"}}},"peer_key":""}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":4,"round":0,"step":"RoundStepCommit"}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":4}}
ENDHEIGHT 4
{"time":"2017-01-02T15:04:05Z","msg":{"height":5,"round":0,"step":"RoundStepNewHeight"}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":5,"round":0,"step":"RoundStepPropose"}}
{"time":"2017-01-02T15:04:05Z","msg":{"msg":{"Proposal":{"height":5,"round":0,"block_parts_header":{"total":1,"hash":"98659ED07C6080957103B281C400E9231E414BB5"},"pol_round":-1,"pol_block_id":{"hash":"","parts":{"total":0,"hash":""}},"signature":{"type":"ed25519","data":"6CA1E49F6695349F57405C87C9F731E51C2CF81366F6EA92DF466C98247C37C3A84E7978BB93160D9431AC3A9970BB18B554F30F94A7AC01044073DD9E833D09"}}},"peer_key":""}}
{"time":"2017-01-02T15:04:05Z","msg":{"msg":{"Height":5,"Round":0,"Part":{"index":0,"bytes":"0101010F74656E6465726D696E745F74657374000000000000000514FDD29188594F800001144FE189BA54B8B74E2EB75EBC17B0CBDC33C5B79A0101011439C9FFC17158E7778D71124BC250255A237F858F011474B1B24F2434F021A18896BFF930FBFA3CC7B9D00001147297262C6CD96190E46846C9A0DE1227E76077CF0001000101144FE189BA54B8B74E2EB75EBC17B0CBDC33C5B79A0101011439C9FFC17158E7778D71124BC250255A237F858F0101010114D028C9981F7A87F3093672BF0D5B0E2A1B3ED456000000000000000004000201144FE189BA54B8B74E2EB75EBC17B0CBDC33C5B79A0101011439C9FFC17158E7778D71124BC250255A237F858F01FAF93A0EDDED185BDA9C42289010F919AF3D65C9ABE1CC9471FD203056B5274E0F07DB9CB50764A15EB77736FBACD0764793E83409E4F98C4637C2F2888BCF05","proof":{"aunts":[]}}},"peer_key":""}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":5,"round":0,"step":"RoundStepPrevote"}}
{"time":"2017-01-02T15:04:05Z","msg":{"msg":{"Vote":{"validator_address":"D028C9981F7A87F3093672BF0D5B0E2A1B3ED456","validator_index":0,"height":5,"round":0,"type":1,"block_id":{"hash":"FF93B12D957B34CBF980CDA128476807C04D98F4","parts":{"total":1,"hash":"98659ED07C6080957103B281C400E9231E414BB5"}},"signature":{"type":"ed25519","data":"011E422E359884EDA9637C85EB7023AD22AC442C8273FDC279C663751950713FA661F3C5AA627530620411833EC6AEC7FFE5ED5E66090B20191AE30FEFFD3E0E"}}},"peer_key":""}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":5,"round":0,"step":"RoundStepPrecommit"}}
{"time":"2017-01-02T15:04:05Z","msg":{"msg":{"Vote":{"validator_address":"D028C9981F7A87F3093672BF0D5B0E2A1B3ED456","validator_index":0,"height":5,"round":0,"type":2,"block_id":{"hash":"FF93B12D957B34CBF980CDA128476807C04D98F4","parts":{"total":1,"hash":"98659ED07C6080957103B281C400E9231E414BB5"}},"signature":{"type":"ed25519","data":"C7E2D32E29BCFD3166EF1878C08653097195E495554C52ED596C95919F2779753A0FF6AB04C58040C40344C8B6C3D016D70BE3734FEE1443CEBB230848D84000"}}},"peer_key":""}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":5,"round":0,"step":"RoundStepCommit"}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":5}}
ENDHEIGHT 5
{"time":"2017-01-02T15:04:05Z","msg":{"height":6,"round":0,"step":"RoundStepNewHeight"}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":6,"round":0,"step":"RoundStepPropose"}}
{"time":"2017-01-02T15:04:05Z","msg":{"msg":{"Proposal":{"height":6,"round":0,"block_parts_header":{"total":1,"hash":"1E6F1735B07CFC65B1DC8A38FA89ED2BB2F557E8"},"pol_round":-1,"pol_block_id":{"hash":"","parts":{"total":0,"hash":""}},"signature":{"type":"ed25519","data":"47F615FDF3927C0024614D5C7EC36C03FA75F9F8DBABEB8D2F4D8E153A932FEB2DB5F6FA36D86509231F0F4A4A236F4907BC5107BAD847A7CFD58C31A798DC04"}}},"peer_key":""}}
{"time":"2017-01-02T15:04:05Z","msg":{"msg":{"Height":6,"Round":0,"Part":{"index":0,"bytes":"0101010F74656E6465726D696E745F74657374000000000000000614FDD29189F54C40000114FF93B12D957B34CBF980CDA128476807C04D98F40101011498659ED07C6080957103B281C400E9231E414BB50114B8D4E0A962C6ED6F7168CEFEB02F43EF751B2D860001147297262C6CD96190E46846C9A0DE1227E76077CF000100010114FF93B12D957B34CBF980CDA128476807C04D98F40101011498659ED07C6080957103B281C400E9231E414BB50101010114D028C9981F7A87F3093672BF0D5B0E2A1B3ED45600000000000000000500020114FF93B12D957B34CBF980CDA128476807C04D98F40101011498659ED07C6080957103B281C400E9231E414BB501C7E2D32E29BCFD3166EF1878C08653097195E495554C52ED596C95919F2779753A0FF6AB04C58040C40344C8B6C3D016D70BE3734FEE1443CEBB230848D84000","proof":{"aunts":[]}}},"peer_key":""}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":6,"round":0,"step":"RoundStepPrevote"}}
{"time":"2017-01-02T15:04:05Z","msg":{"msg":{"Vote":{"validator_address":"D028C9981F7A87F3093672BF0D5B0E2A1B3ED456","validator_index":0,"height":6,"round":0,"type":1,"block_id":{"hash":"C310E4D2AD6382F011FACB5CB2ABEB3719AABBAE","parts":{"total":1,"hash":"1E6F1735B07CFC65B1DC8A38FA89ED2BB2F557E8"}},"signature":{"type":"ed25519","data":"E48C336B811FCF202C0D2BE1CD2B77E815CF6E57964A152F6D9DCB76A05FE7F23DE92633D4ABF9751EB18D22F7F626126E64A3FD8721E35CB85596AB3739C30C"}}},"peer_key":""}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":6,"round":0,"step":"RoundStepPrecommit"}}
{"time":"2017-01-02T15:04:05Z","msg":{"msg":{"Vote":{"validator_address":"D028C9981F7A87F3093672BF0D5B0E2A1B3ED456","validator_index":0,"height":6,"round":0,"type":2,"block_id":{"hash":"C310E4D2AD6382F011FACB5CB2ABEB3719AABBAE","parts":{"total":1,"hash":"1E6F1735B07CFC65B1DC8A38FA89ED2BB2F557E8"}},"signature":{"type":"ed25519","data":"1555AE2406DC27C1E9DC90E270A609EC3E97D5740D9730AB3C14651881F1F94FD8D0CB803165CA99B78C70AD0C056593013D94453C39C54D16E2D76E21578906"}}},"peer_key":""}}
{"time":"2017-01-02T15:04:05Z","msg":{"height":6,"round":0,"step":"RoundStepCommit"}}
```

**Comment by melekes** [comment]
but tests are failing with 

```
--- FAIL: TestHandshakeReplayAll (0.24s)
panic: Exec failed for application: Wrong Block.Header.AppHash.  Expected 7C2D453D301AD298FD45CCC559FF3D356F0875E1, got  [recovered]
        panic: Exec failed for application: Wrong Block.Header.AppHash.  Expected 7C2D453D301AD298FD45CCC559FF3D356F0875E1, got

goroutine 20 [running]:
testing.tRunner.func1(0xc4204641e0)
        /usr/local/go/src/testing/testing.go:711 +0x2d2
panic(0xa9a540, 0xc42019b2d0)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/tendermint/tendermint/consensus.applyBlock(0xc4209fc5a0, 0xc420b36760, 0x106ab60, 0xc4200ae100)
        /home/vagrant/go/src/github.com/tendermint/tendermint/consensus/replay_test.go:402 +0x15f
github.com/tendermint/tendermint/consensus.buildTMStateFromChain(0xc4201ac540, 0xc4209fc5a0, 0xc420aee400, 0x6, 0x8, 0x0, 0x0, 0x0, 0x0)
        /home/vagrant/go/src/github.com/tendermint/tendermint/consensus/replay_test.go:460 +0x417
github.com/tendermint/tendermint/consensus.testHandshakeReplay(0xc4204641e0, 0x0, 0x0)
        /home/vagrant/go/src/github.com/tendermint/tendermint/consensus/replay_test.go:355 +0x535
github.com/tendermint/tendermint/consensus.TestHandshakeReplayAll(0xc4204641e0)
        /home/vagrant/go/src/github.com/tendermint/tendermint/consensus/replay_test.go:283 +0x5d
testing.tRunner(0xc4204641e0, 0xcc83c8)
        /usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:789 +0x2de
exit status 2
```
