### ISSUE TITLE
state: TestValidateBlockEvidence times out

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4786]
https://circleci.com/gh/tendermint/tendermint/111765?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
coverage: 76.7% of statements
panic: test timed out after 5m0s

goroutine 146 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1460 +0x11c
created by time.goFunc
	/usr/local/go/src/time/sleep.go:168 +0x52

goroutine 1 [chan receive, 4 minutes]:
testing.(*T).Run(0xc000196c60, 0x11e875e, 0x19, 0x133c380, 0x1)
	/usr/local/go/src/testing/testing.go:1044 +0x699
testing.runTests.func1(0xc000196c60)
	/usr/local/go/src/testing/testing.go:1285 +0xa7
testing.tRunner(0xc000196c60, 0xc0004f1cc8)
	/usr/local/go/src/testing/testing.go:992 +0x1ec
testing.runTests(0xc000526a20, 0x1b60300, 0x1f, 0x1f, 0x0)
	/usr/local/go/src/testing/testing.go:1283 +0x528
testing.(*M).Run(0xc0004ae200, 0x0)
	/usr/local/go/src/testing/testing.go:1200 +0x300
github.com/tendermint/tendermint/state_test.TestMain(0xc0004ae200)
	/go/src/github.com/tendermint/tendermint/state/main_test.go:12 +0x5a
main.main()
	_testmain.go:170 +0x334

goroutine 119 [runnable]:
github.com/tendermint/tendermint/evidence/mock.(*EvidencePool).IsCommitted(0xc00046f3e0, 0x14a1ce0, 0xc0013be080, 0x0)
	/go/src/github.com/tendermint/tendermint/evidence/mock/pool_mock.go:80 +0xaa
github.com/tendermint/tendermint/state.validateBlock(0x149a340, 0xc00046f3e0, 0x14a4d60, 0xc00000f8e0, 0xa, 0x0, 0x11d8fef, 0x6, 0x11e09d7, 0xf, ...)
	/go/src/github.com/tendermint/tendermint/state/validation.go:136 +0x11f3
github.com/tendermint/tendermint/state.(*BlockExecutor).ValidateBlock(0xc00011cb60, 0xa, 0x0, 0x11d8fef, 0x6, 0x11e09d7, 0xf, 0x8, 0xc001a45be0, 0x20, ...)
	/go/src/github.com/tendermint/tendermint/state/execution.go:117 +0x125
github.com/tendermint/tendermint/state_test.makeAndApplyGoodBlock(0xa, 0x0, 0x11d8fef, 0x6, 0x11e09d7, 0xf, 0x8, 0xc001a45be0, 0x20, 0x20, ...)
	/go/src/github.com/tendermint/tendermint/state/helpers_test.go:56 +0x1d0
github.com/tendermint/tendermint/state_test.makeAndCommitGoodBlock(0xa, 0x0, 0x11d8fef, 0x6, 0x11e09d7, 0xf, 0x8, 0xc001a45be0, 0x20, 0x20, ...)
	/go/src/github.com/tendermint/tendermint/state/helpers_test.go:40 +0x17f
github.com/tendermint/tendermint/state_test.TestValidateBlockEvidence(0xc0004b1200)
	/go/src/github.com/tendermint/tendermint/state/validation_test.go:247 +0x955
testing.tRunner(0xc0004b1200, 0x133c380)
	/usr/local/go/src/testing/testing.go:992 +0x1ec
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1043 +0x661
FAIL	github.com/tendermint/tendermint/state	300.834s
```

**Comment by melekes** [comment]
The test failed in https://github.com/tendermint/tendermint/pull/4764, but I am pretty confident it's not related to the changes.
