### ISSUE TITLE
Consensus runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by denight** [tendermint/tendermint#4987]
I am trying to use an app based on the cosmos-sdk in windows and encountered an error

**Tendermint version**:

tendermint: 0.33.3
abci: 0.16.1
blockprotocol: 10
p2pprotocol: 7

**ABCI app**:

The generated application by scaffold tool "scaffold.exe app lvl-1". 
The scaffold was built from commit 8ef28f6f2163841cd5767876604d5b15be7ccc8f.

**Environment**:
- Windows Server 2012R2:
- go version go1.14.3 windows/amd64:

**What happened**:

The runtime error: invalid memory address or nil pointer dereference

And unable to start node again.

**What you expected to happen**:

At least able to start.

**Have you tried the latest version**: yes

**Logs**:

```
E[2020-06-09|03:50:57.066] CONSENSUS FAILURE!!!                         module=consensus err="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 7 [running]:
runtime/debug.Stack(0xc003edeb70, 0x10ae100, 0x1df6bf0)
	C:/tools/go/src/runtime/debug/stack.go:24 +0xa4
github.com/tendermint /tendermint/consensus.(*State).receiveRoutine.func2(0xc001317180, 0x1399c58)
	d:/golang/pkg/mod/github.com/tendermint/tendermint@v0.33.3/consensus/state.go:613 +0x5e
panic(0x10ae100, 0x1df6bf0)
	C:/tools/go/src/runtime/panic.go:969 +0x174
github.com/tendermint/tendermint/consensus.(*State).recordMetrics(0xc001317180, 0x6f94, 0xc000614c40)
	d:/golang/pkg/mod/github.com/tendermint/tendermint@v0.33.3/consensus/state.go:1522 +0x7d2
github.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc001317180, 0x6f94)
	d:/golang/pkg/mod/github.com/tendermint/tendermint@v0.33.3/consensus/state.go:1447 +0xb14
github.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc001317180, 0x6f94)
	d:/golang/pkg/mod/github.com/tendermint/tendermint@v0.33.3/consensus/state.go:1350 +0x38a
github.com/tendermint/tendermint/consensus.(*State).enterCommit.func1(0xc001317180, 0x0, 0x6f94)
	d:/golang/pkg/mod/github.com/tendermint/tendermint@v0.33.3/consensus/state.go:1285 +0x97
github.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc001317180, 0x6f94, 0x0)
	d:/golang/pkg/mod/github.com/tendermint/tendermint@v0.33.3/consensus/state.go:1322 +0x625
github.com/tendermint/tendermint/consensus.(*State).addVote(0xc001317180, 0xc002492460, 0xc000d1eae0, 0x28, 0x1045100, 0xc001309e08, 0x139af90)
	d:/golang/pkg/mod/github.com/tendermint/tendermint@v0.33.3/consensus/state.go:1822 +0xa40
github.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc001317180, 0xc002492460, 0xc000d1eae0, 0x28, 0xc000503400, 0xc003ec6000, 0x30)
	d:/golang/pkg/mod/github.com/tendermint/tendermint@v0.33.3/consensus/state.go:1642 +0x60
github.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc001317180, 0x155aa40, 0xc0000ca278, 0xc000d1eae0, 0x28)
	d:/golang/pkg/mod/github.com/tendermint/tendermint@v0.33.3/consensus/state.go:709 +0x52c
github.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc001317180, 0x0)
	d:/golang/pkg/mod/github.com/tendermint/tendermint@v0.33.3/consensus/state.go:644 +0x710
created by github.com/tendermint/tendermint/consensus.(*State).OnStart
	d:/golang/pkg/mod/github.com/tendermint/tendermint@v0.33.3/consensus/state.go:335 +0x141
```
Restarting the node does not work.
```
I[2020-06-09|10:00:49.862] starting ABCI with Tendermint                module=main
panic: StateBlockHeight (28564) > StoreBlockHeight (28561)

goroutine 1 [running]:
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc0000ef0f0, 0xa, 0x0, 0xc0010213a0, 0x6, 0xc000c07380, 0x11, 0x6f94, 0xc000c073a0, 0x20, ...)
        d:/golang/pkg/mod/github.com/tendermint/tendermint@v0.33.3/consensus/replay.go:356 +0x167f
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0000ef0f0, 0x158eb20, 0xc0001b2300, 0x80, 0x1086fc0)
        d:/golang/pkg/mod/github.com/tendermint/tendermint@v0.33.3/consensus/replay.go:269 +0x48c
github.com/tendermint/tendermint/node.doHandshake(0x158e0a0, 0xc000148400, 0xa, 0x0, 0xc0010213a0, 0x6, 0xc000c07380, 0x11, 0x6f94, 0xc000c073a0, ...)
        d:/golang/pkg/mod/github.com/tendermint/tendermint@v0.33.3/node/node.go:281 +0x1a1
github.com/tendermint/tendermint/node.NewNode(0xc0003bb900, 0x1574f40, 0xc000e925a0, 0xc0000c1710, 0x155abc0, 0xc000c35c00, 0xc0000c1b60, 0x1399d40, 0xc0000c1b70, 0x157aac0, ...)
        d:/golang/pkg/mod/github.com/tendermint/tendermint@v0.33.3/node/node.go:602 +0x34a
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000e746a0, 0x139a5e8, 0x1d, 0x0, 0x0)
        d:/golang/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.4/server/start.go:157 +0x4c8
github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc000e8d080, 0x1e42c08, 0x0, 0x0, 0x0, 0x0)
        d:/golang/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.4/server/start.go:67 +0xbb
github.com/spf13/cobra.(*Command).execute(0xc000e8d080, 0x1e42c08, 0x0, 0x0, 0xc000e8d080, 0x1e42c08)
        d:/golang/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x45a
github.com/spf13/cobra.(*Command).ExecuteC(0xc000e7c000, 0x1233a54, 0xc000539ed0, 0x5712f9)
        d:/golang/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        d:/golang/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000e7c000, 0x139a9e0, 0x1216e17, 0x10)
        d:/golang/pkg/mod/github.com/tendermint/tendermint@v0.33.3/libs/cli/setup.go:89 +0x43
```

**Config (you can paste only the changes you've made)**:

I use the default config. The network consists of 2 validator nodes with 50% votes power.

**node command runtime flags**:

Nothing special.

**Comment by marbar3778** [comment]
What version of the cosmos-sdk is being used?

**Comment by denight** [comment]
v0.38.4

**Comment by denight** [comment]
@melekes thank you. I tried but got build errors.

```
github.com/cosmos/cosmos-sdk@v0.38.4/client/context/context.go:68:15:  undefined: "github.com/tendermint/tendermint/rpc/client".NewHTTP
github.com/cosmos/cosmos-sdk@v0.38.4/client/context/context.go:160:17: undefined: "github.com/tendermint/tendermint/rpc/client".NewHTTP
github.com/cosmos/cosmos-sdk@v0.38.4/client/context/verifier.go:46:17: undefined: "github.com/tendermint/tendermint/rpc/client".NewHTTP
```
But it is OK for me. I will upgrade the tendermint when the cosmos-sdk allows it. I just want to ensure you know about this issue.
