### ISSUE TITLE
light: query panics

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#5369]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): master

**ABCI app** (name for built-in, URL for self-written if it's publicly available): cosmos-sdk/gaia v3

**Environment**:
- **OS** (e.g. from /etc/os-release): Mac
- **Install tools**:
- **Others**:

**What happened**: When trying to query through the light client it panics, but while querying through the rpc everything works fine.

for example when i run:
```
gaiad query bank balances cosmos18v2cnwafyeqtp6y0w3vc4dvp7z3sfp22h7a9fj --node tcp://ec2-18-189-1-7.us-east-2.compute.amazonaws.com:26657
balances:
- amount: "10000000"
  denom: umuon
pagination:
  next_key: null
  total: "0"
```
it works fine but when using the light client:
```
gaiad query bank balances cosmos18v2cnwafyeqtp6y0w3vc4dvp7z3sfp22h7a9fj --node tcp://127.0.0.1:8888
Error: RPC error -32603 - Internal error: runtime error: index out of range [3] with length 3
```

**What you expected to happen**:
I expected to be able to query through the light client the same way I would with the RPC.

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
run a tendermint light client:
```
tendermint light stargate-2 -p http://ec2-18-189-1-7.us-east-2.compute.amazonaws.com:26657 -w http://ec2-18-188-71-91.us-east-2.compute.amazonaws.com:26657 --height 50000 --hash BAAA6D982956CE70FCFBCD5273DDBA27F25F5311A5339FC396DAEC4FB89AAF75
```

install gaia v3.0
```
git clone https://github.com/cosmos/gaia.git

cd gaia

git checkout stargate-2

make install
```

try to query through light client:

```
gaiad query bank balances cosmos18v2cnwafyeqtp6y0w3vc4dvp7z3sfp22h7a9fj --node tcp://127.0.0.1:8888
```

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

```
E[2020-09-17|10:43:58.628] Panic in RPC HTTP handler                    err="runtime error: index out
 of range [3] with length 3" stack="goroutine 97 [running]:\nruntime/debug.Stack(0x1bae520, 0x1c580c0, 
0xc000038c60)\n\truntime/debug/stack.go:24 +0x9f\ngithub.com/tendermint/tendermint/rpc/jsonrpc
/server.RecoverAndLogHandler.func1.2(0xc000090220, 0x1e50000, 0xc000215aa0, 0xbfd0e653a5702ec8, 
0x1c6b710dcd, 0x24bd9c0, 0xc000596b00)\n\tgithub.com/tendermint/tendermint/rpc/jsonrpc/server
/http_server.go:185 +0x175\npanic(0x1c580c0, 0xc000038c60)\n\truntime/panic.go:969 
+0x175\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.mapParamsToArgs(0xc0000c0af0, 0xc000272420, 
0x1, 0x1b2b2e0, 0xc000188258, 0x0, 0x0, 0xc0000da4d0)\n\tgithub.com/tendermint/tendermint/rpc/jsonrpc
/server/http_json_handler.go:138 +0x3a6\ngithub.com/tendermint/tendermint/rpc/jsonrpc
/server.jsonParamsToArgs(0xc0000c0af0, 0xc000196400, 0x7e, 0x80, 0xc000244250, 0x1, 0x0, 0x0, 0x0)\n
\tgithub.com/tendermint/tendermint/rpc/jsonrpc/server/http_json_handler.go:193 
+0x225\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.makeJSONRPCHandler.func1(0x1e4be80, 
0xc000090220, 0xc000596b00)\n\tgithub.com/tendermint/tendermint/rpc/jsonrpc/server
/http_json_handler.go:92 +0xf5b\ngithub.com/tendermint/tendermint/rpc/jsonrpc
/server.handleInvalidJSONRPCPaths.func1(0x1e4be80, 0xc000090220, 0xc000596b00)\n\tgithub.com/tendermint
/tendermint/rpc/jsonrpc/server/http_json_handler.go:126 
+0x9c\nnet/http.HandlerFunc.ServeHTTP(0xc00008eb10, 0x1e4be80, 0xc000090220, 0xc000596b00)\n\tnet/http
/server.go:2042 +0x44\nnet/http.(*ServeMux).ServeHTTP(0xc00008c100, 0x1e4be80, 0xc000090220, 
0xc000596b00)\n\tnet/http/server.go:2417 +0x1ad\ngithub.com/tendermint/tendermint/rpc/jsonrpc
/server.maxBytesHandler.ServeHTTP(0x1e323c0, 0xc00008c100, 0xf4240, 0x1e4be80, 0xc000090220, 
0xc000596b00)\n\tgithub.com/tendermint/tendermint/rpc/jsonrpc/server/http_server.go:234 
+0xd4\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1(0x1e4c6c0, 
0xc0001562a0, 0xc000596b00)\n\tgithub.com/tendermint/tendermint/rpc/jsonrpc/server/http_server.go:207 
+0x39a\nnet/http.HandlerFunc.ServeHTTP(0xc0002738c0, 0x1e4c6c0, 0xc0001562a0, 0xc000596b00)\n\tnet/http
/server.go:2042 +0x44\nnet/http.serverHandler.ServeHTTP(0xc000156460, 0x1e4c6c0, 0xc0001562a0, 
0xc000596b00)\n\tnet/http/server.go:2843 +0xa3\nnet/http.(*conn).serve(0xc0005b75e0, 0x1e4fc80, 
0xc00018e080)\n\tnet/http/server.go:1925 +0x8ad\ncreated by net/http.(*Server).Serve\n\tnet/http
/server.go:2969 +0x36c\n"
```

**Config (you can paste only the changes you've made)**: all default params

**node command runtime flags**: none

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by marbar3778** [comment]
overlap/duplicate of #5106
