### ISSUE TITLE
Tendermint crashes when no internet

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/tendermint#537]
Moved this from: https://github.com/tendermint/go-p2p/issues/14 and https://github.com/tendermint/basecoin/issues/103

Since this is not a basecoin problem, but rather go-p2p, which is now merged in tendermint.

```
I[06-08|09:10:56.734] Applying block                               module=consensus height=655
I[06-08|09:10:56.734] Applying block                               module=consensus height=656
I[06-08|09:10:56.735] Completed ABCI Handshake - Tendermint and App are synced module=consensus appHeight=0 appHash=
I[06-08|09:10:56.741] Starting EventSwitch                         module=types impl=EventSwitch
I[06-08|09:10:56.741] This node is a validator                     module=consensus 
I[06-08|09:10:56.748] Starting Node                                module=node impl=Node
I[06-08|09:10:56.749] Local listener                               module=p2p ip=:: port=46656
I[06-08|09:10:56.749] Getting UPNP external address                module=p2p
I[06-08|09:10:59.750] Could not perform UPNP discover              module=p2p error="write udp4 0.0.0.0:62196->239.255.255.250:1900: i/o timeout"
panic: Panicked on a Crisis: Could not determine external address!

goroutine 1 [running]:
github.com/tendermint/tmlibs/common.PanicCrisis(0x16ea940, 0xc4216ee3d0)
	/Users/garie/gocode/src/github.com/tendermint/tmlibs/common/errors.go:33 +0xdd
github.com/tendermint/tendermint/p2p.NewDefaultListener(0xc4204b0040, 0x3, 0xc4204b0046, 0xd, 0x1c89000, 0x1c89040, 0xc4207a45a0, 0xd, 0x17f65dc)
	/Users/garie/gocode/src/github.com/tendermint/tendermint/p2p/listener.go:93 +0x72f
github.com/tendermint/tendermint/node.(*Node).OnStart(0xc420442360, 0xc4216ee030, 0xd)
	/Users/garie/gocode/src/github.com/tendermint/tendermint/node/node.go:237 +0x1f5
github.com/tendermint/tmlibs/common.(*BaseService).Start(0xc420442360, 0xc42046c820, 0x1c7f740, 0xc4204b9040)
	/Users/garie/gocode/src/github.com/tendermint/tmlibs/common/service.go:105 +0x482
github.com/tendermint/basecoin/cmd/commands.startTendermint(0xc42012cc00, 0x16, 0xc420468f60, 0xc4204b8640, 0x2)
	/Users/garie/gocode/src/github.com/tendermint/basecoin/cmd/commands/start.go:154 +0x356
github.com/tendermint/basecoin/cmd/commands.startCmd(0x1ccc840, 0x1cf3b68, 0x0, 0x0, 0x0, 0x0)
	/Users/garie/gocode/src/github.com/tendermint/basecoin/cmd/commands/start.go:104 +0xc56
github.com/spf13/cobra.(*Command).execute(0x1ccc840, 0x1cf3b68, 0x0, 0x0, 0x1ccc840, 0x1cf3b68)
	/Users/garie/gocode/src/github.com/spf13/cobra/command.go:647 +0x3f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc42007c6c0, 0x2, 0x2, 0xc42012cca0)
	/Users/garie/gocode/src/github.com/spf13/cobra/command.go:726 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc42007c6c0, 0xc420460310, 0x16)
	/Users/garie/gocode/src/github.com/spf13/cobra/command.go:685 +0x2b
github.com/tendermint/tmlibs/cli.Executor.Execute(0xc42007c6c0, 0x17f5a0b, 0x2)
	/Users/garie/gocode/src/github.com/tendermint/tmlibs/cli/setup.go:92 +0x4e
main.main()
	/Users/garie/gocode/src/github.com/tendermint/basecoin/cmd/basecoin/main.go:33 +0x1c3
```

**Comment by melekes** [comment]
Can we continue if UPnP probe fails? I guess not since we are panicking. Just want to make sure. @ebuchman 

If we can't, should we `--skip-upnp` in all demos?

**Comment by adrianbrink** [comment]
What about falling back to no UPnP if the probe fails? Even though that could introduce some magic.

**Comment by ebuchman** [comment]
We should be able to run just fine without internet. We should make this work. I've done it locally a zillion times eg. when I'm trying to do dev on an airplane ...

**Comment by ethanfrey** [comment]
@ebuchman "we should be able to" is apparently no longer the case.  I tried `--p2p.skip_upnp` and it still paniced....

And I want to code on the plane in a few days....

**Comment by ethanfrey** [comment]
`p2p/listener.go`:

```
	// Determine external address...
	var extAddr *NetAddress
	if !skipUPNP {
		// If the lAddrIP is INADDR_ANY, try UPnP
		if lAddrIP == "" || lAddrIP == "0.0.0.0" {
			extAddr = getUPNPExternalAddress(lAddrPort, listenerPort, logger)
		}
	}
	// Otherwise just use the local address...
	if extAddr == nil {
		extAddr = getNaiveExternalAddress(listenerPort)
	}
	if extAddr == nil {
		cmn.PanicCrisis("Could not determine external address!")
	}
```

```
func getNaiveExternalAddress(port int) *NetAddress {
	addrs, err := net.InterfaceAddrs()
	if err != nil {
		cmn.PanicCrisis(cmn.Fmt("Could not fetch interface addresses: %v", err))
	}

	for _, a := range addrs {
		ipnet, ok := a.(*net.IPNet)
		if !ok {
			continue
		}
		v4 := ipnet.IP.To4()
		if v4 == nil || v4[0] == 127 {
			continue
		} // loopback
		return NewNetAddressIPPort(ipnet.IP, uint16(port))
	}
	return nil
}
```

This totally can return nil if I have no addresses,

**Comment by ebuchman** [comment]
We should be able to as in we should modify the code to enable this. I've made the change locally many times so as to be able to code on flights. We should add it for next release.

**Comment by ethanfrey** [comment]
Can you make a small branch for this in the next few days?  It would help my development efforts.

**Comment by zramsay** [comment]
started in #665

**Comment by ebuchman** [comment]
lets have a config option that allows this

**Comment by ebuchman** [comment]
merged https://github.com/tendermint/tendermint/pull/665
