### ISSUE TITLE
blockchain/v2: duplicate block enqueued by processor

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#5513]
I've been seeing a bunch of these in E2E testnets:

```
panic: duplicate block enqueued by processor

goroutine 91 [running]:
github.com/tendermint/tendermint/blockchain/v2.(*pcState).enqueue(...)
	github.com/tendermint/tendermint/blockchain/v2/processor.go:91
github.com/tendermint/tendermint/blockchain/v2.(*pcState).handle(0xc000cd11d0, 0x141fcc0, 0xc001310b60, 0x1167b60, 0x1207580, 0xf36c00, 0x141fcc0)
	github.com/tendermint/tendermint/blockchain/v2/processor.go:135 +0xd1b
github.com/tendermint/tendermint/blockchain/v2.(*Routine).start(0xc000cce900)
	github.com/tendermint/tendermint/blockchain/v2/routine.go:78 +0x2ed
created by github.com/tendermint/tendermint/blockchain/v2.(*BlockchainReactor).startSync
	github.com/tendermint/tendermint/blockchain/v2/reactor.go:152 +0x12e
```

**Comment by melekes** [comment]
```
panic: duplicate block 1009 (89F3F6EC155D7BA38273E4A752CDF4F46A889F2432EEA4974BD8D8CBC04AB739) enqueued by processor (sent by 0a9c99096b50a6d72a24d5aa5286d3f7022b3555; existing block 89F3F6EC155D7BA38273E4A752CDF4F46A889F2432EEA4974BD8D8CBC04AB739 from eceaaa618fa5c1d5e48e2bd75269e217147ab445) [recovered]

last events:
{priorityNormal:{}}
{priorityNormal:{}}
{priorityNormal:{}}
{priorityNormal:{}}
{priorityNormal:{}}
{priorityNormal:{}}
{priorityNormal:{}}
{priorityNormal:{}}
{priorityNormal:{}}
{priorityNormal:{}}
```

looks like we're getting the same block from another peer

**Comment by melekes** [comment]
```
requesting 1000 from 0a9c99096b50a6d72a24d5aa5286d3f7022b3555
requesting 1001 from 0a9c99096b50a6d72a24d5aa5286d3f7022b3555
requesting 1002 from 94004332dbb949682a1331c240d6a5932ed94738
requesting 1003 from a54399b792ec166437131d2a9801a67a959dd0f7
requesting 1004 from 94004332dbb949682a1331c240d6a5932ed94738
requesting 1005 from a54399b792ec166437131d2a9801a67a959dd0f7
requesting 1006 from 0a9c99096b50a6d72a24d5aa5286d3f7022b3555
requesting 1007 from 94004332dbb949682a1331c240d6a5932ed94738
requesting 1008 from a54399b792ec166437131d2a9801a67a959dd0f7
requesting 1009 from eceaaa618fa5c1d5e48e2bd75269e217147ab445
received 1002 from 94004332dbb949682a1331c240d6a5932ed94738
received 1009 from eceaaa618fa5c1d5e48e2bd75269e217147ab445
received 1004 from 94004332dbb949682a1331c240d6a5932ed94738
received 1007 from 94004332dbb949682a1331c240d6a5932ed94738
received 1003 from a54399b792ec166437131d2a9801a67a959dd0f7
requesting 1000 from 94004332dbb949682a1331c240d6a5932ed94738
requesting 1001 from 94004332dbb949682a1331c240d6a5932ed94738
requesting 1006 from 94004332dbb949682a1331c240d6a5932ed94738
```

we're requesting same blocks from two peers

**Comment by erikgrinaker** [comment]
Still seeing occasional E2E panics caused by this:

```
full01         | panic: duplicate block 1009 (C986A578465D2FDA3BEF840BC089D4ADFB1C52D62DBA2FE7EA9A873DBA5AC544) enqueued by processor (sent by 0a9c99096b50a6d72a24d5aa5286d3f7022b3555; existing block C986A578465D2FDA3BEF840BC089D4ADFB1C52D62DBA2FE7EA9A873DBA5AC544 from eceaaa618fa5c1d5e48e2bd75269e217147ab445) [recovered]
full01         | 	panic: duplicate block 1009 (C986A578465D2FDA3BEF840BC089D4ADFB1C52D62DBA2FE7EA9A873DBA5AC544) enqueued by processor (sent by 0a9c99096b50a6d72a24d5aa5286d3f7022b3555; existing block C986A578465D2FDA3BEF840BC089D4ADFB1C52D62DBA2FE7EA9A873DBA5AC544 from eceaaa618fa5c1d5e48e2bd75269e217147ab445)
full01         | last events:
full01         | 0: scBlockReceived{1004#78114B5C1CB0A55367011C2EEB60DF7163116374C2629B044324594297CC93A6 from a54399b792ec166437131d2a9801a67a959dd0f7}
full01         | 1: scBlockReceived{1007#E13CA4A7A022D74B36CE296322F3AF73A82B1E6CCFC17587EA50DC9F2C943749 from 0a9c99096b50a6d72a24d5aa5286d3f7022b3555}
full01         | 2: scBlockReceived{1001#A088DB5A4463A34D735505C6E9C9B8E995114FE56D402316C0ABF8BDF33C8053 from 0a9c99096b50a6d72a24d5aa5286d3f7022b3555}
full01         | 3: scPeerError{94004332dbb949682a1331c240d6a5932ed94738 errored with peer was stopped}
full01         | 4: scPeerError{8773a83e2f9fa4bc7a3e94303eb4df33af294288 errored with cannot set peer height for a peer in peerStateRemoved}
full01         | 5: scBlockReceived{1009#C986A578465D2FDA3BEF840BC089D4ADFB1C52D62DBA2FE7EA9A873DBA5AC544 from eceaaa618fa5c1d5e48e2bd75269e217147ab445}
full01         | 6: scBlockReceived{1008#C81EA722AB52EAAD355D1E528AA982C6DE20401E7FEE2A21F4E0520EE45FCC0F from a54399b792ec166437131d2a9801a67a959dd0f7}
full01         | 7: scBlockReceived{1007#E13CA4A7A022D74B36CE296322F3AF73A82B1E6CCFC17587EA50DC9F2C943749 from 94004332dbb949682a1331c240d6a5932ed94738}
full01         | 8: scBlockReceived{1006#1631EDE8FB5BAE315EB8DE292E5814B364AD6F26E06D426AEB674F786D47C938 from 0a9c99096b50a6d72a24d5aa5286d3f7022b3555}
full01         | 9: scBlockReceived{1005#084C6B42431A8FB3D8B0825BE7339C1889FD7D0D004BEA0E12FD94E3AE61C3AC from a54399b792ec166437131d2a9801a67a959dd0f7}
full01         | 10: scBlockReceived{1002#0BFDFCBF04F9FBBD6C0349B50EB39F07D7012B4F83B57541B6297026C68BFA22 from a54399b792ec166437131d2a9801a67a959dd0f7}
full01         | 11: scBlockReceived{1004#78114B5C1CB0A55367011C2EEB60DF7163116374C2629B044324594297CC93A6 from 94004332dbb949682a1331c240d6a5932ed94738}
full01         | 12: scBlockReceived{1001#A088DB5A4463A34D735505C6E9C9B8E995114FE56D402316C0ABF8BDF33C8053 from 94004332dbb949682a1331c240d6a5932ed94738}
full01         | 13: scBlockReceived{1003#A8F60CDC222DB85DD35EB682DC632F6C7F18A802B520DE461A77C99E47D37C1C from 0a9c99096b50a6d72a24d5aa5286d3f7022b3555}
full01         | 14: scBlockReceived{1000#D3CE5E0A3358A4D675163C30483006C6633B54AC8294EE565E6A7728C28143B8 from 0a9c99096b50a6d72a24d5aa5286d3f7022b3555}
full01         | 
full01         | 
full01         | goroutine 67 [running]:
full01         | github.com/tendermint/tendermint/blockchain/v2.(*Routine).start.func1(0xc000148230)
full01         | 	github.com/tendermint/tendermint/blockchain/v2/routine.go:77 +0x32e
full01         | panic(0x1110860, 0xc002db6180)
full01         | 	runtime/panic.go:969 +0x1b9
full01         | github.com/tendermint/tendermint/blockchain/v2.(*pcState).enqueue(0xc0001185d0, 0xc0000dd230, 0x28, 0xc0020fd0e0, 0x3f1)
full01         | 	github.com/tendermint/tendermint/blockchain/v2/processor.go:100 +0x317
full01         | github.com/tendermint/tendermint/blockchain/v2.(*pcState).handle(0xc0001185d0, 0x155fa00, 0xc002db0b00, 0x117d2c0, 0x122c040, 0xf49600, 0x155fa00)
full01         | 	github.com/tendermint/tendermint/blockchain/v2/processor.go:147 +0x17e
full01         | github.com/tendermint/tendermint/blockchain/v2.(*Routine).start(0xc000148230)
full01         | 	github.com/tendermint/tendermint/blockchain/v2/routine.go:94 +0x25f
full01         | created by github.com/tendermint/tendermint/blockchain/v2.(*BlockchainReactor).startSync
full01         | 	github.com/tendermint/tendermint/blockchain/v2/reactor.go:152 +0x12e
```

**Comment by melekes** [comment]
what version is this? `master` or `rc6`?

**Comment by erikgrinaker** [comment]
`master`, I believe.

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/pull/5607 should fix it, but I am not 100% sure if this was the issue in the above case. maybe we can run e2e tests with this branch?

**Comment by erikgrinaker** [comment]
You can run all generated tests locally, like so:

```
$ cd test/e2e
$ make
$ ./build/generator -d networks/generated
$ ./run-multiple.sh networks/generated/*.toml
```

**Comment by erikgrinaker** [comment]
Oh, by the way, I've disabled fast sync v2 in the generator due to all the failures, so you'll need to enable it by modifying `nodeFastSyncs` in `test/e2e/generator/generate.go`.
