### ISSUE TITLE
Gaia halting after network failures 

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#5608]
I received a bug report over email and am posting it here (with permission) for tracking. This may be a Gaia or SDK issue rather than a Tendermint Core issue, but halting always smells like it might be Tendermint. 

I've asked for the output from `tendermint debug` and will post that here, too, once I have it.

**Tendermint version**:
 
Gaia v2.0.13 (Tendermint v0.32.13) 

**What happened**:

When a node has been running for over 24 hours, and the internet is then cut off and then restored, fast sync doesn't resume. 

**What you expected to happen**:

Nodes should start fetching blocks again (fast syncing) after they return to the network.

**Have you tried the latest version**:  

No (but latest Gaia version) 

**How to reproduce it**:

"If I leave the node running for over 24hrs and cut off it’s internet for a few minutes it doesn’t recover." 

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

Logs are below - looks like this is triggered by a panic in the RPC handler: 

```
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:43:13.143] Panic in RPC HTTP handler                    module=rpc-server err="write tcp 172.25.10.100:26657->46.166.138.194:58024: i/o timeout" stack="goroutine 261344639 [running]:\nruntime/debug.Stack(0xc0026d7690, 0x10aeec0, 0xc01441e2d0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1.1(0xc01bd2bb20, 0x15af100, 0xc001ccece0, 0xbfc7abc58884d344, 0x448489bbd9a7, 0x20006e0, 0xc013885c00)\n\t/home/gaiad/go/pkg/mod/github.com/tendermint/tendermint@v0.32.13/rpc/lib/server/http_server.go:161 +0x486\npanic(0x10aeec0, 0xc01441e2d0)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/tendermint/tendermint/rpc/lib/server.WriteRPCResponseHTTP(0x15a96c0, 0xc01bd2bb20, 0x11d3a59, 0x3, 0x1591800, 0x1573920, 0xc01e2f0000, 0x2cd5b, 0x48760, 0x0)\n\t/home/gaiad/go/pkg/mod/github.com/tendermint/tendermint@v0.32.13/rpc/lib/server/http_server.go:112 +0x281\ngithub.com/tendermint/tendermint/rpc/lib/server.makeHTTPHandler.func2(0x15a96c0, 0xc01bd2bb20, 0xc013885c00)\n\t/home/gaiad/go/pkg/mod/github.com/tendermint/tendermint@v0.32.13/rpc/lib/server/handlers.go:326 +0x64e\nnet/http.HandlerFunc.ServeHTTP(0xc0022e0de0, 0x15a96c0, 0xc01bd2bb20, 0xc013885c00)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\nnet/http.(*ServeMux).ServeHTTP(0xc0022dc440, 0x15a96c0, 0xc01bd2bb20, 0xc013885c00)\n\t/usr/local/go/src/net/http/server.go:2387 +0x1bd\ngithub.com/tendermint/tendermint/rpc/lib/server.maxBytesHandler.ServeHTTP(0x15901e0, 0xc0022dc440, 0xf4240, 0x15a96c0, 0xc01bd2bb20, 0xc013885c00)\n\t/home/gaiad/go/pkg/mod/github.com/tendermint/tendermint@v0.32.13/rpc/lib/server/http_server.go:210 +0xcf\ngithub.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1(0x15a9dc0, 0xc014d02000, 0xc013885c00)\n\t/home/gaiad/go/pkg/mod/github.com/tendermint/tendermint@v0.32.13/rpc/lib/server/http_server.go:183 +0x33f\nnet/http.HandlerFunc.ServeHTTP(0xc0022f86f0, 0x15a9dc0, 0xc014d02000, 0xc013885c00)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\nnet/http.serverHandler.ServeHTTP(0xc0022ee0e0, 0x15a9dc0, 0xc014d02000, 0xc013885c00)\n\t/usr/local/go/src/net/http/server.go:2802 +0xa4\nnet/http.(*conn).serve(0xc014ce40a0, 0x15ae700, 0xc00f4f7e00)\n\t/usr/local/go/src/net/http/server.go:1890 +0x875\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2927 +0x38e\n"
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: 2020/08/20 10:43:13 http: superfluous response.WriteHeader call from github.com/tendermint/tendermint/rpc/lib/server.(*ResponseWriterWrapper).WriteHeader (http_server.go:195)
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: 2020/08/20 10:43:13 http: panic serving 46.166.138.194:58024: write tcp 172.25.10.100:26657->46.166.138.194:58024: i/o timeout
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: goroutine 261344639 [running]:
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: net/http.(*conn).serve.func1(0xc014ce40a0)
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: #011/usr/local/go/src/net/http/server.go:1767 +0x139
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: panic(0x10aeec0, 0xc01441e2d0)
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: #011/usr/local/go/src/runtime/panic.go:679 +0x1b2
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: github.com/tendermint/tendermint/rpc/lib/server.WriteRPCResponseHTTPError(0x15a96c0, 0xc01bd2bb20, 0x1f4, 0x11d3a59, 0x3, 0x1591800, 0x1573990, 0x0, 0x0, 0x0, ...)
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: #011/home/gaiad/go/pkg/mod/github.com/tendermint/tendermint@v0.32.13/rpc/lib/server/http_server.go:100 +0x285
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: github.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1.1(0xc01bd2bb20, 0x15af100, 0xc001ccece0, 0xbfc7abc58884d344, 0x448489bbd9a7, 0x20006e0, 0xc013885c00)
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: #011/home/gaiad/go/pkg/mod/github.com/tendermint/tendermint@v0.32.13/rpc/lib/server/http_server.go:163 +0x672
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: panic(0x10aeec0, 0xc01441e2d0)
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: #011/usr/local/go/src/runtime/panic.go:679 +0x1b2
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: github.com/tendermint/tendermint/rpc/lib/server.WriteRPCResponseHTTP(0x15a96c0, 0xc01bd2bb20, 0x11d3a59, 0x3, 0x1591800, 0x1573920, 0xc01e2f0000, 0x2cd5b, 0x48760, 0x0)
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: #011/home/gaiad/go/pkg/mod/github.com/tendermint/tendermint@v0.32.13/rpc/lib/server/http_server.go:112 +0x281
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: github.com/tendermint/tendermint/rpc/lib/server.makeHTTPHandler.func2(0x15a96c0, 0xc01bd2bb20, 0xc013885c00)
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: #011/home/gaiad/go/pkg/mod/github.com/tendermint/tendermint@v0.32.13/rpc/lib/server/handlers.go:326 +0x64e
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: net/http.HandlerFunc.ServeHTTP(0xc0022e0de0, 0x15a96c0, 0xc01bd2bb20, 0xc013885c00)
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: #011/usr/local/go/src/net/http/server.go:2007 +0x44
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: net/http.(*ServeMux).ServeHTTP(0xc0022dc440, 0x15a96c0, 0xc01bd2bb20, 0xc013885c00)
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: #011/usr/local/go/src/net/http/server.go:2387 +0x1bd
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: github.com/tendermint/tendermint/rpc/lib/server.maxBytesHandler.ServeHTTP(0x15901e0, 0xc0022dc440, 0xf4240, 0x15a96c0, 0xc01bd2bb20, 0xc013885c00)
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: #011/home/gaiad/go/pkg/mod/github.com/tendermint/tendermint@v0.32.13/rpc/lib/server/http_server.go:210 +0xcf
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: github.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1(0x15a9dc0, 0xc014d02000, 0xc013885c00)
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: #011/home/gaiad/go/pkg/mod/github.com/tendermint/tendermint@v0.32.13/rpc/lib/server/http_server.go:183 +0x33f
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: net/http.HandlerFunc.ServeHTTP(0xc0022f86f0, 0x15a9dc0, 0xc014d02000, 0xc013885c00)
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: #011/usr/local/go/src/net/http/server.go:2007 +0x44
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: net/http.serverHandler.ServeHTTP(0xc0022ee0e0, 0x15a9dc0, 0xc014d02000, 0xc013885c00)
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: #011/usr/local/go/src/net/http/server.go:2802 +0xa4
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: net/http.(*conn).serve(0xc014ce40a0, 0x15ae700, 0xc00f4f7e00)
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: #011/usr/local/go/src/net/http/server.go:1890 +0x875
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: created by net/http.(*Server).Serve
Aug 20 10:43:13 cosmos-sentry-1 gaiad[1192]: #011/usr/local/go/src/net/http/server.go:2927 +0x38e
Aug 20 10:43:55 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:43:55.493] Connection failed @ sendRoutine              module=p2p peer=2de24612cce2fee96b58f38b8504bd70f4836ef5@34.73.194.163:32944 conn=MConn{34.73.194.163:32944} err="pong timeout"
Aug 20 10:43:55 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:43:55.494] Stopping peer for error                      module=p2p peer="Peer{MConn{34.73.194.163:32944} 2de24612cce2fee96b58f38b8504bd70f4836ef5 in}" err="pong timeout"Aug 20 10:43:56 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:43:56.147] Connection failed @ sendRoutine              module=p2p peer=959ef1f39af22bd4652f8253315e6c2bab7a067e@183.178.40.3:47276 conn=MConn{183.178.40.3:47276} err="pong timeout"
Aug 20 10:43:56 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:43:56.147] Stopping peer for error                      module=p2p peer="Peer{MConn{183.178.40.3:47276} 959ef1f39af22bd4652f8253315e6c2bab7a067e in}" err="pong timeout"
Aug 20 10:43:56 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:43:56.157] Connection failed @ sendRoutine              module=p2p peer=72f22eae9c394edc9fce2a83e4168ab55ecc506b@35.231.27.172:16854 conn=MConn{35.231.27.172:16854} err="pong timeout"
Aug 20 10:43:56 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:43:56.157] Stopping peer for error                      module=p2p peer="Peer{MConn{35.231.27.172:16854} 72f22eae9c394edc9fce2a83e4168ab55ecc506b in}" err="pong timeout"
Aug 20 10:43:58 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:43:58.154] Connection failed @ sendRoutine              module=p2p peer=7f6ac6aad6bfc8d265870ba5e6da34cc09ad8a2e@46.4.17.85:1556 conn=MConn{46.4.17.85:1556} err="pong timeout"
Aug 20 10:43:58 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:43:58.155] Stopping peer for error                      module=p2p peer="Peer{MConn{46.4.17.85:1556} 7f6ac6aad6bfc8d265870ba5e6da34cc09ad8a2e in}" err="pong timeout"
Aug 20 10:43:59 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:43:59.094] Connection failed @ sendRoutine              module=p2p peer=51d186e6fe616362c2bc8ce41e54425000832bee@78.47.250.73:49022 conn=MConn{78.47.250.73:49022} err="pong timeout"
Aug 20 10:43:59 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:43:59.094] Stopping peer for error                      module=p2p peer="Peer{MConn{78.47.250.73:49022} 51d186e6fe616362c2bc8ce41e54425000832bee in}" err="pong timeout"
Aug 20 10:43:59 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:43:59.685] Connection failed @ sendRoutine              module=p2p peer=d4b04e29e642a002738f5b53f1081ed298cea261@109.194.199.73:36340 conn=MConn{109.194.199.73:36340} err="pong timeout"
Aug 20 10:43:59 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:43:59.685] Stopping peer for error                      module=p2p peer="Peer{MConn{109.194.199.73:36340} d4b04e29e642a002738f5b53f1081ed298cea261 in}" err="pong timeout"
Aug 20 10:44:01 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:01.031] Connection failed @ sendRoutine              module=p2p peer=f9bcd7e809e51612b510f48712962ed2a90b3a05@54.250.243.217:55114 conn=MConn{54.250.243.217:55114} err="pong timeout"
Aug 20 10:44:01 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:01.031] Stopping peer for error                      module=p2p peer="Peer{MConn{54.250.243.217:55114} f9bcd7e809e51612b510f48712962ed2a90b3a05 in}" err="pong timeout"
Aug 20 10:44:02 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:02.116] Connection failed @ sendRoutine              module=p2p peer=d59aad20fe483e666dd9c1ccce91533ab9d1e2ec@34.243.183.211:50402 conn=MConn{34.243.183.211:50402} err="pong timeout"
Aug 20 10:44:02 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:02.116] Stopping peer for error                      module=p2p peer="Peer{MConn{34.243.183.211:50402} d59aad20fe483e666dd9c1ccce91533ab9d1e2ec in}" err="pong timeout"
Aug 20 10:44:03 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:03.262] Connection failed @ sendRoutine              module=p2p peer=00774a8e06fb7edec86af23835e212718986c789@80.71.51.61:58399 conn=MConn{80.71.51.61:58399} err="pong timeout"
Aug 20 10:44:06 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:06.069] Connection failed @ sendRoutine              module=p2p peer=58c6a5b49289f1ecb6203d5dd6c0df01f4bb965c@52.214.189.9:29165 conn=MConn{52.214.189.9:29165} err="pong timeout"
Aug 20 10:44:06 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:06.070] Stopping peer for error                      module=p2p peer="Peer{MConn{52.214.189.9:29165} 58c6a5b49289f1ecb6203d5dd6c0df01f4bb965c in}" err="pong timeout"
Aug 20 10:44:12 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:12.599] Connection failed @ sendRoutine              module=p2p peer=0572211b0bbdee826ae862a50f94ffc60ea36a8f@39.99.175.113:57220 conn=MConn{39.99.175.113:57220} err="pong timeout"
Aug 20 10:44:12 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:12.599] Stopping peer for error                      module=p2p peer="Peer{MConn{39.99.175.113:57220} 0572211b0bbdee826ae862a50f94ffc60ea36a8f in}" err="pong timeout"
Aug 20 10:44:13 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:13.660] Connection failed @ sendRoutine              module=p2p peer=77c81f2eae6661904d388089e741f2e3c98abbd6@54.87.200.30:49936 conn=MConn{54.87.200.30:49936} err="pong timeout"
Aug 20 10:44:13 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:13.660] Stopping peer for error                      module=p2p peer="Peer{MConn{54.87.200.30:49936} 77c81f2eae6661904d388089e741f2e3c98abbd6 in}" err="pong timeout"
Aug 20 10:44:13 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:13.739] Connection failed @ sendRoutine              module=p2p peer=6afce8315d19486c85db832374fc41e70d4d630a@3.93.0.196:36138 conn=MConn{3.93.0.196:36138} err="pong timeout"
Aug 20 10:44:13 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:13.739] Stopping peer for error                      module=p2p peer="Peer{MConn{3.93.0.196:36138} 6afce8315d19486c85db832374fc41e70d4d630a in}" err="pong timeout"
Aug 20 10:44:14 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:14.751] Connection failed @ sendRoutine              module=p2p peer=a371d7f3a3d65a4e963acb63467f6f53961f3177@3.92.229.233:26656 conn=MConn{3.92.229.233:26656} err="pong timeout"
Aug 20 10:44:14 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:14.751] Stopping peer for error                      module=p2p peer="Peer{MConn{3.92.229.233:26656} a371d7f3a3d65a4e963acb63467f6f53961f3177 out}" err="pong timeout"
Aug 20 10:44:19 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:19.568] Connection failed @ sendRoutine              module=p2p peer=1be2bc01d01005833c538dedf11b23207cbb43f1@104.196.234.75:42680 conn=MConn{104.196.234.75:42680} err="pong timeout"
Aug 20 10:44:19 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:19.568] Stopping peer for error                      module=p2p peer="Peer{MConn{104.196.234.75:42680} 1be2bc01d01005833c538dedf11b23207cbb43f1 in}" err="pong timeout"
Aug 20 10:44:19 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:19.626] Connection failed @ sendRoutine              module=p2p peer=b9836729d06f54c64d3ebc6350e3e7321441d62c@91.207.102.246:44398 conn=MConn{91.207.102.246:44398} err="pong timeout"
Aug 20 10:44:19 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:19.627] Stopping peer for error                      module=p2p peer="Peer{MConn{91.207.102.246:44398} b9836729d06f54c64d3ebc6350e3e7321441d62c in}" err="pong timeout"
Aug 20 10:44:19 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:19.754] Connection failed @ sendRoutine              module=p2p peer=3f0c23ab9c7319ac0431eebc221f58bf870a77e5@35.243.179.58:50682 conn=MConn{35.243.179.58:50682} err="pong timeout"
Aug 20 10:44:19 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:19.754] Stopping peer for error                      module=p2p peer="Peer{MConn{35.243.179.58:50682} 3f0c23ab9c7319ac0431eebc221f58bf870a77e5 in}" err="pong timeout"
Aug 20 10:44:25 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:25.827] Connection failed @ sendRoutine              module=p2p peer=506a9eb648af5ffc26725b0320ce21fba785c0ba@140.82.33.61:40848 conn=MConn{140.82.33.61:40848} err="pong timeout"
Aug 20 10:44:25 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:25.830] Stopping peer for error                      module=p2p peer="Peer{MConn{140.82.33.61:40848} 506a9eb648af5ffc26725b0320ce21fba785c0ba in}" err="pong timeout"
Aug 20 10:44:30 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:30.048] Connection failed @ sendRoutine              module=p2p peer=e6048a5f66fad1cde96cb11759069910a6fb057e@35.183.114.143:34166 conn=MConn{35.183.114.143:34166} err="pong timeout"
Aug 20 10:44:30 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:30.048] Stopping peer for error                      module=p2p peer="Peer{MConn{35.183.114.143:34166} e6048a5f66fad1cde96cb11759069910a6fb057e in}" err="pong timeout"
Aug 20 10:44:30 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:30.663] Connection failed @ sendRoutine              module=p2p peer=c14bfbf8be97f96f7048b354f2b30add97b365c6@46.166.146.165:10644 conn=MConn{46.166.146.165:10644} err="pong timeout"
Aug 20 10:44:30 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:30.664] Stopping peer for error                      module=p2p peer="Peer{MConn{46.166.146.165:10644} c14bfbf8be97f96f7048b354f2b30add97b365c6 in}" err="pong timeout"
Aug 20 10:44:31 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:31.434] Connection failed @ sendRoutine              module=p2p peer=a497767f9acb81e7fa7dafb363cd53b2d1f0ab7a@167.172.57.167:44506 conn=MConn{167.172.57.167:44506} err="pong timeout"
Aug 20 10:44:31 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:31.435] Stopping peer for error                      module=p2p peer="Peer{MConn{167.172.57.167:44506} a497767f9acb81e7fa7dafb363cd53b2d1f0ab7a in}" err="pong timeout"
Aug 20 10:44:33 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:33.733] Connection failed @ sendRoutine              module=p2p peer=b9d6ecd01c01b42ce47486c40c2deb3572bc7981@3.250.223.128:35548 conn=MConn{3.250.223.128:35548} err="pong timeout"
Aug 20 10:44:33 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:33.734] Stopping peer for error                      module=p2p peer="Peer{MConn{3.250.223.128:35548} b9d6ecd01c01b42ce47486c40c2deb3572bc7981 in}" err="pong timeout"
Aug 20 10:44:38 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:38.441] Connection failed @ sendRoutine              module=p2p peer=ba3bacc714817218562f743178228f23678b2873@5.83.160.108:50238 conn=MConn{5.83.160.108:50238} err="pong timeout"
Aug 20 10:44:38 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:38.441] Stopping peer for error                      module=p2p peer="Peer{MConn{5.83.160.108:50238} ba3bacc714817218562f743178228f23678b2873 in}" err="pong timeout"
Aug 20 10:44:41 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:41.913] Connection failed @ sendRoutine              module=p2p peer=054fe0190b365594e711a58c6230ee700d233c61@63.34.54.228:52928 conn=MConn{63.34.54.228:52928} err="pong timeout"
Aug 20 10:44:41 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:41.915] Stopping peer for error                      module=p2p peer="Peer{MConn{63.34.54.228:52928} 054fe0190b365594e711a58c6230ee700d233c61 in}" err="pong timeout"
Aug 20 10:44:43 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:43.273] Connection failed @ sendRoutine              module=p2p peer=570a73d8e007296d208cc8db93f0a8d7b29eebbf@3.84.128.130:38422 conn=MConn{3.84.128.130:38422} err="pong timeout"
Aug 20 10:44:43 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:43.273] Stopping peer for error                      module=p2p peer="Peer{MConn{3.84.128.130:38422} 570a73d8e007296d208cc8db93f0a8d7b29eebbf in}" err="pong timeout"
Aug 20 10:44:44 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:44.524] Connection failed @ sendRoutine              module=p2p peer=ade5ff93caca58b00b5fce66d04cb81b68165a92@3.8.188.26:54932 conn=MConn{3.8.188.26:54932} err="pong timeout"
Aug 20 10:44:44 cosmos-sentry-1 gaiad[1192]: E[2020-08-20|10:44:44.524] Stopping peer for error                      module=p2p peer="Peer{MConn{3.8.188.26:54932} ade5ff93caca58b00b5fce66d04cb81b68165a92 in}" err="pong timeout"

Aug 20 10:45:58 cosmos-sentry-1 systemd-networkd[27277]: ens160: Gained carrier.   (Nic enabled)

Gaia stopped outputting logs
```

**Comment by melekes** [comment]
similar issue https://github.com/tendermint/tendermint/issues/5475

**Comment by marbar3778** [comment]
is this actually a edge case we want to cover. If the internet goes down we can keep retrying the nodes but after a certain amount of time, IMO, we should shut down. It could signify larger issues.
