### ISSUE TITLE
panic: enterPrecommit: +2/3 prevoted for an invalid block: wrong Block.Header.LastBlockID.  Expected X, got Y

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#5732]
`TestWALCrash` failed with the following panic [here](https://github.com/tendermint/tendermint/pull/5728/checks?check_run_id=1484646514):

```
panic: enterPrecommit: +2/3 prevoted for an invalid block: wrong Block.Header.LastBlockID.  Expected CFD0603262E70BC667D5C0CF3E93FD354710ED821CEA47627252C861DAB0DBBF:1:5ACFF27F1268, got B049D66C2C658D93A202F6CD5F47C8A6DF72C3E230FF9C0BA0146AF97D3DC0B5:1:B08023847A3F [recovered]
	panic: enterPrecommit: +2/3 prevoted for an invalid block: wrong Block.Header.LastBlockID.  Expected CFD0603262E70BC667D5C0CF3E93FD354710ED821CEA47627252C861DAB0DBBF:1:5ACFF27F1268, got B049D66C2C658D93A202F6CD5F47C8A6DF72C3E230FF9C0BA0146AF97D3DC0B5:1:B08023847A3F

goroutine 70973 [running]:
testing.tRunner.func1.1(0x1211a40, 0xc009c02060)
	/opt/hostedtoolcache/go/1.15.5/x64/src/testing/testing.go:1072 +0x46a
testing.tRunner.func1(0xc009f52000)
	/opt/hostedtoolcache/go/1.15.5/x64/src/testing/testing.go:1075 +0x636
panic(0x1211a40, 0xc009c02060)
	/opt/hostedtoolcache/go/1.15.5/x64/src/runtime/panic.go:975 +0x47a
github.com/tendermint/tendermint/consensus.(*State).enterPrecommit(0xc0079abc00, 0x3, 0x0)
	/home/runner/work/tendermint/tendermint/consensus/state.go:1339 +0x2e2f
github.com/tendermint/tendermint/consensus.(*State).addVote(0xc0079abc00, 0xc0051c6320, 0x0, 0x0, 0xc009cb3220, 0x20, 0xc009cb3220)
	/home/runner/work/tendermint/tendermint/consensus/state.go:2027 +0x1ab7
github.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc0079abc00, 0xc0051c6320, 0x0, 0x0, 0x0, 0x48c059, 0xc0012d08b0)
	/home/runner/work/tendermint/tendermint/consensus/state.go:1846 +0x95
github.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc0079abc00, 0x15c7460, 0xc00860e1f0, 0x0, 0x0)
	/home/runner/work/tendermint/tendermint/consensus/state.go:803 +0xe73
github.com/tendermint/tendermint/consensus.(*State).readReplayMessage(0xc0079abc00, 0xc009e236e0, 0x0, 0x0, 0x0, 0x0)
	/home/runner/work/tendermint/tendermint/consensus/replay.go:82 +0x88a
github.com/tendermint/tendermint/consensus.(*State).catchupReplay(0xc0079abc00, 0x3, 0x0, 0x0)
	/home/runner/work/tendermint/tendermint/consensus/replay.go:161 +0x695
github.com/tendermint/tendermint/consensus.(*State).OnStart(0xc0079abc00, 0xc008173800, 0x16)
	/home/runner/work/tendermint/tendermint/consensus/state.go:320 +0x465
github.com/tendermint/tendermint/libs/service.(*BaseService).Start(0xc0079abc00, 0x1364282, 0x11)
	/home/runner/work/tendermint/tendermint/libs/service/service.go:140 +0x539
github.com/tendermint/tendermint/consensus.startNewStateAndWaitForBlock(0xc009f52000, 0xc0016fcdc0, 0x3, 0x15e94a0, 0xc0090a4b00, 0x15e80a0, 0xc0052fe980)
	/home/runner/work/tendermint/tendermint/consensus/replay_test.go:84 +0x3ca
github.com/tendermint/tendermint/consensus.crashWALandCheckLiveness(0xc009f52000, 0xc0016fcdc0, 0x14c4500, 0x3)
	/home/runner/work/tendermint/tendermint/consensus/replay_test.go:203 +0xc99
github.com/tendermint/tendermint/consensus.TestWALCrash.func3(0xc009f52000)
	/home/runner/work/tendermint/tendermint/consensus/replay_test.go:143 +0xbf
testing.tRunner(0xc009f52000, 0xc004b6c9f0)
	/opt/hostedtoolcache/go/1.15.5/x64/src/testing/testing.go:1123 +0x203
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.15.5/x64/src/testing/testing.go:1168 +0x5bc
FAIL	github.com/tendermint/tendermint/consensus	92.205s
```

**Comment by erikgrinaker** [comment]
Looks like #5723 messed up these tests. I think it was too zealous in replacing `defer` with `t.Cleanup`. Two notable differences:

* `defer` is called on panics, `t.Cleanup` is not.
* `defer` is called when the local function exits, `t.Cleanup` is called when the entire test ends.

For example, `startNewStateAndWaitForBlock` is now using `t.Cleanup`, but this will only be called at the end of the test which is too late to do the cleanup that is necessary, and won't be called at all on panics (even though Tendermint code uses panics all over the place, and the WAL tests in particular trigger panics explicitly).

**Comment by alessio** [comment]
Will take a look ASAP @erikgrinaker!

**Comment by erikgrinaker** [comment]
Hm, nevermind, `t.Cleanup` _does_ run on panics -- I thought I'd read differently somewhere. But subtleties in panic handling may still cause issues with this.

**Comment by alessio** [comment]
Hey @melekes! #5734 should address the point raised by @erikgrinaker's `defer is called when the local function exits, t.Cleanup is called when the entire test ends.` Mind testing it and see whether it solves this issue?

**Comment by melekes** [comment]
Yep, can't replicate on master. Thanks @alessio 👍
