### ISSUE TITLE
mempool: test timeouts

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#5956]
I'm seeing frequent test timeouts, that I suspect are caused by the recent mempool reactor refactor.

```
panic: test timed out after 8m0s

goroutine 2280 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.15.6/x64/src/testing/testing.go:1618 +0x11f
created by time.goFunc
	/opt/hostedtoolcache/go/1.15.6/x64/src/time/sleep.go:167 +0x52

goroutine 1 [chan receive, 7 minutes]:
testing.(*T).Run(0xc00048a600, 0x10d172a, 0x16, 0x1221db8, 0x1)
	/opt/hostedtoolcache/go/1.15.6/x64/src/testing/testing.go:1169 +0x5f4
testing.runTests.func1(0xc00048a600)
	/opt/hostedtoolcache/go/1.15.6/x64/src/testing/testing.go:1439 +0xa7
testing.tRunner(0xc00048a600, 0xc00009fc78)
	/opt/hostedtoolcache/go/1.15.6/x64/src/testing/testing.go:1123 +0x203
testing.runTests(0xc000488840, 0x17e2100, 0x14, 0x14, 0xbffb4b01ab5249fb, 0x6fec0ffd5c, 0x17ef560, 0xc00046c228)
	/opt/hostedtoolcache/go/1.15.6/x64/src/testing/testing.go:1437 +0x613
testing.(*M).Run(0xc000406300, 0x0)
	/opt/hostedtoolcache/go/1.15.6/x64/src/testing/testing.go:1345 +0x3b4
main.main()
	_testmain.go:149 +0x357

goroutine 2273 [chan receive, 7 minutes]:
github.com/tendermint/tendermint/mempool.(*Reactor).OnStop(0xc0000baf00)
	/home/runner/work/tendermint/tendermint/mempool/reactor.go:158 +0x225
github.com/tendermint/tendermint/libs/service.(*BaseService).Stop(0xc0000baf00, 0x0, 0xc000c3fd40)
	/home/runner/work/tendermint/tendermint/libs/service/service.go:169 +0x516
github.com/tendermint/tendermint/mempool.setup.func1()
	/home/runner/work/tendermint/tendermint/mempool/reactor_test.go:89 +0x78
testing.(*common).Cleanup.func1()
	/opt/hostedtoolcache/go/1.15.6/x64/src/testing/testing.go:880 +0x104
testing.(*common).runCleanup(0xc0000d3c80, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.15.6/x64/src/testing/testing.go:957 +0xcb
testing.tRunner.func2(0xc0000d3c80)
	/opt/hostedtoolcache/go/1.15.6/x64/src/testing/testing.go:1117 +0x75
testing.tRunner(0xc0000d3c80, 0x1221db8)
	/opt/hostedtoolcache/go/1.15.6/x64/src/testing/testing.go:1127 +0x22b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.15.6/x64/src/testing/testing.go:1168 +0x5bc

goroutine 12 [syscall, 7 minutes]:
os/signal.signal_recv(0x4a4dc1)
	/opt/hostedtoolcache/go/1.15.6/x64/src/runtime/sigqueue.go:147 +0x9d
os/signal.loop()
	/opt/hostedtoolcache/go/1.15.6/x64/src/os/signal/signal_unix.go:23 +0x30
created by os/signal.Notify.func1.1
	/opt/hostedtoolcache/go/1.15.6/x64/src/os/signal/signal.go:150 +0x7d

goroutine 34 [chan receive, 7 minutes]:
github.com/tendermint/tendermint/abci/server.(*SocketServer).handleResponses(0xc0004d2b00, 0xc0004805a0, 0x7f3e9adc6a40, 0xc001372000, 0xc000480600)
	/home/runner/work/tendermint/tendermint/abci/server/socket_server.go:246 +0xbb
created by github.com/tendermint/tendermint/abci/server.(*SocketServer).acceptConnectionsRoutine
	/home/runner/work/tendermint/tendermint/abci/server/socket_server.go:129 +0x417

goroutine 2276 [chan send, 7 minutes]:
github.com/tendermint/tendermint/mempool.(*Reactor).processMempoolCh(0xc0000baf00)
	/home/runner/work/tendermint/tendermint/mempool/reactor.go:227 +0x732
created by github.com/tendermint/tendermint/mempool.(*Reactor).OnStart
	/home/runner/work/tendermint/tendermint/mempool/reactor.go:133 +0xbd

goroutine 2275 [select, 7 minutes]:
github.com/tendermint/tendermint/mempool.(*Reactor).processPeerUpdates(0xc0000ba780)
	/home/runner/work/tendermint/tendermint/mempool/reactor.go:302 +0x2b4
created by github.com/tendermint/tendermint/mempool.(*Reactor).OnStart
	/home/runner/work/tendermint/tendermint/mempool/reactor.go:134 +0xdf

goroutine 2274 [select, 7 minutes]:
github.com/tendermint/tendermint/mempool.(*Reactor).processMempoolCh(0xc0000ba780)
	/home/runner/work/tendermint/tendermint/mempool/reactor.go:223 +0x22e
created by github.com/tendermint/tendermint/mempool.(*Reactor).OnStart
	/home/runner/work/tendermint/tendermint/mempool/reactor.go:133 +0xbd

goroutine 2145 [select, 7 minutes]:
github.com/tendermint/tendermint/mempool.(*Reactor).broadcastTxRoutine(0xc0000ba780, 0xc000c00580, 0x20, 0xc000b998a0)
	/home/runner/work/tendermint/tendermint/mempool/reactor.go:339 +0xd2b
created by github.com/tendermint/tendermint/mempool.(*Reactor).processPeerUpdate
	/home/runner/work/tendermint/tendermint/mempool/reactor.go:277 +0x5e5

FAIL	github.com/tendermint/tendermint/mempool	480.735s
```

**Comment by alexanderbez** [comment]
Do you have a specific test or a CI log I can look at?

**Comment by alexanderbez** [comment]
Do you have a specific test or CI log I can look at so I know which test I can trigger this on?

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/pull/5960/checks?check_run_id=1760666570

**Comment by erikgrinaker** [comment]
Had another failure here:

https://github.com/tendermint/tendermint/pull/5971/checks?check_run_id=1769772600

```
2021-01-26T14:26:45.2951055Z panic: test timed out after 8m0s
2021-01-26T14:26:45.2951489Z 
2021-01-26T14:26:45.2952011Z goroutine 2092 [running]:
2021-01-26T14:26:45.2952558Z testing.(*M).startAlarm.func1()
2021-01-26T14:26:45.2953861Z 	/opt/hostedtoolcache/go/1.15.6/x64/src/testing/testing.go:1618 +0x11f
2021-01-26T14:26:45.2954643Z created by time.goFunc
2021-01-26T14:26:45.2955447Z 	/opt/hostedtoolcache/go/1.15.6/x64/src/time/sleep.go:167 +0x52
2021-01-26T14:26:45.2955986Z 
2021-01-26T14:26:45.2956445Z goroutine 1 [chan receive, 7 minutes]:
2021-01-26T14:26:45.2957166Z testing.(*T).Run(0xc00048e780, 0x10d7fe3, 0x16, 0x1228880, 0x1)
2021-01-26T14:26:45.2958057Z 	/opt/hostedtoolcache/go/1.15.6/x64/src/testing/testing.go:1169 +0x5f4
2021-01-26T14:26:45.2958906Z testing.runTests.func1(0xc00048e780)
2021-01-26T14:26:45.2959728Z 	/opt/hostedtoolcache/go/1.15.6/x64/src/testing/testing.go:1439 +0xa7
2021-01-26T14:26:45.2960441Z testing.tRunner(0xc00048e780, 0xc000121c78)
2021-01-26T14:26:45.2961302Z 	/opt/hostedtoolcache/go/1.15.6/x64/src/testing/testing.go:1123 +0x203
2021-01-26T14:26:45.2962253Z testing.runTests(0xc000488b80, 0x17ec240, 0x14, 0x14, 0xbffc27894ff73aca, 0x6fee46f57e, 0x17f96e0, 0xc0000a24f0)
2021-01-26T14:26:45.2963231Z 	/opt/hostedtoolcache/go/1.15.6/x64/src/testing/testing.go:1437 +0x613
2021-01-26T14:26:45.2964022Z testing.(*M).Run(0xc000406280, 0x0)
2021-01-26T14:26:45.2964700Z 	/opt/hostedtoolcache/go/1.15.6/x64/src/testing/testing.go:1345 +0x3b4
2021-01-26T14:26:45.2965476Z main.main()
2021-01-26T14:26:45.2965887Z 	_testmain.go:149 +0x357
2021-01-26T14:26:45.2966182Z 
2021-01-26T14:26:45.2966614Z goroutine 16 [chan receive, 7 minutes]:
2021-01-26T14:26:45.2967645Z github.com/tendermint/tendermint/abci/server.(*SocketServer).handleResponses(0xc00001cbb0, 0xc0010641e0, 0x7fc181ec24c0, 0xc0004e8048, 0xc001064240)
2021-01-26T14:26:45.2968867Z 	/home/runner/work/tendermint/tendermint/abci/server/socket_server.go:246 +0xbb
2021-01-26T14:26:45.2970019Z created by github.com/tendermint/tendermint/abci/server.(*SocketServer).acceptConnectionsRoutine
2021-01-26T14:26:45.2971181Z 	/home/runner/work/tendermint/tendermint/abci/server/socket_server.go:129 +0x417
2021-01-26T14:26:45.2972086Z 
2021-01-26T14:26:45.2972523Z goroutine 2099 [select, 7 minutes]:
2021-01-26T14:26:45.2973365Z github.com/tendermint/tendermint/mempool.(*Reactor).processPeerUpdates(0xc0000ba6e0)
2021-01-26T14:26:45.2974578Z 	/home/runner/work/tendermint/tendermint/mempool/reactor.go:302 +0x2b4
2021-01-26T14:26:45.2975463Z created by github.com/tendermint/tendermint/mempool.(*Reactor).OnStart
2021-01-26T14:26:45.2976375Z 	/home/runner/work/tendermint/tendermint/mempool/reactor.go:134 +0xdf
2021-01-26T14:26:45.2976863Z 
2021-01-26T14:26:45.2977301Z goroutine 24 [syscall, 7 minutes]:
2021-01-26T14:26:45.2977838Z os/signal.signal_recv(0x4a4dc1)
2021-01-26T14:26:45.2978549Z 	/opt/hostedtoolcache/go/1.15.6/x64/src/runtime/sigqueue.go:147 +0x9d
2021-01-26T14:26:45.2979172Z os/signal.loop()
2021-01-26T14:26:45.2979951Z 	/opt/hostedtoolcache/go/1.15.6/x64/src/os/signal/signal_unix.go:23 +0x30
2021-01-26T14:26:45.2980707Z created by os/signal.Notify.func1.1
2021-01-26T14:26:45.2981473Z 	/opt/hostedtoolcache/go/1.15.6/x64/src/os/signal/signal.go:150 +0x7d
2021-01-26T14:26:45.2981925Z 
2021-01-26T14:26:45.2982441Z goroutine 2098 [select, 7 minutes]:
2021-01-26T14:26:45.2983265Z github.com/tendermint/tendermint/mempool.(*Reactor).processMempoolCh(0xc0000ba6e0)
2021-01-26T14:26:45.2984420Z 	/home/runner/work/tendermint/tendermint/mempool/reactor.go:223 +0x22e
2021-01-26T14:26:45.2987942Z created by github.com/tendermint/tendermint/mempool.(*Reactor).OnStart
2021-01-26T14:26:45.2988899Z 	/home/runner/work/tendermint/tendermint/mempool/reactor.go:133 +0xbd
2021-01-26T14:26:45.2989388Z 
2021-01-26T14:26:45.2989826Z goroutine 1985 [chan receive, 7 minutes]:
2021-01-26T14:26:45.2990580Z github.com/tendermint/tendermint/mempool.(*Reactor).OnStop(0xc0000baf00)
2021-01-26T14:26:45.2991494Z 	/home/runner/work/tendermint/tendermint/mempool/reactor.go:158 +0x225
2021-01-26T14:26:45.2992448Z github.com/tendermint/tendermint/libs/service.(*BaseService).Stop(0xc0000baf00, 0x0, 0xc0004c3d40)
2021-01-26T14:26:45.2993459Z 	/home/runner/work/tendermint/tendermint/libs/service/service.go:169 +0x516
2021-01-26T14:26:45.2994540Z github.com/tendermint/tendermint/mempool.setup.func1()
2021-01-26T14:26:45.2995453Z 	/home/runner/work/tendermint/tendermint/mempool/reactor_test.go:89 +0x78
2021-01-26T14:26:45.2996183Z testing.(*common).Cleanup.func1()
2021-01-26T14:26:45.2996907Z 	/opt/hostedtoolcache/go/1.15.6/x64/src/testing/testing.go:880 +0x104
2021-01-26T14:26:45.2997643Z testing.(*common).runCleanup(0xc000ef6180, 0x0, 0x0, 0x0)
2021-01-26T14:26:45.2998404Z 	/opt/hostedtoolcache/go/1.15.6/x64/src/testing/testing.go:957 +0xcb
2021-01-26T14:26:45.2999142Z testing.tRunner.func2(0xc000ef6180)
2021-01-26T14:26:45.2999934Z 	/opt/hostedtoolcache/go/1.15.6/x64/src/testing/testing.go:1117 +0x75
2021-01-26T14:26:45.3000612Z testing.tRunner(0xc000ef6180, 0x1228880)
2021-01-26T14:26:45.3001362Z 	/opt/hostedtoolcache/go/1.15.6/x64/src/testing/testing.go:1127 +0x22b
2021-01-26T14:26:45.3001991Z created by testing.(*T).Run
2021-01-26T14:26:45.3002676Z 	/opt/hostedtoolcache/go/1.15.6/x64/src/testing/testing.go:1168 +0x5bc
2021-01-26T14:26:45.3003125Z 
2021-01-26T14:26:45.3003689Z goroutine 2091 [select, 7 minutes]:
2021-01-26T14:26:45.3004600Z github.com/tendermint/tendermint/mempool.(*Reactor).broadcastTxRoutine(0xc0000ba6e0, 0xc000f3bbc0, 0x20, 0xc00108f8a0)
2021-01-26T14:26:45.3005728Z 	/home/runner/work/tendermint/tendermint/mempool/reactor.go:339 +0xbaa
2021-01-26T14:26:45.3006692Z created by github.com/tendermint/tendermint/mempool.(*Reactor).processPeerUpdate
2021-01-26T14:26:45.3007714Z 	/home/runner/work/tendermint/tendermint/mempool/reactor.go:277 +0x5e5
2021-01-26T14:26:45.3008208Z 
2021-01-26T14:26:45.3008643Z goroutine 2103 [chan receive, 7 minutes]:
2021-01-26T14:26:45.3009598Z github.com/tendermint/tendermint/mempool.simulateRouter.func2(0xc000cee050, 0xc000cee001)
2021-01-26T14:26:45.3010753Z 	/home/runner/work/tendermint/tendermint/mempool/reactor_test.go:130 +0xa5
2021-01-26T14:26:45.3012621Z created by github.com/tendermint/tendermint/mempool.simulateRouter
2021-01-26T14:26:45.3013951Z 	/home/runner/work/tendermint/tendermint/mempool/reactor_test.go:129 +0x193
2021-01-26T14:26:45.3014458Z 
2021-01-26T14:26:45.3014880Z goroutine 2100 [chan send, 7 minutes]:
2021-01-26T14:26:45.3015687Z github.com/tendermint/tendermint/mempool.(*Reactor).processMempoolCh(0xc0000baf00)
2021-01-26T14:26:45.3021524Z 	/home/runner/work/tendermint/tendermint/mempool/reactor.go:227 +0x732
2021-01-26T14:26:45.3022771Z created by github.com/tendermint/tendermint/mempool.(*Reactor).OnStart
2021-01-26T14:26:45.3024938Z 	/home/runner/work/tendermint/tendermint/mempool/reactor.go:133 +0xbd
2021-01-26T14:26:45.3025726Z FAIL	github.com/tendermint/tendermint/mempool	480.773s
```

**Comment by alexanderbez** [comment]
Not 100% confident the last PR fixed this. I just don't get what's going on. Still investigating.

**Comment by alexanderbez** [comment]
Ahhh, I was dropping peer errors for the wrong suite! I'm just going to be safe and drop them for all reactors.
