### ISSUE TITLE
Can Tendermint work on ARM architecture?

### ISSUE THREAD

**Issue by KimuraYu45z** [tendermint/tendermint#6464]
Can Tendermint work on ARM architecture?
I got this error on ARM (I built the program for ARM. I confirmed that I didn't run x64 binary in ARM machine.)

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

```
github.com/cosmos/cosmos-sdk v0.42.3
	github.com/gogo/protobuf v1.3.3
	github.com/golang/protobuf v1.5.2
	github.com/gorilla/mux v1.8.0
	github.com/grpc-ecosystem/grpc-gateway v1.16.0
	github.com/regen-network/cosmos-proto v0.3.1
	github.com/spf13/cast v1.3.1
	github.com/spf13/cobra v1.1.3
	github.com/spf13/pflag v1.0.5
	github.com/tendermint/tendermint v0.34.8
	github.com/tendermint/tm-db v0.6.4
	google.golang.org/genproto v0.0.0-20210114201628-6edceaf6022f
	google.golang.org/grpc v1.36.1
	google.golang.org/protobuf v1.26.0
```

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:
- ARM

**What happened**:

```
May 10 06:38:50 rockpi-4c appd[16192]: 6:38AM INF starting ABCI with Tendermint
May 10 06:38:50 rockpi-4c appd[16192]: unexpected fault address 0x747365742da27d
May 10 06:38:50 rockpi-4c appd[16192]: fatal error: fault
May 10 06:38:50 rockpi-4c appd[16192]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x747365742da27d pc=0xb68e00]
May 10 06:38:50 rockpi-4c appd[16192]: goroutine 1 [running]:
May 10 06:38:50 rockpi-4c appd[16192]: runtime.throw(0x18f8671, 0x5)
May 10 06:38:50 rockpi-4c appd[16192]:         runtime/panic.go:1117 +0x54 fp=0x4000323980 sp=0x4000323950 pc=0x439e64
May 10 06:38:50 rockpi-4c appd[16192]: runtime.sigpanic()
May 10 06:38:50 rockpi-4c appd[16192]:         runtime/signal_unix.go:741 +0x230 fp=0x40003239c0 sp=0x4000323980 pc=0x451ad0
May 10 06:38:50 rockpi-4c appd[16192]: github.com/golang/snappy.encodeBlock(0x4000d41502, 0x32d7, 0x32d7, 0x4000149000, 0x2b76, 0x2c6f, 0x1)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/golang/snappy@v0.0.2/encode_arm64.s:666 +0x360 fp=0x400032ba60 sp=0x40003239d0 pc=0xb68e00
May 10 06:38:50 rockpi-4c appd[16192]: github.com/golang/snappy.Encode(0x4000d41500, 0x32d9, 0x32d9, 0x0, 0x0, 0x0, 0x2b03, 0x2b03, 0x400032bb78)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/golang/snappy@v0.0.2/encode.go:39 +0x17c fp=0x400032bab0 sp=0x400032ba60 pc=0xb6833c
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb/table.(*Writer).writeBlock(0x40001586c0, 0x4000158718, 0x2, 0x0, 0x12, 0x20, 0x400081c740)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/table/writer.go:171 +0xb0 fp=0x400032bb30 sp=0x400032bab0 pc=0xb70b20
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb/table.(*Writer).finishBlock(0x40001586c0, 0x4001200000, 0x12)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/table/writer.go:222 +0x4c fp=0x400032bb80 sp=0x400032bb30 pc=0xb70fbc
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb/table.(*Writer).Append(0x40001586c0, 0x4001200000, 0x12, 0x400000, 0x4001200012, 0x2b03, 0x3fffee, 0x100, 0x1)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/table/writer.go:255 +0x1e4 fp=0x400032bbf0 sp=0x400032bb80 pc=0xb71224
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb.(*tWriter).append(0x4000e810e0, 0x4001200000, 0x12, 0x400000, 0x4001200012, 0x2b03, 0x3fffee, 0x0, 0x0)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/table.go:559 +0xbc fp=0x400032bc60 sp=0x400032bbf0 pc=0xb92d8c
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb.(*tOps).createFrom(0x40010df260, 0x1d922f8, 0x4000860880, 0x0, 0x0, 0x0, 0x0)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/table.go:397 +0x11c fp=0x400032bd00 sp=0x400032bc60 pc=0xb9210c
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb.(*session).flushMemdb(0x4000ce44b0, 0x400003e460, 0x40010fa460, 0x0, 0x0, 0x0, 0x0)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/session_compaction.go:35 +0xa4 fp=0x400032be60 sp=0x400032bd00 pc=0xb8a384
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb.(*DB).recoverJournal(0x4000d48380, 0x4000d48380, 0x40002372c0)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db.go:612 +0xa80 fp=0x400032c080 sp=0x400032be60 pc=0xb76050
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb.openDB(0x4000ce44b0, 0x0, 0x0, 0x4000ce44b0)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db.go:131 +0x488 fp=0x400032c170 sp=0x400032c080 pc=0xb75098
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb.Open(0x1d90cd8, 0x4000cf0070, 0x0, 0x0, 0x0, 0x0)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db.go:203 +0xd0 fp=0x400032c1e0 sp=0x400032c170 pc=0xb752f0
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb.OpenFile(0x400081c560, 0x19, 0x0, 0x400081c560, 0x19, 0x400117a158)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db.go:225 +0x7c fp=0x400032c260 sp=0x400032c1e0 pc=0xb754ec
May 10 06:38:50 rockpi-4c appd[16192]: github.com/tendermint/tm-db.NewGoLevelDBWithOpts(0x18f8c16, 0x5, 0x400117a180, 0x10, 0x0, 0xf, 0x400013c750, 0xc)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/tendermint/tm-db@v0.6.4/goleveldb.go:32 +0xa4 fp=0x400032c2d0 sp=0x400032c260 pc=0xba2264
May 10 06:38:50 rockpi-4c appd[16192]: github.com/tendermint/tm-db.NewGoLevelDB(...)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/tendermint/tm-db@v0.6.4/goleveldb.go:27
May 10 06:38:50 rockpi-4c appd[16192]: github.com/tendermint/tm-db.init.0.func1(0x18f8c16, 0x5, 0x400117a180, 0x10, 0x400013c7d8, 0x400117a101, 0x10, 0x0)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/tendermint/tm-db@v0.6.4/goleveldb.go:15 +0x44 fp=0x400032c320 sp=0x400032c2d0 pc=0xba88f4
May 10 06:38:50 rockpi-4c appd[16192]: github.com/tendermint/tm-db.NewDB(0x18f8c16, 0x5, 0x4000f9cd40, 0x9, 0x400117a180, 0x10, 0x1d94100, 0x400000e078, 0x4000d481c0, 0x1b5def0)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/tendermint/tm-db@v0.6.4/db.go:64 +0x2b4 fp=0x400032c450 sp=0x400032c320 pc=0xba2034
May 10 06:38:50 rockpi-4c appd[16192]: github.com/tendermint/tendermint/node.DefaultDBProvider(0x400000e090, 0x400000e090, 0x0, 0x0, 0x0)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/tendermint/tendermint@v0.34.8/node/node.go:67 +0xb0 fp=0x400032c5b0 sp=0x400032c450 pc=0xf19080
May 10 06:38:50 rockpi-4c appd[16192]: github.com/tendermint/tendermint/node.initDBs(0x4000fb8000, 0x1b5e2e0, 0x163dbc0, 0x400117a174, 0x195, 0x3, 0x400161e7d8)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/tendermint/tendermint@v0.34.8/node/node.go:216 +0x144 fp=0x400032c610 sp=0x400032c5b0 pc=0xf19304
May 10 06:38:50 rockpi-4c appd[16192]: github.com/tendermint/tendermint/node.NewNode(0x4000fb8000, 0x1d741d0, 0x400003e1e0, 0x4000214d70, 0x1d412a8, 0x400029c3a8, 0x4000215040, 0x1b5e2e0, 0x4000215290, 0x1d7cef0, ...)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/tendermint/tendermint@v0.34.8/node/node.go:626 +0x38 fp=0x400032ccc0 sp=0x400032c610 pc=0xf1c648
May 10 06:38:50 rockpi-4c appd[16192]: github.com/cosmos/cosmos-sdk/server.startInProcess(0x4000f05580, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1d84ea8, 0x4000ec41e0, ...)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/cosmos/cosmos-sdk@v0.42.3/server/start.go:244 +0x3f4 fp=0x400032d8e0 sp=0x400032ccc0 pc=0xf349d4
May 10 06:38:50 rockpi-4c appd[16192]: github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0x4000effb80, 0x29f7ec0, 0x0, 0x0, 0x0, 0x0)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/cosmos/cosmos-sdk@v0.42.3/server/start.go:120 +0x144 fp=0x400032dcf0 sp=0x400032d8e0 pc=0xf38244
May 10 06:38:50 rockpi-4c appd[16192]: github.com/spf13/cobra.(*Command).execute(0x4000effb80, 0x29f7ec0, 0x0, 0x0, 0x4000effb80, 0x29f7ec0)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/spf13/cobra@v1.1.3/command.go:852 +0x320 fp=0x400032ddb0 sp=0x400032dcf0 pc=0x5d8880
May 10 06:38:50 rockpi-4c appd[16192]: github.com/spf13/cobra.(*Command).ExecuteC(0x4000e30f00, 0x0, 0x0, 0x4000e89ed0)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/spf13/cobra@v1.1.3/command.go:960 +0x268 fp=0x400032de90 sp=0x400032ddb0 pc=0x5d9118
May 10 06:38:50 rockpi-4c appd[16192]: github.com/spf13/cobra.(*Command).Execute(...)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/spf13/cobra@v1.1.3/command.go:897
May 10 06:38:50 rockpi-4c appd[16192]: github.com/spf13/cobra.(*Command).ExecuteContext(...)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/spf13/cobra@v1.1.3/command.go:890
May 10 06:38:50 rockpi-4c appd[16192]: github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x4000e30f00, 0x4000e89ed0, 0xb, 0x1d97858, 0x4000ec41e0)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/cosmos/cosmos-sdk@v0.42.3/server/cmd/execute.go:36 +0x210 fp=0x400032df20 sp=0x400032de90 pc=0xf3a940
May 10 06:38:50 rockpi-4c appd[16192]: main.main()
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/lcnem/app/cmd/appd/main.go:13 +0x44 fp=0x400032df70 sp=0x400032df20 pc=0x15533d4
May 10 06:38:50 rockpi-4c appd[16192]: runtime.main()
May 10 06:38:50 rockpi-4c appd[16192]:         runtime/proc.go:225 +0x274 fp=0x400032dfd0 sp=0x400032df70 pc=0x43c3b4
May 10 06:38:50 rockpi-4c appd[16192]: runtime.goexit()
May 10 06:38:50 rockpi-4c appd[16192]:         runtime/asm_arm64.s:1130 +0x4 fp=0x400032dfd0 sp=0x400032dfd0 pc=0x4713a4
May 10 06:38:50 rockpi-4c appd[16192]: goroutine 67 [select]:
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0x4000e02540)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db_compaction.go:91 +0x74
May 10 06:38:50 rockpi-4c appd[16192]: created by github.com/syndtr/goleveldb/leveldb.openDB
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db.go:148 +0x31c
May 10 06:38:50 rockpi-4c appd[16192]: goroutine 36 [select]:
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x40010fa0e0)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/util/buffer_pool.go:209 +0xcc
May 10 06:38:50 rockpi-4c appd[16192]: created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/util/buffer_pool.go:240 +0x154
May 10 06:38:50 rockpi-4c appd[16192]: goroutine 37 [select]:
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb.(*session).refLoop(0x4000ece780)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/session_util.go:189 +0x3b0
May 10 06:38:50 rockpi-4c appd[16192]: created by github.com/syndtr/goleveldb/leveldb.newSession
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/session.go:93 +0x22c
May 10 06:38:50 rockpi-4c appd[16192]: goroutine 68 [select]:
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0x4000e02540)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db_state.go:101 +0x98
May 10 06:38:50 rockpi-4c appd[16192]: created by github.com/syndtr/goleveldb/leveldb.openDB
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db.go:149 +0x33c
May 10 06:38:50 rockpi-4c appd[16192]: goroutine 69 [select]:
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0x4000e02540)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db_compaction.go:836 +0x188
May 10 06:38:50 rockpi-4c appd[16192]: created by github.com/syndtr/goleveldb/leveldb.openDB
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db.go:155 +0x444
May 10 06:38:50 rockpi-4c appd[16192]: goroutine 70 [select]:
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0x4000e02540)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db_compaction.go:773 +0xd0
May 10 06:38:50 rockpi-4c appd[16192]: created by github.com/syndtr/goleveldb/leveldb.openDB
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db.go:156 +0x464
May 10 06:38:50 rockpi-4c appd[16192]: goroutine 71 [select]:
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x4000260380)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/util/buffer_pool.go:209 +0xcc
May 10 06:38:50 rockpi-4c appd[16192]: created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/util/buffer_pool.go:240 +0x154
May 10 06:38:50 rockpi-4c appd[16192]: goroutine 72 [select]:
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb.(*session).refLoop(0x40000ae5a0)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/session_util.go:189 +0x3b0
May 10 06:38:50 rockpi-4c appd[16192]: created by github.com/syndtr/goleveldb/leveldb.newSession
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/session.go:93 +0x22c
May 10 06:38:50 rockpi-4c appd[16192]: goroutine 73 [select]:
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0x400027e380)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db_compaction.go:91 +0x74
May 10 06:38:50 rockpi-4c appd[16192]: created by github.com/syndtr/goleveldb/leveldb.openDB
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db.go:148 +0x31c
May 10 06:38:50 rockpi-4c appd[16192]: goroutine 74 [select]:
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0x400027e380)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db_state.go:101 +0x98
May 10 06:38:50 rockpi-4c appd[16192]: created by github.com/syndtr/goleveldb/leveldb.openDB
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db.go:149 +0x33c
May 10 06:38:50 rockpi-4c appd[16192]: goroutine 75 [select]:
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0x400027e380)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db_compaction.go:836 +0x188
May 10 06:38:50 rockpi-4c appd[16192]: created by github.com/syndtr/goleveldb/leveldb.openDB
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db.go:155 +0x444
May 10 06:38:50 rockpi-4c appd[16192]: goroutine 76 [select]:
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0x400027e380)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db_compaction.go:773 +0xd0
May 10 06:38:50 rockpi-4c appd[16192]: created by github.com/syndtr/goleveldb/leveldb.openDB
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db.go:156 +0x464
May 10 06:38:50 rockpi-4c appd[16192]: goroutine 24 [select]:
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb.(*session).refLoop(0x4000ce43c0)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/session_util.go:189 +0x3b0
May 10 06:38:50 rockpi-4c appd[16192]: created by github.com/syndtr/goleveldb/leveldb.newSession
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/session.go:93 +0x22c
May 10 06:38:50 rockpi-4c appd[16192]: goroutine 23 [select]:
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x40010fa000)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/util/buffer_pool.go:209 +0xcc
May 10 06:38:50 rockpi-4c appd[16192]: created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/util/buffer_pool.go:240 +0x154
May 10 06:38:50 rockpi-4c appd[16192]: goroutine 38 [select]:
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0x4000d481c0)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db_compaction.go:91 +0x74
May 10 06:38:50 rockpi-4c appd[16192]: created by github.com/syndtr/goleveldb/leveldb.openDB
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db.go:148 +0x31c
May 10 06:38:50 rockpi-4c appd[16192]: goroutine 39 [select]:
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0x4000d481c0)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db_state.go:101 +0x98
May 10 06:38:50 rockpi-4c appd[16192]: created by github.com/syndtr/goleveldb/leveldb.openDB
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db.go:149 +0x33c
May 10 06:38:50 rockpi-4c appd[16192]: goroutine 40 [select]:
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0x4000d481c0)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db_compaction.go:836 +0x188
May 10 06:38:50 rockpi-4c appd[16192]: created by github.com/syndtr/goleveldb/leveldb.openDB
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db.go:155 +0x444
May 10 06:38:50 rockpi-4c appd[16192]: goroutine 41 [select]:
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0x4000d481c0)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db_compaction.go:773 +0xd0
May 10 06:38:50 rockpi-4c appd[16192]: created by github.com/syndtr/goleveldb/leveldb.openDB
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db.go:156 +0x464
May 10 06:38:50 rockpi-4c appd[16192]: goroutine 42 [select]:
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x40010fa1c0)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/util/buffer_pool.go:209 +0xcc
May 10 06:38:50 rockpi-4c appd[16192]: created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/util/buffer_pool.go:240 +0x154
May 10 06:38:50 rockpi-4c appd[16192]: goroutine 43 [select]:
May 10 06:38:50 rockpi-4c appd[16192]: github.com/syndtr/goleveldb/leveldb.(*session).refLoop(0x4000ce44b0)
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/session_util.go:189 +0x3b0
May 10 06:38:50 rockpi-4c appd[16192]: created by github.com/syndtr/goleveldb/leveldb.newSession
May 10 06:38:50 rockpi-4c appd[16192]:         github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/session.go:93 +0x22c
```

**What you expected to happen**:

**Have you tried the latest version**: yes/no

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by marbar3778** [comment]
Hey, I actually have had the same issue with the sdk. Tendermint on its own is fine, but when I run the sdk this issues arises. This issue would be better suited for the sdk.

**Comment by marbar3778** [comment]
In testing Tendermints master and v0.34.x branch I was not able to reproduce this. Lets transfer the issue to the sdk and we can debug there.
