### ISSUE TITLE
Failed Test: TestReactor_Backfill

### ISSUE THREAD

**Issue by williambanfield** [tendermint/tendermint#6675]
Failed [in CI](https://github.com/tendermint/tendermint/pull/6643/checks?check_run_id=3011900134)
```
--- FAIL: TestReactor_Backfill (65.15s)
    --- FAIL: TestReactor_Backfill/failure_rate:_9 (64.05s)
        leaktest.go:132: leaktest: timed out checking goroutines
        leaktest.go:150: leaktest: leaked goroutine: goroutine 162 [chan receive, 1 minutes]:
            github.com/tendermint/tendermint/internal/statesync.(*peerlist).Pop(0xc0001ec000, 0x1, 0x39)
            	/home/runner/work/tendermint/tendermint/internal/statesync/dispatcher.go:284 +0x1eb
            github.com/tendermint/tendermint/internal/statesync.(*dispatcher).LightBlock(0xc00040a9c0, 0x14735f8, 0xc00054c400, 0xc, 0x2, 0x2, 0x1, 0x1460801, 0xc0001da1a0)
            	/home/runner/work/tendermint/tendermint/internal/statesync/dispatcher.go:60 +0x159
            github.com/tendermint/tendermint/internal/statesync.(*Reactor).backfill.func1(0xc000116900, 0xc0000e4f00, 0x14735f8, 0xc00054c400, 0x12168a5, 0xa)
            	/home/runner/work/tendermint/tendermint/internal/statesync/reactor.go:321 +0x325
            created by github.com/tendermint/tendermint/internal/statesync.(*Reactor).backfill
            	/home/runner/work/tendermint/tendermint/internal/statesync/reactor.go:316 +0x3cf
FAIL
```
Appears to be a different failure from #6644 

Ran the tests 20 times with ` go test . -test.v -run TestReactor_Backfill -count 20` and reproduced once.

**Comment by cmwaters** [comment]
Right - I would have introduced this whilst fixing the backfill tests. I wanted to add a test to check for leaky go routines and it seems that occasionally this still fails
