### ISSUE TITLE
mempool: panic re-CheckTx transaction mismatch

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#6741]
## Summary

Witnessed this in an [e2e test](https://github.com/tendermint/tendermint/runs/3110014898?check_suite_focus=true):

```
2021-07-20T02:33:55.8416760Z validator02    | 2021-07-20T02:31:54Z INFO executed block height=35 module=state num_invalid_txs=0 num_valid_txs=5
2021-07-20T02:33:55.8418485Z validator02    | 2021-07-20T02:31:54Z INFO committed state app_hash=60EFBC0A4B6E7C5BCEB16180A704A5D0FDF9622D39165E15EFB1C564A8A4A1D1 height=35 module=state num_txs=5
2021-07-20T02:33:55.8421113Z validator02    | panic: re-CheckTx transaction mismatch; got: F6DCAF251E6975030397BC84415DE4F0571133537A1A6ED965D4D2AF99EDD0DF, expected: AE63C6F4CC4647253C73D2FA85454B1AA270FFDEDCB2C8D200821BE20635464F
2021-07-20T02:33:55.8422649Z validator02    | 
2021-07-20T02:33:55.8423118Z validator02    | goroutine 36 [running]:
2021-07-20T02:33:55.8424042Z validator02    | github.com/tendermint/tendermint/internal/mempool/v1.(*TxMempool).defaultTxCallback(0xc000098d80, 0xc00356f0c0, 0xc00356f2e0)
2021-07-20T02:33:55.8425273Z validator02    | 	github.com/tendermint/tendermint/internal/mempool/v1/mempool.go:627 +0x99f
2021-07-20T02:33:55.8426275Z validator02    | github.com/tendermint/tendermint/abci/client.(*grpcClient).OnStart.func1.1(0xc0036a0d00)
2021-07-20T02:33:55.8427404Z validator02    | 	github.com/tendermint/tendermint/abci/client/grpc_client.go:79 +0x108
2021-07-20T02:33:55.8428388Z validator02    | github.com/tendermint/tendermint/abci/client.(*grpcClient).OnStart.func1(0xc0000dfa20)
2021-07-20T02:33:55.8429347Z validator02    | 	github.com/tendermint/tendermint/abci/client/grpc_client.go:89 +0x95
2021-07-20T02:33:55.8430285Z validator02    | created by github.com/tendermint/tendermint/abci/client.(*grpcClient).OnStart
2021-07-20T02:33:55.8431209Z validator02    | 	github.com/tendermint/tendermint/abci/client/grpc_client.go:68 +0x54
```

Node's manifest:

```
  [node.validator02]
    mode = "validator"
    persistent_peers = ["full01"]
    database = "goleveldb"
    abci_protocol = "grpc"
    privval_protocol = "tcp"
    start_at = 0
    fast_sync = "v0"
    state_sync = false
    persist_interval = 5
    snapshot_interval = 3
    retain_blocks = 0
    perturb = ["pause", "kill"]
    log_level = ""
    disable_legacy_p2p = true
```

Testnet: `gen-group00-0005.toml`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
This is a duplicate @cmwaters. I can't seem to find the issue, but it has to do with the fact that gRPC is used for the communication. We resolved this issue for in-process clients. So this is a known bug for gRPC.

**Comment by cmwaters** [comment]
Do you mean this issue https://github.com/tendermint/tendermint/issues/5519?

**Comment by alexanderbez** [comment]
Actually https://github.com/tendermint/tendermint/issues/5439, which is closed. We should re-open that and close this one.

**Comment by cmwaters** [comment]
Do we want to disable grpc in e2e again? @alexanderbez

**Comment by alexanderbez** [comment]
Yes IMO
