### ISSUE TITLE
Document that app should return AppHash in response to Commit

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#695]
From Rocket chat:

```
And when I send a transaction, I'm getting the error:

2017-10-02T12:51:08.578728711Z panic: Panicked questionably: Failed to process committed block (118:37353841374132414642413934354234433837334530434432313837424532313742444432314644): Exec failed for application: Wrong Block.Header.AppHash. Expected 7B9835027FC7FDCB48E2F827410BFD10192DE28A, got 
2017-10-02T12:51:08.57877568Z 
2017-10-02T12:51:08.578787576Z goroutine 26 [running]:
2017-10-02T12:51:08.578797317Z panic(0xa5d160, 0xc4204b7200)
2017-10-02T12:51:08.578806051Z /usr/local/go/src/runtime/panic.go:500 +0x1a1
2017-10-02T12:51:08.578815911Z github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common.PanicQ(0xa5d160, 0xc4204b71e0)
2017-10-02T12:51:08.578825117Z /go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common/errors.go:44 +0xe0
2017-10-02T12:51:08.578849808Z github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine(0xc420094000)
2017-10-02T12:51:08.578860637Z /go/src/github.com/tendermint/tendermint/blockchain/reactor.go:249 +0x1119
2017-10-02T12:51:08.578870609Z created by github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).OnStart
2017-10-02T12:51:08.578879108Z /go/src/github.com/tendermint/tendermint/blockchain/reactor.go:93 +0x6e

melekes Cosmos 5:05 PM
well, the height is increasing over time. it means TM is making blocks
as for tx processing
looks like the app did not send an apphash (it's empty)

gian 2:31 AM
But how can I generate an apphash ? Every example I've seen, the apphash is empty in genesis file

adribeiro 4:19 AM
hi @gian, you can update when send the answer in commit with the OK status code.
 gian 2:31 AM
But how can I generate an apphash ? Every example I've seen, the apphash is empty in genesis file
so you can you into info answers as well

julian.smith 8:47 AM   
@melekes - what’s best documentation around (or specific lines of sample code) having an ABCI app “sending the apphash” to TM so we can rectify ? 😀

melekes Cosmos 9:09 AM
https://github.com/tendermint/abci/blob/develop/example/dummy/persistent_dummy.go#L101
 
github.com
tendermint/abci
abci - Serverside Blockchain API

melekes Cosmos 9:16 AM
https://github.com/tendermint/tendermint/blob/develop/state/execution.go#L270
 
github.com
tendermint/tendermint
tendermint - Tendermint Core (BFT Consensus) in Go
we should probably document this better
```

**Comment by melekes** [comment]
It's actually already in the docs. I guess we should just make this clearer.
