### ISSUE TITLE
fuzz: reported crash in mempool during nightly run

### ISSUE THREAD

**Issue by creachadair** [tendermint/tendermint#7189]
Possibly reordered some initialization code during #7171?

Actions run: https://github.com/tendermint/tendermint/actions/runs/1410627573

Log:

```
panic: testing: Verbose called before Init

goroutine 1 [running]:
testing.Verbose(...)
	/opt/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:453
github.com/tendermint/tendermint/libs/log.TestingLoggerWithOutput({0xc0000001a0, 0xc000048000})
	/home/runner/work/tendermint/tendermint/libs/log/testing.go:34 +0x465
github.com/tendermint/tendermint/libs/log.TestingLogger(...)
	/home/runner/work/tendermint/tendermint/libs/log/testing.go:23
github.com/tendermint/tendermint/test/fuzz/mempool.init.0.func1()
	/home/runner/work/tendermint/tendermint/test/fuzz/mempool/checktx.go:31 +0x85
github.com/tendermint/tendermint/test/fuzz/mempool.Fuzz({0x7fa45be00000, 0x0, 0x0})
	/home/runner/work/tendermint/tendermint/test/fuzz/mempool/checktx.go:43 +0x4c
go-fuzz-dep.Main({0xc0001f7f68, 0x1, 0xcc1880})
	go-fuzz-dep/main.go:36 +0x15b
main.main()
	github.com/tendermint/tendermint/test/fuzz/mempool/go.fuzz.main/main.go:15 +0x3b
exit status 2
```

**Comment by creachadair** [comment]
I see the trouble, we're creating a `TestingLogger` in `init`, in open defiance of the documentation:

```go
// NOTE:
// - A call to NewTestingLogger() must be made inside a test (not in the init func)
// because verbose flag only set at the time of testing.
```
