### ISSUE TITLE
[statesync] module=blockchain fail check AppHash, HeaderVersion in block.

### ISSUE THREAD

**Issue by dualsystems** [tendermint/tendermint#7461]
In few situation statesync restore snapshot without any errors, but when switch to fastsync (replayBlock), process is break:

**Block Header Version wrong:**
```
6:20PM INF Verified ABCI app appHash="���0*V�Ahfj\x06��?@'�_�\f���\x13��\x17'{��" height=2397500 module=statesync
6:20PM INF Snapshot restored format=1 hash="��bV_�����\rӒd�\x00�]�6�X��!\x0f\u009fZ\x03<�" height=2397500 module=statesync

6:20PM INF Starting BlockPool service impl=BlockPool module=blockchain

panic: Failed to process committed block (2397501:C85C412DEFBE083B3BAC5D3E6B7967366B300293E94C5A30FC7CD46B8B5C61E8): wrong Block.Header.Version. Expected {11 0}, got {11 1}

goroutine 199 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc0001f4c40, 0xc163591f01)
        github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:401 +0x15a5
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).SwitchToFastSync
        github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:125 +0xd5
```

**AppHash wrong:**  (if wait to next snapshot sync is ok)
```
9:54AM ERR WARNING: Attempt to allocate proposer rewards to unknown proposer . This should happen only if the proposer unbonded completely within a single block, which generally should not happen except in exceptional circumstances (or fuzz testing). We recommend you investigate immediately. module=x/distribution
9:54AM INF Endblock: Block 287401 was proposed by 51C818CB49A0B0C8FE8CDD7F217ABFF15AAE9988 module=emz
9:54AM INF executed block height=287401 module=state num_invalid_txs=0 num_valid_txs=0
9:54AM INF commit synced commit=436F6D6D697449447B5B31333020333220353320313635203134372031333420393320353820323620363620353520313420323037203131312032303320323438203230322031333520323620373420323020342032303220313337203135352031393620323320313833203136302031323620313038203134325D3A34363241397D
9:54AM INF committed state app_hash=822035A593865D3A1A42370ECF6FCBF8CA871A4A1404CA899BC417B7A07E6C8E height=287401 module=state num_txs=0
9:54AM INF indexed block height=287401 module=txindex
panic: Failed to process committed block (287402:1FA2B4F5E50AAE13B01760135A6D69957DB83BF6D7B06EF71E25712C2C2F6910): wrong Block.Header.AppHash.  Expected 822035A593865D3A1A42370ECF6FCBF8CA871A4A1404CA899BC417B7A07E6C8E, got 3CFB2E821E8F9FECAB9A793935BCCE45DAAE88365928BC90BFE4ED7AF71B424C
```
Error not clear in that point.. failed is block version or app version:
https://github.com/tendermint/tendermint/blob/7705c9d0865ca97c7e0fd16e2fa26245c946e11e/internal/state/validation.go#L21

**Comment by dualsystems** [comment]
In osmosis genesis.json - version: {"app_version": "1"}, but other chains that value is not set.

**Comment by cmwaters** [comment]
Hey @dualsystems, So I actually came across this exact same error when state syncing my osmosis node and I put together a command that will manually override the app version so I could get the node to start up with AppVersion 1 (instead of 0). To do this:
```bash
git clone https://github.com/tendermint/tendermint
cd tendermint
git checkout callum/app-version
make install
tendermint set-app-version 1 --home ~/.osmosisd
```
then try restart your node again.

I did some digging around and I believe the actual problem resides in the SDK. I think it's returning an empty app version after state sync so this bug occurs for every non zero app version. I plan to open a more thorough issue on this in the SDK when I get the time.

**Comment by dualsystems** [comment]
@cmwaters It's that?
https://github.com/tendermint/tendermint/blob/7705c9d0865ca97c7e0fd16e2fa26245c946e11e/internal/state/state.go#L32

**Comment by dualsystems** [comment]
Thank you!

**Comment by cmwaters** [comment]
Here's the issue I wrote up: https://github.com/cosmos/cosmos-sdk/issues/10791
