### ISSUE TITLE
Leak detector failure in TestSignerClose

### ISSUE THREAD

**Issue by creachadair** [tendermint/tendermint#7553]
From a build of #7552 in CI. Not related to that change.

```
--- FAIL: TestSignerClose (5.08s)
    leaktest.go:132: leaktest: timed out checking goroutines
    leaktest.go:150: leaktest: leaked goroutine: goroutine 26 [sleep]:
        time.Sleep(0x5f5e100)
        	/opt/hostedtoolcache/go/1.17.5/x64/src/runtime/time.go:193 +0x12e
        github.com/tendermint/tendermint/privval.(*SignerDialerEndpoint).ensureConnection(0xc000240000)
        	/home/runner/work/tendermint/tendermint/privval/signer_dialer_endpoint.go:90 +0x105
        github.com/tendermint/tendermint/privval.(*SignerServer).serviceLoop(0xc0001d2300, {0x11243d8, 0xc000104240})
        	/home/runner/work/tendermint/tendermint/privval/signer_server.go:100 +0xca
        created by github.com/tendermint/tendermint/privval.(*SignerServer).OnStart
        	/home/runner/work/tendermint/tendermint/privval/signer_server.go:46 +0xe7
FAIL
```

**Comment by tychoish** [comment]
I didn't see this issue, but I think https://github.com/tendermint/tendermint/commit/841629f5b7223825601263002f8ec92214db4489 should resolve this.

**Comment by tychoish** [comment]
I just ran the test 1000 times and it didn't fail, going to close this one off.
