### ISSUE TITLE
Nil envelope delivered to PEX reactor

### ISSUE THREAD

**Issue by creachadair** [tendermint/tendermint#7619]
Discovered while testing #7608.

It appears the iterator can report true from `Next` but deliver a `nil` Envelope message.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdc4c5f]

goroutine 231 [running]:
github.com/tendermint/tendermint/internal/p2p/pex.(*Reactor).processPexCh(0xc0004180b0, {0x11fb038, 0xc000498a00})
	/home/runner/work/tendermint/tendermint/internal/p2p/pex/reactor.go:202 +0x6ff
created by github.com/tendermint/tendermint/internal/p2p/pex.(*Reactor).OnStart
	/home/runner/work/tendermint/tendermint/internal/p2p/pex/reactor.go:147 +0xe7
FAIL	github.com/tendermint/tendermint/internal/p2p/pex	3.363s
```

**Comment by creachadair** [comment]
This should be fixed by #7623.
