### ISSUE TITLE
BUG REPORT: Full network crash - panic: notified txs available but mempool is empty!

### ISSUE THREAD

**Issue by illya13** [tendermint/tendermint#802]
tendermint version: **0.10.4-'9af837c**
ABCI App: **ethermint 0.4.0**

Environment: **"16.04.3 LTS (Xenial Xerus)**

ethremint logs
```
ubuntu@ip-172-31-23-39:~$ tail -200f .ethermint/logs/ethermint.log
WARN [11-01|12:28:46] DeliverTx error                          err="invalid nonce: have 10103484, expected 10103486"
WARN [11-01|12:28:46] DeliverTx error                          err="invalid nonce: have 10103485, expected 10103486"
WARN [11-01|12:28:51] DeliverTx error                          err="invalid nonce: have 10103499, expected 10103504"
WARN [11-01|12:28:51] DeliverTx error                          err="invalid nonce: have 10103500, expected 10103504"
WARN [11-01|12:28:51] DeliverTx error                          err="invalid nonce: have 10103501, expected 10103504"
WARN [11-01|12:28:51] DeliverTx error                          err="invalid nonce: have 10103502, expected 10103504"
WARN [11-01|12:28:51] DeliverTx error                          err="invalid nonce: have 10103503, expected 10103504"
WARN [11-01|12:29:03] DeliverTx error                          err="invalid nonce: have 10103545, expected 10103552"
WARN [11-01|12:29:03] DeliverTx error                          err="invalid nonce: have 10103546, expected 10103552"
WARN [11-01|12:29:03] DeliverTx error                          err="invalid nonce: have 10103547, expected 10103552"
WARN [11-01|12:29:03] DeliverTx error                          err="invalid nonce: have 10103548, expected 10103552"
WARN [11-01|12:29:03] DeliverTx error                          err="invalid nonce: have 10103549, expected 10103552"
WARN [11-01|12:29:06] DeliverTx error                          err="invalid nonce: have 10103552, expected 10103557"
WARN [11-01|12:29:06] DeliverTx error                          err="invalid nonce: have 10103553, expected 10103557"
WARN [11-01|12:29:09] DeliverTx error                          err="invalid nonce: have 10103557, expected 10103558"
WARN [11-01|12:29:12] DeliverTx error                          err="invalid nonce: have 10103559, expected 10103578"
WARN [11-01|12:29:12] DeliverTx error                          err="invalid nonce: have 10103560, expected 10103578"
WARN [11-01|12:29:12] DeliverTx error                          err="invalid nonce: have 10103561, expected 10103578"
WARN [11-01|12:29:12] DeliverTx error                          err="invalid nonce: have 10103562, expected 10103578"
WARN [11-01|12:29:12] DeliverTx error                          err="invalid nonce: have 10103563, expected 10103578"
WARN [11-01|12:29:12] DeliverTx error                          err="invalid nonce: have 10103564, expected 10103578"
WARN [11-01|12:29:12] DeliverTx error                          err="invalid nonce: have 10103565, expected 10103578"
WARN [11-01|12:29:15] DeliverTx error                          err="invalid nonce: have 10103578, expected 10103589"
WARN [11-01|12:29:15] DeliverTx error                          err="invalid nonce: have 10103579, expected 10103589"
WARN [11-01|12:29:20] DeliverTx error                          err="invalid nonce: have 10103589, expected 10103603"
WARN [11-01|12:29:20] DeliverTx error                          err="invalid nonce: have 10103590, expected 10103603"
WARN [11-01|12:29:29] DeliverTx error                          err="invalid nonce: have 10103616, expected 10103635"
WARN [11-01|12:29:29] DeliverTx error                          err="invalid nonce: have 10103617, expected 10103635"
WARN [11-01|12:29:29] DeliverTx error                          err="invalid nonce: have 10103618, expected 10103635"
WARN [11-01|12:29:29] DeliverTx error                          err="invalid nonce: have 10103619, expected 10103635"
WARN [11-01|12:29:32] DeliverTx error                          err="invalid nonce: have 10103635, expected 10103649"
ERROR[11-01|12:33:16] Connection error                         module=abci-server error=EOF
ERROR[11-01|12:33:16] Connection error                         module=abci-server error=EOF
ERROR[11-01|12:33:16] Connection error                         module=abci-server error=EOF
```

all network nodes crashed with
```
I[11-01|12:33:16.865] Committed state                              module=state height=7887791 txs=11 hash=DA00D930AA7008A06C9ED7623EB8F57873FE1FDE75E166F580C9E0E74340C2E5
panic: notified txs available but mempool is empty!

goroutine 34 [running]:
github.com/tendermint/tendermint/mempool.(*Mempool).notifyTxsAvailable(0xc4204b6880)
        /go/src/github.com/tendermint/tendermint/mempool/mempool.go:288 +0xd5
github.com/tendermint/tendermint/mempool.(*Mempool).resCbRecheck(0xc4204b6880, 0xc4236d6820, 0xc4236d7110)
        /go/src/github.com/tendermint/tendermint/mempool/mempool.go:272 +0x1bc
github.com/tendermint/tendermint/mempool.(*Mempool).resCb(0xc4204b6880, 0xc4236d6820, 0xc4236d7110)
        /go/src/github.com/tendermint/tendermint/mempool/mempool.go:212 +0x48
github.com/tendermint/tendermint/mempool.(*Mempool).(github.com/tendermint/tendermint/mempool.resCb)-fm(0xc4236d6820, 0xc4236d7110)
        /go/src/github.com/tendermint/tendermint/mempool/mempool.go:95 +0x3e
github.com/tendermint/tendermint/vendor/github.com/tendermint/abci/client.(*socketClient).didRecvResponse(0xc42042ac80, 0xc4236d7110, 0x0, 0x0)
        /go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/abci/client/socket_client.go:218 +0x261
github.com/tendermint/tendermint/vendor/github.com/tendermint/abci/client.(*socketClient).recvResponseRoutine(0xc42042ac80, 0x105f7e0, 0xc42000c2b0)
        /go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/abci/client/socket_client.go:177 +0x169
created by github.com/tendermint/tendermint/vendor/github.com/tendermint/abci/client.(*socketClient).OnStart
        /go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/abci/client/socket_client.go:78 +0x1da
```

**Comment by odeke-em** [comment]
@illya13 thank you for the report!

This issue was reported originally in https://github.com/tendermint/tendermint/issues/753 and fixed with https://github.com/tendermint/tendermint/pull/755. Please get the latest code.

I'll close this issue, but please feel to reopen if symptoms persist.

/cc @melekes @ebuchman

**Comment by illya13** [comment]
Guys, I need that in 0.10.x.
or in any version compatible with `ethermint` 0.4.0

**Comment by ebuchman** [comment]
Let's do a 0.10.5 hot-fix release with that. @odeke-em can you help prepare it?

**Comment by illya13** [comment]
I can downgrade (it was my original plan) to `0.10.2`

**Comment by odeke-em** [comment]
@ebuchman SGTM, am on it!

**Comment by illya13** [comment]
thx, can I also expect binaries?

**Comment by odeke-em** [comment]
All done, and yes with binaries :)

v0.10.5 released at https://github.com/tendermint/tendermint/releases/tag/v0.10.5

This is my first Tendermint release, so please bear with me if I screwed up the formatting but the binaries and sha256 sums should be alright. Thank you again for your report @illya13 and for using Tendermint!

**Comment by illya13** [comment]
`tendermint version` doesn't seems valid

**Comment by odeke-em** [comment]
What do you mean @illya13?

**Comment by illya13** [comment]
1. `wget https://github.com/tendermint/tendermint/releases/download/v0.10.5/tendermint_0.10.5_linux_amd64.zip`
2. `unzip tendermint_0.10.5_linux_amd64.zip`
3. `./tendermint version`

==>

`0.10.4-'eebc7f9`

**Comment by odeke-em** [comment]
Thanks for that catch @illya13 :) Ah crap, my bad. I've updated that at the same URL https://github.com/tendermint/tendermint/releases/tag/v0.10.5, please try again

**Comment by illya13** [comment]
thx, seems better

on one of the nodes getting
```
Error starting proxy app connections: Error on replay: Exec failed for application: Wrong Block.Header.AppHash.  Expected 5781468C5DB26200B01B9CC65A758179BF576657F79B99696394F69F51CA8063, got F95B4B8BA97214EE66F1F12148208AC60D3FE3C27BC87C39049B6868AFB343E5
```
any hints to recover ?
/cc @melekes

**Comment by melekes** [comment]
> This is my first Tendermint release

did you use the release script? (/scripts/release.sh)

**Comment by melekes** [comment]
@illya13 could you share the full log?

**Comment by illya13** [comment]
👍 you may close this one
@ebuchman @odeke-em thx for quick fix / release
@melekes it was all I have

**Comment by odeke-em** [comment]
```
@odeke-em did you use the release script? (/scripts/release.sh)
```
For that commit/branch pair, we didn't seem to have a `scripts/release.sh` at least as per https://github.com/tendermint/tendermint/blob/release-v0.10.5/scripts/release.sh. However it is now present in develop. I used the scripts/dist_build.sh script https://github.com/tendermint/tendermint/blob/acc161f7ccd722b217cbd1dbc440f3babf8ad4d8/scripts/dist_build.sh.

Awesome, glad to know your original issue is resolved @illya13, thank you for your feedback and report and for using Tendermint!
