### ISSUE TITLE
Pex false: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mjhubert** [tendermint/tendermint#8088]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
unreleased-master-f992a7e7408bb1c853dd40c3989cd8624ae60599

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
--proxy-app=kvstore

**Environment**:
- **OS** (e.g. from /etc/os-release):
Ubuntu 20.04.1 LTS \n \l

- **Install tools**:
- **Others**:

**What happened**:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xe3a7e5]

goroutine 1 [running]:
github.com/tendermint/tendermint/node.(*nodeImpl).OnStart(0xc00000a960, {0x131d408, 0xc00061fb40})
```

**What you expected to happen**:

The start of a validator without PEX.

**Have you tried the latest version**: yes/no
latest master

**How to reproduce it** (as minimally and precisely as possible):

`git checkout master`
`make install`
`make build`
`tendermint init validator`

edit config.toml to set pex to false

```
# Set true to enable the peer-exchange reactor
pex = false
```
`tendermint start --proxy-app=kvstore`

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

```
2022-03-08T11:48:05+01:00 INFO starting service impl=proxyClient module=proxy service=proxyClient
2022-03-08T11:48:05+01:00 INFO starting service impl=localClient service=localClient
2022-03-08T11:48:05+01:00 INFO starting service impl=EventBus module=eventbus service=EventBus
2022-03-08T11:48:05+01:00 INFO starting service impl=PubSub module=events service=PubSub
2022-03-08T11:48:05+01:00 INFO starting service impl=IndexerService module=txindex service=IndexerService
2022-03-08T11:48:05+01:00 INFO ABCI Handshake App Info hash= height=0 module=handshaker protocol-version=1 software-version=0.17.0
2022-03-08T11:48:05+01:00 INFO ABCI Replay Blocks appHeight=0 module=handshaker stateHeight=0 storeHeight=0
2022-03-08T11:48:05+01:00 INFO Completed ABCI Handshake - Tendermint and App are synced appHash= appHeight=0 module=handshaker
2022-03-08T11:48:05+01:00 INFO Version info block=11 mode=validator p2p=8 tmVersion=unreleased-master-f992a7e7408bb1c853dd40c3989cd8624ae60599
2022-03-08T11:48:05+01:00 INFO This node is a validator addr=227E481619C8EA40C21AFDB7B8BEC15B67CB2C39 pubKey="��\x0f�\x03�7��2v+�\x13�G\t�3\x00\x19K���'���^��"
2022-03-08T11:48:05+01:00 INFO starting service impl=Node service=Node
2022-03-08T11:48:05+01:00 INFO WARNING: Websocket RPC access is deprecated and will be removed in Tendermint v0.37. See https://tinyurl.com/adr075 for more information. module=rpc-server
2022-03-08T11:48:05+01:00 INFO starting service impl=router module=p2p service=router
2022-03-08T11:48:05+01:00 INFO starting router channels=4020212223303860616263 listen_addr=tcp://0.0.0.0:26656 module=p2p node_id=2b94ff79dbbf27e1949835ba8a324c283ec13021 transports=1
2022-03-08T11:48:05+01:00 INFO Starting RPC HTTP server on 127.0.0.1:26657 module=rpc-server
2022-03-08T11:48:05+01:00 INFO starting service impl=Evidence module=evidence service=Evidence
2022-03-08T11:48:05+01:00 INFO starting service impl=Mempool module=mempool service=Mempool
2022-03-08T11:48:05+01:00 INFO starting service impl=Consensus module=consensus service=Consensus
2022-03-08T11:48:05+01:00 INFO starting service impl=State module=consensus service=State
2022-03-08T11:48:05+01:00 INFO starting service impl=baseWAL module=consensus service=baseWAL wal=/home/user/.tendermint/data/cs.wal/wal
2022-03-08T11:48:05+01:00 INFO starting service impl=Group module=consensus service=Group wal=/home/user/.tendermint/data/cs.wal/wal
2022-03-08T11:48:05+01:00 INFO starting service impl=TimeoutTicker module=consensus service=TimeoutTicker
2022-03-08T11:48:05+01:00 INFO Searching for height height=1 max=0 min=0 module=consensus wal=/home/user/.tendermint/data/cs.wal/wal
2022-03-08T11:48:05+01:00 INFO Searching for height height=0 max=0 min=0 module=consensus wal=/home/user/.tendermint/data/cs.wal/wal
2022-03-08T11:48:05+01:00 INFO Found height=0 index=0 module=consensus wal=/home/user/.tendermint/data/cs.wal/wal
2022-03-08T11:48:05+01:00 INFO Catchup by replaying consensus messages height=1 module=consensus
2022-03-08T11:48:05+01:00 INFO Replay: Done module=consensus
2022-03-08T11:48:05+01:00 INFO starting service impl=EventSwitch module=consensus service=EventSwitch
2022-03-08T11:48:05+01:00 INFO starting service impl=BlockSync module=blockchain service=BlockSync
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xe3a7e5]

goroutine 1 [running]:
github.com/tendermint/tendermint/node.(*nodeImpl).OnStart(0xc00000a960, {0x131d408, 0xc00061fb40})
        github.com/tendermint/tendermint/node/node.go:497 +0x1185
github.com/tendermint/tendermint/libs/service.(*BaseService).Start(0xc00000a960, {0x131d408, 0xc00061fb40})
        github.com/tendermint/tendermint/libs/service/service.go:113 +0x219
github.com/tendermint/tendermint/cmd/tendermint/commands.NewRunNodeCmd.func1(0xc00079c500, {0xc00078a330, 0x0, 0x1})
        github.com/tendermint/tendermint/cmd/tendermint/commands/run_node.go:116 +0x1c2
github.com/spf13/cobra.(*Command).execute(0xc00079c500, {0xc00078a320, 0x1, 0x1})
        github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002c8c80)
        github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.3.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.3.0/command.go:895
github.com/tendermint/tendermint/libs/cli.RunWithTrace({0x131cb10, 0xc00016f0c0}, 0x1)
        github.com/tendermint/tendermint/libs/cli/helper.go:47 +0x6e
main.main()
        github.com/tendermint/tendermint/cmd/tendermint/main.go:63 +0x41c
```

```
[]github.com/tendermint/tendermint/libs/service.Service len: 6, cap: 6, [*github.com/tendermint/tendermint/internal/eventbus.EventBus {BaseService: (*"github.com/tendermint/tendermint/libs/service.BaseService")(0xc00063c690), pubsub: *(*"github.com/tenderm...
[0]:github.com/tendermint/tendermint/libs/service.Service(*github.com/tendermint/tendermint/internal/eventbus.EventBus) *{BaseService: (*"github.com/tendermint/tendermint/libs/service.BaseService")(0xc00063c690), pubsub: *(*"github.com/tendermint/tendermint/in...
[1]:github.com/tendermint/tendermint/libs/service.Service(*github.com/tendermint/tendermint/internal/evidence.Reactor) *{BaseService: (*"github.com/tendermint/tendermint/libs/service.BaseService")(0xc0006a4500), logger: github.com/tendermint/tendermint/libs/lo...
[2]:github.com/tendermint/tendermint/libs/service.Service(*github.com/tendermint/tendermint/internal/mempool.Reactor) *{BaseService: (*"github.com/tendermint/tendermint/libs/service.BaseService")(0xc00017a420), logger: github.com/tendermint/tendermint/libs/log...
[3]:github.com/tendermint/tendermint/libs/service.Service(*github.com/tendermint/tendermint/internal/consensus.Reactor) *{BaseService: (*"github.com/tendermint/tendermint/libs/service.BaseService")(0xc0001a8c30), logger: github.com/tendermint/tendermint/libs/l...
[4]:github.com/tendermint/tendermint/libs/service.Service(*github.com/tendermint/tendermint/internal/blocksync.Reactor) *{BaseService: (*"github.com/tendermint/tendermint/libs/service.BaseService")(0xc000380240), logger: github.com/tendermint/tendermint/libs/l...
[5]:github.com/tendermint/tendermint/libs/service.Service nil
```

```
	services: []service.Service{
			eventBus,
			evReactor,
			mpReactor,
			csReactor,
			bcReactor,
			pexReactor,
		},
```

The `pexReactor (n.services[5])` is *nil*. Which leads to a crash on `reactor.Start(...)`.

```

	for _, reactor := range n.services {
		if err := reactor.Start(ctx); err != nil {
			return fmt.Errorf("problem starting service '%T': %w ", reactor, err)
		}
	}
```

**Config (you can paste only the changes you've made)**:

```
# Set true to enable the peer-exchange reactor
pex = false
```

**node command runtime flags**:

`tendermint start --proxy-app=kvstore`

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by williambanfield** [comment]
Thanks @mjhubert for the report and simple repro. This is definitely a bug and I've created a fix. `master` is usually a bit unstable and prone to changes, so if you're looking for a more stable version to develop against, I'd recommend looking at the latest [v0.35.2](https://github.com/tendermint/tendermint/releases/tag/v0.35.2) release.
