### ISSUE TITLE
Wrong Block.Header.Version is got in State Sync on many chains.

### ISSUE THREAD

**Issue by liangping** [tendermint/tendermint#8198]
This issue is found in many chain, eg: stargaze, osmosis

```
2:31PM INF Applied snapshot chunk to ABCI app chunk=21 format=1 height=2178500 module=statesync total=23
2:31PM INF Applied snapshot chunk to ABCI app chunk=22 format=1 height=2178500 module=statesync total=23
2:31PM INF Verified ABCI app appHash="u\x15\b\x01\x19��\x1aksW����0�Z���\x1c����@�}���" height=2178500 module=statesync
2:31PM INF Snapshot restored format=1 hash="�n?��tF\x1f�rOPu�1��U��\x1bHM��v����\x00�" height=2178500 module=statesync
2:31PM INF Starting BlockPool service impl=BlockPool module=blockchain
panic: Failed to process committed block (2178501:6B9B5E35130DE36B84830475C721914B19242C5C873DF21B5593E341C121C60B): wrong Block.Header.Version. Expected {11 0}, got {11 1}

goroutine 4267 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000b21500, 0x1)
	github.com/tendermint/tendermint@v0.34.15/blockchain/v0/reactor.go:401 +0x123a
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).SwitchToFastSync
	github.com/tendermint/tendermint@v0.34.15/blockchain/v0/reactor.go:125 +0xe5

```
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
```
ping@stargaze2:~$ starsd version --long
name: stargaze
server_name: starsd
version: 3.0.0
commit: 6ee57f18714a6d94cc6205afcd1af2ab655f8f0f
build_tags: netgo,ledger
go: go version go1.18 linux/amd64
build_deps:
- filippo.io/edwards25519@v1.0.0-beta.2
- github.com/99designs/keyring@v1.1.6 => github.com/cosmos/keyring@v1.1.7-0.20210622111912-ef00f8ac3d76
- github.com/ChainSafe/go-schnorrkel@v0.0.0-20200405005733-88cbf1b4c40d
- github.com/CosmWasm/wasmd@v0.23.0
- github.com/CosmWasm/wasmvm@v1.0.0-beta5 => github.com/CosmWasm/wasmvm@v1.0.0-beta6
- github.com/Workiva/go-datastructures@v1.0.53
- github.com/armon/go-metrics@v0.3.10
- github.com/beorn7/perks@v1.0.1
- github.com/bgentry/speakeasy@v0.1.0
- github.com/btcsuite/btcd@v0.22.0-beta
- github.com/cespare/xxhash/v2@v2.1.2
- github.com/coinbase/rosetta-sdk-go@v0.7.0
- github.com/confio/ics23/go@v0.6.6
- github.com/cosmos/btcutil@v1.0.4
- github.com/cosmos/cosmos-sdk@v0.45.1
- github.com/cosmos/go-bip39@v1.0.0
- github.com/cosmos/iavl@v0.17.3
- github.com/cosmos/ibc-go/v2@v2.0.3
- github.com/cosmos/ledger-cosmos-go@v0.11.1
- github.com/cosmos/ledger-go@v0.9.2
- github.com/davecgh/go-spew@v1.1.1
- github.com/desertbit/timer@v0.0.0-20180107155436-c41aec40b27f
- github.com/dvsekhvalnov/jose2go@v0.0.0-20200901110807-248326c1351b
- github.com/felixge/httpsnoop@v1.0.1
- github.com/fsnotify/fsnotify@v1.5.1
- github.com/go-kit/kit@v0.12.0
- github.com/go-kit/log@v0.2.0
- github.com/go-logfmt/logfmt@v0.5.1
- github.com/godbus/dbus@v0.0.0-20190726142602-4481cbc300e2
- github.com/gogo/gateway@v1.1.0
- github.com/gogo/protobuf@v1.3.3 => github.com/regen-network/protobuf@v1.3.3-alpha.regen.1
- github.com/golang/protobuf@v1.5.2
- github.com/golang/snappy@v0.0.3
- github.com/google/btree@v1.0.0
- github.com/google/gofuzz@v1.2.0
- github.com/google/orderedcode@v0.0.1
- github.com/gorilla/handlers@v1.5.1
- github.com/gorilla/mux@v1.8.0
- github.com/gorilla/websocket@v1.4.2
- github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0
- github.com/grpc-ecosystem/grpc-gateway@v1.16.0
- github.com/gsterjov/go-libsecret@v0.0.0-20161001094733-a6f4afe4910c
- github.com/gtank/merlin@v0.1.1
- github.com/gtank/ristretto255@v0.1.2
- github.com/hashicorp/go-immutable-radix@v1.3.1
- github.com/hashicorp/golang-lru@v0.5.4
- github.com/hashicorp/hcl@v1.0.0
- github.com/hdevalence/ed25519consensus@v0.0.0-20210204194344-59a8610d2b87
- github.com/improbable-eng/grpc-web@v0.14.1
- github.com/klauspost/compress@v1.13.6
- github.com/lib/pq@v1.10.4
- github.com/libp2p/go-buffer-pool@v0.0.2
- github.com/magiconair/properties@v1.8.5
- github.com/mattn/go-isatty@v0.0.14
- github.com/matttproud/golang_protobuf_extensions@v1.0.1
- github.com/mimoo/StrobeGo@v0.0.0-20181016162300-f8f6d4d2b643
- github.com/minio/highwayhash@v1.0.2
- github.com/mitchellh/mapstructure@v1.4.3
- github.com/mtibben/percent@v0.2.1
- github.com/pelletier/go-toml@v1.9.4
- github.com/pkg/errors@v0.9.1
- github.com/pmezard/go-difflib@v1.0.0
- github.com/prometheus/client_golang@v1.12.0
- github.com/prometheus/client_model@v0.2.0
- github.com/prometheus/common@v0.32.1
- github.com/prometheus/procfs@v0.7.3
- github.com/rakyll/statik@v0.1.7
- github.com/rcrowley/go-metrics@v0.0.0-20200313005456-10cdbea86bc0
- github.com/regen-network/cosmos-proto@v0.3.1
- github.com/rs/cors@v1.8.0
- github.com/rs/zerolog@v1.26.0
- github.com/spf13/afero@v1.6.0
- github.com/spf13/cast@v1.4.1
- github.com/spf13/cobra@v1.2.1
- github.com/spf13/jwalterweatherman@v1.1.0
- github.com/spf13/pflag@v1.0.5
- github.com/spf13/viper@v1.10.1
- github.com/stretchr/testify@v1.7.0
- github.com/subosito/gotenv@v1.2.0
- github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca
- github.com/tendermint/btcd@v0.1.1
- github.com/tendermint/crypto@v0.0.0-20191022145703-50d29ede1e15
- github.com/tendermint/go-amino@v0.16.0
- github.com/tendermint/spm@v0.1.9 => github.com/public-awesome/spm@v0.1.9-stargaze.0.20220218155531-af173fcd55c7
- github.com/tendermint/tendermint@v0.34.15
- github.com/tendermint/tm-db@v0.6.6
- github.com/zondax/hid@v0.9.0
- golang.org/x/crypto@v0.0.0-20210915214749-c084706c2272
- golang.org/x/net@v0.0.0-20211005001312-d4b1ae081e3b
- golang.org/x/sys@v0.0.0-20220114195835-da31bd327af9
- golang.org/x/term@v0.0.0-20201126162022-7de9c90e9dd1
- golang.org/x/text@v0.3.7
- google.golang.org/genproto@v0.0.0-20220118154757-00ab72f36ad5
- google.golang.org/grpc@v1.43.0 => google.golang.org/grpc@v1.33.2
- google.golang.org/protobuf@v1.27.1
- gopkg.in/ini.v1@v1.66.2
- gopkg.in/yaml.v2@v2.4.0
- gopkg.in/yaml.v3@v3.0.0-20210107192922-496545a6307b
- nhooyr.io/websocket@v1.8.6
cosmos_sdk_version: v0.45.1

```

**Comment by marbar3778** [comment]
this is a known issue and isn't a tendermint issue but sdk and how we manage this version number. There is a PR that aims at fixing it https://github.com/cosmos/cosmos-sdk/pull/11182, but we have not been able to test it yet. If you have capacity we'd welcome others testing it.

**Comment by liangping** [comment]
@marbar3778 I know the app version is wrong? I am running validators for many chains. is there a way to config the versions or I have to do by edit the source code?

**Comment by cmwaters** [comment]
There is a temporary work around. You can find instructions for it here: https://github.com/cosmos/cosmos-sdk/issues/10791

**Comment by liangping** [comment]
```
1:54PM INF Applied snapshot chunk to ABCI app chunk=22 format=1 height=2206500 module=statesync total=23
1:54PM INF Verified ABCI app appHash="�`\x12Lg�\x04o�@b\x1eHRQ\\g\\�`s��J�j\r��f�x" height=2206500 module=statesync
1:54PM INF Snapshot restored format=1 hash=";ܺ1��\x1cr��v\x1b����5WiI+賑�\x18\x1eѸ;K)" height=2206500 module=statesync
1:54PM INF Starting BlockPool service impl=BlockPool module=blockchain
panic: Failed to process committed block (2206501:3EE209C7760C161AD2087837810564EB4E742D468467800A22F8A0CC0BA7EC74): wrong Block.Header.Version. Expected {11 0}, got {11 1}

goroutine 1289 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000c21180, 0x1)
	github.com/tendermint/tendermint@v0.34.15/blockchain/v0/reactor.go:401 +0x123a
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).SwitchToFastSync
	github.com/tendermint/tendermint@v0.34.15/blockchain/v0/reactor.go:125 +0xe5
ping@stargaze2:~$ ~/go/bin/tendermint set-app-version 1 --home ~/.starsd
Set app version
ping@stargaze2:~$ starsd start
1:54PM INF starting ABCI with Tendermint
failed initialize pinned codes Error calling the VM: Cache error: Error opening Wasm file for reading: No such file or directory (os error 2): pinning contract failed
```
seems not work.

**Comment by marbar3778** [comment]
state sync doesn't work with cosmwasm. Ethen frey is working on adding it.
