### ISSUE TITLE
vagrant up failing 

### ISSUE THREAD

**Issue by wighawag** [tendermint/tendermint#879]
BUG REPORT

**Tendermint version** 128e2a1d9e88eeb0aa7645973940b23eb7a14803

**Environment**:
- **OS** Windows 10 64bit:
- **Install tools**:
- **Others**:

**What happened**:

After executing ```vagrant up``` provisioning start but when reaching a certain stage, it stop abruptly with 

```
...
default: go/src/runtime/mstats.go
default: go/src/runtime/net_plan9.go
default: go/src/runtime/netpoll.go
default: go/src/runtime/netpoll_epoll.go
default: go/src/runtime/netpoll_kqueue.go
default: go/src/runtime/netpoll_nacl.go
default: go/src/runtime/netpoll_solaris.go
default: go/src/vendor/golang_org/x/net/route/inter
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**How to reproduce it** (as minimally and precisely as possible)
```git clone --recursive git@github.com:tendermint/tendermint.git```
```cd tendermint```
```vagrant up```

**Comment by melekes** [comment]
I do not see any errors in the log above. Could you please run `vagrant up --debug` (https://www.vagrantup.com/docs/other/debugging.html)?

**Comment by wighawag** [comment]
Here is it :
```
...
    default: go/src/vendor/golang_org/x/text/unicode/norm/example_test.go
 INFO interface: detail: go/src/vendor/golang_org/x/text/unicode/norm/forminfo.go
 INFO interface: detail:     default: go/src/vendor/golang_org/x/text/unicode/norm/forminfo.go
    default: go/src/vendor/golang_org/x/text/unicode/norm/forminfo.go
 INFO interface: detail: go/src/vendor/golang_org/x/text/unicode/norm/input.go
go/src/vendor/golang_org/x/text/unicode/norm/iter.go
 INFO interface: detail:     default: go/src/vendor/golang_org/x/text/unicode/norm/input.go
    default: go/src/vendor/golang_org/x/text/unicode/norm/iter.go
    default: go/src/vendor/golang_org/x/text/unicode/norm/input.go
    default: go/src/vendor/golang_org/x/text/unicode/norm/iter.go
 INFO interface: detail: go/src/vendor/golang_org/x/text/unicode/norm/normalize.go
 INFO interface: detail:     default: go/src/vendor/golang_org/x/text/unicode/norm/normalize.go
    default: go/src/vendor/golang_org/x/text/unicode/norm/normalize.go
 INFO interface: detail: go/src/vendor/golang_org/x/text/unicode/norm/readwriter.go
 INFO interface: detail:     default: go/src/vendor/golang_org/x/text/unicode/norm/readwriter.go
    default: go/src/vendor/golang_org/x/text/unicode/norm/readwriter.go
 INFO interface: detail: go/src/vendor/golang_o
 INFO interface: detail:     default: go/src/vendor/golang_o
    default: go/src/vendor/golang_o
DEBUG ssh: Exit status: 2
ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::HandleForwardedPortCollisions:0x0000000007bdb058>
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x000000000805e210>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x0000000005e05e48>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00000000081f6398>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x000000000823b128>
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<VagrantPlugins::ProviderVirtualBox::Action::Import:0x0000000007ba3630>
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "showvminfo", "7be09e7c-c3ef-40aa-98fd-7f2553158b1b", "--machinereadable"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: name="tendermint_default_1511256777598_8760"
groups="/"
ostype="Ubuntu (64-bit)"
UUID="7be09e7c-c3ef-40aa-98fd-7f2553158b1b"
CfgFile="C:\\Users\\wighawag\\VirtualBox VMs\\tendermint_default_1511256777598_8760\\tendermint_default_1511256777598_8760.vbox"
SnapFldr="C:\\Users\\wighawag\\VirtualBox VMs\\tendermint_default_1511256777598_8760\\Snapshots"
LogFldr="C:\\Users\\wighawag\\VirtualBox VMs\\tendermint_default_1511256777598_8760\\Logs"
hardwareuuid="7be09e7c-c3ef-40aa-98fd-7f2553158b1b"
memory=4096
pagefusion="off"
vram=12
cpuexecutioncap=100
hpet="off"
chipset="piix3"
firmware="BIOS"
cpus=2
pae="off"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="off"
cpuid-portability-level=0
bootmenu="messageandmenu"
boot1="disk"
boot2="none"
boot3="none"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="off"
vtxvpid="on"
vtxux="on"
paravirtprovider="legacy"
effparavirtprovider="none"
VMState="running"
VMStateChangeTime="2017-11-21T09:33:02.554000000"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
storagecontrollername0="SATAController"
storagecontrollertype0="IntelAhci"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="30"
storagecontrollerportcount0="1"
storagecontrollerbootable0="on"
"SATAController-0-0"="C:\Users\wighawag\VirtualBox VMs\tendermint_default_1511256777598_8760\box-disk1.vmdk"
"SATAController-ImageUUID-0-0"="fe412b3e-132d-4e6a-819a-8d2bf2aa74a0"
natnet1="nat"
macaddress1="08002759BD07"
cableconnected1="on"
nic1="nat"
nictype1="82540EM"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="ssh,tcp,127.0.0.1,2222,,22"
nic2="none"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="none"
audio_in="true"
audio_out="true"
clipboard="disabled"
draganddrop="disabled"
SessionName="headless"
VideoMode="720,400,0"@0,0 1
vrde="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="vagrant"
SharedFolderPathMachineMapping1="\\?\C:\dev\experiments\tendermint"
VRDEActiveConnection="off"
VRDEClients=0
videocap="off"
videocapscreens=0
videocapfile="C:\Users\wighawag\VirtualBox VMs\tendermint_default_1511256777598_8760\tendermint_default_1511256777598_8760.webm"
videocapres=1024x768
videocaprate=512
videocapfps=25
videocapopts=
GuestMemoryBalloon=0
GuestOSType="Linux26_64"
GuestAdditionsRunLevel=2
GuestAdditionsVersion="4.3.36_Ubuntu r105129"
GuestAdditionsFacility_VirtualBox Base Driver=50,1511256789430
GuestAdditionsFacility_VirtualBox System Service=50,1511256793029
GuestAdditionsFacility_Seamless Mode=0,1511256789430
GuestAdditionsFacility_Graphics Mode=0,1511256789430
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO warden: Recovery complete.
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x000000000823b1a0>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-1d44e759dc9e823e9d27f8139f149ad2
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x0000000007b2a140>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::VagrantError: The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.>
ERROR vagrant: The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
ERROR vagrant: D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/plugins/communicators/ssh/communicator.rb:257:in `execute'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/plugins/provisioners/shell/provisioner.rb:89:in `block (2 levels) in provision_ssh'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/plugins/provisioners/shell/provisioner.rb:63:in `tap'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/plugins/provisioners/shell/provisioner.rb:63:in `block in provision_ssh'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/plugins/provisioners/shell/provisioner.rb:287:in `with_script_file'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/plugins/provisioners/shell/provisioner.rb:61:in `provision_ssh'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/plugins/provisioners/shell/provisioner.rb:27:in `provision'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/provision.rb:138:in `run_provisioner'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:95:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builder.rb:116:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `block in run'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/busy.rb:19:in `busy'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `run'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/environment.rb:543:in `hook'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/provision.rb:126:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/provision.rb:126:in `block in call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/provision.rb:103:in `each'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/provision.rb:103:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/plugins/providers/virtualbox/action/set_name.rb:50:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builder.rb:116:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `block in run'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/busy.rb:19:in `busy'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `run'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/call.rb:53:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builder.rb:116:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `block in run'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/busy.rb:19:in `busy'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `run'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/call.rb:53:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builder.rb:116:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `block in run'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/busy.rb:19:in `busy'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `run'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/call.rb:53:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/box_check_outdated.rb:78:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/plugins/providers/virtualbox/action/match_mac_address.rb:19:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/plugins/providers/virtualbox/action/discard_state.rb:15:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/plugins/providers/virtualbox/action/import.rb:74:in `import'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/plugins/providers/virtualbox/action/import.rb:13:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/plugins/providers/virtualbox/action/prepare_clone_snapshot.rb:17:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/prepare_clone.rb:15:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/plugins/providers/virtualbox/action/customize.rb:40:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builder.rb:116:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `block in run'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/busy.rb:19:in `busy'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `run'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/call.rb:53:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builder.rb:116:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `block in run'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/busy.rb:19:in `busy'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `run'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/call.rb:53:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builder.rb:116:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `block in run'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/busy.rb:19:in `busy'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `run'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:227:in `action_raw'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:202:in `block in action'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/environment.rb:631:in `lock'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:188:in `call'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:188:in `action'
D:/Installations/x64/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
 INFO interface: error: The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
 INFO interface: Machine: error-exit ["Vagrant::Errors::VagrantError", "The SSH command responded with a non-zero exit status. Vagrant\nassumes that this means the command failed. The output for this command\nshould be in the log above. Please read the output to determine what\nwent wrong."]
```

**Comment by melekes** [comment]
hmm.. this does look like a Vagrant issue.. I'd suggest updating VirtualBox & vagrant & installing vbguest plugin https://github.com/dotless-de/vagrant-vbguest
 
```
vagrant plugin install vagrant-vbguest
```

not sure if this will help, but who knows.

**Comment by wighawag** [comment]
I was at the latest version. I installed the plugin and rerun vagrant up --debug (doing vagrant destroy before) and I get the same issue. I am using vagrant on windows 10 (64bit) if that matters.

**Comment by melekes** [comment]
Maybe VB ran out of disk space available to the box (check disk space, must be at least 1GB).

**Comment by melekes** [comment]
Ouh, I just destroyed and recreated the box. got this error:

```
==> default: go get github.com/mitchellh/gox github.com/tcnksm/ghr github.com/Masterminds/glide
==> default: go: missing Git command. See https://golang.org/s/gogetcmd
==> default: package github.com/mitchellh/gox: exec: "git": executable file not found in $PATH
==> default: go: missing Git command. See https://golang.org/s/gogetcmd
==> default: package github.com/tcnksm/ghr: exec: "git": executable file not found in $PATH
==> default: go: missing Git command. See https://golang.org/s/gogetcmd
==> default: package github.com/Masterminds/glide: exec: "git": executable file not found in $PATH
==> default: make:
```

**Comment by melekes** [comment]
Fixed in https://github.com/tendermint/tendermint/pull/891

**Comment by wighawag** [comment]
rexecuted vagrant up on that branch and it worked
