### ISSUE TITLE
Possible panic when processing a peer update message

### ISSUE THREAD

**Issue by james-chf** [tendermint/tendermint#8840]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): commit [`2e11760fbe96dacdf8c4e37b7a179ed777a9ebf`](https://github.com/tendermint/tendermint/commit/2e11760fbe96dacdf8c4e37b7a179ed777a9ebf) which is latest `master` at the time of writing

**ABCI app** (name for built-in, URL for self-written if it's publicly available): https://github.com/anoma/anoma

**Environment**:
- **OS** (e.g. from /etc/os-release): macOS 12.4 and Ubuntu 22.04
- **Install tools**:
- **Others**:

**What happened**:
Tendermint sometimes exits due to a nil pointer dereference when running a test in our project. This panic occurs most of the times the test is run but not every time.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100b97d78]

goroutine 546 [running]:
github.com/tendermint/tendermint/internal/consensus/types.(*HeightVoteSet).Prevotes(0x2?, 0x0?)
        github.com/tendermint/tendermint/internal/consensus/types/height_vote_set.go:159 +0x28
github.com/tendermint/tendermint/internal/consensus.(*Reactor).queryMaj23Routine.func1(0x0?, 0x14000146000)
        github.com/tendermint/tendermint/internal/consensus/reactor.go:842 +0x88
created by github.com/tendermint/tendermint/internal/consensus.(*Reactor).queryMaj23Routine
        github.com/tendermint/tendermint/internal/consensus/reactor.go:838 +0x2f4
```

The panic occurs due to `rs.Votes` possibly being nil [on this line](https://github.com/tendermint/tendermint/blob/d2ca0b868d964d0dabb3ea99bc54d096a1a6def9/internal/consensus/reactor.go#L842).

**What you expected to happen**:
tendermint should never panic like this - waiting until `rs.Votes != nil` in `queryMaj23Routine` crudely works around the issue, as in [this PR](https://github.com/james-chf/tendermint/pull/1/files). That is, running the test with a `tendermint` binary built from that PR avoids the panic and passes.

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):

This requires your machine [is able to build the Anoma project from source](https://docs.anoma.net/user-guide/install.html#from-source). It's not very minimal but should be able to reproduce the issue.

1. Checkout this commit - https://github.com/anoma/anoma/commit/5ce75fcf77d86e9037d667900801c6acd527ce79
2. Set the `TENDERMINT` environment variable to the path to an affected `tendermint` binary eg one built from commit tendermint commit `2e11760fbe96dacdf8c4e37b7a179ed777a9ebf`
3. Run the `test_node_connectivity.sh` script.

The test should finish with some output like:
```
Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
FAILED

failures:

failures:
    e2e::ledger_tests::test_node_connectivity

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 48 filtered out; finished in 130.33s
```

You will have to scroll up quite a bit to see the panic logs as detailed more below.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

Some logs from the node which panics when running that end-to-end test.

```
2022-06-22T13:28:24+01:00 INFO starting service impl=Evidence module=evidence service=Evidence
2022-06-22T13:28:24+01:00 INFO starting service impl=Mempool module=mempool service=Mempool
2022-06-22T13:28:24+01:00 INFO starting service impl=Consensus service=Consensus
2022-06-22T13:28:24+01:00 DEBUG consensus wait sync wait_sync=false
2022-06-22T13:28:24+01:00 INFO starting service impl=State module=consensus service=State
2022-06-22T13:28:24+01:00 DEBUG resolving peer address module=p2p peer={"Hostname":"127.0.0.1","NodeID":"f4e3247b010e7ebda5bc0251784c74fe079379d4","Path":"","Port":28656,"Protocol":"tcp"}
2022-06-22T13:28:24+01:00 DEBUG dialed peer endpoint={"IP":"127.0.0.1","Path":"","Port":28656,"Protocol":"tcp"} module=p2p peer=f4e3247b010e7ebda5bc0251784c74fe079379d4
2022-06-22T13:28:24+01:00 INFO starting service impl=baseWAL module=consensus service=baseWAL wal=/var/folders/cy/fxxsxwd56yg67d68vxj6l52h0000gn/T/.tmps2UqVU/e2e-test.da81c470e2d57daa7d92a/setup/validator-1/.anoma/e2e-test.da81c470e2d57daa7d92a/tendermint/data/cs.wal/wal
2022-06-22T13:28:24+01:00 INFO starting service impl=MConnection module=p2p peer={"Hostname":"127.0.0.1","NodeID":"f4e3247b010e7ebda5bc0251784c74fe079379d4","Path":"","Port":28656,"Protocol":"mconn"} service=MConnection
2022-06-22T13:28:24+01:00 INFO peer connected endpoint={} module=p2p peer=f4e3247b010e7ebda5bc0251784c74fe079379d4
2022-06-22T13:28:24+01:00 DEBUG received peer update module=evidence peer=f4e3247b010e7ebda5bc0251784c74fe079379d4 status=up
2022-06-22T13:28:24+01:00 DEBUG received peer update module=mempool peer=f4e3247b010e7ebda5bc0251784c74fe079379d4 status=up
2022-06-22T13:28:24+01:00 INFO starting service impl=Group module=consensus service=Group wal=/var/folders/cy/fxxsxwd56yg67d68vxj6l52h0000gn/T/.tmps2UqVU/e2e-test.da81c470e2d57daa7d92a/setup/validator-1/.anoma/e2e-test.da81c470e2d57daa7d92a/tendermint/data/cs.wal/wal
2022-06-22T13:28:24+01:00 INFO starting service impl=TimeoutTicker module=consensus service=TimeoutTicker
2022-06-22T13:28:24+01:00 INFO Searching for height height=1 max=0 min=0 module=consensus wal=/var/folders/cy/fxxsxwd56yg67d68vxj6l52h0000gn/T/.tmps2UqVU/e2e-test.da81c470e2d57daa7d92a/setup/validator-1/.anoma/e2e-test.da81c470e2d57daa7d92a/tendermint/data/cs.wal/wal
2022-06-22T13:28:24+01:00 INFO Searching for height height=0 max=0 min=0 module=consensus wal=/var/folders/cy/fxxsxwd56yg67d68vxj6l52h0000gn/T/.tmps2UqVU/e2e-test.da81c470e2d57daa7d92a/setup/validator-1/.anoma/e2e-test.da81c470e2d57daa7d92a/tendermint/data/cs.wal/wal
2022-06-22T13:28:24+01:00 INFO Found height=0 index=0 module=consensus wal=/var/folders/cy/fxxsxwd56yg67d68vxj6l52h0000gn/T/.tmps2UqVU/e2e-test.da81c470e2d57daa7d92a/setup/validator-1/.anoma/e2e-test.da81c470e2d57daa7d92a/tendermint/data/cs.wal/wal
2022-06-22T13:28:24+01:00 INFO Catchup by replaying consensus messages height=1 module=consensus
2022-06-22T13:28:24+01:00 INFO Replay: Done module=consensus
2022-06-22T13:28:24+01:00 INFO starting service impl=BlockSync module=blockchain service=BlockSync
2022-06-22T13:28:24+01:00 DEBUG Received tick module=consensus new_ti={"duration":"-19436000","height":"1","round":0,"step":1} old_ti={"duration":"0","height":"0","round":0,"step":0}
2022-06-22T13:28:24+01:00 DEBUG Internal state machine timeout scheduled duration=-19.436 height=1 module=consensus round=0 step=1
2022-06-22T13:28:24+01:00 INFO starting service impl=StateSync module=statesync service=StateSync
2022-06-22T13:28:24+01:00 DEBUG Internal state machine timeout elapsed  duration=-19.436 height=1 module=consensus round=0 step=1
2022-06-22T13:28:24+01:00 DEBUG received tock height=1 module=consensus round=0 step=1 timeout=-19.436
2022-06-22T13:28:24+01:00 DEBUG received peer update peer=f4e3247b010e7ebda5bc0251784c74fe079379d4 status=up
2022-06-22T13:28:24+01:00 DEBUG entering new round current=1/0/RoundStepNewHeight height=1 module=consensus round=0
2022-06-22T13:28:24+01:00 DEBUG entering propose step current=1/0/RoundStepNewRound height=1 module=consensus round=0
2022-06-22T13:28:24+01:00 DEBUG Send channel=32 conn={} module=p2p msgBytes="\n\x11 ï¿½ï¿½ï¿½ï¿½\"(ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½\x01" peer={"Hostname":"127.0.0.1","NodeID":"f4e3247b010e7ebda5bc0251784c74fe079379d4","Path":"","Port":28656,"Protocol":"mconn"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100b97d78]

goroutine 546 [running]:
github.com/tendermint/tendermint/internal/consensus/types.(*HeightVoteSet).Prevotes(0x2?, 0x0?)
        github.com/tendermint/tendermint/internal/consensus/types/height_vote_set.go:159 +0x28
github.com/tendermint/tendermint/internal/consensus.(*Reactor).queryMaj23Routine.func1(0x0?, 0x14000146000)
        github.com/tendermint/tendermint/internal/consensus/reactor.go:842 +0x88
created by github.com/tendermint/tendermint/internal/consensus.(*Reactor).queryMaj23Routine
        github.com/tendermint/tendermint/internal/consensus/reactor.go:838 +0x2f4
2022-06-22T12:28:24.627477Z  INFO anoma_apps::node::ledger: Tendermint node is no longer running.
2022-06-22T12:28:24.627516Z ERROR anoma_apps::node::ledger: Err(Tendermint(Runtime("exit status: 2")))
2022-06-22T12:28:24.627557Z  INFO anoma_apps::node::ledger: Tendermint has exited, shutting down...
2022-06-22T12:28:24.627634Z  INFO anoma_apps::node::ledger::broadcaster: Shutting down broadcaster...
2022-06-22T12:28:24.627653Z  INFO anoma_apps::node::ledger: Broadcaster is no longer running.
2022-06-22T12:28:24.627715Z  INFO anoma_apps::node::ledger: Anoma ledger node has shut down.
```

**Config (you can paste only the changes you've made)**:

**node command runtime flags**: N/A

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**: N/A

**Comment by cmwaters** [comment]
Thanks for opening the issue. We'll look to triage it in the coming days
