### ISSUE TITLE
Non deterministic test failures

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#908]
1) https://circleci.com/gh/tendermint/tendermint/2254
```
I[11-29|21:42:32.776] Loaded BlockCommit for catch-up              validator=2 peer="Peer{MConn{pipe} AD32C4E8CCC6 in}" height=19 commit="&{BlockID:400412DF7DCF5C14D469FB050
06A7DB6782EF45F:1:6E2B6F478EF2 Precommits:[Vote{0:05E8B1970EA4 19/00/2(Precommit) 400412DF7DCF {/BA20B3DAB000.../}} Vote{1:0D8215755EE9 19/00/2(Precommit) 400412DF7DCF {/AA7
A24DD8BEB.../}} Vote{2:1DCE56FF4C49 19/00/2(Precommit) 400412DF7DCF {/3705BF818A10.../}} Vote{3:839D678997D7 19/00/2(Precommit) 400412DF7DCF {/2F7B00BAE930.../}} Vote{4:9A69
12BE4E90 19/00/2(Precommit) 400412DF7DCF {/982B695E9CBF.../}}] firstPrecommit:<nil> hash:[] bitArray:<nil>}"
I[11-29|21:42:32.877] Loaded BlockCommit for catch-up              validator=2 peer="Peer{MConn{pipe} AD32C4E8CCC6 in}" height=19 commit="&{BlockID:400412DF7DCF5C14D469FB050
06A7DB6782EF45F:1:6E2B6F478EF2 Precommits:[Vote{0:05E8B1970EA4 19/00/2(Precommit) 400412DF7DCF {/BA20B3DAB000.../}} Vote{1:0D8215755EE9 19/00/2(Precommit) 400412DF7DCF {/AA7
A24DD8BEB.../}} Vote{2:1DCE56FF4C49 19/00/2(Precommit) 400412DF7DCF {/3705BF818A10.../}} Vote{3:839D678997D7 19/00/2(Precommit) 400412DF7DCF {/2F7B00BAE930.../}} Vote{4:9A69
12BE4E90 19/00/2(Precommit) 400412DF7DCF {/982B695E9CBF.../}}] firstPrecommit:<nil> hash:[] bitArray:<nil>}"
I[11-29|21:42:32.980] Loaded BlockCommit for catch-up              validator=2 peer="Peer{MConn{pipe} AD32C4E8CCC6 in}" height=19 commit="&{BlockID:400412DF7DCF5C14D469FB050
06A7DB6782EF45F:1:6E2B6F478EF2 Precommits:[Vote{0:05E8B1970EA4 19/00/2(Precommit) 400412DF7DCF {/BA20B3DAB000.../}} Vote{1:0D8215755EE9 19/00/2(Precommit) 400412DF7DCF {/AA7
A24DD8BEB.../}} Vote{2:1DCE56FF4C49 19/00/2(Precommit) 400412DF7DCF {/3705BF818A10.../}} Vote{3:839D678997D7 19/00/2(Precommit) 400412DF7DCF {/2F7B00BAE930.../}} Vote{4:9A69
12BE4E90 19/00/2(Precommit) 400412DF7DCF {/982B695E9CBF.../}}] firstPrecommit:<nil> hash:[] bitArray:<nil>}"
I[11-29|21:42:33.084] Loaded BlockCommit for catch-up              validator=2 peer="Peer{MConn{pipe} AD32C4E8CCC6 in}" height=19 commit="&{BlockID:400412DF7DCF5C14D469FB050
06A7DB6782EF45F:1:6E2B6F478EF2 Precommits:[Vote{0:05E8B1970EA4 19/00/2(Precommit) 400412DF7DCF {/BA20B3DAB000.../}} Vote{1:0D8215755EE9 19/00/2(Precommit) 400412DF7DCF {/AA7
A24DD8BEB.../}} Vote{2:1DCE56FF4C49 19/00/2(Precommit) 400412DF7DCF {/3705BF818A10.../}} Vote{3:839D678997D7 19/00/2(Precommit) 400412DF7DCF {/2F7B00BAE930.../}} Vote{4:9A69
12BE4E90 19/00/2(Precommit) 400412DF7DCF {/982B695E9CBF.../}}] firstPrecommit:<nil> hash:[] bitArray:<nil>}"
I[11-29|21:42:33.185] Loaded BlockCommit for catch-up              validator=2 peer="Peer{MConn{pipe} AD32C4E8CCC6 in}" height=19 commit="&{BlockID:400412DF7DCF5C14D469FB050
06A7DB6782EF45F:1:6E2B6F478EF2 Precommits:[Vote{0:05E8B1970EA4 19/00/2(Precommit) 400412DF7DCF {/BA20B3DAB000.../}} Vote{1:0D8215755EE9 19/00/2(Precommit) 400412DF7DCF {/AA7
A24DD8BEB.../}} Vote{2:1DCE56FF4C49 19/00/2(Precommit) 400412DF7DCF {/3705BF818A10.../}} Vote{3:839D678997D7 19/00/2(Precommit) 400412DF7DCF {/2F7B00BAE930.../}} Vote{4:9A69
12BE4E90 19/00/2(Precommit) 400412DF7DCF {/982B695E9CBF.../}}] firstPrecommit:<nil> hash:[] bitArray:<nil>}"
I[11-29|21:42:33.287] Loaded BlockCommit for catch-up              validator=2 peer="Peer{MConn{pipe} AD32C4E8CCC6 in}" height=19 commit="&{BlockID:400412DF7DCF5C14D469FB050
06A7DB6782EF45F:1:6E2B6F478EF2 Precommits:[Vote{0:05E8B1970EA4 19/00/2(Precommit) 400412DF7DCF {/BA20B3DAB000.../}} Vote{1:0D8215755EE9 19/00/2(Precommit) 400412DF7DCF {/AA7
A24DD8BEB.../}} Vote{2:1DCE56FF4C49 19/00/2(Precommit) 400412DF7DCF {/3705BF818A10.../}} Vote{3:839D678997D7 19/00/2(Precommit) 400412DF7DCF {/2F7B00BAE930.../}} Vote{4:9A69
12BE4E90 19/00/2(Precommit) 400412DF7DCF {/982B695E9CBF.../}}] firstPrecommit:<nil> hash:[] bitArray:<nil>}"
I[11-29|21:42:33.389] Loaded BlockCommit for catch-up              validator=2 peer="Peer{MConn{pipe} AD32C4E8CCC6 in}" height=19 commit="&{BlockID:400412DF7DCF5C14D469FB050
06A7DB6782EF45F:1:6E2B6F478EF2 Precommits:[Vote{0:05E8B1970EA4 19/00/2(Precommit) 400412DF7DCF {/BA20B3DAB000.../}} Vote{1:0D8215755EE9 19/00/2(Precommit) 400412DF7DCF {/AA7
A24DD8BEB.../}} Vote{2:1DCE56FF4C49 19/00/2(Precommit) 400412DF7DCF {/3705BF818A10.../}} Vote{3:839D678997D7 19/00/2(Precommit) 400412DF7DCF {/2F7B00BAE930.../}} Vote{4:9A69
12BE4E90 19/00/2(Precommit) 400412DF7DCF {/982B695E9CBF.../}}] firstPrecommit:<nil> hash:[] bitArray:<nil>}"
I[11-29|21:42:33.491] Loaded BlockCommit for catch-up              validator=2 peer="Peer{MConn{pipe} AD32C4E8CCC6 in}" height=19 commit="&{BlockID:400412DF7DCF5C14D469FB050
06A7DB6782EF45F:1:6E2B6F478EF2 Precommits:[Vote{0:05E8B1970EA4 19/00/2(Precommit) 400412DF7DCF {/BA20B3DAB000.../}} Vote{1:0D8215755EE9 19/00/2(Precommit) 400412DF7DCF {/AA7
A24DD8BEB.../}} Vote{2:1DCE56FF4C49 19/00/2(Precommit) 400412DF7DCF {/3705BF818A10.../}} Vote{3:839D678997D7 19/00/2(Precommit) 400412DF7DCF {/2F7B00BAE930.../}} Vote{4:9A69
12BE4E90 19/00/2(Precommit) 400412DF7DCF {/982B695E9CBF.../}}] firstPrecommit:<nil> hash:[] bitArray:<nil>}"
```

2) https://circleci.com/gh/tendermint/tendermint/2253

```
Passed Test: Counter over GRPC

test/app/test.sh: line 80: 13940 Killed                  abci-cli counter --serial --abci grpc > /dev/null
test/app/test.sh: line 80: 13941 Killed                  tendermint node --abci grpc > tendermint.log
Starting counter_over_grpc_grpc (ie. with grpc broadcast_tx)
running test
... sending tx. expect no error
... building grpc_client
RESPONSE
rpc error: code = Unavailable desc = grpc: the connection is unavailable
parse error: Invalid numeric literal at line 1, column 4
parse error: Invalid numeric literal at line 1, column 4
-------
TX 00
RESPONSE rpc error: code = Unavailable desc = grpc: the connection is unavailable
ERROR rpc error: code = Unavailable desc = grpc: the connection is unavailable
----
Unexpected error sending tx (00): rpc error: code = Unavailable desc = grpc: the connection is unavailable
```

[test_integrations.log.zip](https://github.com/tendermint/tendermint/files/1516009/test_integrations.log.zip)
[test_integrations (1).log.zip](https://github.com/tendermint/tendermint/files/1516010/test_integrations.1.log.zip)

**Comment by ebuchman** [comment]
Yeh just saw this recently too. Note I've have an open issue for these https://github.com/tendermint/tendermint/issues/460.

I'll change the title of this one to be specifically for this GRPC issue ...

**Comment by ebuchman** [comment]
```
	reactor_test.go:386: 
panic: Timed out waiting for all validators to commit a block [recovered]
	panic: Timed out waiting for all validators to commit a block

goroutine 1151 [running]:
testing.tRunner.func1(0xc42178e2d0)
	/usr/local/go/src/testing/testing.go:711 +0x5d9
panic(0xda2d20, 0x1075200)
	/usr/local/go/src/runtime/panic.go:491 +0x2a2
github.com/tendermint/tendermint/consensus.timeoutWaitGroup(0xc42178e2d0, 0x4, 0xc4278dfb00, 0xc4223fadc0, 0x4, 0x4)
	/go/src/github.com/tendermint/tendermint/consensus/reactor_test.go:389 +0x54a
github.com/tendermint/tendermint/consensus.waitForAndValidateBlock(0xc42178e2d0, 0x4, 0xc420d1a9c0, 0xc420dad3a0, 0x4, 0x4, 0xc4223fadc0, 0x4, 0x4, 0x0, ...)
	/go/src/github.com/tendermint/tendermint/consensus/reactor_test.go:300 +0x1d5
github.com/tendermint/tendermint/consensus.TestVotingPowerChange(0xc42178e2d0)
	/go/src/github.com/tendermint/tendermint/consensus/reactor_test.go:180 +0xeed
testing.tRunner(0xc42178e2d0, 0xffd3d0)
	/usr/local/go/src/testing/testing.go:746 +0x16d
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x569
exit status 2
FAIL	github.com/tendermint/tendermint/consensus	91.096s
make: *** [test_integrations] Error 1
```
https://circleci.com/gh/tendermint/tendermint/2390#artifacts/containers/0

**Comment by zramsay** [comment]
```
	reactor_test.go:425: 
panic: Timed out waiting for all validators to commit a block [recovered]
	panic: Timed out waiting for all validators to commit a block

goroutine 10068 [running]:
testing.tRunner.func1(0xc4201861e0)
	/usr/local/go/src/testing/testing.go:711 +0x5d9
panic(0xda9700, 0x107f1b0)
	/usr/local/go/src/runtime/panic.go:491 +0x2a2
github.com/tendermint/tendermint/consensus.timeoutWaitGroup(0xc4201861e0, 0x7, 0xc42e325560, 0xc427c6d980, 0x7, 0x7)
	/var/lib/jenkins/workspace/05.Test.Tendermint.FeatureBranches.Cover/go/src/github.com/tendermint/tendermint/consensus/reactor_test.go:428 +0x54a
github.com/tendermint/tendermint/consensus.waitForAndValidateBlockWithTx(0xc4201861e0, 0x7, 0xc42738f1d0, 0xc427b305c0, 0x7, 0x7, 0xc427c6d980, 0x7, 0x7, 0xc4215c6e20, ...)
	/var/lib/jenkins/workspace/05.Test.Tendermint.FeatureBranches.Cover/go/src/github.com/tendermint/tendermint/consensus/reactor_test.go:330 +0x1ed
github.com/tendermint/tendermint/consensus.TestReactorValidatorSetChanges(0xc4201861e0)
	/var/lib/jenkins/workspace/05.Test.Tendermint.FeatureBranches.Cover/go/src/github.com/tendermint/tendermint/consensus/reactor_test.go:252 +0xbc4
testing.tRunner(0xc4201861e0, 0x10050c0)
	/usr/local/go/src/testing/testing.go:746 +0x16d
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x569
exit status 2
FAIL	github.com/tendermint/tendermint/consensus	512.337s
```

ref: https://ci.interblock.io/job/05.Test.Tendermint.FeatureBranches.Cover/71/console

**Comment by zramsay** [comment]
```
--- FAIL: TestNodeStartStop (5.11s)
	node_test.go:26: Started node NodeInfo{pk: PubKeyEd25519{C724E96CBA1E6BE4CB8FEEDF1223DB2AB0ABB1067048F54D1EF859B85ECDF954}, moniker: penguin, network: tendermint_test [remote , listen 192.168.1.9:36656], version: 0.15.0 ([wire_version=0.7.2 p2p_version=0.5.0 consensus_version=v1/0.2.2 rpc_version=0.7.0/3 tx_index=on rpc_addr=tcp://0.0.0.0:36657])}
	node_test.go:35: timed out waiting for the node to produce a block
FAIL
```
this failed locally

**Comment by zramsay** [comment]
```
--- FAIL: TestBlockEvents (7.58s)
      Error Trace:      event_test.go:61
	Error:      	Expected nil, but got: timed out waiting for event
	Messages:   	2: timed out waiting for event
	            	github.com/tendermint/tendermint/rpc/client.WaitForOneEvent
	            		github.com/tendermint/tendermint/rpc/client/_test/_obj_test/helpers.go:83
	            	github.com/tendermint/tendermint/rpc/client_test.TestBlockEvents
	            		/home/zicter/goApps/src/github.com/tendermint/tendermint/rpc/client/event_test.go:60
	            	testing.tRunner
	            		/usr/local/go/src/testing/testing.go:746
	            	runtime.goexit
	            		/usr/local/go/src/runtime/asm_amd64.s:2337
```

**Comment by zramsay** [comment]
```
--- FAIL: TestProgressAfterCreateEmptyBlocksInterval (4.23s)
panic: We shouldnt be stuck waiting [recovered]
	panic: We shouldnt be stuck waiting

goroutine 637 [running]:
testing.tRunner.func1(0xc420192870)
	/usr/local/go/src/testing/testing.go:711 +0x5d9
panic(0xdaa6a0, 0x1080090)
	/usr/local/go/src/runtime/panic.go:491 +0x2a2
github.com/tendermint/tendermint/consensus.ensureNewStep(0xc420080a80)
	/home/jslave/workspace/05.Test.Tendermint.FeatureBranches.Cover.Slow/go/src/github.com/tendermint/tendermint/consensus/common_test.go:330 +0x165
github.com/tendermint/tendermint/consensus.TestProgressAfterCreateEmptyBlocksInterval(0xc420192870)
	/home/jslave/workspace/05.Test.Tendermint.FeatureBranches.Cover.Slow/go/src/github.com/tendermint/tendermint/consensus/mempool_test.go:52 +0x428
testing.tRunner(0xc420192870, 0x1005ff0)
	/usr/local/go/src/testing/testing.go:746 +0x16d
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x569
exit status 2
FAIL	github.com/tendermint/tendermint/consensus	14.010s
make: *** [test_cover_slow] Error 1
```

**Comment by ebuchman** [comment]
```
=== RUN   TestReactorValidatorSetChanges

....

panic: open /root/.tendermint_test/consensus_val_set_changes_test_6/data/cs.wal/wal: no such file or directory                                                                  
                                                                                                                                                                                
goroutine 682 [running]:                                                                                                                                                        
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/autofile.(*Group).checkHeadSizeLimit(0xc4239b4fa0)                                                         
    /root/goApps/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/autofile/group.go:213 +0xf6                                                           
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/autofile.(*Group).processTicks(0xc4239b4fa0)                                                               
    /root/goApps/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/autofile/group.go:195 +0x3f                                                           created by github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/autofile.(*Group).OnStart                                                                       
    /root/goApps/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/autofile/group.go:103 +0x4f                                                           exit status 2                                               
```

**Comment by ebuchman** [comment]
These are quite old and I think many have been fixed. Will close for now. Let's keep tracking new non-deterministic failures in the other or new issues
