### ISSUE TITLE
Tendermint crashes when ResponseInfo contains height < 0

### ISSUE THREAD

**Issue by srmo** [tendermint/tendermint#911]
**BUG REPORT**
**Tendermint version** 
0.12.0

**What happened**:
When returning a value < 0 as app-height and an empty appHash to answer the RequestInfo, tendermint crashes.
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15f78d6]

goroutine 1 [running]:
github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x0, 0x0, 0x1cacbc0, 0xc4201c1310, 0x0, 0x1caa220, 0xc4200e27e0, 0x0, 0x16fd420, 0x0)
	/Users/smueller/development/projects/tendermint/code/src/github.com/tendermint/tendermint/state/execution.go:47 +0xa6
github.com/tendermint/tendermint/state.ExecCommitBlock(0x1cacbc0, 0xc4201c1310, 0x0, 0x1caa220, 0xc4200e27e0, 0x2, 0x102ba7f, 0xc420100e38, 0x10128bc, 0xc4201c1868)
	/Users/smueller/development/projects/tendermint/code/src/github.com/tendermint/tendermint/state/execution.go:299 +0x89
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlocks(0xc420200ab0, 0x1caf020, 0xc4200ac800, 0xfffffffffffffff6, 0x7, 0x0, 0x2909cb8, 0x1060ef2, 0x1, 0x1, ...)
	/Users/smueller/development/projects/tendermint/code/src/github.com/tendermint/tendermint/consensus/replay.go:317 +0x217
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc420200ab0, 0x0, 0x0, 0x0, 0xfffffffffffffff6, 0x1caf020, 0xc4200ac800, 0xfffffffffffffff6, 0x0, 0x0, ...)
	/Users/smueller/development/projects/tendermint/code/src/github.com/tendermint/tendermint/consensus/replay.go:261 +0x382
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc420200ab0, 0x1caf020, 0xc4200ac800, 0x0, 0x1caa220)
	/Users/smueller/development/projects/tendermint/code/src/github.com/tendermint/tendermint/consensus/replay.go:211 +0x512
github.com/tendermint/tendermint/proxy.(*multiAppConn).OnStart(0xc4200ac800, 0xc42018cd20, 0x15)
	/Users/smueller/development/projects/tendermint/code/src/github.com/tendermint/tendermint/proxy/multi_app_conn.go:108 +0x89e
github.com/tendermint/tmlibs/common.(*BaseService).Start(0xc4200ac800, 0x1caa200, 0x0, 0x0)
	/Users/smueller/development/projects/tendermint/code/src/github.com/tendermint/tmlibs/common/service.go:105 +0x472
github.com/tendermint/tendermint/node.NewNode(0xc42009d3b0, 0x1cab0c0, 0xc420235f40, 0x1ca0720, 0xc420270f30, 0xc420286ff0, 0x1964d08, 0x1caa220, 0xc420284b40, 0x9, ...)
	/Users/smueller/development/projects/tendermint/code/src/github.com/tendermint/tendermint/node/node.go:165 +0x846
github.com/tendermint/tendermint/node.DefaultNewNode(0xc42009d3b0, 0x1caa220, 0xc420284b40, 0x0, 0x0, 0xc420101c08)
	/Users/smueller/development/projects/tendermint/code/src/github.com/tendermint/tendermint/node/node.go:81 +0x1bd
github.com/tendermint/tendermint/cmd/tendermint/commands.NewRunNodeCmd.func1(0xc4201fa480, 0x1d12320, 0x0, 0x0, 0x0, 0x0)
	/Users/smueller/development/projects/tendermint/code/src/github.com/tendermint/tendermint/cmd/tendermint/commands/run_node.go:47 +0x5b
github.com/spf13/cobra.(*Command).execute(0xc4201fa480, 0x1d12320, 0x0, 0x0, 0xc4201fa480, 0x1d12320)
	/Users/smueller/development/projects/tendermint/code/src/github.com/spf13/cobra/command.go:696 +0x47b
github.com/spf13/cobra.(*Command).ExecuteC(0x1cecdc0, 0xc420245480, 0xc420101e58, 0x1419981)
	/Users/smueller/development/projects/tendermint/code/src/github.com/spf13/cobra/command.go:781 +0x349
github.com/spf13/cobra.(*Command).Execute(0x1cecdc0, 0xc420101ed0, 0x1419222)
	/Users/smueller/development/projects/tendermint/code/src/github.com/spf13/cobra/command.go:734 +0x2b
github.com/tendermint/tmlibs/cli.Executor.Execute(0x1cecdc0, 0x1965be8, 0x2, 0xc420245420)
	/Users/smueller/development/projects/tendermint/code/src/github.com/tendermint/tmlibs/cli/setup.go:97 +0x4e
main.main()
	/Users/smueller/development/projects/tendermint/code/src/github.com/tendermint/tendermint/cmd/tendermint/main.go:40 +0x1b5```

**What you expected to happen**:
Not sure.

**Comment by melekes** [comment]
we really need to make height uint64, so it is not even possible to send that

**Comment by srmo** [comment]
@melekes not sure how this helps with languages like Java, which doesn't have the concept of an unsigned int.

**Comment by melekes** [comment]
oh, right

**Comment by melekes** [comment]
btw, https://developers.google.com/protocol-buffers/docs/proto3#scalar we can make height uint64 in protobuf

**Comment by melekes** [comment]
ouh, it is already uint64

**Comment by melekes** [comment]
```
	blockHeight := int(res.LastBlockHeight) // XXX: beware overflow
```

classic

**Comment by wolfposd** [comment]
for reference
protobuf converts uint64 to long in java:
```   
     /**
     * <code>uint64 height = 3;</code>
     */
     long getHeight();
```

> The long data type is a 64-bit two's complement integer. The signed long has a minimum value of -2^63 and a maximum value of 2^63-1. In Java SE 8 and later, you can use the long data type to represent an unsigned 64-bit long, which has a minimum value of 0 and a maximum value of 2^64-1

**Comment by melekes** [comment]
@srmo and other guys. what do you think TM should do. ie. what is the best way to handle input errors from the app? should TM panic because app is not sending correct data? or just try and continue to run (depending on the case of course)

**Comment by melekes** [comment]
Fixed in https://github.com/tendermint/tendermint/pull/914.
